'use strict';
window.LS_DATA = Object.freeze({
  version: 7.3,
  personalities: ['Kind','Ambitious','Curious','Calm','Bold','Funny','Romantic','Practical','Creative','Competitive','Shy','Social','Stubborn','Empathetic','Independent','Adventurous','Responsible','Athletic'],
  talents: ['Music','Writing','Art','Sports','Math','Science','Programming','Business','Languages','Acting','Fashion','Cooking','Photography','Gaming','Leadership','Dance'],
  names: ['Mina','Lena','Sofia','Emma','Ari','Nora','Maya','Iris','Lina','Elena','Avery','Jade','Theo','Noah','Leo','Eli','Kai','Lucas','Julian','Alex','Mia','Jordan','Sam','Rowan'],
  places: ['Ho Chi Minh City, Vietnam','Seoul, South Korea','Tokyo, Japan','London, UK','Paris, France','New York City, USA','Vancouver, Canada','Singapore','Bangkok, Thailand','Sydney, Australia'],
  weatherTypes: ['Sunny','Cloudy','Rainy','Stormy','Cool','Hot','Windy'],
  moods: ['good','busy','quiet','excited','stressed','curious','tired','happy','annoyed','confident','lonely'],
  ageRules: {
    phone: 13,
    partTimeWork: 16,
    adult: 18,
    investing: 18,
    datingApps: 18,
    independentTravel: 18,
    smallBusiness: 6,
    cookingHelp: 7,
    driving: 16
  },
  // v7.2 item lifecycle catalog.
  // lifecycleType: consumable | finite | durable | wearable | device | container | progress | perishable | gift
  // uses: data-driven actions. effects = needs/stats, skills = practice gains (diminishing), consume = % used per action,
  // wear = [chance%, min, max] condition loss, progress = % progress per session, prep = school preparation.
  catalog: {
    coldRelief: {name:'Cold Relief',icon:'🤧',price:9,category:'Pharmacy',minAge:6,permissionPrice:0,lifecycleType:'finite',stackable:false,unitLabel:'uses',units:6,medKind:'coldRelief',description:'Eases cough, runny nose, sore throat, sneezing and headache for a few hours. It does not cure a cold. Game item — no real dosing information.',effectLabels:['Symptom relief'],uses:[{id:'takeMedicine',label:'Use',minutes:5,medicine:true,minAge:3}]},
    feverPain: {name:'Fever/Pain Relief',icon:'🌡️',price:8,category:'Pharmacy',minAge:6,permissionPrice:0,lifecycleType:'finite',stackable:false,unitLabel:'uses',units:8,medKind:'feverPain',description:'Eases fever, headache, body aches and pain for a few hours. Game item — no real dosing information.',effectLabels:['Symptom relief'],uses:[{id:'takeMedicine',label:'Use',minutes:5,medicine:true,minAge:3}]},
    allergyRelief: {name:'Allergy Relief',icon:'🌼',price:10,category:'Pharmacy',minAge:6,permissionPrice:0,lifecycleType:'finite',stackable:false,unitLabel:'uses',units:10,medKind:'allergyRelief',description:'Eases sneezing and a runny nose from allergies. Game item — no real dosing information.',effectLabels:['Symptom relief'],uses:[{id:'takeMedicine',label:'Use',minutes:5,medicine:true,minAge:3}]},
    coughRelief: {name:'Cough Relief',icon:'🍯',price:8,category:'Pharmacy',minAge:6,permissionPrice:0,lifecycleType:'finite',stackable:false,unitLabel:'uses',units:6,medKind:'coughRelief',description:'Soothes a cough and a sore throat. Game item — no real dosing information.',effectLabels:['Symptom relief'],uses:[{id:'takeMedicine',label:'Use',minutes:5,medicine:true,minAge:3}]},
    stomachRelief: {name:'Stomach Relief',icon:'🫖',price:9,category:'Pharmacy',minAge:6,permissionPrice:0,lifecycleType:'finite',stackable:false,unitLabel:'uses',units:6,medKind:'stomachRelief',description:'Settles nausea and stomach pain a little. Game item — no real dosing information.',effectLabels:['Symptom relief'],uses:[{id:'takeMedicine',label:'Use',minutes:5,medicine:true,minAge:3}]},
    firstAid: {name:'Bandages / First Aid',icon:'🩹',price:7,category:'Pharmacy',minAge:6,permissionPrice:0,lifecycleType:'finite',stackable:false,unitLabel:'uses',units:10,medKind:'firstAid',description:'For cuts, scrapes and sprains. Game item — no real dosing information.',effectLabels:['Symptom relief'],uses:[{id:'takeMedicine',label:'Use',minutes:5,medicine:true,minAge:3}]},
    snackPack: {name:'Snack pack',icon:'🍪',price:6,category:'Food & drinks',minAge:5,permissionPrice:25,lifecycleType:'consumable',stackable:true,maxQuantity:12,hunger:30,description:'A small packaged snack to eat later.',effectLabels:['Hunger','Fun']},
    juiceBox: {name:'Juice box',icon:'🧃',price:3,category:'Food & drinks',minAge:3,permissionPrice:25,lifecycleType:'consumable',stackable:true,maxQuantity:12,drink:true,hunger:6,comfort:14,description:'A sweet drink in a little carton.',effectLabels:['Thirst','Comfort']},
    sandwich: {name:'Sandwich',icon:'🥪',price:7,category:'Food & drinks',minAge:6,permissionPrice:25,lifecycleType:'perishable',stackable:true,maxQuantity:4,hunger:48,freshnessDays:2,description:'Proper food. Best eaten within two days.',effectLabels:['Hunger','Energy']},
    fruit: {name:'Fresh fruit',icon:'🍎',price:4,category:'Food & drinks',minAge:3,permissionPrice:25,lifecycleType:'perishable',stackable:true,maxQuantity:8,hunger:20,freshnessDays:6,healthy:true,description:'Healthy and quick. Goes soft after a few days.',effectLabels:['Hunger','Health']},
    waterBottle: {name:'Water bottle',icon:'🫗',price:15,category:'Weather & outdoors',minAge:3,permissionPrice:35,lifecycleType:'container',capacity:600,repairable:false,agingPerYear:4,description:'Reusable 600 ml bottle. Holds water — it does not make it.',effectLabels:['Hydration','Comfort']},
    umbrella: {name:'Umbrella',icon:'☂️',price:12,category:'Weather & outdoors',minAge:0,permissionPrice:35,lifecycleType:'durable',weather:'rain',repairable:true,agingPerYear:5,description:'Keeps you drier when it rains outside.',effectLabels:['Rain comfort']},
    sunglasses: {name:'Sunglasses',icon:'🕶️',price:18,category:'Weather & outdoors',minAge:4,permissionPrice:35,lifecycleType:'wearable',slot:'eyewear',weather:'sun',wearPerDay:.15,agingPerYear:3,description:'Useful on bright days.',effectLabels:['Sun comfort','Style']},
    raincoat: {name:'Raincoat',icon:'🧥',price:28,category:'Clothes',minAge:0,permissionPrice:35,lifecycleType:'wearable',slot:'outerwear',weather:'rain',wearPerDay:.2,agingPerYear:4,description:'Wearable rain protection.',effectLabels:['Rain comfort']},
    sweater: {name:'Sweater',icon:'🧶',price:24,category:'Clothes',minAge:0,permissionPrice:35,lifecycleType:'wearable',slot:'top',weather:'cold',wearPerDay:.25,agingPerYear:4,description:'Warm knit top for cool days.',effectLabels:['Warmth','Comfort']},
    hoodie: {name:'Hoodie',icon:'👕',price:40,category:'Clothes',minAge:6,permissionPrice:45,lifecycleType:'wearable',slot:'top',weather:'cold',style:3,wearPerDay:.25,agingPerYear:4,description:'Everyday comfort and a bit of style.',effectLabels:['Warmth','Style']},
    tshirt: {name:'T-shirt',icon:'👚',price:12,category:'Clothes',minAge:0,permissionPrice:30,lifecycleType:'wearable',slot:'top',style:1,wearPerDay:.35,agingPerYear:5,description:'A basic top. Wears out with washing.',effectLabels:['Comfort']},
    jeans: {name:'Jeans',icon:'👖',price:35,category:'Clothes',minAge:4,permissionPrice:40,lifecycleType:'wearable',slot:'bottom',style:2,wearPerDay:.18,agingPerYear:3,description:'Durable everyday pants.',effectLabels:['Style']},
    sneakers: {name:'Sneakers',icon:'👟',price:55,category:'Clothes',minAge:3,permissionPrice:45,lifecycleType:'wearable',slot:'shoes',style:2,exerciseBonus:1,wearPerDay:.25,agingPerYear:4,description:'Comfortable shoes that make exercise easier.',effectLabels:['Fitness','Style']},
    cap: {name:'Cap',icon:'🧢',price:16,category:'Clothes',minAge:4,permissionPrice:30,lifecycleType:'wearable',slot:'head',weather:'sun',style:1,wearPerDay:.15,agingPerYear:3,description:'Shade for your eyes and a bit of style.',effectLabels:['Sun comfort','Style']},
    backpack: {name:'Backpack',icon:'🎒',price:35,category:'School supplies',minAge:5,permissionPrice:60,lifecycleType:'wearable',slot:'bag',schoolBonus:true,wearPerDay:.1,agingPerYear:5,repairable:true,description:'Carries books and supplies. School days are a little less tiring.',effectLabels:['School convenience']},
    notebook: {name:'Notebook',icon:'📓',price:4,category:'School supplies',minAge:6,permissionPrice:25,lifecycleType:'finite',stackable:true,maxQuantity:6,unitLabel:'pages',units:80,homeworkBonus:true,description:'80 pages. Homework goes faster with something to write in.',effectLabels:['Homework speed'],uses:[{id:'write',label:'Write / doodle',minutes:30,consume:5,effects:{fun:4,stress:-3},skills:{writing:2},minAge:6,text:['You fill a page with notes, then a margin with doodles.','You write until the thoughts in your head feel a little more organized.']}]},
    workbook: {name:'Workbook',icon:'📘',price:14,category:'School supplies',minAge:6,permissionPrice:30,lifecycleType:'progress',progressType:'exercises',description:'Practice exercises. Helps preparation for the subject you choose.',effectLabels:['Study prep','Knowledge'],uses:[{id:'practice',label:'Do exercises',minutes:45,progress:20,prep:7,skills:{knowledge:1.5},effects:{stress:2},minAge:6,text:['You work through a page of exercises. Two of them take far too long.','A set of practice problems — slow at first, then faster.']}]},
    deskLamp: {name:'Desk lamp',icon:'💡',price:45,category:'Furniture',minAge:8,permissionPrice:55,lifecycleType:'durable',studyBonus:true,agingPerYear:2,repairable:true,description:'Good light makes study sessions more effective.',effectLabels:['Study efficiency','Comfort']},
    beanbag: {name:'Beanbag chair',icon:'🛋️',price:60,category:'Furniture',minAge:4,permissionPrice:55,lifecycleType:'durable',agingPerYear:4,repairable:true,description:'A soft spot to flop into.',effectLabels:['Comfort','Stress relief'],uses:[{id:'relax',label:'Flop and relax',minutes:20,effects:{comfort:18,stress:-4},wear:[10,1,2],text:['You sink into the beanbag and stop thinking for a while.','The beanbag makes a sad whoosh as you collapse into it. Perfect.']}]},
    book: {name:'Book',icon:'📖',price:20,category:'Books',minAge:4,permissionPrice:40,lifecycleType:'progress',progressType:'reading',description:'A story you can read, reread or give away.',effectLabels:['Reading','Knowledge','Stress relief'],uses:[{id:'read',label:'Read',minutes:45,progress:25,effects:{fun:7,stress:-4},skills:{reading:2.5,knowledge:1},minAge:5,text:['You read until the chapter ends on a cliffhanger.','The story pulls you in; you look up and forty minutes have passed.','A slow chapter, but one line sticks with you.']}]},
    comicBook: {name:'Comic book',icon:'💥',price:8,category:'Books',minAge:6,permissionPrice:30,lifecycleType:'progress',progressType:'reading',description:'Quick to read, fun to reread.',effectLabels:['Fun','Reading','Imagination'],uses:[{id:'read',label:'Read',minutes:25,progress:50,effects:{fun:10,stress:-3},skills:{reading:1,imagination:1.5},minAge:5,text:['You race through the panels, then go back to stare at the best one.','The art is incredible. The plot is ridiculous. You love it.']}]},
    toy: {name:'Toy',icon:'🧸',price:25,category:'Toys & games',minAge:0,permissionPrice:40,lifecycleType:'durable',repairable:true,agingPerYear:5,description:'A reusable toy appropriate for your age.',effectLabels:['Fun','Imagination'],uses:[{id:'play',label:'Play',minutes:40,effects:{fun:15},skills:{imagination:2},wear:[18,1,3],maxAge:13,text:['You invent a whole adventure, complete with a villain and a rescue.','The toy becomes a spaceship, then a dragon, then a teacher.','You play quietly for a long time, lost in it.']}]},
    puzzle: {name:'Jigsaw puzzle',icon:'🧩',price:18,category:'Toys & games',minAge:5,permissionPrice:35,lifecycleType:'progress',progressType:'pieces',description:'500 pieces. Patience pays off.',effectLabels:['Focus','Stress relief'],uses:[{id:'solve',label:'Work on puzzle',minutes:50,progress:20,effects:{fun:6,stress:-6},skills:{knowledge:.8,imagination:.8},text:['You finish the edges and feel unreasonably proud.','Half an hour hunting for one sky-blue piece.']}]},
    craftKit: {name:'Craft kit',icon:'✂️',price:16,category:'Arts & crafts',minAge:5,permissionPrice:35,lifecycleType:'finite',unitLabel:'projects',units:2,description:'Materials for two complete projects.',effectLabels:['Creativity','Fun'],uses:[{id:'craft',label:'Make a project',minutes:70,consume:50,effects:{fun:14,happiness:4},skills:{art:2.5,creativity:2},text:['You build something wobbly and glittery, and it is yours.','The instructions are confusing, so you improvise. It turns out better.']}]},
    artSupplies: {name:'Art supplies',icon:'🎨',price:25,category:'Arts & crafts',minAge:4,permissionPrice:45,lifecycleType:'finite',unitLabel:'sessions',units:15,description:'Paints, pencils and paper — about 15 sessions.',effectLabels:['Art','Creativity','Fun'],uses:[{id:'art',label:'Create art',minutes:60,consume:7,effects:{fun:11,happiness:3,stress:-3},skills:{art:3,creativity:2},text:['You paint until the colors start to mean something.','The first sketch is a disaster. The second is not bad at all.','You lose track of time mixing exactly the right shade.']}]},
    sketchbook: {name:'Sketchbook',icon:'✏️',price:12,category:'Arts & crafts',minAge:6,permissionPrice:30,lifecycleType:'finite',unitLabel:'pages',units:40,description:'40 good pages for drawing.',effectLabels:['Art','Creativity'],uses:[{id:'sketch',label:'Sketch',minutes:40,consume:5,effects:{fun:7,stress:-4},skills:{art:2,creativity:1},text:['You draw the view from the window three different ways.','A quick sketch of a face. The eyes came out surprisingly right.']}]},
    makeup: {name:'Makeup set',icon:'💄',price:45,category:'Beauty & care',minAge:13,permissionPrice:50,lifecycleType:'finite',unitLabel:'uses',units:30,description:'Cosmetics for about 30 looks.',effectLabels:['Confidence','Style'],uses:[{id:'apply',label:'Do makeup',minutes:20,consume:3.3,effects:{happiness:3},skills:{style:2},confidence:true,text:['You try a new look and keep glancing at the mirror.','Simple and clean today. It makes you stand a little straighter.']}]},
    skincare: {name:'Skincare set',icon:'🧴',price:30,category:'Beauty & care',minAge:11,permissionPrice:45,lifecycleType:'finite',unitLabel:'uses',units:40,description:'Cleanser and moisturizer, about 40 routines.',effectLabels:['Hygiene','Comfort'],uses:[{id:'routine',label:'Skincare routine',minutes:10,consume:2.5,effects:{hygiene:10,comfort:6,stress:-2},text:['A slow routine that feels like resetting the day.','Two minutes of care and your face feels fresh.']}]},
    sportsBall: {name:'Sports ball',icon:'⚽',price:30,category:'Sports',minAge:4,permissionPrice:45,lifecycleType:'durable',repairable:true,agingPerYear:6,description:'Kick it, throw it, practice with it.',effectLabels:['Sports','Fitness','Fun'],uses:[{id:'practice',label:'Practice outside',minutes:45,effects:{fun:9,energy:-8,stress:-5},skills:{sports:2.5,fitness:1.5},wear:[15,1,3],outdoor:true,text:['You practice until your passes start landing where you aim.','The ball rolls into a bush three times. Progress, though.']}]},
    jumpRope: {name:'Jump rope',icon:'🪢',price:9,category:'Sports',minAge:5,permissionPrice:25,lifecycleType:'durable',agingPerYear:5,description:'Cheap, simple cardio.',effectLabels:['Fitness'],uses:[{id:'jump',label:'Jump rope',minutes:20,effects:{energy:-7,stress:-4},skills:{fitness:2},wear:[10,1,2],text:['You count to a hundred, trip, and start again.','Your calves are burning by the end. Good.']}]},
    bicycle: {name:'Bicycle',icon:'🚲',price:220,category:'Sports',minAge:6,permissionPrice:50,lifecycleType:'durable',repairable:true,agingPerYear:4,transport:true,description:'Transport, exercise and freedom on two wheels.',effectLabels:['Fitness','Cycling','Fun','Transport'],uses:[{id:'ride',label:'Ride',minutes:45,effects:{fun:10,energy:-7,stress:-6},skills:{cycling:2.5,fitness:2},wear:[45,1,3],outdoor:true,text:['You ride a loop around the neighborhood with the wind in your face.','You find a new street with a long downhill. You ride it twice.','A pedal squeaks the whole way, but the ride is still great.']}]},
    boardGame: {name:'Board game',icon:'🎲',price:28,category:'Toys & games',minAge:5,permissionPrice:40,lifecycleType:'durable',agingPerYear:3,social:true,description:'Better with someone else at the table.',effectLabels:['Fun','Social'],uses:[{id:'play',label:'Play with family',minutes:60,effects:{fun:14,social:14},family:2,wear:[8,1,2],text:['The game gets competitive. Someone accuses someone of cheating. Everyone laughs.','You win by one point and are insufferable about it for an hour.']}]},
    bakedCookies: {name:'Homemade cookies',icon:'🍪',price:0,category:'Food & drinks',minAge:0,permissionPrice:0,lifecycleType:'perishable',stackable:true,maxQuantity:12,hunger:12,freshnessDays:5,shopHidden:true,description:'Baked at home. Lovely as a gift.',effectLabels:['Hunger','Mood']},
    cupcakes: {name:'Homemade cupcakes',icon:'🧁',price:0,category:'Food & drinks',minAge:0,permissionPrice:0,lifecycleType:'perishable',stackable:true,maxQuantity:12,hunger:16,freshnessDays:3,shopHidden:true,description:'Frosting slightly uneven, which is part of the charm.',effectLabels:['Hunger','Mood']},
    heartCookies: {name:'Heart cookies',icon:'💗',price:0,category:'Food & drinks',minAge:0,permissionPrice:0,lifecycleType:'perishable',stackable:true,maxQuantity:12,hunger:12,freshnessDays:5,shopHidden:true,description:'Valentine-shaped, made at home.',effectLabels:['Hunger','Mood']},
    heartWrap: {name:'Heart wrapping paper',icon:'💝',price:4,category:'Seasonal',minAge:5,permissionPrice:20,lifecycleType:'finite',unitLabel:'gifts',units:5,seasonal:['valentines'],description:'Hearts everywhere. About five gifts.',effectLabels:['Relationships']},
    kidsWatch: {name:"Kids' smartwatch",icon:'⌚',price:120,category:'Electronics',minAge:5,permissionPrice:0,lifecycleType:'device',repairable:true,agingPerYear:8,description:'Calls and messages with family only (Mom, Dad, grandparents). Common Grade 1 gift.',effectLabels:['Family calls'],uses:[]},
    headphones: {name:'Headphones',icon:'🎧',price:80,category:'Electronics',minAge:10,permissionPrice:50,lifecycleType:'device',repairable:true,agingPerYear:6,description:'Personal sound for music and focus.',effectLabels:['Music','Comfort'],uses:[{id:'listen',label:'Listen to music',minutes:30,effects:{fun:9,stress:-5,comfort:4},skills:{music:1},wear:[8,1,2],text:['You put on an album start to finish and let it fill the room in your head.','One song on repeat until you know every word.']}]},
    gameConsole: {name:'Game console',icon:'🎮',price:450,category:'Electronics',minAge:8,permissionPrice:40,lifecycleType:'device',repairable:true,agingPerYear:5,permission:'sharedDevice',description:'Home gaming system. Some games need one.',effectLabels:['Fun','Gaming'],uses:[{id:'play',label:'Play',minutes:60,effects:{fun:16,stress:-4},skills:{gaming:2},wear:[10,1,2],text:['You finally beat the level that has been beating you for a week.','Online match: chaos, shouting, a narrow win.']}]},
    videoGame: {name:'Video game',icon:'💿',price:50,category:'Toys & games',minAge:8,permissionPrice:40,lifecycleType:'progress',progressType:'story',requires:'gameConsole',permission:'sharedDevice',description:'A long story game. Needs a console.',effectLabels:['Fun','Gaming','Imagination'],uses:[{id:'play',label:'Play the story',minutes:75,progress:10,effects:{fun:16,stress:-4},skills:{gaming:2,imagination:1},text:['A big twist in the story. You did not see it coming.','You spend most of the session exploring instead of following the plot.']}]},
    tablet: {name:'Tablet',icon:'📱',price:350,category:'Electronics',minAge:8,permissionPrice:40,lifecycleType:'device',repairable:true,agingPerYear:6,permission:'sharedDevice',battery:true,description:'Schoolwork, videos and drawing apps.',effectLabels:['Study','Fun','Creativity'],uses:[{id:'study',label:'Study app',minutes:45,prep:4,skills:{knowledge:1.5},effects:{stress:1},battery:12,text:['A learning app quizzes you until the answers come quickly.']},{id:'draw',label:'Digital drawing',minutes:45,skills:{art:1.5,creativity:1.5},effects:{fun:9},battery:12,text:['You try digital brushes and undo far too many times.']},{id:'watch',label:'Watch videos',minutes:40,effects:{fun:11,stress:-3},battery:15,text:['One video turns into five.']}]},
    laptop: {name:'Laptop',icon:'💻',price:900,category:'Electronics',minAge:10,permissionPrice:35,lifecycleType:'device',repairable:true,agingPerYear:6,permission:'sharedDevice',battery:true,description:'Study, write, code, play or watch.',effectLabels:['Programming','Writing','Study','Gaming'],uses:[{id:'study',label:'Study',minutes:60,prep:7,skills:{knowledge:1.5},effects:{stress:2},battery:12,text:['You research, take notes and actually understand the topic better.','Too many tabs open, but the work gets done.']},{id:'code',label:'Practice programming',minutes:60,skills:{programming:3},effects:{fun:4,stress:2},battery:14,minAge:10,text:['Your program finally runs. Then it crashes. Then it runs again.','You fix a bug that took an hour to find. It was one missing character.']},{id:'write',label:'Write',minutes:45,skills:{writing:2.5,creativity:1},effects:{stress:-3},battery:10,text:['You write a page you are not ashamed of.','The words come slowly, then all at once.']},{id:'game',label:'Play a game',minutes:60,skills:{gaming:1.5},effects:{fun:14},battery:16,text:['A quick game becomes a long game.']},{id:'watch',label:'Watch something',minutes:50,effects:{fun:11,stress:-4},battery:15,text:['You watch an episode and immediately start the next one.']}]},
    phoneUsed: {name:'Used smartphone',icon:'📱',price:250,category:'Electronics',minAge:12,permissionPrice:35,lifecycleType:'device',phone:true,model:'Used smartphone',condition:68,repairable:true,agingPerYear:8,battery:true,description:'Cheaper, older phone. Independent use still follows phone-age rules.',effectLabels:['Messages','Apps']},
    phone: {name:'Smartphone',icon:'📱',price:600,category:'Electronics',minAge:12,permissionPrice:30,lifecycleType:'device',phone:true,model:'Smartphone',condition:100,repairable:true,agingPerYear:6,battery:true,description:'Mainstream new smartphone.',effectLabels:['Messages','Apps','Photos']},
    phoneFlagship: {name:'Flagship smartphone',icon:'📱',price:1100,category:'Electronics',minAge:14,permissionPrice:20,lifecycleType:'device',phone:true,model:'Flagship smartphone',condition:100,repairable:true,agingPerYear:5,battery:true,description:'Expensive premium phone.',effectLabels:['Messages','Apps','Camera']},
    giftBox: {name:'Small gift',icon:'🎁',price:20,category:'Gifts',minAge:6,permissionPrice:35,lifecycleType:'gift',stackable:true,maxQuantity:6,description:'A wrapped present to give someone.',effectLabels:['Relationships']},
    greetingCard: {name:'Greeting card',icon:'💌',price:4,category:'Gifts',minAge:5,permissionPrice:25,lifecycleType:'gift',stackable:true,maxQuantity:10,personal:true,description:'Write something real inside and give it.',effectLabels:['Relationships','Trust']},
    flowers: {name:'Flowers',icon:'💐',price:18,category:'Gifts',minAge:8,permissionPrice:35,lifecycleType:'perishable',gift:true,freshnessDays:5,description:'Beautiful for a few days.',effectLabels:['Relationships']},
    costume: {name:'Costume',icon:'🎭',price:30,category:'Seasonal',minAge:3,permissionPrice:40,lifecycleType:'wearable',slot:'outerwear',style:2,wearPerDay:.4,agingPerYear:8,seasonal:['halloween'],description:'For Halloween parties and trick-or-treating. A free homemade one works too.',effectLabels:['Fun','Style']},
    candyBag: {name:'Bag of candy',icon:'🍬',price:6,category:'Seasonal',minAge:3,permissionPrice:25,lifecycleType:'consumable',stackable:true,maxQuantity:10,hunger:10,seasonal:['halloween','christmas'],description:'For trick-or-treaters — or for you.',effectLabels:['Fun','Hunger']},
    decorations: {name:'Holiday decorations',icon:'🏮',price:15,category:'Seasonal',minAge:4,permissionPrice:35,lifecycleType:'finite',unitLabel:'holidays',units:3,seasonal:['halloween','christmas','lunarNewYear'],description:'Makes decorating more fun. Lasts about three holidays.',effectLabels:['Fun','Family']},
    giftWrap: {name:'Gift wrap',icon:'🎀',price:5,category:'Seasonal',minAge:5,permissionPrice:25,lifecycleType:'finite',unitLabel:'gifts',units:5,seasonal:['christmas','valentines','mothersDay','fathersDay'],description:'Wrapped gifts feel more special. About five gifts.',effectLabels:['Relationships']},
    usedCar: {name:'Used car',icon:'🚗',price:6500,category:'Transport',minAge:18,permissionPrice:0,lifecycleType:'durable',repairable:true,agingPerYear:5,transport:true,description:'An older personal car for adult transportation.',effectLabels:['Transport','Independence'],uses:[{id:'drive',label:'Drive somewhere',minutes:45,effects:{fun:5},wear:[30,1,2],minAge:18,text:['A local drive with the windows down.','You run errands and take the long way home.']}]}
  },
  chores: [
    {id:'tidyRoom',name:'Clean room',minAge:5,minutes:30,pay:[1,4],responsibility:4},
    {id:'dishes',name:'Wash dishes',minAge:7,minutes:25,pay:[1,4],responsibility:4},
    {id:'trash',name:'Take trash out',minAge:7,minutes:10,pay:[1,3],responsibility:3},
    {id:'pet',name:'Feed pet',minAge:6,minutes:10,pay:[0,3],responsibility:3},
    {id:'vacuum',name:'Vacuum',minAge:9,minutes:35,pay:[2,6],responsibility:5},
    {id:'laundry',name:'Help with laundry',minAge:10,minutes:40,pay:[2,6],responsibility:5},
    {id:'cookHelp',name:'Help cook',minAge:7,minutes:35,pay:[0,4],responsibility:4},
    {id:'babysit',name:'Babysit sibling',minAge:13,minutes:120,pay:[5,20],responsibility:7}
  ],
  standProducts: [
    {id:'lemonade',name:'Lemonade',baseCost:0.65,basePrice:3,weatherBonus:{Hot:22,Sunny:12,Rainy:-30,Stormy:-45}},
    {id:'cookies',name:'Cookies',baseCost:0.8,basePrice:3,weatherBonus:{Rainy:3,Stormy:-8}},
    {id:'cupcakes',name:'Cupcakes',baseCost:1.2,basePrice:4,weatherBonus:{Hot:-8,Rainy:3}},
    {id:'bracelets',name:'Bracelets',baseCost:1.5,basePrice:7,weatherBonus:{Sunny:5,Rainy:-12}},
    {id:'drawings',name:'Drawings',baseCost:0.5,basePrice:6,weatherBonus:{Sunny:5,Rainy:-15}}
  ],
  standLocations: [
    {id:'home',name:'Outside home',traffic:42,safety:95,minAge:6},
    {id:'park',name:'Near the park',traffic:65,safety:80,minAge:8},
    {id:'community',name:'Community event',traffic:82,safety:90,minAge:8},
    {id:'school',name:'School fundraiser',traffic:74,safety:96,minAge:7}
  ],
  clubDefs: {
    'Art Club': {skill:'art',actions:[['practice','Draw / create',60],['special','Prepare an exhibit',90],['social','Collaborate with member',45]]},
    'Reading Club': {skill:'reading',actions:[['practice','Read & discuss',60],['special','Reading challenge',90],['social','Talk about a book',40]]},
    'Music Group': {skill:'music',actions:[['practice','Rehearse',75],['special','Perform',120],['social','Jam with member',60]]},
    'Music': {skill:'music',actions:[['practice','Rehearse',75],['special','Perform',120],['social','Jam with member',60]]},
    'Sports Club': {skill:'sports',actions:[['practice','Train',75],['special','Play match',120],['social','Talk to teammate',45]]},
    'Football': {skill:'sports',actions:[['practice','Train',90],['special','Play match',120],['social','Talk to teammate',45]]},
    'Nature Club': {skill:'nature',actions:[['practice','Explore nature',75],['special','Community project',120],['social','Work with member',45]]},
    'Chess Club': {skill:'chess',actions:[['practice','Practice puzzles',45],['special','Play tournament game',90],['social','Play a friendly match',45]]},
    'Science Club': {skill:'science',actions:[['practice','Run experiment',75],['special','Build science project',120],['social','Work with teammate',60]]},
    'Drama': {skill:'acting',actions:[['practice','Rehearse',90],['special','Audition / perform',120],['social','Talk with cast',45]]},
    'Coding Club': {skill:'coding',actions:[['practice','Build project',90],['special','Hackathon session',150],['social','Pair program',60]]},
    'Debate': {skill:'debate',actions:[['practice','Practice argument',60],['special','Debate match',120],['social','Prep with teammate',60]]},
    'Photography': {skill:'photography',actions:[['practice','Photo walk',75],['special','Submit photo',60],['social','Shoot with member',60]]}
  },
  schoolEvents: {
    young: ['School Art Day','Reading Challenge','Mini Sports Day','Class Science Showcase'],
    middle: ['Math Challenge','Science Fair','Art Showcase','School Sports Meet','Coding Challenge'],
    high: ['Math Olympiad','Science Fair','Debate Tournament','Art Showcase','Coding Challenge','School Sports Meet','Talent Show']
  },
  jobs: {
    teen: [
      {id:'cafe',title:'Cafe assistant',pay:14,hours:4,minAge:16},
      {id:'retail',title:'Retail associate',pay:15,hours:4,minAge:16},
      {id:'babysitter',title:'Babysitter',pay:16,hours:3,minAge:16},
      {id:'tutor',title:'Tutor',pay:18,hours:3,minAge:16},
      {id:'dogwalk',title:'Dog walker',pay:13,hours:2,minAge:16},
      {id:'freelanceArt',title:'Freelance artist',pay:20,hours:3,minAge:16}
    ],
    adult: [
      {id:'office',title:'Office coordinator',pay:24,hours:8,minAge:18},
      {id:'developer',title:'Junior developer',pay:32,hours:8,minAge:18,skill:'Programming'},
      {id:'designer',title:'Junior designer',pay:28,hours:8,minAge:18,skill:'Art'},
      {id:'teacherAide',title:'Teaching assistant',pay:23,hours:7,minAge:18},
      {id:'creator',title:'Content creator',pay:22,hours:6,minAge:18},
      {id:'sales',title:'Sales associate',pay:25,hours:8,minAge:18}
    ]
  },
  placesOutside: [
    {id:'park',name:'Park',minAge:0,cost:0,minutes:90,weatherSensitive:true},
    {id:'playground',name:'Playground',minAge:2,maxAge:12,cost:0,minutes:90,weatherSensitive:true},
    {id:'library',name:'Library',minAge:5,cost:0,minutes:120},
    {id:'mall',name:'Mall',minAge:8,cost:8,minutes:180},
    {id:'cafe',name:'Cafe',minAge:12,cost:12,minutes:90},
    {id:'restaurant',name:'Restaurant',minAge:0,cost:22,minutes:120},
    {id:'cinema',name:'Cinema',minAge:8,cost:18,minutes:180},
    {id:'gym',name:'Gym',minAge:14,cost:15,minutes:90},
    {id:'supermarket',name:'Supermarket',minAge:5,cost:5,minutes:90},
    {id:'beach',name:'Beach',minAge:0,cost:10,minutes:240,weatherSensitive:true},
    {id:'friend',name:"Friend's house",minAge:6,cost:0,minutes:180}
  ],
  eventDefs: [
    {id:'familyOrdinary',minAge:0,maxAge:5,weight:8,cooldown:8,title:'A small family moment',text:'An ordinary moment with family becomes part of your early memory.',choices:['Lean into it','Keep playing']},
    {id:'relativeBabyShower',minAge:0,maxAge:99,weight:1,cooldown:150,title:'A baby shower in the family',text:'A relative is expecting a baby, and the family is gathering to celebrate.',choices:['Attend with family','Help choose a gift','Stay home']},
    {id:'birthdayInvite',deprecated:true,minAge:3,maxAge:18,weight:4,cooldown:35,title:'Birthday invitation',text:'Someone your age invites you to a birthday party.',choices:['Go','Ask caregiver / make a plan','Decline']},
    {id:'neighborhoodDay',minAge:4,maxAge:99,weight:2,cooldown:80,title:'Something is happening nearby',text:'Neighbors are gathering for a small community event.',choices:['Go see','Help out','Stay home']},
    {id:'neighborMoves',minAge:3,maxAge:99,weight:4,cooldown:45,title:'Someone is moving in nearby',text:'A moving truck stops in the neighborhood. New people can change old routines.',choices:['Pay attention','Leave them alone']},
    {id:'findCoins',minAge:5,maxAge:99,weight:3,cooldown:35,title:'Something on the ground',text:'You notice some money near the pavement.',choices:['Pick it up','Leave it']},
    {id:'rainPlan',minAge:3,maxAge:99,weight:5,cooldown:14,weather:['Rainy','Stormy'],title:'The weather changes the plan',text:'Rain disrupts what people around you expected to do today.',choices:['Adapt the plan','Stay home']},
    {id:'schoolRumor',minAge:10,maxAge:18,weight:4,cooldown:21,school:true,title:'Two versions of the same story',text:'A rumor is spreading at school and people disagree about what actually happened.',choices:['Stay out of it','Ask what happened','Pass it on']},
    {id:'friendInvite',deprecated:true,minAge:6,maxAge:60,weight:5,cooldown:12,title:'An invitation',text:'Someone you know wants to spend time together soon.',choices:['Accept','Maybe later','Decline']},
    {id:'parentGrades',minAge:7,maxAge:18,weight:3,cooldown:30,school:true,title:'A caregiver asks about school',text:'A caregiver wants to know how things are going academically.',choices:['Show everything','Downplay problems','Ask for help']},
    {id:'creativeNotice',minAge:10,maxAge:99,weight:1,cooldown:90,title:'Someone notices your work',text:'Something creative you made gets unexpected attention.',choices:['Share more','Keep it private']},
    {id:'celebritySighting',minAge:12,maxAge:99,weight:.35,cooldown:180,title:'A familiar face?',text:'You think you recognize a public figure nearby. It might become a story—or nothing at all.',choices:['Stay respectful','Say hello','Ignore it']}
  ]
});
