
// ---------- v7.2 Month calendar, date agenda & Life Planner ----------
let calView=null,calSelected=null,calFilter=null;
const CAL_CATS={workDay:'Work',wedding:'Family',program:'Activity',trip:'Family',conference:'School',term:'School',prom:'Social',tryout:'Club',plan:'Social',election:'Club',schoolDay:'School',exam:'Exam',homework:'Homework',clubSession:'Club',schoolEvent:'Competition',party:'Social',holiday:'Holiday',birthday:'Birthday',decision:'Decision',generic:'Other'};
const CAL_TONE={School:'school',Exam:'exam',Homework:'homework',Club:'club',Competition:'competition',Social:'social',Holiday:'holiday',Birthday:'birthday',Decision:'decision',Other:'other'};
function calShift(n){const v=calView||currentDate().slice(0,7),[y,m]=v.split('-').map(Number);calView=isoDate(new Date(Date.UTC(y,m-1+n,1))).slice(0,7)}
function monthLabel(ym){const [y,m]=ym.split('-').map(Number);return new Date(Date.UTC(y,m-1,1)).toLocaleDateString(undefined,{month:'long',year:'numeric',timeZone:'UTC'})}
function agendaFor(dateISO){
 const items=[],seen=new Set(),today=currentDate();
 for(const ev of [...S.calendar,...(S.archive?.calendar||[])].filter(e=>e.dateISO===dateISO)){if(seen.has(ev.id))continue;seen.add(ev.id);const d=obDef(ev.type);items.push({id:ev.id,cat:CAL_CATS[ev.type]||'Other',icon:d.icon,title:ev.type==='schoolDay'?'School day':ev.title,minute:ev.startMinute??ev.minute??null,end:ev.endMinute??null,status:ev.status||'Scheduled',location:ev.location||d.location||'',required:ev.required??d.required,participants:ev.participants||[],type:ev.type,attendance:ev.attendanceStatus||null})}
 for(const x of holidaysOn(dateISO))items.push({id:'hol-'+x.h.id,cat:'Holiday',icon:x.h.icon,title:x.h.durationDays>1?`${x.h.name} (day ${x.day})`:x.h.name,minute:null,status:dateISO<today?'Passed':'Holiday',type:'holiday',holiday:x});
 for(const mk of academicMarkers().filter(x=>x.dateISO===dateISO))items.push({id:mk.id,cat:'School',icon:mk.icon,title:mk.title,minute:null,status:'',type:'term'});
 if(sameMonthDay(S.dob,dateISO))items.push({id:'bday',cat:'Birthday',icon:'🎂',title:dateISO.slice(0,4)===S.dob.slice(0,4)?'You were born':`Your ${ordinal(Number(dateISO.slice(0,4))-Number(S.dob.slice(0,4)))} birthday`,minute:null,status:'',type:'birthday'});
 if(S.school?.subjects)for(const s of S.school.subjects){const hw=s.homework;if(hw?.dueDate===dateISO&&hw.status!=='None')items.push({id:hw.id||s.name,cat:'Homework',icon:'📒',title:`${s.name} homework due`,minute:480,status:HW_OPEN.includes(hw.status)?homeworkLabel(hw):hw.status,type:'homework'})}
 for(const p of [...S.pendingDecisions,...(S.archive?.pending||[])].filter(x=>x.resolveDate===dateISO||x.resolvedDate===dateISO&&x.resolved))items.push({id:p.id,cat:'Decision',icon:'⏳',title:p.title,minute:null,status:p.resolved?p.status:'Decision due',type:'decision'});
 // conflicts: two live, timed, non-school-day obligations overlapping (school-internal items are part of the school day)
 const timed=items.filter(i=>i.minute!=null&&i.end!=null&&!isTerminal(i.status)&&i.type!=='schoolDay'&&i.type!=='homework');
 for(const a of timed)for(const b of timed)if(a!==b&&a.minute<b.end&&b.minute<a.end){a.conflict=b.title;b.conflict=a.title}
 for(const p of birthdayPeopleOn(dateISO).filter(careAboutBirthday))items.push({id:'pbday-'+p.id+dateISO,type:'birthday',icon:'🎂',title:`${displayName(p)}'s birthday`,status:'Scheduled',category:'Social'});
 if(dateISO>=currentDate()&&S.age>=6)for(const b of freeBlocks(dateISO,90))items.push({id:'free-'+dateISO+b.from,type:'free',icon:'🟢',title:freeLabel(b),minute:b.from,status:'Free',category:'Free'});
 return items.sort((a,b)=>(a.minute??-1)-(b.minute??-1))
}
function monthGrid(ym,{mini=false}={}){
 const [y,m]=ym.split('-').map(Number),first=new Date(Date.UTC(y,m-1,1)),lead=(first.getUTCDay()+6)%7,days=new Date(Date.UTC(y,m,0)).getUTCDate(),today=currentDate(),sel=calSelected||today,cells=[];
 for(let i=0;i<lead;i++)cells.push('<div class="cal-cell is-empty"></div>');
 for(let d=1;d<=days;d++){const iso=`${ym}-${String(d).padStart(2,'0')}`,ag=agendaFor(iso).filter(i=>i.type!=='schoolDay'&&(!calFilter||i.cat===calFilter)),cats=[...new Set(ag.map(i=>i.cat))].slice(0,mini?3:4),hol=ag.find(i=>i.cat==='Holiday');
  cells.push(`<button class="cal-cell ${iso===today?'is-today':''} ${iso===sel?'is-selected':''} ${isWeekend(iso)?'is-weekend':''} ${S.school&&!isSchoolDay(iso)&&!isWeekend(iso)?'is-break':''}" data-cal-day="${iso}" aria-label="${formatDate(iso)}${ag.length?`, ${ag.length} item${ag.length===1?'':'s'}`:''}"><span class="cal-num">${d}</span>${!mini&&hol?`<span class="cal-hol">${hol.icon}</span>`:''}<span class="cal-dots">${cats.map(c=>`<i class="dot-${CAL_TONE[c]}"></i>`).join('')}</span>${!mini&&ag.some(i=>i.conflict)?'<span class="cal-warn" title="Schedule conflict">!</span>':''}</button>`)}
 return `<div class="cal-grid ${mini?'mini':''}">${['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(w=>`<div class="cal-wd">${mini?w[0]:w}</div>`).join('')}${cells.join('')}</div>`
}
function agendaListHtml(dateISO){
 const ag=agendaFor(dateISO).filter(i=>!calFilter||i.cat===calFilter),d=daysBetween(currentDate(),dateISO);
 const head=`<div class="agenda-head"><b>${formatDate(dateISO)}</b><small>${d===0?'Today':d===1?'Tomorrow':d===-1?'Yesterday':d>0?`in ${d} days`:`${-d} days ago`}${S.school&&isSchoolDay(dateISO)?' • school day':S.school&&!isWeekend(dateISO)?' • no school':''}</small></div>`;
 if(!ag.length)return head+'<p class="muted-text">Nothing on this day.</p>';
 return head+ag.map(i=>`<div class="agenda-item tone-${CAL_TONE[i.cat]}"><span class="agenda-time">${i.minute!=null?timeLabel(i.minute):'All day'}</span><div><b>${i.icon} ${esc(i.title)}</b><small>${esc(i.cat)}${i.location?` • ${esc(i.location)}`:''}${i.required?' • required':i.type==='clubSession'?' • optional (attendance tracked)':''}${i.attendance?` • ${esc(i.attendance)}`:''}${i.participants?.length?` • with ${esc(i.participants.slice(0,3).join(', '))}`:''}</small>${i.conflict?`<small class="urgent-text">⚠ Conflicts with ${esc(i.conflict)} — you can only be at one.</small>`:''}${i.holiday&&d===0?`<div class="holiday-acts">${availableActivities(Object.assign({},i.holiday,{days:0})).slice(0,4).map(a=>`<button class="small" data-holiday-act="${i.holiday.h.id}:${a.id}">${esc(a.label)}</button>`).join('')}</div>`:''}</div>${i.status&&!['Scheduled','Holiday',''].includes(i.status)?statusTag(i.status):''}</div>`).join('')
}
function calendarPanel(){
 const ym=calView||currentDate().slice(0,7),sel=calSelected||currentDate(),up=upcomingEvents(14),rec=S.school?.record;
 const recent=[...S.calendar].filter(e=>isTerminal(e.status)&&e.type!=='schoolDay').sort((a,b)=>stampOf(b.resolvedAt||{dateISO:b.dateISO}).localeCompare(stampOf(a.resolvedAt||{dateISO:a.dateISO}))).slice(0,10);
 const y=parseISO(currentDate()).getUTCFullYear(),hols=HOLIDAYS.filter(holidayObserved).map(h=>({h,d:holidayDate(h,y)})).filter(x=>x.d).sort((a,b)=>a.d.localeCompare(b.d));
 const filters=Object.keys(CAL_TONE).filter(c=>c!=='Other');
 return `<div class="dashboard"><section class="card wide" data-sub="month"><div class="cal-toolbar"><div class="cal-nav"><button class="small ghost" data-cal-month="-1" aria-label="Previous month">‹</button><h3>${esc(monthLabel(ym))}</h3><button class="small ghost" data-cal-month="1" aria-label="Next month">›</button><button class="small" data-cal-today="1">Today</button></div><div class="filter-row">${filters.map(c=>`<button class="filter-chip ${calFilter===c?'active':''}" data-cal-filter="${c}"><i class="dot-${CAL_TONE[c]}"></i>${c}</button>`).join('')}</div></div><div class="cal-layout">${monthGrid(ym)}<div class="cal-agenda">${agendaListHtml(sel)}</div></div></section>
 <section class="card" data-sub="today"><h3>Today • ${esc(weekday())}</h3>${agendaListHtml(currentDate())}</section><section class="card" data-sub="today"><h3>Now</h3>${statRow('Time',timeLabel(currentMinute()))}${statRow('School',esc(schoolDayStatus()))}${statRow('Bedtime',S.age<18?timeLabel(bedtimeMinute()):'Your choice')}${statRow('Calendar profile',esc(calendarProfile().region))}<h4>Pending decisions</h4>${pendingHtml()}</section>
 <section class="card wide" data-sub="upcoming"><h3>Upcoming</h3>${up.map(e=>{const d=daysBetween(currentDate(),e.dateISO);return `<div class="calendar-row"><div><b>${e.icon||typeIcon(e.type)} ${esc(e.title)}</b><small>${formatDate(e.dateISO)}${e.minute!=null&&e.type!=='homework'?` • ${timeLabel(e.minute)}`:''}${e.location?` • ${esc(e.location)}`:''}${e.required?' • required':''}</small></div><div class="inline-actions">${e.status&&e.status!=='Scheduled'?statusTag(e.status):''}<span class="countdown">${d===0?'TODAY':d===1?'TOMORROW':`${d} days`}</span></div></div>`}).join('')||'<p class="muted-text">Nothing scheduled.</p>'}</section>
 <section class="card" data-sub="history"><h3>Recently resolved</h3>${recent.map(e=>`<div class="calendar-row"><div><b>${typeIcon(e.type)} ${esc(e.title)}</b><small>${formatDate(e.dateISO)}${e.resolutionReason?` • ${esc(e.resolutionReason)}`:''}</small></div>${statusTag(e.status)}</div>`).join('')||'<p class="muted-text">Nothing resolved recently.</p>'}</section><section class="card" data-sub="history"><h3>Holidays this year (${calendarProfile().region})</h3>${hols.map(x=>`<div class="calendar-row"><div><b>${x.h.icon} ${esc(x.h.name)}</b><small>${formatDate(x.d)}</small></div><span class="countdown">${x.d<currentDate()?'passed':daysBetween(currentDate(),x.d)+'d'}</span></div>`).join('')}</section></div>`
}
function renderPlanner(){
 const host=$('planner');if(!host||!S)return;const ym=currentDate().slice(0,7),today=agendaFor(currentDate()).filter(i=>i.type!=='birthday'||true),next=upcomingEvents(6).filter(e=>e.dateISO>currentDate()).slice(0,5),pend=pendingOpen().slice(0,3),hol=upcomingHolidays(3);
 host.innerHTML=`<div class="planner-head"><b>${esc(monthLabel(ym))}</b><button class="small ghost planner-close" data-planner-toggle="1" aria-label="Close planner">×</button></div>${monthGrid(ym,{mini:true})}<h4>Weather</h4>${weatherForecastHtml()}<h4>Today</h4>${today.length?today.slice(0,6).map(i=>`<div class="pl-row ${isTerminal(i.status)?'done':''}"><span>${i.icon}</span><b>${esc(i.title)}</b><small>${i.minute!=null?timeLabel(i.minute):''}</small></div>`).join(''):'<p class="muted-text">Free day.</p>'}<h4>Next up</h4>${next.map(e=>`<div class="pl-row"><span>${e.icon||typeIcon(e.type)}</span><b>${esc(e.title)}</b><small>${daysBetween(currentDate(),e.dateISO)}d</small></div>`).join('')||'<p class="muted-text">Nothing scheduled.</p>'}${pend.length?`<h4>Pending</h4>${pend.map(p=>`<div class="pl-row"><span>⏳</span><b>${esc(p.title)}</b><small>${p.resolveDate?daysBetween(currentDate(),p.resolveDate)+'d':esc(p.status)}</small></div>`).join('')}`:''}<h4>Holidays</h4>${hol.map(x=>`<div class="pl-row"><span>${x.h.icon}</span><b>${esc(x.h.name)}</b><small>${daysBetween(currentDate(),x.dateISO)}d</small></div>`).join('')}`
}
document.addEventListener('click',e=>{const b=e.target.closest('#planner button');if(!b||!S)return;if(b.dataset.calDay){calSelected=b.dataset.calDay;calView=b.dataset.calDay.slice(0,7);active='calendar';UI.subTab.calendar='month';saveUI();document.body.classList.remove('planner-open');render()}else if(b.dataset.plannerToggle)document.body.classList.toggle('planner-open')});
