
// =====================================================================
// v7.3 B1 — University brochures (location, campus, dorms, Greek life, clubs, facilities, events, strengths),
// unique tuition per school, and facilities that actually matter while you study there
// =====================================================================
const FACILITY={cafeteria:'🍽️ Cafeteria',gym:'🏋️ Gym',pool:'🏊 Pool',stadium:'🏟️ Stadium',library24:'📚 24/7 library',library:'📚 Library',labs:'🔬 Research labs',makerspace:'🛠️ Makerspace',theater:'🎭 Theater',artStudio:'🎨 Art studios',concertHall:'🎵 Concert hall',boathouse:'🚣 Boathouse'};
const CAMPUS={
 uni0:{tuition:58400,fee:95,need:94,city:'Northbridge',km:4,setting:'Historic city campus',size:'210 acres',students:21000,style:'Ivy-covered brick halls around a central green',dorm:1150,greek:'high',clubs:['Rowing Club','Model UN','Northbridge A Cappella','Entrepreneurs Society'],fac:['cafeteria','gym','pool','stadium','library24','labs','theater','concertHall'],events:'weekly',concert:'Ava Sterling (pop singer, alumna)',strengths:['Law & Politics','Economics','Medicine']},
 uni1:{tuition:54900,fee:90,need:93,city:'Halden Valley',km:18,setting:'Small liberal-arts college',size:'95 acres',students:2600,style:'Rolling green quad with old stone chapels',dorm:980,greek:'low',clubs:['Literary Review','Philosophy Circle','Outdoor Club','Chamber Orchestra'],fac:['cafeteria','gym','library24','theater','artStudio','concertHall'],events:'twice a month',concert:'The Lanterns (indie band, alumni)',strengths:['Literature','Philosophy','Fine Arts']},
 uni2:{tuition:46200,fee:85,need:90,city:'Westfield Tech Park',km:7,setting:'Science & technology campus',size:'140 acres',students:11000,style:'Modern glass buildings and labs',dorm:1040,greek:'low',clubs:['Robotics Team','Hackathon Club','Rocketry Society','Esports League'],fac:['cafeteria','gym','library24','labs','makerspace'],events:'weekly',concert:null,festival:'an annual tech fest',strengths:['Computer Science','Engineering','Physics']},
 uni3:{tuition:41750,fee:75,need:88,city:'Marlow (city center)',km:1.5,setting:'Urban campus',size:'40 acres',students:26000,style:'High-rise buildings right downtown',dorm:1220,greek:'medium',clubs:['Debate Union','Film Society','Finance Club','Marlow Radio'],fac:['cafeteria','gym','pool','library24','theater'],events:'weekly',concert:'DJ Kairo (electronic artist, alumnus)',strengths:['Business','Communications','Media']},
 uni4:{tuition:38900,fee:70,need:87,city:'Ashford (suburbs)',km:15,setting:'Big sports university',size:'640 acres',students:30000,style:'Huge campus built around the football stadium',dorm:890,greek:'high',clubs:['Ashford Cheer','Marching Band','Hiking Club','Volunteer Corps'],fac:['cafeteria','gym','pool','stadium','library'],events:'weekly',concert:'Mason Reyes (country singer, alumnus)',strengths:['Sports Science','Nursing','Education']},
 uni5:{tuition:31300,fee:65,need:83,city:'Lakeview',km:25,setting:'Lakeside college town',size:'180 acres',students:14000,style:'Lakeside lawns and a historic boathouse',dorm:760,greek:'medium',clubs:['Sailing Club','Environmental Society','Photography Club'],fac:['cafeteria','gym','pool','library','boathouse'],events:'twice a month',concert:null,festival:'Lakefest, with local bands',strengths:['Biology','Environmental Science','Psychology']},
 uni6:{tuition:29600,fee:60,need:80,city:'Brighton arts district',km:3,setting:'Art school',size:'25 acres',students:6500,style:'Converted warehouses and galleries',dorm:870,greek:'none',clubs:['Life Drawing Society','Indie Film Collective','Jazz Ensemble','Fashion Lab'],fac:['cafeteria','artStudio','theater','concertHall','library'],events:'weekly',concert:'Nova Lane (singer-songwriter, alumna)',strengths:['Fine Arts','Music','Design']},
 uni7:{tuition:26800,fee:55,need:81,city:'Kingsley',km:12,setting:'Mid-size university',size:'220 acres',students:17000,style:'Red-brick campus with a busy student union',dorm:720,greek:'medium',clubs:['Kingsley Debate','Chess Society','Volunteer Corps','Cultural Association'],fac:['cafeteria','gym','stadium','library'],events:'monthly',concert:null,festival:'a spring fair',strengths:['Psychology','Education','History']},
 uni8:{tuition:14200,fee:50,need:75,city:'Riverside',km:9,setting:'Large public university',size:'900 acres',students:34000,style:'Sprawling riverside campus',dorm:640,greek:'high',clubs:['Intramural Soccer','Gaming Society','Hip-Hop Dance Crew'],fac:['cafeteria','gym','stadium','library'],events:'weekly',concert:null,festival:'a homecoming concert',strengths:['Engineering','Business','Nursing']},
 uni9:{tuition:12600,fee:45,need:73,city:'Pinecrest',km:40,setting:'Small-town public university',size:'300 acres',students:9000,style:'Campus in the middle of a pine forest',dorm:560,greek:'low',clubs:['Outdoor Adventure Club','Forestry Society','Folk Music Club'],fac:['cafeteria','gym','library'],events:'monthly',concert:null,strengths:['Environmental Science','Agriculture','Education']},
 uni10:{tuition:10900,fee:40,need:71,city:'Eastgate',km:6,setting:'Commuter college',size:'60 acres',students:7500,style:'Compact, practical buildings near the train line',dorm:610,greek:'none',clubs:['Student Union','Coding Society','Business Club'],fac:['cafeteria','gym','library'],events:'monthly',concert:null,strengths:['Business','Computer Science','Nursing']},
 uni11:{tuition:4300,fee:0,need:0,city:'Cedar Valley',km:11,setting:'Community college',size:'35 acres',students:5000,style:'Small commuter campus',dorm:0,greek:'none',clubs:['Student Government','Culinary Club'],fac:['cafeteria','library'],events:'rarely',concert:null,strengths:['Transfer programs','Culinary Arts','Nursing']}
};
for(const u of UNIS)Object.assign(u,CAMPUS[u.id]||{});
const EVENT_ODDS={weekly:14,'twice a month':7,monthly:3,rarely:1};
const GREEK_LABEL={none:'No fraternities or sororities',low:'A few small fraternities and sororities',medium:'Active fraternities and sororities',high:'Big Greek life (lots of parties)'};
function uniById(id){return UNIS.find(x=>x.id===id)}
function mySchool(){return S.uni?.enrolled?UNIS.find(x=>x.name===S.uni.school):null}
function hasFac(k){return !!mySchool()?.fac?.includes(k)}
function brochureHtml(x){return `<p class="muted-text">${esc(x.setting)} • ${esc(x.city)}, ${x.km} km from the city center • ${esc(x.size)} • ${x.students.toLocaleString()} students</p><p>${esc(x.style)}.</p>
 ${statRow('Tuition',`${money(x.tuition)}/year • application fee ${x.fee?money(x.fee):'free'}`)}${statRow('Dorms',x.dorm?`Yes — ${money(x.dorm)}/month`:'No dorms (commuter school)')}${statRow('Greek life',GREEK_LABEL[x.greek])}${statRow('Campus events',x.events.replace(/^./,c=>c.toUpperCase()))}
 <h4>Facilities</h4><div class="fac-list">${Object.entries(FACILITY).map(([k,l])=>`<span class="fac ${x.fac.includes(k)?'yes':'no'}">${x.fac.includes(k)?'':'✕ '}${l}</span>`).join('')}</div>
 <h4>Signature clubs</h4><p>${x.clubs.map(esc).join(' • ')}</p>
 <h4>Known for</h4><p>${x.strengths.map(esc).join(' • ')}</p>
 <h4>Big events</h4><p>${x.concert?`Annual concert headlined by ${esc(x.concert)}.`:x.festival?`No big-name concert, but ${esc(x.festival)}.`:'No big annual events.'}</p>`}
function openBrochure(id){const x=uniById(id);if(!x)return;openModal(`${x.name} • brochure`,brochureHtml(x))}
// ---------- living there ----------
function syncDormRent(){const x=mySchool();if(x)HOUSING.dorm.rent=x.dorm||0}
function campusWorkout(kind){const x=mySchool();if(!x)return;if(!x.fac.includes(kind)){toast(`${x.name} has no ${kind==='pool'?'pool':'gym'}.`);return}if(S.energy<15){toast('Too tired.');return}const g=practiceSkill('fitness',1);if(g===0&&S.lastFarmNote){toast(S.lastFarmNote);S.lastFarmNote=null;return}advanceTime(60,{silent:true});S.energy=clamp(S.energy-12);S.stress=clamp(S.stress-6);S.happiness=clamp(S.happiness+3);log(kind==='pool'?'Campus pool':'Campus gym',kind==='pool'?'Laps until your arms give up. Great for your head, too.':'A sweaty hour at the campus gym.')}
function greekParty(){const x=mySchool();if(!x)return;if(x.greek==='none'){toast(`${x.name} has no fraternities or sororities.`);return}if(currentMinute()<1140){toast('Parties start in the evening.');return}const p=freshPeers(1)[0];advanceTime(150,{silent:true});S.needs.fun=clamp(S.needs.fun+20);S.needs.social=clamp(S.needs.social+20);S.energy=clamp(S.energy-15);S.happiness=clamp(S.happiness+4);
 const met=p&&chance({low:35,medium:55,high:75}[x.greek]);if(met){const np=personFromNpc(p,'friend',`met at a party at ${x.name}`);np.rel=48;S.people.push(np)}log('Party on Greek Row',`Loud music, a sticky floor, a crowded kitchen.${met?` You end up talking to ${p.fullName} for an hour.`:''}`)}
function campusDaily(){const x=mySchool();if(!x||SIM.skipping)return;syncDormRent();if(chance(EVENT_ODDS[x.events]||2)){S.needs.fun=clamp(S.needs.fun+8);S.happiness=clamp(S.happiness+2);log(`Campus life • ${x.name}`,rand([`A ${rand(['movie night on the lawn','food truck festival','open-mic night','career fair','charity run'])} on campus.`,`The ${rand(x.clubs)} puts on an event everyone talks about.`]))}
 const md=currentDate().slice(5);S.uni.concerts=S.uni.concerts||{};const yk=S.uni.yearKey;if((x.concert||x.festival)&&!S.uni.concerts[yk]&&(md==='10-15'||md==='04-15')){S.uni.concerts[yk]=true;queueEvent({type:'campusConcert',title:x.concert?`${x.concert.split(' (')[0]} live on campus`:`Campus: ${x.festival}`,text:x.concert?`${x.concert} is coming back to perform at ${x.name} tonight.`:`Tonight: ${x.festival}.`,priority:3,expiresDays:1,choices:[{id:'go',label:'Go with friends'},{id:'skip',label:'Stay in'}]})}}
function campusEventChoice(e,id){if(e.type!=='campusConcert')return false;if(id==='go'){advanceTime(180,{silent:true});S.needs.fun=clamp(S.needs.fun+30);S.needs.social=clamp(S.needs.social+20);S.happiness=clamp(S.happiness+8);S.milestones.unshift({dateISO:currentDate(),age:S.age,title:'🎤 Campus concert',text:e.title+'.'});log('Concert night','The whole campus sings along. One of the best nights of the year.',true)}else log('Stayed in','You hear the music from your window.');return true}
function campusClick(b){const d=b.dataset;if(d.uniBrochure){openBrochure(d.uniBrochure);return true}if(d.campus){if(d.campus==='party')greekParty();else campusWorkout(d.campus);save();render();return true}return false}
function campusActionsHtml(){const x=mySchool();if(!x)return '';return `<div class="inline-actions">${x.fac.includes('gym')?'<button class="small ghost" data-campus="gym">Campus gym (1 h)</button>':''}${x.fac.includes('pool')?'<button class="small ghost" data-campus="pool">Swim laps (1 h)</button>':''}${x.greek!=='none'?'<button class="small ghost" data-campus="party">Greek Row party (evening)</button>':''}<button class="small ghost" data-uni-brochure="${x.id}">Campus guide</button></div>`}
