// =====================================================================
// H3.1 — Parent/Guardian Authority + Central Decision Ledger
// Major requests use a stable parent/guardian authority and remember the
// result. Caregiver/support status is intentionally NOT authority status.
// =====================================================================
const DECISION_LEDGER_LIMIT=180;
function isActualGuardian(p){return !!p&&!p.deceased&&(p.role==='guardian'||p.relation==='guardian'||p.isGuardian===true||p.legalGuardian===true||p.guardian===true)}
function decisionAuthorities(){
 const out=[];for(const rel of ['mother','father']){const p=familyByRelation(rel);if(p&&!p.deceased&&!out.some(x=>x.id===p.id))out.push(p)}
 for(const p of S.people||[])if(isActualGuardian(p)&&!out.some(x=>x.id===p.id))out.push(p);
 return out
}
function decisionAuthorityPerson(preferredId=null){const a=decisionAuthorities();if(preferredId){const p=a.find(x=>x.id===preferredId);if(p)return p}return a[0]||null}
function decisionMakerLabel(pOrId){const p=typeof pOrId==='string'?personById(pOrId):pOrId;if(!p)return 'Your guardian';if(p.relation==='mother')return 'Mom';if(p.relation==='father')return 'Dad';return firstName(p)||familyRelationLabel(p)||'Your guardian'}
function stableDecisionValue(v){if(Array.isArray(v))return v.map(stableDecisionValue);if(v&&typeof v==='object'){const o={};for(const k of Object.keys(v).sort())o[k]=stableDecisionValue(v[k]);return o}return v}
function decisionContextSignature(requestType,targetKey,context={}){return JSON.stringify(stableDecisionValue({requestType,targetKey:targetKey??null,context:context||{}}))}
function normalizeDecisionRecord(r){
 r.id=r.id||uid('decision');r.requesterId=r.requesterId||'player';r.requestType=r.requestType||'request';r.targetKey=r.targetKey??null;r.createdDate=r.createdDate||currentDate();r.createdMinute=Number.isFinite(Number(r.createdMinute))?Number(r.createdMinute):0;r.outcome=r.outcome||'Pending';r.reason=r.reason||'';r.requirements=r.requirements||null;r.reconsiderAfter=r.reconsiderAfter||null;r.resolved=!!r.resolved;r.expired=!!r.expired;r.contextSignature=r.contextSignature||decisionContextSignature(r.requestType,r.targetKey,r.context||{});return r
}
function decisionRequirementMet(r){const q=r?.requirements;if(!q)return false;if(q.type==='saveHalf')return availableFunds()>=Number(q.target||Infinity);if(q.type==='grades')return !!S.school&&schoolAverage()>=Number(q.target||Infinity);if(q.type==='chores')return (S.choresDone||0)>=Number(q.target||Infinity);if(q.type==='date')return currentDate()>=String(q.target||'9999-12-31');return false}
function decisionReusable(r){if(!r||r.expired)return false;if(decisionRequirementMet(r))return false;if(r.reconsiderAfter&&currentDate()>=r.reconsiderAfter)return false;return true}
function pruneDecisionLedger(){
 S.decisionLedger=Array.isArray(S.decisionLedger)?S.decisionLedger:[];if(S.decisionLedger.length<=DECISION_LEDGER_LIMIT)return;
 const keep=S.decisionLedger.filter(r=>decisionReusable(r)||!r.resolved),old=S.decisionLedger.filter(r=>!keep.includes(r)).sort((a,b)=>String(b.createdDate).localeCompare(String(a.createdDate))||Number(b.createdMinute||0)-Number(a.createdMinute||0));
 S.decisionLedger=[...keep,...old.slice(0,Math.max(0,DECISION_LEDGER_LIMIT-keep.length))]
}
function normalizeDecisionLedger(){
 S.decisionLedger=Array.isArray(S.decisionLedger)?S.decisionLedger:[];const seen=new Set();S.decisionLedger=S.decisionLedger.map(normalizeDecisionRecord).filter(r=>{if(seen.has(r.id))return false;seen.add(r.id);return true});
 // Deterministically link legacy purchase/school approval pendings without rerolling them.
 for(const p of S.pendingDecisions||[]){if(!['purchaseConsideration','conditionalPurchase','clubApproval','contestApproval'].includes(p.type))continue;const authority=decisionAuthorityPerson(p.decisionMakerId);if(authority&&!p.decisionMakerId)p.decisionMakerId=authority.id;if(p.decisionId)continue;const id=`decision:${p.id}`;let r=S.decisionLedger.find(x=>x.id===id);if(!r){r=normalizeDecisionRecord({id,requesterId:'player',decisionMakerId:p.decisionMakerId||null,requestType:p.type,targetKey:p.payload?.key||p.payload?.offerId||p.payload?.contestId||null,createdDate:p.createdDate||currentDate(),createdMinute:0,outcome:p.status||'Pending',reason:p.detail||'',requirements:p.type==='conditionalPurchase'?{type:p.payload?.condition,target:p.payload?.target}:null,reconsiderAfter:p.resolveDate||null,resolved:!!p.resolved,context:{migratedPendingId:p.id}});S.decisionLedger.push(r)}p.decisionId=id}
 pruneDecisionLedger();return S.decisionLedger
}
function findDecision(requestType,targetKey,context={},decisionMakerId=null){normalizeDecisionLedger();const sig=decisionContextSignature(requestType,targetKey,context);return [...S.decisionLedger].reverse().find(r=>r.requestType===requestType&&r.targetKey===targetKey&&r.contextSignature===sig&&(!decisionMakerId||r.decisionMakerId===decisionMakerId)&&decisionReusable(r))||null}
function recordDecision(spec){normalizeDecisionLedger();const r=normalizeDecisionRecord(Object.assign({id:uid('decision'),requesterId:'player',createdDate:currentDate(),createdMinute:currentMinute(),context:{}},spec));if(!r.contextSignature)r.contextSignature=decisionContextSignature(r.requestType,r.targetKey,r.context);S.decisionLedger.push(r);pruneDecisionLedger();return r}
function requestDecision({requestType,targetKey=null,context={},preferredDecisionMakerId=null,decide}){
 const maker=decisionAuthorityPerson(preferredDecisionMakerId);if(S.age<18&&!maker)return {record:null,reused:false,error:'No parent or guardian decision authority is available.'};const makerId=maker?.id||null,old=findDecision(requestType,targetKey,context,makerId);if(old)return {record:old,reused:true,maker};const result=decide?decide(maker):{};const rec=recordDecision(Object.assign({requestType,targetKey,context,decisionMakerId:makerId},result||{}));return {record:rec,reused:false,maker}
}
function bindPendingDecisionAuthority(p){if(!p||!['purchaseConsideration','conditionalPurchase','clubApproval','contestApproval'].includes(p.type))return p;const maker=decisionAuthorityPerson(p.decisionMakerId);if(maker)p.decisionMakerId=maker.id;return p}
function resolveDecisionRecord(id,outcome,reason='',extra={}){const r=(S.decisionLedger||[]).find(x=>x.id===id);if(!r)return null;Object.assign(r,extra);r.outcome=outcome||r.outcome;r.reason=reason||r.reason;r.resolved=true;r.resolvedDate=currentDate();return r}
function purchaseDecisionContext(d,parentPays,qty=1){return {kind:parentPays?'parentPurchase':'ownMoneyPermission',qty:Number(qty)||1,wealth:S.wealth,price:d.price*(Number(qty)||1),gradeBand:S.school?Math.floor(schoolAverage()/5)*5:null}}
function replayPurchaseDecision(r,d){const who=decisionMakerLabel(r.decisionMakerId);if(r.outcome==='Yes'||r.outcome==='Approved'){log(`${who}'s answer`,`${who} already said yes to ${d.name}.`);return true}if(r.outcome==='Considering'){log(`${who} is still considering it`,`${d.name}: the decision has not changed${r.reconsiderAfter?` before ${formatDate(r.reconsiderAfter)}`:''}.`);return false}if(['Birthday','Christmas'].includes(r.outcome)){log(`${who}'s answer`,`${d.name} is still a ${r.outcome} request.`);return false}if(r.requirements){log(`${who}'s condition`,r.reason||`The condition for ${d.name} still applies.`);return false}log(`${who}'s answer`,`${who} already said no to ${d.name} for now.`);return false}
function caregiverRequestOptions(key){
 const d=catalogItem(key);if(!d)return;const context=purchaseDecisionContext(d,true,1),existing=findDecision('parentPurchase',key,context,decisionAuthorityPerson()?.id||null);if(existing){replayPurchaseDecision(existing,d);return}
 const score=purchaseScore(d,true);const q=requestDecision({requestType:'parentPurchase',targetKey:key,context,decide:(maker)=>{const roll=Math.random()*100,who=decisionMakerLabel(maker);
  if(score>=78||roll<Math.max(5,score-58))return {outcome:'Yes',reason:`${who} approved the purchase.`,resolved:true};
  if(score>=55||roll<55){const days=2+Math.floor(Math.random()*5),date=addDays(currentDate(),days);return {outcome:'Considering',reason:`${who} is thinking about it.`,reconsiderAfter:date,resolved:false,meta:{resolveDate:date}}}
  if(score>=38){const variants=[];if(S.traditions.christmas)variants.push('Christmas');variants.push('Birthday','saveHalf','chores');if(S.school&&S.age>=6)variants.push('grades');const v=rand(variants);if(v==='Birthday'||v==='Christmas')return {outcome:v,reason:`${who} suggests waiting for ${v}.`,requirements:{type:'date',target:v==='Birthday'?nextBirthday():nextOccurrence(12,25)},resolved:false};if(v==='saveHalf'){const target=Math.ceil(d.price/2);return {outcome:'Partial payment',reason:`Save ${money(target)}; ${who} may cover the rest.`,requirements:{type:'saveHalf',target},resolved:false}}if(v==='grades'){const target=Math.min(92,Math.max(72,Math.round(schoolAverage()+5)));return {outcome:'Improve grades first',reason:`Raise your academic average to ${target}% or higher.`,requirements:{type:'grades',target},resolved:false}}const target=(S.choresDone||0)+4;return {outcome:'Complete chores first',reason:'Complete 4 more household chores, then ask again.',requirements:{type:'chores',target},resolved:false}}
  return {outcome:'No',reason:'Price, finances, household rules and your history all mattered.',reconsiderAfter:addDays(currentDate(),1),resolved:true}
 }});if(q.error){toast(q.error);return}const r=q.record,who=decisionMakerLabel(r.decisionMakerId);
 if(r.outcome==='Yes'){addItem(key,'caregiver purchase');S.family.closeness=clamp(S.family.closeness+2);feedback(`${who} said yes`,`${d.name} was bought for you.`,5);return}
 if(r.outcome==='Considering'){const p=createPending({type:'purchaseConsideration',title:`${d.name} request`,resolveDate:r.meta?.resolveDate||r.reconsiderAfter,payload:{key},status:'Considering',detail:`${who} is thinking about it. Decision expected ${formatDate(r.meta?.resolveDate||r.reconsiderAfter)}.`,decisionId:r.id,decisionMakerId:r.decisionMakerId});log(`${who} will think about it`,`${d.name}: a decision is scheduled.`);return p}
 if(['Birthday','Christmas'].includes(r.outcome)){requestFutureGift(key,r.outcome,r);return}
 if(r.requirements){const type=r.requirements.type,target=r.requirements.target;createPending({type:'conditionalPurchase',title:type==='saveHalf'?`Save toward ${d.name}`:type==='grades'?`Grades for ${d.name}`:`Earn ${d.name}`,resolveDate:null,payload:{key,condition:type,target},status:'Conditional',detail:r.reason,decisionId:r.id,decisionMakerId:r.decisionMakerId});log(`${who}'s condition`,r.reason);return}
 log(`${who} said no`,`${d.name}: ${r.reason}`);setEmotion('Disappointed',`You were told no about ${d.name}.`,40)
}
function requestFutureGift(key,occasion,linkedDecision=null){const d=catalogItem(key);if(!d)return;const context={occasion,wealth:S.wealth};let r=linkedDecision;if(!r){const q=requestDecision({requestType:'futureGift',targetKey:key,context,decide:(maker)=>({outcome:occasion,reason:`${decisionMakerLabel(maker)} will revisit this at ${occasion}.`,requirements:{type:'date',target:occasion==='Birthday'?nextBirthday():nextOccurrence(12,25)},resolved:false})});if(q.error){toast(q.error);return}r=q.record}const old=S.giftRequests.find(x=>!x.resolved&&x.itemKey===key&&x.occasion===occasion);if(old){old.decisionId=old.decisionId||r.id;old.decisionMakerId=old.decisionMakerId||r.decisionMakerId;log('Asked again',`${d.name} is still waiting for ${occasion}; ${decisionMakerLabel(r.decisionMakerId)} has not changed the answer.`);return}S.giftRequests.push({id:uid('giftreq'),itemKey:key,item:d.name,occasion,requestedDate:currentDate(),requestedAge:S.age,begging:1,chancePenalty:0,resolved:false,status:`Waiting for ${occasion}`,decisionId:r.id,decisionMakerId:r.decisionMakerId});log('Future gift request',`${decisionMakerLabel(r.decisionMakerId)} agrees to revisit ${d.name} for ${occasion}.`)}
function buyWithOwnMoney(key,qty=1){
 qty=Math.max(1,Math.min(10,Math.round(Number(qty)||1)));const d=catalogItem(key),check=canBuyItem(key,qty);if(!check.ok){toast(check.reason);return}const total=d.price*qty;
 if(check.needsPermission&&S.age<18){const context=purchaseDecisionContext(d,false,qty),q=requestDecision({requestType:'ownMoneyPurchasePermission',targetKey:key,context,decide:(maker)=>{const ok=purchaseScore(d,false)>=45;return {outcome:ok?'Yes':'No',reason:ok?`${decisionMakerLabel(maker)} approved spending your own money.`:`${decisionMakerLabel(maker)} does not approve this purchase for now.`,reconsiderAfter:ok?null:addDays(currentDate(),1),resolved:true}}});if(q.error){toast(q.error);return}if(q.record.outcome!=='Yes'){log('Purchase permission denied',q.record.reason);setEmotion('Disappointed','A purchase request was denied.',45);return}log('Purchase approved',q.reused?`${decisionMakerLabel(q.record.decisionMakerId)}'s approval still stands.`:q.record.reason)}
 if(!spendOwn(total)){toast('Not enough money.');return}addItem(key,'own money',null,{quantity:qty});advanceTime(15);feedback(`Bought ${qty>1?qty+'× ':''}${d.name}`,`${money(total)} spent`,15)
}
function resolvePurchaseDecision(p){const d=catalogItem(p.payload?.key);if(!d){resolvePendingDecision(p,'Cancelled','Unknown item');return}const maker=decisionAuthorityPerson(p.decisionMakerId);if(maker&&!p.decisionMakerId)p.decisionMakerId=maker.id;const who=decisionMakerLabel(p.decisionMakerId),score=purchaseScore(d,true)+(S.luck-50)*.08,roll=Math.random()*100;if(roll<score){addItem(p.payload.key,'caregiver purchase after consideration');resolvePendingDecision(p,'Approved',`${who} approved after consideration`,{title:'Request approved',text:`After thinking it over, ${who} buys ${d.name}.`,important:true});resolveDecisionRecord(p.decisionId,'Approved',`${who} approved after consideration.`);return}if(roll<score+18){p.type='conditionalPurchase';p.status='Conditional';p.resolveDate=null;p.expiresDate=addDays(currentDate(),180);p.payload.condition='saveHalf';p.payload.target=Math.ceil(d.price/2);p.detail=`Save ${money(p.payload.target)}; ${who} will reconsider.`;const r=(S.decisionLedger||[]).find(x=>x.id===p.decisionId);if(r){r.outcome='Partial payment';r.reason=p.detail;r.requirements={type:'saveHalf',target:p.payload.target};r.reconsiderAfter=null;r.resolved=false}log('A conditional answer',p.detail);return}resolvePendingDecision(p,'Denied',`${who} decided against it`,{title:'Request denied',text:`After considering ${d.name}, ${who} decides against it for now.`});resolveDecisionRecord(p.decisionId,'No',`${who} decided against it for now.`,{reconsiderAfter:addDays(currentDate(),1)})}
function checkConditionalRequests(){for(const p of S.pendingDecisions.filter(x=>!x.resolved&&x.type==='conditionalPurchase')){const d=catalogItem(p.payload?.key);if(!d)continue;const who=decisionMakerLabel(p.decisionMakerId);if(p.payload.condition==='saveHalf'&&availableFunds()>=p.payload.target){if(spendOwn(p.payload.target)){addItem(p.payload.key,'shared purchase');resolvePendingDecision(p,'Completed','Saved required share',{title:'You saved your share',text:`You pay ${money(p.payload.target)} toward ${d.name}; ${who} covers the rest.`,important:true});resolveDecisionRecord(p.decisionId,'Completed','Saved required share')}}else if(p.payload.condition==='chores'&&(S.choresDone||0)>=p.payload.target){addItem(p.payload.key,'earned through chores');resolvePendingDecision(p,'Completed','Chore requirement met',{title:'You earned it',text:`After following through on chores, ${who} buys ${d.name}.`,important:true});resolveDecisionRecord(p.decisionId,'Completed','Chore requirement met')}else if(p.payload.condition==='grades'&&S.school&&schoolAverage()>=p.payload.target){addItem(p.payload.key,'grade reward');resolvePendingDecision(p,'Completed','Grade requirement met',{title:'Grade reward',text:`You meet the academic condition and ${who} gets you ${d.name}.`,important:true});resolveDecisionRecord(p.decisionId,'Completed','Grade requirement met')}}}
