// PHASE 5D.5 — Actual-order Calendar commitments, bounded competition, family help, talent evidence.
// Intentionally backend-only (5D.6 provides player UI); never replays historic income.
const MICRO_ORDER_STATES_5D5=Object.freeze(['Scheduled','Due','Completed','Missed','Cancelled']);
function microbusinessState5D5(){
 const st=ensureMicrobusiness5D1();if(!Array.isArray(st.orders5D5))st.orders5D5=[];return st;
}
function migrateMicrobusiness5D5(){return {orders:microbusinessState5D5().orders5D5.length}}
function microbusinessOrder5D5(id){return microbusinessState5D5().orders5D5.find(o=>o.id===id)||null}
function microbusinessOrderCalendar5D5(o){return (S.calendar||[]).find(ev=>ev.id===`micro-order:${o.id}`)||null}
function microbusinessMarketContext5D5(s){
 if(!s)return {trafficDelta:0,scoreDelta:0,competition:0,communityEvent:false};
 const rivals=(S.businesses||[]).filter(b=>b.id!==s.businessId&&b.status==='Open'&&b.location===s.location&&b.kind===s.businessType).length;
 const competition=Math.min(3,rivals);
 const communityEvent=(S.calendar||[]).some(ev=>ev.dateISO===currentDate()&&!isTerminal(ev.status)&&
  ['neighborhood','community','festival','holiday','market'].some(term=>String(ev.type||'').toLowerCase().includes(term))&&
  (!ev.location||ev.location===s.location||ev.location==='Neighborhood'));
 const time=currentMinute(),peak=time>=660&&time<=1020;
 // Existing 5D.3 weather rules stay authoritative. This adds ONLY modest local demand effects.
 const trafficDelta=Math.max(-2,Math.min(2,(communityEvent?1:0)+(peak?1:0)-competition));
 const scoreDelta=Math.max(-6,Math.min(6,(communityEvent?2:0)+(peak?1:0)-competition*2));
 return {trafficDelta,scoreDelta,competition,communityEvent};
}
function microbusinessCaregiver5D5(personId){
 return householdCaregivers().find(p=>p.id===personId&&!p.deceased&&!p.movedAway)||null;
}
function microbusinessFamilyHelp5D5(sessionId,personId,purpose){
 const s=microbusinessSession5D1(sessionId);if(!s||!['planned','preparing','open'].includes(s.status))return {ok:false,reason:'invalid_session_state'};
 if(s.dateISO!==currentDate())return {ok:false,reason:'session_expired'};
 if(!['prepare','supervise','supplies','encourage'].includes(purpose))return {ok:false,reason:'invalid_help_type'};
 const p=microbusinessCaregiver5D5(personId);if(!p)return {ok:false,reason:'caregiver_not_at_home'};
 const gate=microbusinessEligibility5D1(s.businessType,s.location);if(!gate.ok)return gate;
 const permission=microbusinessPermission5D1(s.businessType,s.location);if(!permission.ok)return {ok:false,reason:'permission_denied'};
 s.familyHelp5D5=Array.isArray(s.familyHelp5D5)?s.familyHelp5D5:[];
 const old=s.familyHelp5D5.find(x=>x.personId===personId&&x.purpose===purpose);
 if(old)return {ok:old.accepted,reused:true,reason:old.accepted?'approved':'declined',help:old};
 const context={sessionId:s.id,purpose,helperId:p.id,businessType:s.businessType};
 // H3 remembers the result even if another button path repeats the same request.
 const decision=requestDecision({requestType:'microbusinessFamilyHelp5D5',targetKey:`${s.id}:${personId}:${purpose}`,context,decide:(maker)=>{
  const strict=Number(familyRules().strictness||0),trust=Number(S.family?.trust??50);
  const score=clamp(76-strict*.24+(trust-50)*.18+(purpose==='supervise'?-6:0),15,95);
  const roll=hashOf(`${maker?.id||'adult'}|${p.id}|${s.id}|${purpose}`)%100;
  return {outcome:roll<score?'Yes':'No',resolved:true,reason:roll<score?'Caregiver agrees to help.':'Caregiver is unavailable or unwilling to help.'};
 }});
 if(!decision.record)return {ok:false,reason:'guardian_required'};
 const accepted=['Yes','Approved'].includes(decision.record.outcome);
 const help={personId:p.id,purpose,accepted,decisionId:decision.record.id,dateISO:currentDate(),minute:currentMinute()};
 // 'supplies' is only an offer to help acquire supplies; 5D.2 still charges/consumes
 // actual stock. No inventory, money, or receipts are generated by this approval.
 s.familyHelp5D5.push(help);
 return {ok:accepted,reason:accepted?'approved':'declined',help};
}
function microbusinessSupervisorGate5D5(s){
 if(S.age>=12)return {ok:true};
 const helpers=s.familyHelp5D5||[];
 return helpers.some(h=>h.purpose==='supervise'&&h.accepted&&microbusinessCaregiver5D5(h.personId))?{ok:true}:{ok:false,reason:'adult_supervision_required'};
}
function microbusinessOrderCustomer5D5(s,npcId){
 const book=microbusinessState5D4().customerBook5D4[npcId];
 if(!book||book.purchases<1||!microbusinessNeighborCandidates5D4().some(n=>n.id===npcId))return false;
 // Require actual matching same-business sale; a made-up book record is not enough.
 return ensureMicrobusiness5D1().sessions.some(x=>x.businessId===s.businessId&&(x.customerEncounters||[]).some(e=>e.customerKey5D4===npcId&&
   x.transactions.some(t=>t.kind==='sale'&&t.transactionId===e.saleTransactionId)));
}
function microbusinessCreateOrder5D5({requestId,sessionId,customerNpcId,productId,quantity,unitPrice,pickupDateISO,pickupMinute}={}){
 const st=microbusinessState5D5(),key=typeof requestId==='string'?requestId.trim():'';
 if(!/^[\w-]{5,80}$/.test(key))return {ok:false,reason:'invalid_request_id'};
 const id=`order5d5:${key}`,sig=JSON.stringify({sessionId,customerNpcId,productId,quantity,unitPrice,pickupDateISO,pickupMinute});
 const prior=microbusinessOrder5D5(id);if(prior)return prior.signature===sig?{ok:true,reused:true,order:prior}:{ok:false,reason:'order_id_conflict'};
 const gate=microbusinessCustomerGate5D3(sessionId);if(!gate.ok)return gate;
 const s=gate.session,supervision=microbusinessSupervisorGate5D5(s);if(!supervision.ok)return supervision;
 if(s.businessType==='yard')return {ok:false,reason:'yard_orders_not_supported'};
 const product=microbusinessBatchProduct5D2(s.businessType);
 if(!product||product.id!==productId||!s.batches.some(b=>b.productId===productId&&b.source!=='unbacked'))return {ok:false,reason:'product_not_offered'};
 if(!microbusinessOrderCustomer5D5(s,customerNpcId))return {ok:false,reason:'customer_not_established'};
 if(!Number.isInteger(quantity)||quantity<1||quantity>12||!microbusinessPrice5D2(s.businessType,unitPrice))return {ok:false,reason:'invalid_order_terms'};
 if(!s.batches.some(b=>b.productId===productId&&b.remaining>0&&b.unitPrice>=Number(unitPrice)))return {ok:false,reason:'price_exceeds_current_offer'};
 if(typeof pickupDateISO!=='string'||!/^\d{4}-\d\d-\d\d$/.test(pickupDateISO)||!Number.isInteger(daysBetween(currentDate(),pickupDateISO))||daysBetween(currentDate(),pickupDateISO)<1||daysBetween(currentDate(),pickupDateISO)>7||addDays(currentDate(),daysBetween(currentDate(),pickupDateISO))!==pickupDateISO||!Number.isInteger(pickupMinute)||pickupMinute<540||pickupMinute>1080)return {ok:false,reason:'invalid_pickup_time'};
 const same=st.orders5D5.filter(o=>o.businessId===s.businessId&&!['Cancelled','Completed','Missed'].includes(o.status));
 if(same.length>=5||same.some(o=>o.customerNpcId===customerNpcId&&o.pickupDateISO===pickupDateISO))return {ok:false,reason:'order_capacity'};
 const end=Math.min(1439,pickupMinute+60);
 const conflicting=(S.calendar||[]).some(ev=>ev.dateISO===pickupDateISO&&!isTerminal(ev.status)&&ev.required!==false&&ev.type!=='microbusinessOrder'&&Number(ev.startMinute??0)<end&&pickupMinute<Number(ev.endMinute??1439));
 if(conflicting)return {ok:false,reason:'calendar_conflict'};
 const o={id,signature:sig,businessId:s.businessId,businessType:s.businessType,sourceSessionId:s.id,customerNpcId,productId,quantity,unitPrice:Number(unitPrice),pickupDateISO,pickupMinute,graceMinute:end,status:'Scheduled',createdDateISO:currentDate(),createdMinute:currentMinute(),saleTransactionId:null,fulfilledSessionId:null};
 const event=createCalendarEvent({id:`micro-order:${id}`,type:'microbusinessOrder',title:`Customer pickup • ${BIZ_TYPES[s.businessType].name}`,dateISO:pickupDateISO,startMinute:pickupMinute,endMinute:end,graceMinute:end,location:s.location,required:true,category:'business',source:'microbusiness5D5',payload:{orderId:id}});
 if(!event||event.payload?.orderId!==id)return {ok:false,reason:'calendar_unavailable'};
 st.orders5D5.push(o);return {ok:true,order:o,calendarId:event.id};
}
function microbusinessOrderFeedback5D5(o,event,delta){
 const source=microbusinessSession5D1(o.sourceSessionId);
 if(!source||source.businessId!==o.businessId)return false;
 // The existing 5D.4 reputation authority applies its normal daily bounds.
 return microbusinessAdjustReputation5D4(source,o,event,delta,`customer order ${event}`);
}
function microbusinessOrderCalendarTick5D5(event){
 const o=microbusinessOrder5D5(event?.payload?.orderId);
 if(!o){setCalendarStatus(event,'Cancelled','Unlinked customer order');return false}
 if(['Completed','Cancelled','Missed'].includes(o.status)){
  if(!isTerminal(event.status))setCalendarStatus(event,o.status,'Already resolved');return false;
 }
 const source=microbusinessSource5D1(o.businessId);
 if(!source||source.kind!==o.businessType){o.status='Cancelled';microbusinessOrderFeedback5D5(o,'business_unavailable',-2);setCalendarStatus(event,'Cancelled','Business unavailable');return true}
 const now=stamp(currentDate(),currentMinute()),start=stamp(o.pickupDateISO,o.pickupMinute),end=stamp(o.pickupDateISO,o.graceMinute);
 if(now>end){o.status='Missed';o.resolvedDateISO=currentDate();microbusinessOrderFeedback5D5(o,'pickup_missed',-3);setCalendarStatus(event,'Missed','Pickup missed');return true}
 if(now>=start&&o.status==='Scheduled'){
  o.status='Due';setCalendarStatus(event,'Due','Customer pickup window open');
  if(!SIM.skipping)notify('Customer pickup due',`${BIZ_TYPES[o.businessType].name}: ${o.quantity} reserved for pickup.`,{sourceType:'microbusinessOrder',sourceId:event.id,tab:'business'});
  return true;
 }
 return false;
}
function microbusinessFulfillOrder5D5(orderId,sessionId,batchId){
 const o=microbusinessOrder5D5(orderId);if(!o)return {ok:false,reason:'unknown_order'};
 if(o.status==='Completed')return {ok:true,reused:true,order:o};
 if(['Missed','Cancelled'].includes(o.status))return {ok:false,reason:'order_closed'};
 const event=microbusinessOrderCalendar5D5(o);if(!event)return {ok:false,reason:'calendar_missing'};
 microbusinessOrderCalendarTick5D5(event);
 if(['Missed','Cancelled'].includes(o.status))return {ok:false,reason:'order_closed'};
 if(o.pickupDateISO!==currentDate()||currentMinute()<o.pickupMinute)return {ok:false,reason:'pickup_not_due'};
 const gate=microbusinessCustomerGate5D3(sessionId);if(!gate.ok)return gate;
 const s=gate.session,supervision=microbusinessSupervisorGate5D5(s);if(!supervision.ok)return supervision;
 if(s.businessId!==o.businessId||s.businessType!==o.businessType)return {ok:false,reason:'wrong_business'};
 const b=s.batches.find(x=>x.batchId===batchId);
 if(!b||b.productId!==o.productId||b.remaining<o.quantity||b.unitPrice<o.unitPrice)return {ok:false,reason:'order_stock_or_price'};
 if(!microbusinessOrderCustomer5D5(s,o.customerNpcId))return {ok:false,reason:'customer_not_established'};
 const person=microbusinessState5D4().customerBook5D4[o.customerNpcId]?.personId;
 const amount=MICRO_CENTS_5D2(o.quantity*o.unitPrice),txid=`micro5d5:sale:${o.id}`;
 const sale=microbusinessCommit5D1(s.id,{transactionId:txid,kind:'sale',quantity:o.quantity,batchId,amount,encounterId:o.id,personId:person&&personById(person)?person:null});
 if(!sale.ok)return sale;
 o.status='Completed';o.saleTransactionId=txid;o.fulfilledSessionId=s.id;o.resolvedDateISO=currentDate();o.resolvedMinute=currentMinute();
 setCalendarStatus(event,'Completed','Order collected and paid');
 microbusinessOrderFeedback5D5(o,'pickup_completed',2);
 microbusinessOrderEvidence5D5(s,o,sale.receipt);
 return {ok:true,order:o,sale:sale.receipt};
}
function microbusinessCancelOrder5D5(orderId){
 const o=microbusinessOrder5D5(orderId);if(!o)return {ok:false,reason:'unknown_order'};
 if(o.status==='Cancelled')return {ok:true,reused:true,order:o};
 if(['Completed','Missed'].includes(o.status))return {ok:false,reason:'order_closed'};
 const event=microbusinessOrderCalendar5D5(o);if(!event)return {ok:false,reason:'calendar_missing'};
 microbusinessOrderCalendarTick5D5(event);if(!['Scheduled','Due'].includes(o.status))return {ok:false,reason:'order_closed'};
 o.status='Cancelled';o.resolvedDateISO=currentDate();microbusinessOrderFeedback5D5(o,'seller_cancelled',-1);setCalendarStatus(event,'Cancelled','Seller cancelled agreed order');return {ok:true,order:o};
}
function microbusinessSaleEvidence5D5(s,e){
 if(!s||!e||e.talentRecorded5D5||!s.customerEncounters?.includes(e))return false;
 const receipt=s.transactions.find(t=>t.kind==='sale'&&t.transactionId===e.saleTransactionId&&t.encounterId===e.id);
 if(!receipt||receipt.quantity<1)return false;
 e.talentRecorded5D5=true;
 const basis={source:'served a paying customer',system:'microbusiness',eventId:`${receipt.transactionId}:business`,context:s.businessType,quality:1};
 recordTalentEvidence('Business',basis);
 if(e.turns>0)recordTalentEvidence('Leadership',{...basis,source:'guided a customer through a product choice',eventId:`${receipt.transactionId}:leadership`,quality:.6});
 const batch=s.batches.find(b=>b.batchId===e.batchId);
 if(['cookies','cupcakes'].includes(s.businessType)&&batch?.source==='baked_inventory')recordTalentEvidence('Cooking',{...basis,source:'sold personally baked food',eventId:`${receipt.transactionId}:cooking`,quality:.75});
 return true;
}
function microbusinessOrderEvidence5D5(s,o,receipt){
 if(!receipt||receipt.transactionId!==o.saleTransactionId||o.talentRecorded5D5)return false;
 o.talentRecorded5D5=true;
 recordTalentEvidence('Business',{source:'fulfilled a scheduled paying customer order',system:'microbusiness',eventId:`${receipt.transactionId}:order`,context:'special order',quality:1.2});
 if((s.familyHelp5D5||[]).some(h=>h.accepted&&h.purpose==='prepare'))recordTalentEvidence('Leadership',{source:'coordinated family help for a completed order',system:'microbusiness',eventId:`${receipt.transactionId}:coordination`,context:'family assistance',quality:.6});
 return true;
}
