// =====================================================================
// PHASE 5B.3 — Tutoring / Summer Academics / Social Integration
// Subject-specific academic offerings reuse S.programs + Calendar + 5B.2
// attendance/instructor/participant systems. Workbook self-study remains
// separate and no peer is automatically promoted to a Phone contact/romance.
// =====================================================================
const PROGRAM_ACADEMIC_SCHEMA_5B3=1;
const PROGRAM_ACADEMIC_PREFIX_5B3='academic5b3:';
function ensureAcademicPrograms5B3(){
 const f=S.programAcademic5B3=S.programAcademic5B3||{};f.schema=PROGRAM_ACADEMIC_SCHEMA_5B3;f.selectedSubject=f.selectedSubject||null;return f
}
function academicSubjectEligible5B3(name){return /math|number|science|biology|chemistry|physics|english|language|literature|reading|history|social|geography|technology|computer/i.test(String(name||''))}
function academicSubjects5B3(){
 if(!S.school||!needsFormalSchool())return [];const all=(S.school.subjects||[]).map(s=>s.name);const core=all.filter(academicSubjectEligible5B3);return (core.length?core:all.filter(n=>!/physical|movement|art|music/i.test(n))).slice(0,6)
}
function academicSubjectSlug5B3(subject){return encodeURIComponent(String(subject||'').trim())}
function academicProgramTemplateId5B3(subject,format,scope){return `${PROGRAM_ACADEMIC_PREFIX_5B3}${scope}:${format==='1:1'?'one':'group'}:${academicSubjectSlug5B3(subject)}`}
function academicProgramDefinition5B3(id){
 if(!String(id||'').startsWith(PROGRAM_ACADEMIC_PREFIX_5B3))return null;const rest=String(id).slice(PROGRAM_ACADEMIC_PREFIX_5B3.length),parts=rest.split(':');if(parts.length<3)return null;const scope=parts[0],format=parts[1]==='one'?'1:1':'group',subject=decodeURIComponent(parts.slice(2).join(':')),term=scope==='after_school',sch=academicSchedule5B3(subject,format,scope);
 return {id,templateId:id,name:term?`${subject} ${format==='1:1'?'1:1 Tutoring':'Group Tutoring'}`:`${subject} ${format==='1:1'?'Summer Tutor':'Summer Class'}`,skill:'knowledge',rep:'academic',minAge:6,maxAge:17,cost:format==='1:1'?(term?180:210):(term?90:120),weeks:term?6:4,days:[...sch.days],start:sch.start,end:sch.end,final:null,formal:true,kind:'formal_program',category:'Academic',provider:term?(format==='1:1'?'Local Tutoring Center':'School Learning Center'):(format==='1:1'?'Community Tutor Network':'Local School District'),location:term?'School study center':'Community learning center',format,scope,academic:true,safety:'low',academicSubject:subject,tutoring:term||format==='1:1'}
}
function academicTrack5B3(subject){const s=(S.school?.subjects||[]).find(x=>x.name===subject),score=Number(s?.score??70);if(score<60)return {track:'remedial',label:'Support recommended',reason:`${subject} is currently one of your weaker subjects.`};if(score>=85)return {track:'enrichment',label:'Enrichment available',reason:`Strong ${subject} performance makes enrichment a reasonable option.`};return {track:'standard',label:'Optional study',reason:'Optional structured study if you want extra practice.'}}
function academicSchedule5B3(subject,format,scope){
 const subs=academicSubjects5B3(),idx=Math.max(0,subs.indexOf(subject)),term=scope==='after_school';let slots;
 if(term)slots=format==='1:1'?[{days:[1],start:990,end:1050},{days:[2],start:990,end:1050},{days:[3],start:990,end:1050},{days:[4],start:990,end:1050},{days:[5],start:990,end:1050},{days:[6],start:600,end:660}]:[{days:[1,3],start:960,end:1020},{days:[2,4],start:960,end:1020},{days:[1,3],start:1020,end:1080},{days:[2,4],start:1020,end:1080},{days:[5],start:960,end:1020},{days:[6],start:600,end:660}];
 else slots=format==='1:1'?[{days:[1],start:600,end:660},{days:[2],start:600,end:660},{days:[3],start:600,end:660},{days:[4],start:600,end:660},{days:[5],start:600,end:660},{days:[6],start:600,end:660}]:[{days:[1,3],start:600,end:690},{days:[2,4],start:600,end:690},{days:[1,3],start:780,end:870},{days:[2,4],start:780,end:870},{days:[5],start:600,end:690},{days:[5],start:780,end:870}];
 return slots[idx%slots.length]
}
function academicProgramOffer5B3(subject,format='group',{dateISO=currentDate()}={}){
 if(!academicSubjects5B3().includes(subject)||!['group','1:1'].includes(format)||S.age<6||S.age>17)return null;const br=schoolBreakState5B1(dateISO),scope=br.kind==='summer'?'summer':'after_school';if(scope==='after_school'&&br.onBreak)return null;const defId=academicProgramTemplateId5B3(subject,format,scope),def=academicProgramDefinition5B3(defId),sch=academicSchedule5B3(subject,format,scope),a=academicInfo(dateISO);let from,to;
 if(scope==='summer'){const w=summerWindow();if(!w.open)return null;from=addDays(w.from<dateISO?dateISO:w.from,2);to=w.to}else{if(!a.semester)return null;from=addDays(dateISO,1);to=a.semester===1?a.sem1End:a.end}
 const dates=datesForWeekdays5B1({days:sch.days,weeks:def.weeks},from,to,{afterSchool:scope==='after_school'});if(!dates.length)return null;const tr=academicTrack5B3(subject),startDate=dates[0],endDate=dates[dates.length-1],programId=programOfferingId5B1(def,scope,startDate);
 return {programId,templateId:defId,progId:defId,name:def.name,kind:'formal_program',formal:true,category:'Academic',provider:def.provider,location:def.location,format,scope,academic:true,academic5B3:true,academicSubject:subject,academicTrack:tr.track,tutoring5B3:def.tutoring,minAge:def.minAge,maxAge:def.maxAge,cost:def.cost,skill:'knowledge',startDate,endDate,startMinute:sch.start,endMinute:sch.end,days:[...sch.days],dates,durationSessions:dates.length,safety:'low',recommendation:tr}
}
function activeAcademicPrograms5B3(){return (S.programs||[]).filter(r=>r.academic5B3&&r.scope==='summer'&&['Enrolled','Active'].includes(r.status))}
function summerAcademicSubjects5B3(){return [...new Set(activeAcademicPrograms5B3().map(r=>r.academicSubject).filter(Boolean))]}
function academicProgramCount5B3(){return summerAcademicSubjects5B3().length}
function academicProgramGate5B3(offer){
 if(!offer)return {ok:false,reason:'Academic program is unavailable.'};const same=(S.programs||[]).find(r=>r.academic5B3&&r.academicSubject===offer.academicSubject&&r.scope===offer.scope&&['Enrolled','Active'].includes(r.status));if(same)return {ok:false,reason:`You already have a structured ${offer.academicSubject} program in this period.`,existing:same};if(offer.scope==='summer'&&!summerAcademicSubjects5B3().includes(offer.academicSubject)&&academicProgramCount5B3()>=3)return {ok:false,reason:'You can take at most three formal summer academic subjects at once.',limit:true};return programEnrollmentGate5B1(offer)
}
function enrollAcademicProgram5B3(offer){
 ensureAcademicPrograms5B3();const gate=academicProgramGate5B3(offer);if(!gate.ok){toast(gate.reason);return gate.existing||null}const rec=enrollFormalProgram5B1(offer);if(!rec)return null;rec.schema5B3=PROGRAM_ACADEMIC_SCHEMA_5B3;rec.academic5B3=true;rec.academicSubject=offer.academicSubject;rec.academicTrack=offer.academicTrack;rec.tutoring5B3=!!offer.tutoring5B3;rec.format=offer.format;rec.category='Academic';rec.skill='knowledge';rec.scope=offer.scope;rec.provider=offer.provider;rec.location=offer.location;rec.schedule=Object.assign({},rec.schedule||{},{days:[...offer.days],startMinute:offer.startMinute,endMinute:offer.endMinute,startDate:offer.startDate,endDate:offer.endDate});normalizeProgramEnrollment5B2(rec);return rec
}
function academicProgramApplySession5B3(rec,pg,{late=false}={}){
 rec=canonicalProgramRecord5B2(rec);if(!rec?.academic5B3||!rec.academicSubject||!S.school?.subjects)return false;const sub=S.school.subjects.find(s=>s.name===rec.academicSubject);if(!sub)return false;const attendance=late?.75:1,focus=rec.format==='1:1'?1.35:1,track=rec.academicTrack==='remedial'?1.08:rec.academicTrack==='enrichment'?.92:1,scoreGain=Math.round((.34*focus*track*attendance)*100)/100,skillGain=Math.round((.48*focus*attendance)*100)/100,prepGain=Math.round((.8*focus*attendance)*100)/100,before=Number(sub.score||0);sub.score=Math.min(100,Math.round((before+scoreGain)*100)/100);sub.skill=clamp(Number(sub.skill||0)+skillGain);sub.prep=clamp(Number(sub.prep||0)+prepGain);rec.lastAcademicGain5B3={dateISO:currentDate(),subject:sub.name,format:rec.format,scoreBefore:before,scoreAfter:sub.score,scoreGain:Math.round((sub.score-before)*100)/100,skillGain,prepGain};return true
}
function academicProgramPeerContext5B3(rec){
 if(!rec?.academic5B3)return null;const tutoring=rec.tutoring5B3,sub=rec.academicSubject||'academic';return {roleLabel:tutoring?`${sub} tutoring classmate`:`${sub} summer classmate`,metAt:tutoring?`${sub} tutoring`:`${sub} summer class`,metVia:tutoring?'group tutoring':'summer academic program'}
}
function academicPeerRomanceEligibility5B3(pOrId){const p=typeof pOrId==='string'?personById(pOrId):pOrId;if(!p||isFamilyPerson(p))return {eligible:false,reason:'Not a peer romance candidate'};const c=typeof romanceCompatibility==='function'?romanceCompatibility(p):null,eligible=typeof eligibleRomance==='function'?!!eligibleRomance(p):!!c?.orientationOK;return {eligible,orientationOK:c?.orientationOK!==false,committedElsewhere:!!c?.committedElsewhere,stage:typeof romanceStageLabel3B3==='function'?romanceStageLabel3B3(p):null}}
function academicProgramOfferSummary5B3(subject){return ['group','1:1'].map(f=>academicProgramOffer5B3(subject,f)).filter(Boolean)}
function academicProgramsHtml5B3(){
 ensureAcademicPrograms5B3();const subs=academicSubjects5B3();if(!subs.length)return '';const f=ensureAcademicPrograms5B3();if(!subs.includes(f.selectedSubject))f.selectedSubject=subs[0];const subject=f.selectedSubject,offers=academicProgramOfferSummary5B3(subject),tr=academicTrack5B3(subject),count=academicProgramCount5B3(),summer=schoolBreakState5B1().kind==='summer';
 return `<h4>${summer?'Summer academics':'Tutoring & after-school academics'}</h4><div class="soft-panel"><label>Subject <select data-academic-subject5b3>${subs.map(s=>`<option value="${esc(s)}" ${s===subject?'selected':''}>${esc(s)}</option>`).join('')}</select></label><p class="muted-text">${esc(tr.label)} — ${esc(tr.reason)}${summer?` • Formal summer subjects: ${count}/3.`:' • Workbook self-study remains separate.'}</p>${offers.map(o=>{const g=academicProgramGate5B3(o),rec=programEnrollmentByProgramId5B1(o.programId),state=rec?.status||'Available',blocked=!g.ok||['Enrolled','Active','Done','Completed'].includes(state);return `<div class="calendar-row"><div><b>${esc(o.name)}</b><small>${o.format==='1:1'?'Focused 1:1 support':'Group class with peer opportunities'} • ${o.cost?money(o.cost):'Free'}<br>${formatDate(o.startDate)}–${formatDate(o.endDate)} • ${timeLabel(o.startMinute)}–${timeLabel(o.endMinute)}</small></div><div class="inline-actions">${statusTag(!g.ok?g.reason:state)}<button class="small primary" data-academic-program5b3="${esc(o.templateId)}" ${blocked?'disabled':''}>${state==='Considering'||state==='Declined'?'Ask again':'Enroll'}</button></div></div>`}).join('')}</div>`
}
function handlePanelChange5B3(e){const el=e?.target?.closest?.('[data-academic-subject5b3]');if(!el||!S)return false;ensureAcademicPrograms5B3().selectedSubject=el.value;save();render();return true}
function academicProgramClick5B3(b){const id=b?.dataset?.academicProgram5b3;if(!id)return false;const def=academicProgramDefinition5B3(id),subject=def?.academicSubject,format=def?.format;if(!subject||!format)return true;const offer=academicProgramOffer5B3(subject,format);if(offer)enrollAcademicProgram5B3(offer);save();render();return true}
function migratePrograms5B3(){
 ensureAcademicPrograms5B3();for(const rec of S.programs||[]){if(!String(rec.progId||rec.templateId||'').startsWith(PROGRAM_ACADEMIC_PREFIX_5B3))continue;const def=academicProgramDefinition5B3(rec.progId||rec.templateId);if(!def)continue;rec.schema5B3=PROGRAM_ACADEMIC_SCHEMA_5B3;rec.academic5B3=true;rec.academicSubject=rec.academicSubject||def.academicSubject;rec.tutoring5B3=rec.tutoring5B3??!!def.tutoring;rec.category='Academic';rec.format=rec.format||def.format;rec.provider=rec.provider||def.provider;rec.location=rec.location||def.location;rec.skill='knowledge';normalizeProgramEnrollment5B2(rec)}return S.programs
}
