// =====================================================================
// PHASE 5B.2 — Formal Programs / Coaches / Attendance / Skills
// Extends the 5B.1 canonical PROGRAMS + S.programs + Calendar foundation.
// Jobs remain legacy until 5B.4; tutoring/summer academics are expanded in 5B.3.
// =====================================================================
const PROGRAM_SCHEMA_5B2=1;
const PROGRAM_INSTRUCTOR_NAMES_5B2=['Jordan Lee','Maya Chen','Alex Rivera','Priya Shah','Daniel Kim','Morgan Ellis','Samira Patel','Noah Bennett','Lina Park','Theo Martin'];
const PROGRAM_TRYOUT_TEMPLATES_5B2=new Set(['bballCamp','soccerLeague']);
function ensureProgramRuntime5B2(){
 ensureProgramFoundation5B1();
 const f=S.programFoundation5B2=S.programFoundation5B2||{};f.schema=PROGRAM_SCHEMA_5B2;f.instructors=f.instructors&&typeof f.instructors==='object'?f.instructors:{};f.tryouts=f.tryouts&&typeof f.tryouts==='object'?f.tryouts:{};return f
}
function programFormatModifier5B2(format){return format==='1:1'?1.28:format==='team'?1.12:1}
function canonicalProgramRecord5B2(x){if(!x)return null;if(typeof x==='string')return (S.programs||[]).find(r=>r.id===x||r.programId===x)||null;if(x.id){const r=(S.programs||[]).find(q=>q.id===x.id);if(r)return r}if(x.programId){const r=(S.programs||[]).find(q=>q.programId===x.programId);if(r)return r}return x}
function programInstructorRole5B2(rec){if(rec.tutoring5B3)return 'tutor';if(rec.category==='Academic')return 'instructor';if(/Music|Arts|Theater|Baking/.test(rec.category||''))return 'instructor';return /Basketball|Soccer|Swimming/.test(rec.category||'')?'coach':'instructor'}
function ensureProgramInstructor5B2(rec){
 rec=canonicalProgramRecord5B2(rec);if(!rec||rec.kind==='legacy_job')return null;const f=ensureProgramRuntime5B2(),key=rec.programId||rec.id;if(f.instructors[key]){rec.instructorId=f.instructors[key].id;return f.instructors[key]}
 const seed=hashOf(`${key}|instructor`),name=PROGRAM_INSTRUCTOR_NAMES_5B2[seed%PROGRAM_INSTRUCTOR_NAMES_5B2.length],role=programInstructorRole5B2(rec),quality=55+(seed%31);
 const inst={id:`program-instructor:${key}`,programId:key,name,role,quality,opinion:50};f.instructors[key]=inst;rec.instructorId=inst.id;return inst
}
function programTryoutRequired5B2(x){const id=typeof x==='string'?x:(x?.templateId||x?.progId);return PROGRAM_TRYOUT_TEMPLATES_5B2.has(id)}
function programTryoutState5B2(programId){const f=ensureProgramRuntime5B2();return f.tryouts[programId]||null}
function programTryoutScore5B2(offer){
 const skill=skillValue(offer.skill||'sports'),talent=(S.talents||[]).includes(SKILL_TALENT[offer.skill]||'')?8:0,health=(S.health??50)*.12,energy=(S.energy??50)*.10,prep=(S.reputation?.athletic||ensureRep().athletic||0)*.05,noise=(hashOf(`${offer.programId}|${S.name}|${S.dob}|tryout`)%1800)/100-9;
 return Math.round(clamp(skill*.58+talent+health+energy+prep+noise,0,100)*10)/10
}
function attemptProgramTryout5B2(offer,{forceOutcome=null}={}){
 if(!offer||!programTryoutRequired5B2(offer))return {required:false,passed:true};const f=ensureProgramRuntime5B2(),old=f.tryouts[offer.programId];if(old&&old.status==='Resolved')return old;
 const score=programTryoutScore5B2(offer),threshold=52+(hashOf(`${offer.programId}|field`)%1200)/100,passed=forceOutcome==='pass'?true:forceOutcome==='fail'?false:score>=threshold;
 const r={programId:offer.programId,templateId:offer.templateId,status:'Resolved',dateISO:currentDate(),score,threshold:Math.round(threshold*10)/10,passed,result:passed?'Selected':'Not selected'};f.tryouts[offer.programId]=r;if(forceOutcome==null){advanceTime(90,{silent:true});S.energy=clamp(S.energy-8);S.stress=clamp(S.stress+2)}recordOutcome('Program tryout',offer.name,r.result,`Tryout score ${score}; selection line ${r.threshold}.`);if(forceOutcome==null&&!SIM.skipping)log(`${offer.name} tryout`,passed?'You make the cut. Enrollment is now available.':'You do not make the cut this time. Casual practice remains available, and a future season may offer another tryout.');return r
}
// 5B.2 hardens the 5B.1 enrollment gate for competitive programs.
function programEnrollmentGate5B1(offer){
 const existing=programEnrollmentByProgramId5B1(offer.programId);if(existing&&['Enrolled','Active','Done','Completed'].includes(existing.status))return {ok:false,reason:`You are already ${existing.status==='Done'||existing.status==='Completed'?'finished with':'enrolled in'} this program.`,existing};
 const conflicts=programScheduleConflicts5B1(offer);if(conflicts.length)return {ok:false,reason:`Schedule conflict with ${conflicts[0].title} on ${formatDate(conflicts[0].dateISO)}.`,conflicts};
 if(programTryoutRequired5B2(offer)){const t=programTryoutState5B2(offer.programId);if(!t||t.status!=='Resolved')return {ok:false,reason:'This competitive program requires a tryout first.',tryoutRequired:true};if(!t.passed)return {ok:false,reason:'You were not selected at this tryout. Practice and try again next eligible period.',tryout:t}}
 return {ok:true,existing}
}
function normalizeProgramEnrollment5B2(rec){
 rec=canonicalProgramRecord5B2(rec);if(!rec)return null;normalizeProgramEnrollment5B1(rec);rec.schema5B2=PROGRAM_SCHEMA_5B2;rec.attendance5B2=rec.attendance5B2&&typeof rec.attendance5B2==='object'?rec.attendance5B2:{};rec.consecutiveAbsences=Math.max(0,Number(rec.consecutiveAbsences??rec.streakMissed??0));rec.streakMissed=rec.consecutiveAbsences;rec.participantIds=Array.isArray(rec.participantIds)?[...new Set(rec.participantIds)]:[...new Set(rec.teammates||[])];rec.teammates=rec.participantIds;rec.programProgress=Math.max(0,Number(rec.programProgress||0));rec.completionRecorded=!!rec.completionRecorded;if(rec.formal!==false&&rec.kind!=='legacy_job')ensureProgramInstructor5B2(rec);return rec
}
function programSessionRecord5B2(rec,ev){
 normalizeProgramEnrollment5B2(rec);const id=ev?.id||'unknown';let r=rec.attendance5B2[id];if(!r)r=rec.attendance5B2[id]={eventId:id,dateISO:ev?.dateISO||currentDate(),status:'scheduled'};return r
}
function programParticipantContext5B2(rec){return `the ${rec.name}`}
function ensureProgramParticipants5B2(rec,{force=false}={}){
 rec=canonicalProgramRecord5B2(rec);normalizeProgramEnrollment5B2(rec);if(rec.format==='1:1'||rec.kind==='legacy_job')return [];const ids=rec.participantIds||[];if(ids.length)return ids.map(personById).filter(Boolean);if(!force&&!chance(rec.format==='team'?55:35))return [];
 const n=freshPeers(1)[0];if(!n)return [];const cx=typeof academicProgramPeerContext5B3==='function'?academicProgramPeerContext5B3(rec):null;let p=(S.people||[]).find(x=>x.npcId===n.id);if(!p){p=personFromNpc(n,'friend',cx?.roleLabel||`met at ${rec.name.toLowerCase()}`);p.rel=34;p.trust=38;p.roleLabel=cx?.roleLabel||`${rec.name} ${rec.format==='team'?'teammate':'classmate'}`;p.metAt=cx?.metAt||programParticipantContext5B2(rec);p.metVia=cx?.metVia||rec.name;S.people.push(p)}
 if(typeof recordMeetingProvenance4A4==='function')recordMeetingProvenance4A4(p,{sourceType:'program',programId:rec.programId,metAt:cx?.metAt||programParticipantContext5B2(rec),metVia:cx?.metVia||rec.name,knownSinceAge:S.age});rec.participantIds=[...new Set([...(rec.participantIds||[]),p.id])];rec.teammates=rec.participantIds;return [p]
}
function programSessionProgress5B2(rec,pg,{late=false}={}){
 const inst=ensureProgramInstructor5B2(rec),fmt=programFormatModifier5B2(rec.format),quality=(inst?.quality||60)/70,attendance=late?.78:1,base=pg.academic?1.5:2.05,gain=practiceSkill(pg.skill,base*fmt*quality*attendance);rec.lastSkillGain5B2=Math.round(gain*100)/100;rec.programProgress=Math.round(clamp(rec.programProgress+Math.max(.5,gain*(pg.academic?4.2:5.2)))*10)/10;
 const talent=SKILL_TALENT[pg.skill];if(talent)recordTalentEvidence(talent,{source:rec.name,system:'formal programs',eventId:`${rec.id}:${currentDate()}:${rec.attended}`,context:rec.name,quality:gain>=1.8?2:1,recognizerId:inst?.id||null});recordTraitEvidence('Responsible',{source:'attended formal program',system:'formal programs',eventId:`${rec.id}:${currentDate()}:responsible:${rec.attended}`,context:rec.name,quality:1});return gain
}
function programAttendanceApply5B2(rec,ev,status,{reason='',simulated=false}={}){
 const pg=programDefinition5B1(rec.progId||rec.templateId);if(!pg)return null;const sr=programSessionRecord5B2(rec,ev);if(sr.status!=='scheduled'&&sr.status!=='Scheduled')return sr;sr.status=status.toLowerCase();sr.recordedDate=currentDate();sr.recordedMinute=currentMinute();sr.reason=reason||null;
 const inst=ensureProgramInstructor5B2(rec);if(status==='Attended'||status==='Late'){
  rec.status='Active';rec.lifecycle='active';rec.attended=Number(rec.attended||0)+1;rec.consecutiveAbsences=0;rec.streakMissed=0;if(inst)inst.opinion=clamp((inst.opinion??50)+(status==='Late'?1:2));rec.coach=clamp((rec.coach??50)+(status==='Late'?1:2));setCalendarStatus(ev,status,reason||status);programSessionProgress5B2(rec,pg,{late:status==='Late'});const met=ensureProgramParticipants5B2(rec);for(const p of met)p.rel=clamp((p.rel??34)+1);for(const p of (rec.participantIds||[]).map(personById).filter(Boolean))if(!met.includes(p)&&chance(25))p.rel=clamp((p.rel??34)+.5)
 }else if(status==='Absent'){
  rec.missed=Number(rec.missed||0)+1;rec.consecutiveAbsences=Number(rec.consecutiveAbsences||0)+1;rec.streakMissed=rec.consecutiveAbsences;if(inst)inst.opinion=clamp((inst.opinion??50)-3);rec.coach=clamp((rec.coach??50)-3);setCalendarStatus(ev,'Missed',reason||'Did not attend');if(rec.consecutiveAbsences>=10&&rec.status!=='Removed'){rec.status='Removed';rec.lifecycle='removed';rec.removedReason='10 consecutive unexcused absences';for(const e of programCalendarEvents5B1(rec))if(!isTerminal(e.status))setCalendarStatus(e,'Cancelled','Removed for non-attendance');recordOutcome('Program',rec.name,'Removed','10 consecutive unexcused absences.');if(!simulated&&!SIM.skipping)log(`Removed from ${rec.name}`,'Ten consecutive unexcused absences — the program gives your place to someone else.')}
 }else if(status==='Excused'){setCalendarStatus(ev,'Excused',reason||'Excused absence')
 }else if(status==='Cancelled'){setCalendarStatus(ev,'Cancelled',reason||'Program session cancelled')}
 return sr
}
function markProgramSession5B2(evId,status,reason=''){const ev=(S.calendar||[]).find(e=>e.id===evId);if(!ev)return null;const rec=programRec(ev);if(!rec)return null;return programAttendanceApply5B2(rec,ev,status,{reason})}
function attendProgram(evId,{simulated=false}={}){
 const ev=(S.calendar||[]).find(e=>e.id===evId);if(!ev||isTerminal(ev.status))return null;const rec=programRec(ev),pg=rec&&programDefinition5B1(rec.progId);if(!rec||!pg)return null;if(rec.summerJob5B4&&typeof attendSummerJobShift5B4==='function')return attendSummerJobShift5B4(evId,{simulated});normalizeProgramEnrollment5B2(rec);if(rec.status==='Removed'||rec.status==='Dropped')return null;
 if(!simulated){if(ev.dateISO!==currentDate()){toast('That session is on another day.');return null}const m=currentMinute();if(m>Number(ev.graceMinute??pg.start+30)){programAttendanceApply5B2(rec,ev,'Absent',{reason:'Arrived after the attendance grace period'});return null}if(m<pg.start)advanceTime(pg.start-m,{silent:true})}
 const late=!simulated&&currentMinute()>pg.start,status=late?'Late':'Attended';programAttendanceApply5B2(rec,ev,status,{reason:simulated?'Simulated attendance':late?'Arrived after the session started':'Attended',simulated});
 if(pg.academic&&needsFormalSchool()){const handled=typeof academicProgramApplySession5B3==='function'&&academicProgramApplySession5B3(rec,pg,{late:status==='Late'});if(!handled){const low=[...(S.school?.subjects||[])].sort((a,b)=>a.score-b.score)[0];if(low){low.score=Math.min(100,Math.round((low.score+.35)*10)/10);low.skill=clamp((low.skill||0)+.5)}}}
 if(!simulated){const end=Number(ev.endMinute??pg.end),remain=Math.max(0,end-currentMinute());if(remain)advanceTime(remain,{silent:true});S.energy=clamp(S.energy-(late?9:12));S.stress=clamp(S.stress+1)}
 if(ev.payload?.last)finishProgram(rec,pg);else if(!simulated&&!SIM.skipping){const inst=ensureProgramInstructor5B2(rec);log(`${rec.name} • ${status.toLowerCase()}`,`${inst?.name||'Your instructor'} leads the session. ${status==='Late'?'You miss part of the warm-up, but still get useful practice.':'Structured feedback helps you progress faster than casual practice.'}`)}return rec
}
function programMissed(ev){const rec=programRec(ev);if(!rec)return;if(rec.summerJob5B4&&typeof missSummerJobShift5B4==='function')return missSummerJobShift5B4(ev,'Did not attend');normalizeProgramEnrollment5B2(rec);return programAttendanceApply5B2(rec,ev,'Absent',{reason:'Did not attend'})}
function programCompletionReady5B2(rec){const evs=programCalendarEvents5B1(rec);return evs.length>0&&evs.every(e=>isTerminal(e.status))&&rec.status!=='Removed'&&rec.status!=='Dropped'}
function finishProgram(rec,pg){
 rec=canonicalProgramRecord5B2(rec);normalizeProgramEnrollment5B2(rec);if(rec.completionRecorded)return rec;rec.status='Done';rec.lifecycle='completed';rec.completedDate=currentDate();rec.completionRecorded=true;const total=Math.max(1,rec.total||programCalendarEvents5B1(rec).length),rate=(rec.attended||0)/total,lvl=skillValue(pg.skill)/10,inst=ensureProgramInstructor5B2(rec),score=clamp(lvl*7+rate*40+(inst?.quality||60)*.15+(hashOf(`${rec.programId}|${S.name}|finish`)%1800)/100,0,100),tier=score>=75?'Top result':score>=55?'Strong finish':score>=35?'Completed':'Struggled';rec.completion={dateISO:currentDate(),attendanceRate:Math.round(rate*100),score:Math.round(score*10)/10,tier};devProgramResult(rec,pg,score);if(pg.rep)addRep(pg.rep,tier==='Top result'?4:2);S.happiness=clamp(S.happiness+(tier==='Struggled'?-1:4));recordOutcome('Program',pg.name,tier,`Attendance ${Math.round(rate*100)}% • ${pg.skill} level ${Math.max(1,Math.ceil(lvl))}.`);if(pg.final&&tier!=='Struggled')S.milestones.unshift({dateISO:currentDate(),age:S.age,title:`☀️ ${pg.name}`,text:`${pg.final}: ${tier.toLowerCase()} (${Math.round(rate*100)}% attendance).`});return rec
}
function programStatusSummary5B2(rec){normalizeProgramEnrollment5B2(rec);const inst=ensureProgramInstructor5B2(rec);return {status:rec.status,format:rec.format,instructor:inst?`${inst.name} • ${inst.role}`:null,attendance:`${rec.attended||0}/${rec.total||0}`,consecutiveAbsences:rec.consecutiveAbsences||0,progress:Math.round(rec.programProgress||0),participants:(rec.participantIds||[]).length}}
function programOfferHtml5B2(offer){
 const rec=programEnrollmentByProgramId5B1(offer.programId),state=rec?.status||'Available',conf=programScheduleConflicts5B1(offer),tryout=programTryoutRequired5B2(offer),tr=tryout?programTryoutState5B2(offer.programId):null,selected=!tryout||!!tr?.passed,blocked=conf.length>0||['Enrolled','Active','Done','Completed'].includes(state)||!selected,reason=conf.length?`Conflict: ${conf[0].title}`:tryout&&!tr?'Tryout required':tryout&&!tr?.passed?'Not selected':state;
 return `<div class="calendar-row"><div><b>${esc(offer.name)}</b><small>${esc(offer.category)} • ${esc(offer.provider)} • ${offer.format} • ${offer.cost?money(offer.cost):'Free'}<br>${formatDate(offer.startDate)}–${formatDate(offer.endDate)} • ${timeLabel(offer.startMinute)}–${timeLabel(offer.endMinute)} • ${offer.durationSessions} sessions${tryout?`<br>Selection: ${tr?esc(tr.result):'tryout required'}`:''}</small></div><div class="inline-actions">${statusTag(reason)}${tryout&&!tr?`<button class="small" data-program-tryout="${esc(offer.templateId)}">Try out</button>`:''}<button class="small primary" data-program="${esc(offer.templateId)}" ${blocked?'disabled':''}>${state==='Considering'?'Ask again':state==='Declined'?'Ask again':'Enroll'}</button></div></div>`
}
function programsHtml(){
 ensureProgramRuntime5B2();const br=schoolBreakState5B1(),offers=discoverProgramOffers5B1().filter(o=>!(typeof academicProgramsHtml5B3==='function'&&o.templateId==='summerSchool')),mine=(S.programs||[]).filter(r=>['Enrolled','Active','Considering','Declined','Removed','Done'].includes(r.status)&&r.formal!==false),cas=Object.entries(CASUAL).filter(([,c])=>S.age>=c.minAge),jobs=PROGRAMS.filter(x=>x.job).map(pg=>({pg,d:legacyJobDates5B1(pg)})).filter(x=>x.d);
 return `<div class="card"><h3>☀️ Programs & free time</h3><p class="muted-text">${br.onBreak?`${esc(br.reason)} — normal school-term classes are not running. Free time is yours unless you enroll in something.`:'School term — formal extracurriculars must fit around the real school timetable.'}</p>${mine.length?`<h4>Your programs</h4>${mine.map(r=>{const q=programStatusSummary5B2(r);return `<div class="calendar-row"><div><b>${esc(r.name)}</b><small>${esc(r.category||'Program')} • ${esc(q.format||'group')}${q.instructor?` • ${esc(q.instructor)}`:''}<br>Attendance ${esc(q.attendance)} • consecutive absences ${q.consecutiveAbsences} • progress ${q.progress}%</small></div>${statusTag(r.status)}</div>`}).join('')}`:''}<h4>Formal programs</h4>${offers.length?offers.map(programOfferHtml5B2).join(''):'<p class="muted-text">No formal program currently fits your age, season and schedule.</p>'}${typeof academicProgramsHtml5B3==='function'?academicProgramsHtml5B3():''}<h4>Casual practice (free & flexible)</h4><div class="inline-actions">${cas.map(([k,c])=>`<button class="small ghost" data-casual="${k}">${esc(c.label)}</button>`).join('')}</div>${typeof summerJobsHtml5B4==='function'?summerJobsHtml5B4():(jobs.length?`<h4>Existing summer work options</h4><div class="prog-list">${jobs.map(({pg,d})=>`<button class="prog-opt" data-program="${pg.id}"><b>${esc(pg.name)}</b><small>${money(pg.pay)}/shift • ${d.length} shifts • ${formatDate(d[0])}–${formatDate(d[d.length-1])}</small></button>`).join('')}</div>`:'')}</div>`
}
function lmpqClick(b){const d=b.dataset;if(typeof summerJobClick5B4==='function'&&summerJobClick5B4(b))return true;if(typeof academicProgramClick5B3==='function'&&academicProgramClick5B3(b))return true;if(d.programTryout){const offer=programOffer5B1(d.programTryout);if(offer)attemptProgramTryout5B2(offer);save();render();return true}if(d.program){enrollProgram(d.program);save();render();return true}if(d.casual){casualPractice(d.casual);save();render();return true}if(d.bake){bake(d.bake);save();render();return true}if(d.admirerOpen){openAdmirer(d.admirerOpen);return true}if(d.admirer){leaveAdmirer(d.admirer,d.personId,d.signed==='1');save();render();return true}if(d.familyOuting){familyOuting();save();render();return true}if(d.wrap){wrapItem(d.wrap,d.paper);save();render();return true}if(d.programGo){attendProgram(d.programGo);save();render();return true}return false}

function migratePrograms5B2(){ensureProgramRuntime5B2();for(const rec of S.programs||[])normalizeProgramEnrollment5B2(rec);return S.programs}
