
// ---------- v7.2 PHASE 5b: PROM (§63–70) ----------
function promEligible(){const g=gradeNumber();return needsFormalSchool()&&g>=8&&g<=12}
function promDaysLeft(){const pr=S.school?.prom;return pr?daysBetween(currentDate(),pr.dateISO):null}
function promTick(){
 const pr=ensureProm();if(!pr||['Done','Skipped'].includes(pr.status))return;const d=promDaysLeft();
 if(pr.status==='Upcoming'&&d<=28){pr.status='Season';const th=thread('prom',`prom-${pr.year}`,'Prom season');threadStep(th,'Prom announced',`${formatDate(pr.dateISO)} at ${pr.venue}`);if(!SIM.skipping)log(pr.junior?'💃 Junior Prom is coming':'💃 Prom is coming',`Posters go up everywhere: ${pr.junior?'junior prom':'prom'} is on ${formatDate(pr.dateISO)} at ${pr.venue}. Dress code: formal. Tickets ${money(pr.ticket)}. Suddenly everyone is asking everyone.`,true)}
 if(pr.status!=='Season')return;
 // NPC agency: peers pair up, some decide not to go
 const pool=S.people.filter(p=>!isFamilyPerson(p)&&personAge(p)>=13&&personAge(p)<=18&&Math.abs(personAge(p)-S.age)<=2&&!p.promWith&&p.id!==pr.partnerId);
 for(const p of pool){if(personPromWith(p))continue;const cpl=p.datingNpc&&(S.npcs||[]).find(n=>n.fullName===p.datingNpc);if(cpl&&!cpl.promWith){pairPersonWithNpc(p,cpl);continue}if(chance(3)){const other=freePromNpc([p.npcId],personAge(p));if(other){pairPersonWithNpc(p,other);if(p.rel>=60&&!SIM.skipping)log('Prom news',`${firstName(p)} is going to prom with ${other.fullName}.`)}}else if(chance(.6))p.notGoingProm=true}
 // NPC asks the player
 const dleft=promDaysLeft();if(!SIM.skipping&&!pr.partnerId&&!pr.received.some(r=>r.status==='Pending')&&chance(7+(dleft<=14?8:0))){const c=S.people.filter(p=>eligibleRomance(p)&&!personPromWith(p)&&!p.datingNpc).map(ensureRomanceProfile).filter(p=>(p.attraction>=45&&p.rel>=40)||(dleft<=10&&p.rel>=55)).sort((a,b)=>b.attraction-a.attraction)[0];if(c)npcAsksToProm(c)}
}
function npcAsksToProm(p){const pr=S.school.prom;pr.received.push({personId:p.id,dateISO:currentDate(),status:'Pending'});queueEvent({type:'promInvite',title:`${displayName(p)} asks about prom`,text:`"So… do you have plans for prom? Would you want to go with me?" ${firstName(p)} looks nervous.`,participants:[p.id],priority:4,expiresDays:3,choices:[{id:'accept',label:'Accept'},{id:'friends',label:'Suggest going as friends'},{id:'time',label:'Say you need time'},{id:'decline',label:'Politely decline'},...(pr.partnerId?[{id:'have',label:'Tell them you already have a date'}]:[])]})}
function handlePromInvite(e,id){
 const pr=S.school?.prom,p=personById(e.participants?.[0]);if(!pr||!p)return true;const rec=pr.received.find(r=>r.personId===p.id&&r.status==='Pending');const th=thread('prom',`prom-${pr.year}`,'Prom season');
 if(id==='accept'){if(pr.partnerId){toast('You already have a prom date.');return true}pr.partnerId=p.id;pr.plan='date';pr.asFriends=false;if(rec)rec.status='Accepted';p.rel=clamp(p.rel+6);setPromWithPerson(p,S.name);threadStep(th,'Got a prom date',`${displayName(p)} asked you`);recordOutcome('Prom',`${displayName(p,'formal')} asked you`,'Accepted','You said yes.');log('Prom date!',`You say yes. ${firstName(p)} grins and tries to act casual about it. It is not working.`,true);if(eligibleRomance(p)&&p.romanceStage==='none')p.romanceStage='crush'}
 else if(id==='friends'){pr.partnerId=p.id;pr.plan='date';pr.asFriends=true;if(rec)rec.status='Accepted as friends';p.rel=clamp(p.rel+3);setPromWithPerson(p,S.name);threadStep(th,'Going with a friend',displayName(p));log('Prom — as friends',`"As friends? Sure — honestly that's less pressure," ${firstName(p)} says.`)}
 else if(id==='time'){if(rec){rec.status='Waiting';rec.deadline=addDays(currentDate(),2)}scheduleFollowUp('promTimeout',{personId:p.id},{days:2,minute:1080});log('You need time',`"Can I get back to you?" ${firstName(p)} nods. "Sure… just don't take too long."`)}
 else if(id==='have'){if(rec)rec.status='Declined';log('Already going',`You tell ${firstName(p)} you already have a date. "Oh — right. Of course." It is a little awkward.`)}
 else{if(rec)rec.status='Declined';p.rel=clamp(p.rel-1);log('Declined',`You thank ${firstName(p)} but say no. They take it well, mostly.`);if(chance(70)){const o=freePromNpc([p.npcId],personAge(p));if(o)pairPersonWithNpc(p,o)}}
 return true
}
const PROM_APPROACH={casual:'Ask casually',private:'Ask privately',promposal:'Make a cute promposal',text:'Ask by text',public:'Ask in front of friends',gift:'Ask with a small gift',joke:'Ask jokingly'};
function promCandidates(){return S.people.filter(p=>!isFamilyPerson(p)&&personAge(p)>=13&&personAge(p)<=18&&Math.abs(personAge(p)-S.age)<=2&&!p.movedAway).map(p=>{ensureRomanceProfile(p);return p})}
function promAskTarget(id){if(String(id).startsWith('npc:')){const n=npcById(id.slice(4));if(!n)return null;const p=addNeighborPerson(n,'neighbor');p.rel=Math.max(p.rel,45);ensureRomanceProfile(p);return p}return personById(id)}
function promAskModal(personId){const p=promAskTarget(personId);if(!p)return;openModal(`Ask ${displayName(p)} to prom`,`<p class="muted-text">How you ask matters — and depends on who they are.${p.trust>=55&&p.boundaries?.includes('noPublicAffection')?` You know ${firstName(p)} dislikes public attention.`:''}</p><div class="modal-action-grid">${Object.entries(PROM_APPROACH).filter(([k])=>k!=='text'||canUsePhone()).map(([k,l])=>`<button data-prom-approach="${k}" data-person-id="${p.id}">${esc(l)}${k==='gift'?` • ${money(8)}`:k==='promposal'?` • ${money(10)}`:''}</button>`).join('')}<button class="ghost" data-close-modal="1">Not yet</button></div>`)}
function askToProm(personId,approach){
 const pr=S.school?.prom,p=promAskTarget(personId);if(!pr||!p||pr.status!=='Season'){toast('It is not prom season.');return}closeChoiceModal();if(pr.partnerId){toast('You already have a prom date.');return}
 if(pr.asked.some(a=>a.personId===p.id&&a.result!=='Pending')){toast(`You already asked ${firstName(p)}.`);return}
 if((approach==='gift'||approach==='promposal')&&S.age>=13&&!spendOwn(approach==='gift'?8:10)){toast('You cannot afford that approach.');return}
 const recent=pr.asked.filter(a=>daysBetween(a.dateISO,currentDate())<=7).length,tr=p.traits||[],romantic=eligibleRomance(p),a=p.attraction??40;
 const bonus={casual:0,private:tr.includes('Shy')?8:4,promposal:tr.includes('Outgoing')||tr.includes('Funny')?12:tr.includes('Shy')?-6:8,text:tr.includes('Shy')?4:-2,public:tr.includes('Outgoing')?10:(tr.includes('Shy')||tr.includes('Quiet'))?-20:0,gift:p.boundaries?.includes('noExpensiveGifts')?2:5,joke:tr.includes('Funny')?8:-6}[approach]||0;
 let result,reason,story;const prev=pr.asked[pr.asked.length-1];
 const pw=personPromWith(p);if(pw&&pw!==S.name){result='Rejected';reason='Already has a date';story=`"I really like hanging out with you, but I already told ${pw} I'd go with them. I'm sorry."`}
 else if(p.datingNpc){result='Rejected';reason='Dating someone else';story=`"I'm going with ${p.datingNpc} — we're together. But thank you for asking."`}
 else if(p.notGoingProm){result='Rejected';reason='Not going to prom';story=`"I'm actually not going to prom at all. It's just not my thing."`}
 else if(approach==='public'&&(p.boundaries?.includes('noPublicAffection')||tr.includes('Shy'))){result='Rejected';reason='Embarrassed by the public promposal';story=`Everyone turns to look. ${firstName(p)} goes bright red. "I— can we talk about this later?" Later, quietly: "I'm sorry. I just can't do this when everyone is watching."`;addRep('social',-2)}
 else if((p.conflict||0)>25){result='Rejected';reason='Recent argument';story=`"After everything lately? I don't think that's a good idea."`}
 else if(S.romance.partnerId===p.id){result='Accepted';reason='You are together';story=`"Was that even a question? Of course."`}
 else if(p.rel<35){result='Rejected';reason='Low relationship';story=`"That's… nice of you, but we don't really know each other that well."`}
 else{const dl=promDaysLeft(),late=dl<=7?14:dl<=14?8:0,grp=(S.groups||[]).some(g=>g.members.includes(p.id))?6:0;const score=(romantic?a*.45:15)+p.rel*.35+bonus+late+grp+Math.random()*20-10-(recent>=2?10:0);
  if(score>=55&&romantic&&p.romanceOpen){result='Accepted';reason=a>=70?'Already had a crush on you':approach==='promposal'?'Impressed by the promposal':'Hoping you would ask';story=a>=70?`${firstName(p)} laughs, then covers their face. "Yes. I was literally hoping you'd ask."`:approach==='promposal'?`Your promposal gets a crowd laughing — ${firstName(p)} is laughing hardest. "Okay, okay — YES."`:`"Yes! I'd love to."`}
  else if(chance(12)&&!romantic){result='Rejected';reason='Going with their friend group';story=`"Aww — I already promised my friends we'd all go as a group. Come find us there?"`}
  else if((p.rel>=45||(p.rel>=35&&late>0))&&chance(clamp(35+(p.rel-45)*1.5+late,15,90))){result='Accepted as friends';reason=romantic&&a<45?'No romantic interest, but happy to go as friends':'Strong friendship';story=`"I'd love to go — just as friends, if that's okay?"`}
  else if(tr.includes('Shy')&&chance(50)){result='Pending';reason='Nervous — needs time';story=`"Can I… think about it? I'll tell you by ${formatDate(addDays(currentDate(),2))}."`;scheduleFollowUp('promAnswer',{personId:p.id},{days:2,minute:1020})}
  else{result='Rejected';reason=romantic&&a<35?'Does not share romantic attraction':'Simply not interested';story=`"Thank you for asking — really. But I don't think so."`}}
 if(recent>=1&&prev&&prev.result==='Rejected'&&result!=='Pending'&&chance(40)){const pp=personById(prev.personId);if(pp)story+=` (${firstName(p)} also mentions they heard you asked ${firstName(pp)} first.)`}
 pr.asked.push({personId:p.id,dateISO:currentDate(),approach,result,reason});
 if(recent>=2&&!pr.gossiped){pr.gossiped=true;addRep('social',-3);log('People are talking',`Word gets around that you have asked several people to prom this week. Someone makes a joke about it in the hallway.`)}
 const th=thread('prom',`prom-${pr.year}`,'Prom season');
 if(result.startsWith('Accepted')){pr.partnerId=p.id;pr.plan='date';pr.asFriends=result!=='Accepted';setPromWithPerson(p,S.name);p.rel=clamp(p.rel+(pr.asFriends?3:6));setEmotion('Excited','You have a prom date.',70);threadStep(th,pr.asFriends?'Going with a friend':'Got a prom date',`${displayName(p)} — ${reason}`)}
 else if(result==='Rejected'){p.rel=clamp(p.rel-(reason==='Embarrassed by the public promposal'?5:1));S.happiness=clamp(S.happiness-4);setEmotion('Disappointed','A prom rejection.',55);threadStep(th,'Rejected',`${displayName(p)} — ${reason}`)}
 recordOutcome('Prom',`Asked ${displayName(p,'formal')} (${PROM_APPROACH[approach].toLowerCase()})`,result,reason);rememberPerson(p,`You asked them to prom: ${result.toLowerCase()}.`,2);advanceTime(20);log(`Prom: ${result}`,story,result.startsWith('Accepted'))
}
const PROM_PREP={outfitBuy:['Buy a formal outfit',120,'outfit','bought'],outfitOwn:['Wear something you own',0,'outfit','existing'],outfitBorrow:['Borrow an outfit',0,'outfit','borrowed'],hairSalon:['Get hair styled',30,'hair','salon'],hairDiy:['Do your own hair',0,'hair','diy'],makeup:['Do makeup',0,'makeup','done'],corsage:['Buy a corsage / boutonnière',25,'corsage','yes'],rideParents:['Ask a caregiver to drive',0,'transport','parents'],rideCarpool:['Carpool with friends',0,'transport','carpool'],rideLimo:['Split a limo',40,'transport','limo'],dinnerOut:['Plan dinner out',30,'dinner','restaurant'],dinnerHome:['Dinner at home first',0,'dinner','home'],photos:['Plan pre-prom photos',0,'photos','yes'],ticket:['Buy your ticket',40,'ticket','bought'],waiver:['Ask about a ticket waiver',0,'ticket','waiver']};
function promPrep(key){
 const pr=S.school?.prom,x=PROM_PREP[key];if(!pr||!x||pr.status!=='Season')return;const [label,cost,slot,val]=x;
 if(slot==='outfit'&&val==='existing'&&S.inventoryItems.filter(i=>i.lifecycleType==='wearable'&&i.condition>40).length<2){toast('You do not own anything nice enough — borrow or buy.');return}
 if(slot==='makeup'&&!findUsable('makeup')){toast('You do not own a makeup set.');return}
 if(slot==='corsage'&&!['US','UK','CA','AU'].includes(calendarProfile().region)){toast('Not really a tradition here.');return}
 if(cost){const parentsPay=S.age<18&&['outfit','ticket'].includes(slot)&&caregiverYes(S.wealth==='Struggling'?-25:0);if(parentsPay){log('Caregiver helps',`${primaryCaregiver()} offers to cover it: ${label.toLowerCase()}.`)}else if(!spendOwn(cost)){toast(`${label} costs ${money(cost)}. Try a free option.`);return}}
 if(slot==='ticket'&&val==='waiver'&&!chance(70)){toast('The waiver list is full — ask a caregiver or buy a ticket.');return}
 if(slot==='makeup'){const it=openOne(findUsable('makeup'));it.remaining=clamp(it.remaining-3)}
 pr.prep[slot]=val;if(slot==='ticket')pr.ticketBought=true;advanceTime(slot==='outfit'&&val==='bought'?120:30);log(`Prom prep • ${label}`,{outfit:val==='borrowed'?'It fits — mostly. A safety pin fixes the rest.':val==='existing'?'With a little ironing, something you already own looks great.':'You find something that makes you stand up straighter.',hair:val==='salon'?'The stylist works magic.':'A tutorial, two attempts, and it looks good.',transport:val==='limo'?'The group chat explodes with excitement about the limo.':val==='carpool'?'Your friends work out who drives.':`${primaryCaregiver()} agrees to drive, on the condition of taking photos.`,dinner:val==='restaurant'?'Reservations made.':'Home dinner first — cheaper and calmer.',photos:'Someone volunteers their backyard for photos.',ticket:val==='waiver'?'The school quietly covers your ticket.':'Ticket bought.',corsage:'Ordered, in a color that matches.',makeup:'You practice the look once, just to be sure.'}[slot])
}
function setPromPlan(plan){const pr=S.school?.prom;if(!pr||pr.status!=='Season')return;if(plan==='committee'){if(pr.committee>=3){toast('Planning is done.');return}if(atSchool()){toast('After classes.');return}pr.committee++;addRep('leadership',2);addRep('social',1);advanceTime(60);log('Prom committee',rand(['You argue for twenty minutes about balloon colors. You win.','You help design the decorations. It is going to look good.','You handle the playlist requests — a thankless job.']));return}
 if(plan!=='date'&&pr.partnerId){const p=personById(pr.partnerId);if(p){p.rel=clamp(p.rel-6);p.promWith=null;log('Prom plans changed',`You tell ${firstName(p)} you are not going together after all. They are hurt.`)}pr.partnerId=null}
 pr.plan=plan;const th=thread('prom',`prom-${pr.year}`,'Prom season');threadStep(th,{friends:'Going with friends',alone:'Going alone',skip:'Skipping prom',wait:'Waiting to be asked'}[plan]||plan,'');log('Prom plans',{friends:'You and your friends decide to go as a group. No pressure, all fun.',alone:'You decide to go on your own. Plenty of people do.',skip:'You decide prom is not for you this year.',wait:'You decide to wait and see if someone asks.'}[plan])}
function promHtml(){
 const pr=S.school?.prom;if(!pr||!['Season'].includes(pr.status))return '';const d=promDaysLeft(),partner=pr.partnerId?personById(pr.partnerId):null;
 const cands=promCandidates().filter(p=>p.id!==pr.partnerId&&!pr.asked.some(a=>a.personId===p.id)),nbs=neighborPromCandidates();
 const prepRow=(slot,keys)=>`<div class="prom-prep"><b>${slot}</b>${pr.prep[slot.toLowerCase()]?`<span class="tag ok">${esc(pr.prep[slot.toLowerCase()])}</span>`:keys.map(k=>`<button class="small ${PROM_PREP[k][1]?'':'ghost'}" data-prom-prep="${k}">${esc(PROM_PREP[k][0])}${PROM_PREP[k][1]?` • ${money(PROM_PREP[k][1])}`:''}</button>`).join('')}</div>`;
 return `<div class="holiday-card prom-card"><div class="holiday-head"><span class="holiday-icon">💃</span><div><b>Prom • ${d===0?'tonight':`in ${d} day${d===1?'':'s'}`}</b><small>${formatDate(pr.dateISO)} • ${esc(pr.venue)} • formal${partner?` • going with ${esc(displayName(partner))}${pr.asFriends?' (as friends)':''}`:pr.plan?` • plan: ${esc(pr.plan)}`:''}</small></div></div>
 ${!partner&&pr.plan!=='skip'?`<h4>Ask someone</h4>${cands.length||nbs.length?`<div class="holiday-acts">${cands.slice(0,10).map(p=>`<button class="small" data-prom-ask="${p.id}">${esc(displayName(p))}${personPromWith(p)?' • has a date':''}${eligibleRomance(p)?'':' (as friends)'}</button>`).join('')}${nbs.slice(0,4).map(n=>`<button class="small ghost" data-prom-ask="npc:${n.id}">${esc(n.fullName)} (neighbor)</button>`).join('')}</div>`:'<p class="muted-text">Nobody left to ask right now — meet more people at school, clubs or around town.</p>'}`:''}
 <div class="holiday-acts">${['friends','alone','wait','skip'].filter(x=>x!==pr.plan).map(x=>`<button class="small ghost" data-prom-plan="${x}">${{friends:'Go with friends',alone:'Go alone',wait:'Wait to be asked',skip:'Skip prom'}[x]}</button>`).join('')}${pr.committee<3?`<button class="small ghost" data-prom-plan="committee">Help the prom committee (${pr.committee}/3)</button>`:''}</div>
 ${pr.plan!=='skip'?`<h4>Preparation</h4>${prepRow('Ticket',['ticket','waiver'])}${prepRow('Outfit',['outfitOwn','outfitBorrow','outfitBuy'])}${prepRow('Hair',['hairDiy','hairSalon'])}${findUsable('makeup')?prepRow('Makeup',['makeup']):''}${partner&&['US','UK','CA','AU'].includes(calendarProfile().region)?prepRow('Corsage',['corsage']):''}${prepRow('Transport',['rideParents','rideCarpool','rideLimo'])}${prepRow('Dinner',['dinnerHome','dinnerOut'])}${prepRow('Photos',['photos'])}<small class="muted-text">Nothing expensive is required — free options work.</small>`:''}</div>`
}
// ---------- Prom night as a scene (§69) ----------
const PROM_SCENE={steps:[
 {view:sc=>({title:'Prom night • getting ready',text:sc.data.accident?'Disaster: a seam splits / a stain appears an hour before you leave.':`You get ready${S.school.prom.prep.outfit?` in your ${S.school.prom.prep.outfit==='bought'?'new':S.school.prom.prep.outfit} outfit`:''}. The mirror says: not bad at all.`,choices:sc.data.accident?[{id:'fix',label:'Fix it fast'},{id:'laugh',label:'Laugh and improvise'}]:[{id:'go',label:'Head out',primary:true}]}),
  choose:(sc,id)=>({line:id==='fix'?'A safety pin and some panic later, it is fixed.':id==='laugh'?'You improvise. It almost looks intentional.':'You head out the door.',score:id==='go'?2:id==='laugh'?3:1,minutes:30})},
 {view:sc=>{const pr=S.school.prom,p=pr.partnerId?personById(pr.partnerId):null;const late=p&&sc.data.late;return {title:'Meeting up',text:p?(late?`${firstName(p)} is running late. Twenty minutes and counting.`:`${firstName(p)} arrives looking great. ${pr.prep.photos?'Photos in the backyard: awkward poses, real smiles.':''}`):pr.plan==='friends'?'Your friends pile into the meeting spot, everyone talking at once.':'You arrive on your own. It is less scary than you thought.',choices:late?[{id:'wait',label:'Wait patiently'},{id:'text',label:'Text them'},{id:'annoyed',label:'Get annoyed'}]:[{id:'compliment',label:'Give a compliment',primary:true},{id:'go',label:'Let\'s go'}]}},
  choose:(sc,id)=>{const p=S.school.prom.partnerId?personById(S.school.prom.partnerId):null;return {line:{wait:'You wait. They arrive breathless and grateful you did not make a scene.',text:'"5 min!!" They arrive ten minutes later.',annoyed:'You are annoyed, and it shows. The ride is quiet.',compliment:p?`${firstName(p)} smiles. "You too."`:'Someone compliments you right back.',go:'Off you go.'}[id],score:{wait:5,text:2,annoyed:-8,compliment:6,go:2}[id],minutes:40}}},
 {view:sc=>{const ev=sc.data.ev2||(sc.data.ev2=rand(['none','none','crush','friend','compliment']));return {title:'Arrival & dancing',text:{none:`The venue looks amazing. The music is loud; the dance floor fills up fast.`,crush:'You spot your old crush across the room — with someone else.',friend:'A friend pulls you aside: they had a fight with their date and are upset.',compliment:'Someone you barely know tells you that you look incredible.'}[ev],choices:ev==='crush'?[{id:'shrug',label:'Shrug it off and dance'},{id:'stare',label:'Keep looking over'}]:ev==='friend'?[{id:'help',label:'Help your friend'},{id:'later',label:'Tell them you\'ll talk later'}]:[{id:'dance',label:'Dance',primary:true},{id:'snacks',label:'Hang by the snacks'},{id:'talk',label:'Talk with friends'}]}},
  choose:(sc,id)=>({line:{shrug:'You shrug it off. Tonight is yours.',stare:'You keep glancing over. It takes some shine off the night.',help:'You spend fifteen minutes helping your friend. They will remember that.',later:'"Later" turns into never. Your friend notices.',dance:'You dance until your feet hurt. Worth it.',snacks:'The snack table is where the best gossip happens.',talk:'You and your friends shout conversations over the music.'}[id],score:{shrug:4,stare:-6,help:6,later:-4,dance:8,snacks:2,talk:5}[id],minutes:60})},
 {view:sc=>{const pr=S.school.prom,p=pr.partnerId?personById(pr.partnerId):null;const confess=!p&&chance(18)&&S.people.find(x=>eligibleRomance(x)&&(x.attraction||0)>=65&&!x.promWith);if(confess)sc.data.confessor=confess.id;return {title:'Slow song',text:confess?`During the slow song, ${firstName(confess)} comes over. "Can I tell you something? I've liked you for a while."`:p?`A slow song starts. ${firstName(p)} looks at you.`:'A slow song starts. Couples drift to the floor.',choices:confess?[{id:'feelings',label:'Say you feel the same'},{id:'gentle',label:'Gently say you see them as a friend'},{id:'time',label:'Say you need time to think'}]:p?[{id:'slow',label:'Ask for a slow dance',primary:true},{id:'sit',label:'Sit this one out'}]:[{id:'groupdance',label:'Join a group sway with friends'},{id:'sit',label:'Grab a drink'}]}},
  choose:(sc,id)=>{const c=sc.data.confessor?personById(sc.data.confessor):null;if(id==='feelings'&&c){if(!S.romance.partnerId)setPartner(c,'dating');c.rel=clamp(c.rel+8);sc.data.newCouple=c.id}if(id==='gentle'&&c){c.rel=clamp(c.rel-2);c.attraction=clamp((c.attraction||50)-20)}const p=S.school.prom.partnerId?personById(S.school.prom.partnerId):null;
   return {line:{slow:`You sway together, not very skillfully. ${S.school.prom.asFriends?'It is goofy and sweet.':'It is a moment you will remember.'}`,sit:'You sit it out and watch. Still nice.',groupdance:'A circle of friends swaying badly to a love song. Perfect.',feelings:`You tell ${firstName(c)} you feel the same. The rest of the night is a blur of smiling.`,gentle:`You tell ${firstName(c)} kindly. They nod — it hurts, but they are glad they said it.`,time:`"Can I think about it?" ${firstName(c)} nods.`}[id],score:{slow:9,sit:0,groupdance:6,feelings:10,gentle:1,time:2}[id],minutes:20}}},
 {view:sc=>{const r=ensureRep(),nom=(r.social+r.leadership)/2>=45&&chance(55);sc.data.nominated=nom;return {title:'Prom court',text:nom?'They announce the prom court nominees — and your name is called.':'They announce prom court. Your friends cheer for the winners.',choices:[{id:'ok',label:nom?'Walk up to the stage':'Cheer',primary:true}]}},
  choose:(sc,id)=>{if(!sc.data.nominated)return {line:'You cheer for the court. Someone throws confetti.',score:2,minutes:20};const win=chance(35+ensureRep().social*.3);sc.data.court=win;if(win){addRep('social',6);return {line:'You win. There is a crown or a sash involved, and photos you will never live down.',score:10,minutes:20}}return {line:'You do not win, but being nominated was a nice surprise.',score:4,minutes:20}}},
 {view:sc=>({title:'After prom',text:'The lights come up. What now?',choices:[{id:'diner',label:'Late-night diner with friends'},{id:'home',label:'Go home'},{id:'after',label:'Go to the after-party'}]}),
  choose:(sc,id)=>{if(id==='after'&&S.age<18&&curfewMinute()&&curfewMinute()<1439&&!caregiverYes(-10)){sc.data.defied=true;return {line:'Your curfew says no. You go anyway, a little nervous the whole time.',score:2,end:true,minutes:90}}return {line:{diner:'Pancakes at midnight in formal clothes. The best part of the night, maybe.',home:'You go home and kick your shoes off. Tired and happy.',after:'The after-party is loud and fun, and you leave at a reasonable hour.'}[id],score:{diner:6,home:2,after:4}[id],end:true,minutes:id==='home'?30:90}}}
],finish(sc){
 const pr=S.school?.prom;if(!pr)return;pr.status='Done';const p=pr.partnerId?personById(pr.partnerId):null,s=sc.score,tier=s>=80?'A wonderful night':s>=62?'A good night':s>=45?'A mixed night':'A rough night';
 const ev=S.calendar.find(e=>e.id===`prom-${pr.year}`);if(ev)setCalendarStatus(ev,'Attended','Went to prom');
 if(p){p.rel=clamp(p.rel+(s>=62?6:1));rememberPerson(p,`You went to prom together${pr.asFriends?' as friends':''}: ${tier.toLowerCase()}.`,3)}
 S.needs.social=clamp(S.needs.social+25);S.needs.fun=clamp(S.needs.fun+25);S.happiness=clamp(S.happiness+(s>=62?8:0));addRep('social',3);
 const memory=p?`You attended prom with ${displayName(p,'formal')}${pr.asFriends?' as friends':''}.`:pr.plan==='friends'?'You went to prom with your friends.':'You went to prom on your own.';
 S.milestones.unshift({dateISO:currentDate(),age:S.age,title:'💃 Prom',text:`${memory} ${tier}.${sc.data.court?' You were crowned on prom court.':''}`});
 const th=thread('prom',`prom-${pr.year}`,'Prom season');threadStep(th,'Prom night',tier,{resolve:true});recordOutcome('Prom','Prom night',tier,sc.lines.slice(-3).join(' '));
 if(sc.data.defied)defyCheck({endMinute:1439});
 log(`💃 Prom — ${tier.toLowerCase()}`,`${memory} ${sc.lines.join(' ')}`,true)
}};
function attendProm(){const pr=S.school?.prom;if(!pr||pr.status!=='Season'||pr.dateISO!==currentDate()){toast('Prom is not tonight.');return}if(pr.plan==='skip'){toast('You decided to skip prom.');return}if(!pr.ticketBought){toast('You need a ticket (or a waiver) first.');return}const ev=S.calendar.find(e=>e.id===`prom-${pr.year}`);if(currentMinute()<1080){toast('Prom starts at 7:00 PM.');return}if(ev&&currentMinute()>ev.graceMinute){processCalendar();return}if(ev)setCalendarStatus(ev,'Attending','Getting ready');startScene('prom',{accident:chance(10),late:!!pr.partnerId&&chance(15)})}
function promMissed(ev){const pr=S.school?.prom;if(!pr){setCalendarStatus(ev,'Expired','No prom');return}if(pr.plan==='skip'){setCalendarStatus(ev,'Completed','Skipped by choice');pr.status='Skipped';if(SIM.skipping)return;queueEvent({type:'promSkipNight',title:'Prom night — not going',text:'Everyone is at prom tonight. What do you do instead?',priority:2,expiresDays:1,choices:[{id:'gaming',label:'Game night with other non-prom friends'},{id:'family',label:'Movie night with family'},{id:'alone',label:'Enjoy a quiet evening'}]});return}
 pr.status='Done';setCalendarStatus(ev,'Missed','Did not go');const p=pr.partnerId?personById(pr.partnerId):null;if(p){p.rel=clamp(p.rel-10);p.trust=clamp(p.trust-8);p.conflict=clamp((p.conflict||0)+12);rememberPerson(p,'You were supposed to go to prom together and never showed.',3);if(!SIM.skipping)log('Missed prom',`${firstName(p)} waited, then went in alone. That is going to be hard to fix.`)}recordOutcome('Prom','Prom night','Missed',p?'Your date went without you.':'You did not go.')}
function handlePromSkip(id){const t={gaming:'You skipped prom and spent the evening gaming with friends who also skipped. Zero regrets.',family:'You skipped prom and watched movies with your family. Honestly lovely.',alone:'A quiet night: snacks, a book, no dress code.'}[id];S.milestones.unshift({dateISO:currentDate(),age:S.age,title:'Prom night',text:t});recordOutcome('Prom','Skipped prom','Chose something else',t);log('Prom night',t);return true}
function promClick(b){const d=b.dataset;if(d.promAsk){promAskModal(d.promAsk);return true}if(d.promApproach){askToProm(d.personId,d.promApproach);save();render();return true}if(d.promPrep){promPrep(d.promPrep);save();render();return true}if(d.promPlan){setPromPlan(d.promPlan);save();render();return true}if(d.promGo){attendProm();save();return true}if(d.sceneChoice){sceneChoice(d.sceneChoice);return true}if(d.sceneResume){renderScene();return true}if(d.romance){const rp=personById(d.personId);romanceAction(rp,d.romance);syncLoveAfterRomance(rp,d.romance);save();render();return true}if(d.romanceOpen){romanceMenu(d.romanceOpen);return true}return false}

// v7.3: prom date = middle of semester 2 (moved to the following Saturday); consistent two-way pairs
function promDateFor(yearKey){const a=academicYear(yearKey);let d=addDays(a.sem2Start,Math.floor(daysBetween(a.sem2Start,a.end)/2));while(parseISO(d).getUTCDay()!==6)d=addDays(d,1);return d}
function ensureProm(){
 if(!promEligible())return null;const sc=S.school;if(sc.yearKey==null)return null;if(sc.prom&&sc.prom.year===sc.yearKey)return sc.prom;
 const d=promDateFor(sc.yearKey);if(d<=currentDate())return null;const junior=gradeNumber()<=9;
 sc.prom={year:sc.yearKey,junior,dateISO:d,venue:junior?'the school gym, transformed':rand(['the Grand Hotel ballroom','the school gym, transformed','the riverside event hall','the old city museum']),dress:'Formal',status:'Upcoming',plan:null,partnerId:null,asFriends:false,asked:[],received:[],prep:{},committee:0,ticket:junior?20:40,ticketBought:false};
 createCalendarEvent({id:`prom-${sc.yearKey}`,type:'prom',title:junior?'Junior Prom':'Prom',dateISO:d,startMinute:1140,endMinute:1380,graceMinute:1230,location:sc.prom.venue,payload:{year:sc.yearKey},required:false,source:'school'});return sc.prom
}
function npcPromWith(n){return n?.promWith||null}
function personPromWith(p){return p?.promWith||npcById(p?.npcId)?.promWith||null}
function setPromWithNpc(npcId,name){const n=npcById(npcId);if(n)n.promWith=name;for(const p of S.people)if(p.npcId===npcId)p.promWith=name}
function setPromWithPerson(p,name){p.promWith=name;if(p.npcId)setPromWithNpc(p.npcId,name)}
function freePromNpc(excludeIds,age){return (S.npcs||[]).filter(n=>!excludeIds.includes(n.id)&&!n.promWith&&Math.abs(npcAge(n)-age)<=1&&npcAge(n)>=13&&npcAge(n)<=18&&!n.movedAway).sort(()=>Math.random()-.5)[0]||null}
function pairPersonWithNpc(p,n){if(!p||!n)return;setPromWithPerson(p,n.fullName);setPromWithNpc(n.id,displayName(p,'formal'))}
function neighborPromCandidates(){const ids=new Set(S.people.map(p=>p.npcId).filter(Boolean));return (S.neighborhood?.households||[]).map(id=>S.households.find(h=>h.id===id)).filter(Boolean).flatMap(h=>hhKids(h)).filter(n=>!ids.has(n.id)&&npcAge(n)>=13&&npcAge(n)<=18&&Math.abs(npcAge(n)-S.age)<=2&&!n.movedAway)}
