// =====================================================================
// PHASE 3B.3 — Romantic Interactions / Official Relationship / Breakup / Exes
// Builds on 3B.1 canonical p.love, 3B.2 scheduled dates, Phase 3A memory,
// and the H3 Decision Ledger. No matchmaking / blind-date work lives here.
// =====================================================================
const ROMANCE_AFFECTION={
 compliment:{label:'Compliment them',minStage:'noticing',minutes:10,physical:false,base:42,gain:2},
 flirt:{label:'Flirt',minStage:'crushOne',minutes:15,physical:false,base:48,gain:3},
 holdHands:{label:'Hold hands',minStage:'crushMutual',minutes:15,physical:true,base:54,gain:4,milestone:'holdingHands'},
 hug:{label:'Hug',minStage:'crushMutual',minutes:10,physical:true,base:50,gain:3},
 cheekKiss:{label:'Kiss on the cheek',minStage:'goingOut',minutes:10,physical:true,base:59,gain:4,milestone:'cheekKiss'},
 firstKiss:{label:'First kiss',minStage:'goingOut',minutes:15,physical:true,base:67,gain:7,milestone:'firstKiss'},
 kiss:{label:'Kiss',minStage:'goingOut',minutes:10,physical:true,base:62,gain:4},
 goodbyeKiss:{label:'Goodbye kiss',minStage:'goingOut',minutes:10,physical:true,base:60,gain:3}
};
function loveStageIndex3B3(id){if(id==='ex')return -1;const n=LOVE_IDX[id];return Number.isFinite(n)?n:0}
function romanceStageLabel3B3(p){return romanceDisplayLabelH4(p)}
function ensureRomance3B3State(){
 S.romance=S.romance||{};S.romance.history=Array.isArray(S.romance.history)?S.romance.history:[];
 for(const p of S.people||[]){const L=ensureLove(p);L.interactionDays=L.interactionDays&&typeof L.interactionDays==='object'?L.interactionDays:{};L.commitmentHistory=Array.isArray(L.commitmentHistory)?L.commitmentHistory:[];if(L.commitmentHistory.length>20)L.commitmentHistory=L.commitmentHistory.slice(-20)}
}
function migrateRomance3B3(){
 if(!S)return;ensureRomance3B3State();Object.assign(MILESTONE_TYPES,{cheekKiss:'First cheek kiss'});
 for(const p of S.people||[]){const L=ensureLove(p),official=loveStageIndex3B3(L.stage)>=LOVE_IDX.official&&L.stage!=='ex';
  if(official&&S.romance?.partnerId===p.id){const ms=(p.milestones||[]).find(m=>m.type==='official');L.relationshipStartDate=L.relationshipStartDate||S.romance.relationshipStartDate||ms?.dateISO||L.since||null;if(L.relationshipStartDate)S.romance.relationshipStartDate=S.romance.relationshipStartDate||L.relationshipStartDate}
  if(L.stage==='ex'||p.formerPartner){p.formerPartner=true;const bm=(p.milestones||[]).find(m=>m.type==='breakup'),rh=[...(S.romance.history||[])].reverse().find(h=>h.personId===p.id||h.name===displayName(p,'formal'));L.relationshipEndDate=L.relationshipEndDate||bm?.dateISO||rh?.endDate||rh?.dateISO||null;L.relationshipStartDate=L.relationshipStartDate||rh?.startDate||null}
  const keys=Object.keys(L.interactionDays).sort();if(keys.length>21)for(const k of keys.slice(0,-21))delete L.interactionDays[k]
 }
 S.romance3B3Migrated=true;if(typeof migrateRomance3B4==='function')migrateRomance3B4()
}
function romanceDailyProgress3B3(p,key,gain){
 if(romanceH5CanonicalPartner(p)){const r=applyRelationshipOutcomeH5(p.id,key,'completed',{dailyKey:key,gain});if(!r.ok)log('Romantic connection',r.reason);return r.ok}const L=ensureLove(p),day=currentDate(),rec=L.interactionDays[day]||(L.interactionDays[day]={count:0,keys:[]});rec.keys=Array.isArray(rec.keys)?rec.keys:[];
 if(rec.keys.includes(key)||rec.count>=3)return false;rec.keys.push(key);rec.count++;L.progress=clamp((L.progress||0)+gain);return true
}
function romanceDateProgress3B3(p,tier,plan){
 if(!p)return;const gain=tier==='Great date'?10:tier==='Good date'?7:tier==='Okay date'?3:tier==='Awkward date'?-2:4;const L=ensureLove(p);if(romanceH5CanonicalPartner(p)){const r=applyRelationshipOutcomeH5(p.id,'date','completed',{transactionId:'date:'+plan?.id,dailyKey:'date',dateISO:plan?.dateISO||currentDate(),gain,conflict:gain<0?2:0});if(!r.ok)log('Date connection',r.reason)}else{L.progress=clamp((L.progress||0)+gain);if(gain<0)p.conflict=clamp((p.conflict||0)+2)}L.lastMeaningfulRomanceDate=plan?.dateISO||currentDate()
}
function romanceAffectionContext3B3(p,action){const L=ensureLove(p),last=(L.dateHistory||[]).at(-1);return {kind:'romanceAffection',action,stage:L.stage,location:S.location||'Home',afterDate:!!(last&&last.dateISO===currentDate())}}
function affectionGate3B3(p,action){
 const a=ROMANCE_AFFECTION[action],L=ensureLove(p);if(!a||!eligibleRomance(p))return {ok:false,why:'That is not appropriate right now.'};
 if(L.stage==='ex')return {ok:false,why:'You are not currently together.'};if(a.physical&&partnerBoundaryH1(p,'noPublicAffection')&&S.location!=='Home')return {ok:false,why:'They do not feel comfortable with affection in public.'};if(loveStageIndex3B3(L.stage)<loveStageIndex3B3(a.minStage))return {ok:false,why:'The relationship is not at that point yet.'};
 if(['firstKiss','kiss','cheekKiss','goodbyeKiss'].includes(action)&&(p.trust??0)<45)return {ok:false,why:'There is not enough trust for that right now.'};
 if(action==='goodbyeKiss'){const last=(L.dateHistory||[]).at(-1);if(!last||last.dateISO!==currentDate())return {ok:false,why:'A goodbye kiss only makes sense around a date or romantic outing.'}}
 if(action==='firstKiss'&&hasMs(p,'firstKiss'))return {ok:false,why:'You already had your first kiss together.'};if(action==='kiss'&&!hasMs(p,'firstKiss'))return {ok:false,why:'Your first kiss has not happened yet.'};
 return {ok:true}
}
function romanceAffectionResponse3B3(p,action){
 const a=ROMANCE_AFFECTION[action],gate=affectionGate3B3(p,action);if(!gate.ok)return {kind:'blocked',why:gate.why};const L=ensureLove(p),ctx=romanceAffectionContext3B3(p,action),prior=findDecision('romanceAffection',`${p.id}:${action}`,ctx,p.id);
 if(prior)return {kind:prior.outcome==='Accepted'?'yes':prior.outcome==='Hesitate'?'hesitate':'no',why:prior.reason,prior,reused:true};
 const c=romanceCompatibility(p),traits=p.traits||[];let outcome='Declined',why='';
 if(!c.orientationOK)why=`${firstName(p)} gently makes it clear they do not feel that kind of attraction.`;
 else if(c.committedElsewhere&&S.romance?.partnerId!==p.id)why=`${firstName(p)} is committed to someone else.`;
 else if(a.physical&&!L.mutual)why=`${firstName(p)} is not comfortable making the moment physical.`;
 else if((p.conflict||0)>=55)why=`${firstName(p)} pulls back. "Can we sort out what is going on between us first?"`;
 else {const shy=traits.includes('Shy')||traits.includes('Quiet'),bold=traits.includes('Bold'),score=a.base+(p.rel-55)*.24+(p.trust-50)*.28+(L.npcAttraction-50)*.16+(L.mutual?10:0)+(bold?4:0)-(shy&&['firstKiss','kiss'].includes(action)?4:0)-(p.conflict||0)*.25+(Math.random()*14-7);
  if(score>=63){outcome='Accepted';why=action==='holdHands'?`${firstName(p)} smiles and laces their fingers through yours.`:action==='hug'?`${firstName(p)} leans into the hug and holds on for a moment.`:action==='cheekKiss'?`${firstName(p)} smiles, surprised but happy, and stays close.`:['firstKiss','kiss','goodbyeKiss'].includes(action)?`${firstName(p)} meets you halfway. The kiss is mutual and unhurried.`:`${firstName(p)} smiles back. The feeling is clearly mutual.`}
  else if(score>=51){outcome='Hesitate';why=`${firstName(p)} pauses. "Maybe not right now?" You leave it there.`}
  else why=`${firstName(p)} gently says no. You respect the answer.`
 }
 const reconsider=addDays(currentDate(),outcome==='Accepted'?1:outcome==='Hesitate'?3:5);const rec=recordDecision({requestType:'romanceAffection',targetKey:`${p.id}:${action}`,decisionMakerId:p.id,context:ctx,outcome,reason:why,reconsiderAfter:reconsider,resolved:true});return {kind:outcome==='Accepted'?'yes':outcome==='Hesitate'?'hesitate':'no',why,record:rec,reused:false}
}
function romanceAffection3B3(p,action){
 const a=ROMANCE_AFFECTION[action],r=romanceAffectionResponse3B3(p,action);if(!a){return false}closeChoiceModal();if(r.kind==='blocked'){toast(r.why);return false}if(r.reused){log(r.kind==='yes'?'A familiar moment':'Their answer has not changed',r.why);return r.kind==='yes'}
 advanceTime(a.minutes,{silent:true});if(r.kind==='yes'){p.rel=clamp(p.rel+(a.physical?2:1));p.trust=clamp(p.trust+(a.physical?1:0));if(action==='flirt')setPlayerCrush(p,true);if(a.milestone)addPersonMilestone(p,a.milestone,action==='holdHands'?'You held hands for the first time.':action==='cheekKiss'?'Your first cheek kiss.':'Your first kiss together.');romanceDailyProgress3B3(p,action,a.gain);if(action==='firstKiss')rememberPerson(p,'Your first kiss together.',3);else if(action==='holdHands')rememberPerson(p,'You held hands for the first time.',2);log(a.label,r.why,true)}
 else{if(r.kind==='no'&&a.physical)p.trust=clamp(p.trust+1);log(r.kind==='hesitate'?'Not right now':'They say no',r.why)}return r.kind==='yes'
}
function romanceCompliment3B3(p){if(!p||!eligibleRomance(p))return false;closeChoiceModal();advanceTime(10,{silent:true});const fresh=romanceDailyProgress3B3(p,'compliment',2);if(fresh){p.rel=clamp(p.rel+1);if((p.traits||[]).includes('Shy'))log('A compliment',`${firstName(p)} looks away, smiling despite themself.`);else log('A compliment',`${firstName(p)} grins. "Okay, that was smooth."`)}else log('A compliment',`You say something sweet. ${firstName(p)} smiles, but you already had this kind of moment today.`);return true}
function romanceConfess3B3(p){
 if(!p||!eligibleRomance(p))return false;ensureRomanceProfile(p);const L=ensureLove(p);setPlayerCrush(p,true);const ctx={kind:'confessCrush',stage:L.stage},prior=findDecision('romanceConfess',p.id,ctx,p.id);if(prior){log('Their answer has not changed',prior.reason);return prior.outcome==='Accepted'}
 const c=romanceCompatibility(p);let ok=false,why;if(!c.orientationOK)why=`"I really like you, but not in that way," ${firstName(p)} says kindly.`;else if(c.committedElsewhere)why=`${firstName(p)} tells you they are already committed to someone else.`;else{const score=c.score+(L.npcAttraction-50)*.15+(p.trust-50)*.15+Math.random()*12-6;ok=score>=58;why=ok?`${firstName(p)} exhales, relieved. "I like you too."`:`${firstName(p)} is gentle. "I care about you, but I do not feel the same way right now."`}
 recordDecision({requestType:'romanceConfess',targetKey:p.id,decisionMakerId:p.id,context:ctx,outcome:ok?'Accepted':'Declined',reason:why,reconsiderAfter:addDays(currentDate(),ok?1:14),resolved:true});advanceTime(15,{silent:true});if(ok){setNpcRomanticInterest(p,'reciprocates');romanceDailyProgress3B3(p,'confess',5);rememberPerson(p,'You confessed your feelings and learned the attraction was mutual.',3)}else if(c.orientationOK)L.npcInterest='notNow';log(ok?'Mutual feelings':'A hard answer',why,ok);return ok
}
function officialEligibility3B3(p){
 if(!p||!eligibleRomance(p))return {ready:false,reason:'not eligible'};const L=ensureLove(p),c=romanceCompatibility(p),dates=(L.dateHistory||[]).length,days=L.since?Math.max(0,daysBetween(L.since,currentDate())):0,sharedHistory=dates>=2||days>=21&&L.progress>=30||L.progress>=55;
 if(!['goingOut','exclusive'].includes(L.stage))return {ready:false,reason:'not currently seeing each other'};if(!L.mutual)return {ready:false,reason:'feelings are not mutual'};if(!c.orientationOK||c.committedElsewhere)return {ready:false,reason:'not romantically available'};if(!sharedHistory)return {ready:false,reason:'you need more shared romantic history'};if((p.trust??0)<52||(p.rel??0)<58)return {ready:false,reason:'the relationship needs more trust and closeness'};if((p.conflict||0)>=45)return {ready:false,reason:'too much unresolved conflict'};return {ready:true,score:c.score+(p.trust-50)*.18+(p.rel-50)*.12+Math.min(12,dates*3)+Math.min(8,L.progress*.08)-(p.conflict||0)*.2,dates,days}
}
function commitOfficial3B3(p,{initiator='player'}={}){
 let L=ensureLove(p);const start=L.relationshipStartDate||currentDate();setNpcRomanticInterest(p,'reciprocates');setLoveStage(p,'official',initiator==='npc'?`${firstName(p)} asked to make the relationship official`:'you both chose to make the relationship official');L=ensureLove(p);L.relationshipStartDate=start;L.relationshipEndDate=null;L.commitmentHistory=Array.isArray(L.commitmentHistory)?L.commitmentHistory:[];L.commitmentHistory.push({dateISO:currentDate(),event:'official',initiator});S.romance.relationshipStartDate=start;S.romance.status='In a relationship';p.formerPartner=!!p.formerPartner;if(typeof pauseOtherProspects3B4==='function')pauseOtherProspects3B4(p);rememberPerson(p,`You became official on ${formatDate(start)}.`,3);return start
}
function romanceOfficialConversation3B3(p,initiator='player'){
 if(!p||!eligibleRomance(p))return false;const L=ensureLove(p);if(loveStageIndex3B3(L.stage)>=LOVE_IDX.official&&L.stage!=='ex'){log('Already official',`You and ${firstName(p)} are already in a committed relationship.`);return true}
 const e=officialEligibility3B3(p),ctx={kind:'officialConversation',stage:L.stage,dateBand:Math.min(4,(L.dateHistory||[]).length),trustBand:Math.floor((p.trust||0)/10),conflictBand:Math.floor((p.conflict||0)/10)},prior=findDecision('romanceOfficial',p.id,ctx,p.id);if(prior){log(prior.outcome==='Accepted'?'Official':'The conversation has not changed',prior.reason);return prior.outcome==='Accepted'}
 let outcome='Continue seeing each other',reason;if(!e.ready)reason=`${firstName(p)} wants to keep getting to know each other before putting a label on it — ${e.reason}.`;else{const roll=e.score+Math.random()*12-6;if(roll>=69){outcome='Accepted';reason=`${firstName(p)} smiles. "Yeah. I want us to be official."`}else if(roll>=58){outcome='Not ready';reason=`${firstName(p)} squeezes your hand. "I really like this. Can we keep seeing each other without rushing the label?"`}else{outcome='Declined';reason=`${firstName(p)} is honest: "I do not think I can promise that kind of commitment right now."`}}
 recordDecision({requestType:'romanceOfficial',targetKey:p.id,decisionMakerId:p.id,context:ctx,outcome,reason,reconsiderAfter:addDays(currentDate(),outcome==='Accepted'?1:outcome==='Not ready'?14:21),resolved:true});advanceTime(25,{silent:true});if(outcome==='Accepted'){commitOfficial3B3(p,{initiator});log('💗 Official',reason,true);return true}if(outcome==='Declined')L.progress=clamp(L.progress-4);log(outcome==='Not ready'?'Not yet':'Not official',reason);return false
}
function romanceNpcRelationshipInitiative3B3(){
 if(S.age<13||S.romance?.optOut||S.romance?.partnerId||SIM.skipping)return false;const candidates=(S.people||[]).filter(p=>eligibleRomance(p)&&['goingOut','exclusive'].includes(ensureLove(p).stage)).filter(p=>{const L=ensureLove(p),e=officialEligibility3B3(p);return e.ready&&(!L.nextCommitmentInitiativeDate||currentDate()>=L.nextCommitmentInitiativeDate)}).sort((a,b)=>(officialEligibility3B3(b).score||0)-(officialEligibility3B3(a).score||0));if(!candidates.length)return false;const p=candidates[0],L=ensureLove(p),traits=p.traits||[],pct=traits.includes('Bold')?18:traits.includes('Shy')||traits.includes('Quiet')?6:11;if(!chance(pct))return false;L.nextCommitmentInitiativeDate=addDays(currentDate(),traits.includes('Busy')?21:14);queueEvent({type:'romanceOfficialInvite',title:`${firstName(p)} wants to talk about you two`,text:`${firstName(p)} takes a breath. "I've been thinking about us. Do you want to make this official?"`,participants:[p.id],priority:4,expiresDays:2,choices:[{id:'accept',label:'Yes — be official'},{id:'continue',label:'Keep seeing each other for now'},{id:'decline',label:'No'}]});return true
}
function romance3B3EventChoice(e,id){
 if(e.type!=='romanceOfficialInvite')return false;const p=personById(e.participants?.[0]);if(!p)return true;const L=ensureLove(p);if(id==='accept'){commitOfficial3B3(p,{initiator:'npc'});log('💗 Official',`You tell ${firstName(p)} yes. The relief on their face turns into a huge smile.`,true)}else if(id==='continue'){L.nextCommitmentInitiativeDate=addDays(currentDate(),14);log('Keep seeing each other',`You tell ${firstName(p)} you are happy with where things are and do not want to rush the label. They understand.`)}else{L.nextCommitmentInitiativeDate=addDays(currentDate(),30);L.progress=clamp(L.progress-6);log('Not official',`You tell ${firstName(p)} you do not want a committed relationship. It hurts, but the answer is clear.`)}return true
}
function romancePartnerInteraction3B3(p,kind){
 if(!p||S.romance?.partnerId!==p.id)return false;const L=ensureLove(p);if(kind==='support'){if(!romanceDailyProgress3B3(p,'support',4)){log('Already checked in',`You have already had a real emotional check-in with ${firstName(p)} today.`);return false}advanceTime(35,{silent:true});p.trust=clamp(p.trust+3);p.rel=clamp(p.rel+2);rememberPerson(p,'You showed up emotionally when they needed you.',2);log('Emotional support',`${firstName(p)} talks; you listen without trying to fix everything.`);return true}
 if(kind==='talkRel'){if(!romanceDailyProgress3B3(p,'talkRel',4)){log('Enough processing for today',`You and ${firstName(p)} already talked through the relationship today.`);return false}advanceTime(30,{silent:true});p.trust=clamp(p.trust+2);p.conflict=clamp((p.conflict||0)-5);log('Relationship talk',`You both say what has been working and what has not. It feels honest rather than dramatic.`);return true}
 if(kind==='resolve'){if((p.conflict||0)<8){toast('There is no major disagreement to resolve right now.');return false}if(!romanceDailyProgress3B3(p,'resolve',3)){log('Give it some time',`You already worked on this disagreement today.`);return false}advanceTime(40,{silent:true});const drop=Math.min(12,6+Math.floor((p.trust||50)/25));p.conflict=clamp(p.conflict-drop);p.trust=clamp(p.trust+2);rememberPerson(p,'You worked through an argument instead of avoiding it.',2);log('Worked it out',`You slow the argument down, listen, and actually resolve part of it.`);return true}
 if(kind==='future'){if(!romanceDailyProgress3B3(p,'future',3)){log('A conversation for another day',`You already talked about the future today.`);return false}advanceTime(35,{silent:true});p.trust=clamp(p.trust+2);rememberPerson(p,'You had a meaningful conversation about the future.',2);log('Talking about the future',`You compare hopes about school, work, where to live, and what a good life might look like. No promises are forced.`);return true}return false
}
function adultIntimacy3B3(p){
 if(!p||!adultRomance(p)||loveStageIndex3B3(ensureLove(p).stage)<LOVE_IDX.goingOut)return false;const ctx={kind:'adultIntimacy',stage:ensureLove(p).stage,location:S.location||'Home'},prior=findDecision('romanceAdultIntimacy',p.id,ctx,p.id);if(prior){log(prior.outcome==='Accepted'?'A private evening':'Their answer has not changed',prior.reason);return prior.outcome==='Accepted'}
 const c=romanceCompatibility(p),score=c.score+(p.trust-50)*.22-(p.conflict||0)*.25-(p.boundaries?.includes('needsTime')?12:0)+Math.random()*12-6,yes=score>=66;const reason=yes?`You ask clearly; ${firstName(p)} says yes clearly. The rest stays private. (fade to black)`:`${firstName(p)} says not tonight. You accept the answer without pressure, and the evening stays comfortable.`;recordDecision({requestType:'romanceAdultIntimacy',targetKey:p.id,decisionMakerId:p.id,context:ctx,outcome:yes?'Accepted':'Declined',reason,reconsiderAfter:addDays(currentDate(),yes?1:5),resolved:true});if(yes){advanceTime(120,{silent:true});p.trust=clamp(p.trust+2);p.rel=clamp(p.rel+2);romanceDailyProgress3B3(p,'adultIntimacy',4)}else p.trust=clamp(p.trust+1);rememberPerson(p,yes?'A private, mutually chosen evening together.':'You respected a no without pressure.',2);log(`${firstName(p)}`,reason);return yes
}
function breakupReasonText3B3(code,p){return ({changed:'your feelings have changed',conflict:'the conflict has gone on too long',trust:'trust has broken down',goals:'you want different things',distance:'life circumstances are pulling you apart',other:'the relationship no longer feels right'})[code]||'the relationship no longer feels right'}
function endRelationship(p,reason,{byNpc=false,mutual=false}={}){
 if(!p)return;let L=ensureLove(p);const start=L.relationshipStartDate||S.romance?.relationshipStartDate||null,end=currentDate();ringOnBreakup(p);setLoveStage(p,'ex',reason||'the relationship ended');L=ensureLove(p);L.relationshipStartDate=start;L.relationshipEndDate=end;L.lastBreakupReason=reason||'the relationship ended';L.playerCrush=false;L.npcInterest='former';L.mutual=false;p.formerPartner=true;p.conflict=clamp((p.conflict||0)+(mutual?3:byNpc?8:6));
 if(S.romance.exclusivePartnerId===p.id)S.romance.exclusivePartnerId=null;if(S.romance.partnerId===p.id){S.romance.partnerId=null;S.romance.partner=null;S.romance.status='Single';S.romance.relationshipStartDate=null}S.romance.history.push({dateISO:end,startDate:start,endDate:end,personId:p.id,age:S.age,name:displayName(p,'formal'),event:`Broke up — ${reason}`,initiator:mutual?'mutual':byNpc?'npc':'player'});if(S.romance.history.length>80)S.romance.history.shift();rememberPerson(p,`The relationship ended on ${formatDate(end)}: ${reason}.`,3);recordOutcome('Relationship',displayName(p,'formal'),'Broke up',reason);setEmotion(byNpc?'Heartbroken':'Conflicted','A relationship ended.',70)
}
function openBreakup3B3(p){if(!p||S.romance?.partnerId!==p.id)return;openModal(`Break up with ${displayName(p)}?`,`<p class="muted-text">This ends the romantic relationship, but it does not delete ${esc(firstName(p))} or erase your history.</p><div class="modal-action-grid">${[['changed','My feelings changed'],['conflict','Too much unresolved conflict'],['trust','Trust is broken'],['goals','We want different things'],['distance','Life circumstances'],['other','This relationship is not right anymore']].map(([k,l])=>`<button data-r3-break="${k}" data-person-id="${p.id}">${esc(l)}</button>`).join('')}<button class="ghost" data-close-modal="1">Cancel</button></div>`)}
function breakup3B3(p,code){if(!p||S.romance?.partnerId!==p.id)return false;const why=breakupReasonText3B3(code,p);closeChoiceModal();endRelationship(p,`you ended it because ${why}`);log('Relationship ended',`You tell ${firstName(p)} the truth: ${why}. It hurts, but the history between you is not erased.`,true);return true}
function reconcileEligibility3B3(p){const L=ensureLove(p);if(L.stage!=='ex'&&!p.formerPartner)return {ready:false,reason:'not an ex-partner'};if(!L.relationshipEndDate)return {ready:false,reason:'the breakup is too recent to revisit'};const days=daysBetween(L.relationshipEndDate,currentDate());if(days<30)return {ready:false,reason:`it has only been ${days} days since the breakup`};const c=romanceCompatibility(p);if(!c.orientationOK||c.committedElsewhere)return {ready:false,reason:'one of you is not romantically available'};if((p.conflict||0)>35)return {ready:false,reason:'too much conflict is still unresolved'};if((p.trust||0)<48||(p.rel||0)<48)return {ready:false,reason:'trust and closeness have not recovered enough'};return {ready:true,days,score:c.score+(p.trust-50)*.15+(p.rel-50)*.12-(p.conflict||0)*.22}}
function reconcileRequest3B3(p){
 if(!p)return false;const e=reconcileEligibility3B3(p);if(!e.ready){log('Not ready to try again',`${firstName(p)} and you are not in a place to reconcile yet — ${e.reason}.`);return false}const L=ensureLove(p),ctx={kind:'reconcile',ended:L.relationshipEndDate,trustBand:Math.floor((p.trust||0)/10),conflictBand:Math.floor((p.conflict||0)/10)},prior=findDecision('romanceReconcile',p.id,ctx,p.id);if(prior){log('The answer has not changed',prior.reason);return prior.outcome==='Accepted'}
 const ok=e.score+Math.random()*12-6>=66,reason=ok?`${firstName(p)} says they have thought about it too. You agree to start slowly instead of pretending the breakup never happened.`:`${firstName(p)} is kind but clear: "I don't think going back is right for me."`;recordDecision({requestType:'romanceReconcile',targetKey:p.id,decisionMakerId:p.id,context:ctx,outcome:ok?'Accepted':'Declined',reason,reconsiderAfter:addDays(currentDate(),ok?1:21),resolved:true});advanceTime(30,{silent:true});if(ok){L.relationshipStartDate=null;L.relationshipEndDate=null;setPlayerCrush(p,true);setNpcRomanticInterest(p,'reciprocates');setLoveStage(p,'goingOut','reconnected after a past relationship');addPersonMilestone(p,'reconciled','You chose to try again slowly.',{once:false});rememberPerson(p,'You reconciled after time apart and agreed to start slowly.',3)}log(ok?'Trying again':'No reconciliation',reason,ok);return ok
}
function romanceSneakOption3B3(p,mode){if(!p||S.age<16||S.age>=18||!isAtHome()||!canSneak(p))return false;const L=ensureLove(p);if(loveStageIndex3B3(L.stage)<LOVE_IDX.goingOut||L.stage==='ex')return false;if(mode==='over'&&S.location!=='Home')return false;return true}
function romanceMenu(personId){
 const p=personById(personId);if(!p)return;if(!eligibleRomance(p)){toast(S.age<13?'Romance is not part of this stage of life.':'That would not be appropriate.');return}if(ensureLove(p).stage!=='ex'&&((S.romance?.partnerId&&S.romance.partnerId!==p.id)||(S.romance?.exclusivePartnerId&&S.romance.exclusivePartnerId!==p.id))){openModal(displayName(p),`<p class="muted-text">You are in a committed relationship. Other romantic progression is paused unless that relationship ends.</p><button class="ghost" data-close-modal="1">Close</button>`);return}ensureRomanceProfile(p);ensureRomance3B3State();const L=ensureLove(p),i=loveStageIndex3B3(L.stage),official=S.romance?.partnerId===p.id&&i>=LOVE_IDX.official,opts=[];
 if(L.stage==='ex'){const re=reconcileEligibility3B3(p);openModal(`${displayName(p)} • Former partner`,`${loveLadderHtmlH4(p)}<p class="muted-text">Your history remains. A breakup does not reset friendship, memories, or milestones.</p>${L.relationshipStartDate?`<p><b>Relationship began:</b> ${formatDate(L.relationshipStartDate)}</p>`:''}${L.relationshipEndDate?`<p><b>Relationship ended:</b> ${formatDate(L.relationshipEndDate)}</p>`:''}<div class="modal-action-grid">${re.ready?`<button data-r3-action="reconcile" data-person-id="${p.id}">Talk about trying again</button>`:`<span class="muted-text">Reconciliation is not available yet: ${esc(re.reason)}.</span>`}<button class="ghost" data-close-modal="1">Close</button></div>`);return}
 opts.push(['compliment','Compliment them']);if(L.stage==='crushMutual')opts.push(['talkingH4','Talk about getting to know each other']);if(L.stage==='goingOut')opts.push(['exclusiveH4','Discuss dating exclusively']);if(i>=LOVE_IDX.crushOne)opts.push(['flirt','Flirt']);if(L.playerCrush&&!L.mutual&&i<=LOVE_IDX.crushOne)opts.push(['confess','Confess your crush']);if(i<LOVE_IDX.goingOut&&!official)opts.push(['askOut','Ask on a First Date']);
 if(L.mutual&&i>=LOVE_IDX.crushMutual){opts.push(['holdHands','Hold hands'],['hug','Hug'])}if(i>=LOVE_IDX.goingOut){opts.push(['cheekKiss','Cheek kiss']);if(!hasMs(p,'firstKiss'))opts.push(['firstKiss','First kiss']);else opts.push(['kiss','Kiss']);const last=(L.dateHistory||[]).at(-1);if(last?.dateISO===currentDate())opts.push(['goodbyeKiss','Goodbye kiss']);opts.push(['date','Plan a date'])}
 if(['goingOut','exclusive'].includes(L.stage))opts.push(['official','Talk about becoming official'],['endDatingH4','Stop seeing each other']);if(official){opts.push(['support','Emotional support'],['talkRel','Talk about the relationship'],['future','Discuss the future']);if((p.conflict||0)>=8)opts.push(['resolve','Resolve a disagreement']);if(adultRomance(p))opts.push(['intimate','Private intimate evening']);opts.push(['breakUp','Break up'])}
 if(romanceSneakOption3B3(p,'meet'))opts.push(['sneakMeet','Sneak out to meet them']);if(romanceSneakOption3B3(p,'over'))opts.push(['sneakOver','Sneak them in to watch a movie']);
 const ladder=loveLadderHtmlH4(p);openModal(`${displayName(p)} • ${esc(romanceStageLabel3B3(p))}`,`${ladder}<p class="muted-text">${S.age<18?'Teen romance stays age-appropriate.':'Affection and intimacy require current consent every time.'} Friendship remains separate from this romance state.</p>${official&&L.relationshipStartDate?`<p class="muted-text">Official since ${formatDate(L.relationshipStartDate)}.</p>`:''}<div class="modal-action-grid">${opts.map(([id,l])=>`<button data-r3-action="${id}" data-person-id="${p.id}">${esc(l)}</button>`).join('')}${romanceH5GroupHtml(p,opts,isEstablishedPartner(p))}<button class="ghost" data-close-modal="1">Not now</button></div>`)
}
function romance3B3Click(b){const d=b.dataset;if(d.r3Break){const p=personById(d.personId);breakup3B3(p,d.r3Break);save();render();return true}if(d.h5Action){const p=personById(d.personId);if(p)romanceH5Activity(p,d.h5Action);save();render();return true}if(!d.r3Action)return false;const p=personById(d.personId),k=d.r3Action;if(!p)return true;
 if(['talkingH4','exclusiveH4'].includes(k)){romanceStageConversationH4(p,k);save();render();return true}if(k==='endDatingH4'){openModal('Stop seeing each other?',`<p class="muted-text">This ends dating, not your shared friendship history. Your memories and boundaries remain.</p><button data-r3-action="endDatingH4Confirm" data-person-id="${p.id}">Confirm</button><button class="ghost" data-close-modal="1">Cancel</button>`);return true}if(k==='endDatingH4Confirm'){if(['goingOut','exclusive'].includes(ensureLove(p).stage)){endRelationship(p,'you stopped seeing each other');log('Stopped dating',`You and ${firstName(p)} stop seeing each other. Your shared memories stay in your history.`)}closeChoiceModal();save();render();return true}if(k==='askOut'){romanceAskOut3B2(p);return true}if(k==='date'){openRomanceDatePlanner3B2(p.id,true);return true}if(k==='compliment'){romanceCompliment3B3(p)}else if(k==='flirt'){romanceAffection3B3(p,'flirt')}else if(k==='confess'){romanceConfess3B3(p)}else if(ROMANCE_AFFECTION[k])romanceAffection3B3(p,k);else if(k==='official')romanceOfficialConversation3B3(p,'player');else if(['support','talkRel','resolve','future'].includes(k))romancePartnerInteraction3B3(p,k);else if(k==='intimate')adultIntimacy3B3(p);else if(k==='breakUp'){openBreakup3B3(p);return true}else if(k==='reconcile')reconcileRequest3B3(p);else if(k==='sneakMeet'){closeChoiceModal();sneakOut(p.id,'meet')}else if(k==='sneakOver'){closeChoiceModal();sneakOut(p.id,'over')}save();render();return true}
