
// =====================================================================
// v7.2 PHASE 5b — ROMANCE, DATES AS SCENES, BOUNDARIES & CONSENT
// Safety rules enforced in logic (not only UI):
//  • Romance needs the player ≥13 and an age-appropriate partner:
//    minors only with other minors aged 13–17 within 2 years; adults only with adults.
//  • Anything beyond hand-holding / a hug is adult-only (18+, both adults).
//  • Adult intimacy requires mutual consent each time, fades to black, and
//    respecting "no" is never punished.
// =====================================================================
function personAge(p){const n=npcById(p?.npcId);return n?npcAge(n):(p?.age??S.age)}
function eligibleRomance(p){if(!p||isFamilyPerson(p)||S.age<13||S.romance?.optOut)return false;const a=personAge(p);if(S.age<18)return a>=13&&a<18&&Math.abs(a-S.age)<=2;return a>=18}
function adultRomance(p){return S.age>=18&&personAge(p)>=18}
const BOUNDARIES={noPublicAffection:'does not like public displays of affection',noExpensiveGifts:'is uncomfortable with expensive gifts',needsTime:'needs time before anything serious',noParties:'does not enjoy big parties',notReady:'is not ready for a relationship right now'};
function ensureRomanceProfile(p){
 if(p.romanceInit)return p;p.romanceInit=true;const h=dayHash(p.id+'attr');
 p.attraction=p.attraction??Math.round(h*.8+Math.random()*20);p.romanceStage=p.romanceStage||'none';p.romanceOpen=p.romanceOpen??(dayHash(p.id+'open')>=18);if(loveInterestVisible(p)&&p.id!==S.romance?.partnerId&&!npcInterestedInPlayer(p)){p.romanceOpen=false;p.orientationMismatch=true}
 if(!p.boundaries){const t=p.traits||[],b=[];if(t.includes('Shy')||t.includes('Quiet'))b.push('noPublicAffection');if(t.includes('Generous')||chance(20))b.push('noExpensiveGifts');if(chance(25))b.push('needsTime');if(t.includes('Shy')||chance(15))b.push('noParties');if(!p.romanceOpen)b.push('notReady');p.boundaries=[...new Set(b)]}
 return p
}
function partnerPerson(){return S.romance?.partnerId?personById(S.romance.partnerId):null}
function setPartner(p,stage='dating'){S.romance.partnerId=p.id;S.romance.partner=displayName(p,'formal');S.romance.status=stage==='partner'?'In a relationship':S.age<16?'Going out':'Dating';p.romanceStage=stage}
function endRelationship(p,reason,{byNpc=false}={}){if(!p)return;if(p.love){p.love.stage='noticing';p.love.progress=0}ringOnBreakup(p);p.romanceStage='ex';p.conflict=clamp((p.conflict||0)+10);if(S.romance.partnerId===p.id){S.romance.partnerId=null;S.romance.partner=null;S.romance.status='Single'}S.romance.history.push({dateISO:currentDate(),age:S.age,name:displayName(p,'formal'),event:`Broke up — ${reason}`});rememberPerson(p,`You broke up: ${reason}.`,2);recordOutcome('Relationship',displayName(p,'formal'),'Broke up',reason);setEmotion(byNpc?'Heartbroken':'Conflicted','A relationship ended.',70)}
function romanceAskContext(p){return {kind:'askOut',romanceStage:p.romanceStage||'none',romanceOpen:!!p.romanceOpen}}
function romanceAskCooldownDays(p){return p.boundaries?.includes('needsTime')?21:(!p.romanceOpen?14:7)}
function replayRomanceAskDecision(p,r){const story=r.reason||`${firstName(p)} has not changed their answer yet.`;if(r.outcome==='Yes'||r.outcome==='Accepted')log(`${firstName(p)} said yes`,story,true);else log('Not this time',story);return r}
function romanceAction(p,kind){
 if(!eligibleRomance(p))return;ensureRomanceProfile(p);closeChoiceModal();if((kind==='admire'||kind==='askOut')&&p.orientationMismatch){p.loveKnown=true;const o=personIdentity(p).orientation;advanceTime(10,{silent:true});log(`${firstName(p)}`,o==='Not interested in romance'?`${firstName(p)} smiles kindly. "I really like you — I'm just not into dating or romance at all."`:`${firstName(p)} smiles kindly. "I really like you — just not like that. I'm into ${o==='Men'?'guys':o==='Women'?'girls':'someone different'}." It stings, but they are honest, and still your friend.`);return}const a=p.attraction,minor=S.age<18;let story;
 if(kind==='admire'){const ok=p.romanceOpen&&chance(20+a*.5+(p.rel-50)*.4);p.rel=clamp(p.rel+(ok?3:0));if(ok&&p.romanceStage==='none')p.romanceStage='crush';story=ok?rand([`${firstName(p)} goes a little red, then smiles. "I kind of hoped you'd say something."`,`${firstName(p)} laughs, surprised — but they are clearly pleased.`]):p.romanceOpen?`${firstName(p)} smiles kindly. "That's really sweet… I just see you as a friend." It stings, but it is honest.`:`"I'm not really looking for anything like that right now," ${firstName(p)} says gently.`;if(!ok)S.happiness=clamp(S.happiness-3);setEmotion(ok?'Excited':'Embarrassed','A romantic moment.',55)}
 else if(kind==='askOut'){if(S.romance.partnerId&&S.romance.partnerId!==p.id){story=`You are already seeing ${S.romance.partner}. Asking someone else out would not be fair to anyone.`;log('Not like this',story);return}
  if(p.datingNpc){story=`"I'm actually seeing ${p.datingNpc}," ${firstName(p)} says. "Sorry."`;log('Already taken',story);return}
  const askContext=romanceAskContext(p),prior=findDecision('romanceAsk',p.id,askContext,p.id);if(prior){replayRomanceAskDecision(p,prior);return}
  if(p.boundaries?.includes('needsTime')&&(p.romanceAsks||0)>=1&&daysBetween(p.lastRomanceAsk||'2000-01-01',currentDate())<21){p.trust=clamp(p.trust-4);story=`${firstName(p)} looks uncomfortable. "I told you I need some time. Please don't keep asking."`;log('Boundary',story);rememberPerson(p,'You pushed after they asked for time.');return}
  p.romanceAsks=(p.romanceAsks||0)+1;p.lastRomanceAsk=currentDate();
  const ok=p.romanceOpen&&chance(10+a*.55+(p.rel-50)*.5+(p.trust-50)*.2-(p.conflict||0)*.5);
  if(ok){setPartner(p,'dating');p.rel=clamp(p.rel+5);story=minor?`${firstName(p)} says yes. You are officially going out — which mostly means hanging out more and texting a lot.`:`${firstName(p)} says yes. A first date is in your future.`;recordDecision({requestType:'romanceAsk',targetKey:p.id,decisionMakerId:p.id,context:askContext,outcome:'Yes',reason:story,resolved:true});recordOutcome('Relationship',displayName(p,'formal'),'Said yes',`Attraction and closeness were there.`);log(`${firstName(p)} said yes`,story,true);return}
  p.rel=clamp(p.rel-1);story=!p.romanceOpen?`"I really like you — just not like that, and I'm not dating right now," ${firstName(p)} says.`:a<35?`"You're great, but I don't feel that way," ${firstName(p)} says kindly.`:`"Can we stay friends for now? I'm not sure yet."`;recordDecision({requestType:'romanceAsk',targetKey:p.id,decisionMakerId:p.id,context:askContext,outcome:'No',reason:story,reconsiderAfter:addDays(currentDate(),romanceAskCooldownDays(p)),resolved:true});recordOutcome('Relationship',displayName(p,'formal'),'Said no',story);log('Not this time',story);setEmotion('Disappointed','Rejected.',50);return}
 else if(kind==='official'){const ok=p.rel>=65&&chance(40+a*.4);if(ok){setPartner(p,'partner');story=`You talk about it, a little awkwardly. You are officially together.`}else story=`${firstName(p)} wants to keep things casual a bit longer.`}
 else if(kind==='talkRel'){p.trust=clamp(p.trust+3);p.conflict=clamp((p.conflict||0)-4);story=rand([`You talk honestly about what is working and what is not. It feels grown-up.`,`${firstName(p)} admits they have been worried about something. Saying it out loud helps.`])}
 else if(kind==='breakUp'){endRelationship(p,'you ended it');story=`You tell ${firstName(p)} it is over. It is not easy for either of you.`}
 else if(kind==='date'){startDate(p.id);return}
 else if(kind==='intimate'){if(!adultRomance(p)||!['dating','partner'].includes(p.romanceStage))return;const yes=chance(30+(p.attraction||50)*.3+(p.trust-50)*.5+(p.rel-50)*.3-(p.boundaries?.includes('needsTime')?35:0)-(S.stress>70?10:0));if(yes){p.rel=clamp(p.rel+4);p.trust=clamp(p.trust+2);S.stress=clamp(S.stress-6);S.happiness=clamp(S.happiness+4);story=`You ask; ${firstName(p)} says yes, clearly and happily. (fade to black) The next morning feels easy and close.`;advanceTime(120,{silent:true})}else{p.trust=clamp(p.trust+2);story=`${firstName(p)} says not tonight. You say "of course" and mean it — you watch a movie instead, and ${firstName(p)} seems to relax even more around you.`}rememberPerson(p,yes?'An intimate evening together (mutual).':'You respected a no without any pressure.',2);log(`${firstName(p)}`,story);return}
 if(!story)return;rememberPerson(p,story.slice(0,90),2);advanceTime(30);log(`${firstName(p)}`,story)
}
// ---------- Scene runner (dates, prom night) ----------
function startScene(kind,data){S.scene={id:uid('scene'),kind,step:0,score:50,lines:[],data};renderScene()}
function sceneDef(){return S.scene?.kind==='date'?DATE_SCENE:S.scene?.kind==='prom'?PROM_SCENE:null}
function renderScene(){const sc=S.scene,def=sceneDef();if(!sc||!def){S.scene=null;return}const st=def.steps[sc.step];if(!st){finishScene();return}const view=st.view(sc);openModal(view.title,`${sc.lines.length?`<div class="scene-lines">${sc.lines.slice(-3).map(l=>`<p>${esc(l)}</p>`).join('')}</div>`:''}<p class="scene-text">${esc(view.text)}</p><div class="modal-action-grid">${view.choices.map(c=>`<button class="${c.primary?'primary':''}" data-scene-choice="${esc(c.id)}">${esc(c.label)}</button>`).join('')}</div>`)}
function sceneChoice(id){const sc=S.scene,def=sceneDef();if(!sc||!def)return;const st=def.steps[sc.step];const r=st.choose(sc,id)||{};if(r.line)sc.lines.push(r.line);if(r.score)sc.score=clamp(sc.score+r.score);if(r.minutes)advanceTime(r.minutes,{silent:true});if(r.end){finishScene(r);return}sc.step=r.goto??sc.step+1;save();renderScene()}
function finishScene(r={}){const sc=S.scene,def=sceneDef();S.scene=null;closeChoiceModal();if(def)def.finish(sc,r);save();render()}
// ---------- Date as a scene (§83) ----------
const DATE_PLACES=[{id:'picnic',label:'Picnic in the park',outdoor:true,cost:6},{id:'cafe',label:'Café',cost:10},{id:'movie',label:'Movie',cost:14},{id:'walk',label:'Long walk',outdoor:true,cost:0},{id:'arcade',label:'Arcade / mini golf',cost:12},{id:'dinner',label:'Dinner out',cost:35,adult:true},{id:'cook',label:'Cook together at home',cost:8,adult:true},{id:'beach',label:'Beach trip',outdoor:true,cost:10,minAge:16}];
const TOPICS={school:'School / work',family:'Family',future:'The future',interests:'Interests',relationship:'Us',gossip:'Gossip',insecurities:'Something personal',jokes:'Jokes'};
function topicFit(p,t){const tr=p.traits||[];let v=0;if(t==='school'||t==='future')v+=tr.includes('Studious')||tr.includes('Ambitious')?10:0;if(t==='jokes')v+=tr.includes('Funny')?12:tr.includes('Quiet')?-2:4;if(t==='interests')v+=tr.some(x=>['Sporty','Artsy','Curious'].includes(x))?10:4;if(t==='gossip')v+=tr.includes('Outgoing')?6:tr.includes('Kind')?-6:0;if(t==='family')v+=tr.includes('Kind')||tr.includes('Loyal')?8:2;if(t==='insecurities')v+=p.trust>=60?12:-8;if(t==='relationship')v+=p.romanceStage==='partner'?8:p.boundaries?.includes('needsTime')?-10:2;return v}
function startDate(personId,{valentine=false}={}){const p=personById(personId);if(!p||!eligibleRomance(p)){toast('Not possible.');return}if(atSchool()){toast('After school.');return}const st=npcStatusAt(p);if(!st.free){toast(st.why);return}if(S.age<18&&curfewMinute()&&currentMinute()+150>curfewMinute()){toast(`That would run past your ${timeLabel(curfewMinute())} curfew.`);return}closeChoiceModal();startScene('date',{personId,valentine})}
const DATE_SCENE={steps:[
 {view:sc=>{const p=personById(sc.data.personId);return {title:`${sc.data.valentine?"Valentine's date":'Date'} with ${firstName(p)}`,text:'Where do you go?',choices:DATE_PLACES.filter(x=>(!x.adult||S.age>=18)&&(!x.minAge||S.age>=x.minAge)).map(x=>({id:x.id,label:`${x.label}${x.cost&&S.age>=13?` • ${money(x.cost)}`:''}`}))}},
  choose:(sc,id)=>{const pl=DATE_PLACES.find(x=>x.id===id);sc.data.place=id;if(pl.cost&&S.age>=13&&!spendOwn(pl.cost)){sc.data.broke=true;return {line:`You realize you cannot afford the ${pl.label.toLowerCase()}, so you suggest a walk instead.`,score:-4}}const p=personById(sc.data.personId);if(pl.outdoor&&['Rainy','Stormy'].includes(S.weather.type)){sc.data.rain=true;return {line:`It is ${S.weather.type.toLowerCase()} — you end up under an awning, laughing.`,score:2,minutes:20}}return {line:rand([`You meet ${firstName(p)} at the ${pl.label.toLowerCase()}. They look happy to see you.`,`${firstName(p)} is already there, waving.`]),minutes:20}}},
 {view:sc=>({title:'Talking',text:'What do you talk about?',choices:Object.entries(TOPICS).map(([id,l])=>({id,label:l}))}),
  choose:(sc,id)=>{const p=personById(sc.data.personId),v=topicFit(p,id)+Math.random()*8-4;sc.data.topic=id;const good=v>=6,bad=v<=-4;const lines={school:good?`You trade stories about your days; ${firstName(p)} is surprisingly funny about it.`:'The conversation drifts into complaints about school. A bit flat.',family:good?`${firstName(p)} tells you about their family. You learn more than you expected.`:'Family talk gets awkward fast.',future:good?'You talk about the future — big dreams, small fears. It feels easy.':'Talk about the future gets a little heavy for this stage.',interests:good?`You discover you both love the same weird thing. ${firstName(p)} lights up.`:'Your interests barely overlap. You try anyway.',relationship:good?'You talk about where this is going. You both smile more than you talk.':`${firstName(p)} goes a bit quiet. Maybe too soon.`,gossip:good?'Light gossip, lots of laughing.':`${firstName(p)} looks uncomfortable gossiping about people.`,insecurities:good?`You share something personal. ${firstName(p)} listens carefully, then shares something back.`:'You open up, but it is a bit much right now.',jokes:good?`You make ${firstName(p)} laugh so hard they snort. That breaks the ice completely.`:'A joke falls flat. Silence. Then you both laugh at how badly it landed.'};return {line:lines[id],score:good?10:bad?-8:2,minutes:40}}},
 {view:sc=>{const ev=sc.data.ev||(sc.data.ev=rand(['spill','friend','view','phone','none','none']));const t={spill:'Someone bumps your table and a drink goes everywhere.',friend:`You run into a classmate who clearly wants to know what is going on.`,view:'The light is perfect right now — the kind of moment people remember.',phone:'Your phone keeps buzzing.',none:'The conversation finds an easy rhythm.'}[ev];return {title:'Something happens',text:t,choices:ev==='spill'?[{id:'laugh',label:'Laugh it off'},{id:'fuss',label:'Get flustered'}]:ev==='friend'?[{id:'introduce',label:'Introduce them'},{id:'wave',label:'Wave and keep going'}]:ev==='phone'?[{id:'silence',label:'Put it away'},{id:'check',label:'Check it'}]:[{id:'enjoy',label:'Enjoy the moment'},{id:'deep',label:'Ask a deeper question'}]}},
  choose:(sc,id)=>{const p=personById(sc.data.personId);const m={laugh:[`You both laugh it off. ${firstName(p)} says it is the best part so far.`,8],fuss:['You get flustered and apologize too much. It takes a while to recover.',-6],introduce:[p.boundaries?.includes('noPublicAffection')?`${firstName(p)} tenses up a little at being "seen" on a date.`:`${firstName(p)} handles it with a grin. No big deal.`,p.boundaries?.includes('noPublicAffection')?-5:4],wave:['You wave and keep the focus on your date. Noted, and appreciated.',5],silence:['You put your phone face-down. They notice.',6],check:[`${firstName(p)} looks away while you scroll. The mood dips.`,-7],enjoy:['You just enjoy it. No need to fill the silence.',6],deep:[p.trust>=55?`${firstName(p)} answers thoughtfully. You feel closer.`:`${firstName(p)} deflects — too soon for that question.`,p.trust>=55?9:-3]}[id]||['…',0];return {line:m[0],score:m[1],minutes:30}}},
 {view:sc=>{const p=personById(sc.data.personId),adult=adultRomance(p);const ch=[{id:'walkHome',label:adult?'Walk them home':'Walk them home / to their ride'},{id:'hug',label:'Hug goodbye'}];if(S.age>=13)ch.push({id:'hands',label:'Hold hands on the way'});if(adult)ch.push({id:'kiss',label:'Kiss goodnight'},{id:'invite',label:'Ask if they want to come in'});ch.push({id:'early',label:'Call it a night'});return {title:'End of the date',text:'How do you say goodbye?',choices:ch}},
  choose:(sc,id)=>{const p=personById(sc.data.personId);if(['kiss','invite'].includes(id)&&!adultRomance(p))return {line:'You say a warm goodbye.',end:true};
   if(id==='invite'){const yes=chance(sc.score*.6+(p.trust-50)*.4+(p.attraction||50)*.2-(p.boundaries?.includes('needsTime')?30:0));sc.data.invite=yes?'yes':'no';return {line:yes?`${firstName(p)} smiles. "I'd like that." (fade to black)`:`${firstName(p)} hesitates. "Not tonight — but I had a really good time." You say goodnight and mean it.`,end:true}}
   if(id==='kiss'){const ok=chance(sc.score*.7+(p.attraction||50)*.3);return {line:ok?'A goodnight kiss — brief and nice.':`${firstName(p)} turns it into a hug. You take the hint, warmly.`,score:ok?5:0,end:true}}
   return {line:{walkHome:`You walk ${firstName(p)} home. Neither of you is in a hurry.`,hug:'A long hug goodbye.',hands:'You hold hands most of the way. Small thing; big feeling.',early:'You call it a night a little early.'}[id],score:{walkHome:4,hug:3,hands:5,early:-3}[id],end:true}}}
],finish(sc){
 const p=personById(sc.data.personId);if(!p)return;const s=sc.score,tier=s>=78?'Great date':s>=58?'Good date':s>=40?'Awkward date':'Rough date',why=sc.lines.slice(1).join(' ');
 p.rel=clamp(p.rel+(s>=78?7:s>=58?4:s>=40?0:-3));p.fun=clamp(p.fun+5);p.attraction=clamp((p.attraction||50)+(s>=58?4:-3));if(sc.data.invite==='yes')p.trust=clamp(p.trust+3);if(sc.data.invite==='no'){p.trust=clamp(p.trust+2)}
 if(s<40&&p.romanceStage==='dating'&&chance(25))endRelationship(p,'the spark was not there',{byNpc:true});
 S.needs.social=clamp(S.needs.social+15);S.needs.fun=clamp(S.needs.fun+12);rememberPerson(p,`${tier}: ${(DATE_PLACES.find(x=>x.id===sc.data.place)||{}).label||'a date'}.`,2);addLove(p,s>=78?25:s>=58?15:s>=40?5:-10);
 recordOutcome('Date',`${sc.data.valentine?"Valentine's date":'Date'} with ${displayName(p,'formal')}`,tier,why.slice(0,180));
 log(`${sc.data.valentine?"💌 Valentine's date":'Date'} with ${firstName(p)} — ${tier.toLowerCase()}`,`${why} ${sc.data.invite==='yes'?'You spend the night together.':''}`.trim(),s>=78)
}};
