
// =====================================================================
// v7.3 R + S + T — love progression, NPC couples & families, person window, UI reorganization
// Safety: every stage needs mutual consent; minors stop at "Serious" (16+ for a promise ring);
// living together, engagement, marriage and starting a family are adult-only (both 18+), non-explicit.
// =====================================================================
const LOVE=[
 {id:'noticing',label:'Noticing',rs:'none'},
 {id:'crushOne',label:'One-sided crush',rs:'crush'},
 {id:'crushMutual',label:'Mutual crush',rs:'crush'},
 {id:'goingOut',label:'Going out / getting to know each other',rs:'dating'},
 {id:'official',label:'Boyfriend / girlfriend',rs:'partner'},
 {id:'inLove',label:'In love',rs:'partner',auto:{rel:75,trust:65}},
 {id:'superInLove',label:'Super in love',rs:'partner',auto:{rel:85,trust:72}},
 {id:'serious',label:'Serious (promise ring)',rs:'partner',minAge:16},
 {id:'livingTogether',label:'Living together',rs:'partner',adult:true},
 {id:'engaged',label:'Engaged',rs:'partner',adult:true},
 {id:'married',label:'Married',rs:'partner',adult:true},
 {id:'family',label:'Starting a family',rs:'partner',adult:true}
];
const LOVE_IDX=Object.fromEntries(LOVE.map((s,i)=>[s.id,i]));
function ensureLove(p){if(!p)return null;if(!p.love){const rs=p.romanceStage||'none';const id=rs==='partner'?'official':rs==='dating'?'goingOut':rs==='crush'?((p.attraction||0)>=60?'crushMutual':'crushOne'):'noticing';p.love={stage:id,progress:0,since:currentDate()}}return p.love}
function loveStage(p){return LOVE[LOVE_IDX[ensureLove(p).stage]]}
function setLoveStage(p,id,why=''){const L=ensureLove(p),prev=L.stage;if(prev===id)return;{const mt={goingOut:'firstDate',official:'official',engaged:'engaged',married:'married'}[id];if(mt)addPersonMilestone(p,mt,why||'')}L.stage=id;L.progress=0;L.since=currentDate();p.romanceStage=LOVE[LOVE_IDX[id]].rs;if(LOVE_IDX[id]>=LOVE_IDX.official&&S.romance.partnerId!==p.id)setPartner(p,'partner');
 if(LOVE_IDX[id]>=LOVE_IDX.goingOut&&!SIM.skipping){S.milestones.unshift({dateISO:currentDate(),age:S.age,title:`💗 ${LOVE[LOVE_IDX[id]].label}`,text:`${displayName(p,'formal')}${why?` — ${why}`:''}.`});notify('Relationship stage',`${displayName(p)}: ${LOVE[LOVE_IDX[id]].label}`,{sourceType:'love',sourceId:`love-${p.id}-${id}`,tab:'family'})}
 rememberPerson(p,`Relationship: ${LOVE[LOVE_IDX[id]].label}.`,3)}
function addLove(p,amt,why){if(!p||!eligibleRomance(p))return;const L=ensureLove(p);if(LOVE_IDX[L.stage]<LOVE_IDX.goingOut&&amt>0&&L.stage!=='crushMutual')return;L.progress=clamp(L.progress+amt);const st=loveStage(p);
const nx=LOVE[LOVE_IDX[L.stage]+1];if(nx&&nx.auto&&L.progress>=100&&p.rel>=nx.auto.rel&&p.trust>=nx.auto.trust){setLoveStage(p,nx.id);if(!SIM.skipping)log(`💗 ${nx.label}`,nx.id==='inLove'?`Somewhere along the way, it became more than liking ${firstName(p)}. You are in love — and so are they.`:`With ${firstName(p)}, everything feels easy and bright. You are completely gone for each other.`,true)}}
// Next step offered in the romance menu (each needs consent)
function nextLoveStep(p){const L=ensureLove(p),i=LOVE_IDX[L.stage],adult=adultRomance(p);
 if(L.stage==='goingOut')return L.progress>=60?{id:'official',label:S.age<16?'Ask them to be your boyfriend/girlfriend':'Ask to make it official'}:null;
 if(L.stage==='superInLove')return S.age>=16&&personAge(p)>=16&&L.progress>=60?{id:'ring',label:'Give a promise ring'}:null;
 if(L.stage==='serious')return adult&&L.progress>=70?{id:'moveIn',label:'Ask to move in together'}:null;
 if(L.stage==='livingTogether')return adult&&L.progress>=70?{id:'propose',label:'Propose'}:null;
 if(L.stage==='engaged')return adult?{id:'wedding',label:'Plan the wedding'}:null;
 if(L.stage==='married')return adult&&L.progress>=50?{id:'family',label:'Talk about starting a family'}:null;
 return null}
function consent(p,base){return p.romanceOpen!==false&&chance(clamp(base+(p.rel-60)*.6+(p.trust-55)*.5+(ensureLove(p).progress-60)*.3-(p.conflict||0)*.6-(p.boundaries?.includes('needsTime')?15:0),5,96))}
function loveStep(personId,step){
 const p=personById(personId);if(!p||!eligibleRomance(p))return;closeChoiceModal();const fn=firstName(p),L=ensureLove(p);
 if(step==='official'){if(consent(p,55)){setLoveStage(p,'official','made it official');p.rel=clamp(p.rel+4);log('💗 Official',`You ask. ${fn} says yes before you even finish the sentence.`,true)}else{L.progress=clamp(L.progress-20);log('Not yet',`"I really like you — can we keep going like this a little longer?" ${fn} asks. You agree.`)}}
 else if(step==='ring'){if(S.age<16||personAge(p)<16)return;const cost=80;if(S.romance.spareRing)S.romance.spareRing=false;else if(!spendOwn(cost)){toast(`A promise ring costs about ${money(cost)}.`);return}if(consent(p,60)){setLoveStage(p,'serious','promise ring');S.romance.promiseRing={personId:p.id,from:'player',dateISO:currentDate()};log('💍 Promise ring',`You give ${fn} a simple ring — a promise, not a proposal. They put it on right away.`,true)}else{S.romance.spareRing=true;log('Too soon',`${fn} is touched, but says it feels too soon for a ring. You keep it for later.`)}}
 else if(step==='moveIn'){if(!adultRomance(p))return;if(consent(p,50)){setLoveStage(p,'livingTogether','moved in together');S.romance.livingTogether=true;S.housing=Object.assign(S.housing||{},{type:'withPartner',partnerId:p.id,since:currentDate()});log('🏠 Moving in',`You and ${fn} pick a place together. The first week is mostly arguing about where the couch goes.`,true)}else log('Not ready',`${fn} wants to wait a bit before living together. You respect that.`)}
 else if(step==='propose'){if(!adultRomance(p))return;openModal(`Propose to ${displayName(p)}?`,`<p class="muted-text">Both of you are adults. A proposal is a question — the answer can be no.</p><div class="modal-action-grid"><button class="primary" data-love="proposeRing" data-person-id="${p.id}">Propose with a ring (${money(300)})</button><button data-love="proposeSimple" data-person-id="${p.id}">Propose without a ring</button><button data-love="elope" data-person-id="${p.id}">Suggest eloping</button><button class="ghost" data-close-modal="1">Not yet</button></div>`);return}
 else if(step==='proposeRing'||step==='proposeSimple'||step==='elope'){if(!adultRomance(p))return;if(step==='proposeRing'&&!spendOwn(300)){toast(`You need ${money(300)} for the ring.`);return}const ok=consent(p,step==='elope'?40:55);if(!ok){p.conflict=clamp((p.conflict||0)+3);log('Not yet',`${fn} takes your hands. "I love you. I'm just not ready for that yet." It stings, but nothing is broken.`);return}
  if(step==='elope'){setLoveStage(p,'married','eloped');S.romance.married={personId:p.id,dateISO:currentDate(),kind:'eloped'};S.family.tension=clamp(S.family.tension+(chance(50)?6:0));log('💒 Eloped',`A tiny ceremony, two witnesses, and you are married. Your family hears about it afterwards — reactions are mixed.`,true)}
  else{setLoveStage(p,'engaged','engaged');log('💍 Engaged',`${fn} says yes. You both cry a little.`,true)}}
 else if(step==='wedding'){if(!adultRomance(p))return;openModal('Plan the wedding',`<p class="muted-text">Pick a size. The date is set about two months from now.</p><div class="modal-action-grid">${[['courthouse','Courthouse wedding',100],['small','Small wedding',2000],['medium','Medium wedding',8000],['big','Big wedding',20000]].map(([k,l,c])=>`<button data-love="wed-${k}" data-cost="${c}" data-person-id="${p.id}">${l} • ${money(c)}</button>`).join('')}</div>`);return}
 else if(/^wed-/.test(step)){if(!adultRomance(p))return;const size=step.slice(4),cost={courthouse:100,small:2000,medium:8000,big:20000}[size];if(!spendOwn(cost)){toast(`That costs ${money(cost)}. Try a smaller wedding.`);return}const day=addDays(currentDate(),size==='courthouse'?14:60);L.wedding={dateISO:day,size};createCalendarEvent({id:`wedding-${p.id}`,type:'wedding',title:`Wedding with ${displayName(p)}`,dateISO:day,startMinute:900,endMinute:1380,graceMinute:1380,required:false,location:size==='courthouse'?'City hall':'Venue',payload:{personId:p.id,size},source:'romance'});scheduleFollowUp('wedding',{personId:p.id,size},{dateISO:day,minute:960});log('Wedding planned',`${{courthouse:'A simple courthouse wedding',small:'A small wedding',medium:'A medium-sized wedding',big:'A big wedding'}[size]} on ${formatDate(day)}.`)}
 else if(step==='family'){if(!adultRomance(p))return;openModal('Starting a family',`<p class="muted-text">A big decision you make together.</p><div class="modal-action-grid"><button data-love="baby" data-person-id="${p.id}">Have a baby</button><button data-love="adopt" data-person-id="${p.id}">Adopt</button><button class="ghost" data-close-modal="1">Not now</button></div>`);return}
 else if(step==='baby'||step==='adopt'){if(!adultRomance(p))return;if(!consent(p,step==='adopt'?55:60)){log('Not yet',`${fn} wants to wait a while before having kids. You agree to talk again later.`);return}setLoveStage(p,'family',step==='adopt'?'adopting':'expecting');const months=step==='adopt'?8:9;scheduleFollowUp('babyArrives',{personId:p.id,kind:step},{dateISO:addDays(currentDate(),months*30),minute:600});log(step==='adopt'?'👶 Adoption':'👶 Expecting',step==='adopt'?`You and ${fn} start the adoption process. Paperwork, interviews, waiting.`:`You and ${fn} are expecting a baby. Everything is about to change.`,true)}
 advanceTime(20,{silent:true})
}
function babyArrives(f){const p=personById(f.payload.personId);const n=freshPeers(1)[0]||{firstName:rand(['Mai','Leo','Ana','Kai'])};const baby={...makePerson(n.firstName,'child',0,S.age),roleLabel:'your child',relation:'child',residence:'home'};baby.surname=S.familyName||'';baby.fullName=`${baby.name} ${baby.surname}`.trim();S.people.push(baby);S.milestones.unshift({dateISO:currentDate(),age:S.age,title:'👶 A new baby',text:`${baby.name} joins the family${p?` — you and ${displayName(p,'formal')} are parents now`:''}.`});S.happiness=clamp(S.happiness+12);S.stress=clamp(S.stress+10);if(!SIM.skipping)log('👶 Welcome, '+baby.name,'Tiny, loud, and already the center of everything.',true)}
function weddingDay(f){const p=personById(f.payload.personId);if(!p)return;setLoveStage(p,'married','wedding');S.romance.married={personId:p.id,dateISO:currentDate(),kind:f.payload.size};const ev=S.calendar.find(e=>e.id===`wedding-${p.id}`);if(ev)setCalendarStatus(ev,'Completed','Married');S.happiness=clamp(S.happiness+15);S.family.closeness=clamp(S.family.closeness+3);if(!SIM.skipping)log('💒 Married',`${{courthouse:'Ten minutes at city hall, then the best lunch of your life.',small:'Close friends, family, and a lot of happy crying.',medium:'Dancing until late. Someone gives a speech that goes on far too long.',big:'A huge celebration. You barely get to eat, and you do not care.'}[f.payload.size]||'You get married.'} You and ${firstName(p)} are married.`,true)}
// Promise ring on breakup
function ringOnBreakup(p){const r=S.romance.promiseRing;if(!r||r.personId!==p.id||SIM.skipping)return;S.romance.promiseRing=null;queueEvent({type:'ringBack',title:'The promise ring',text:`${firstName(p)} still has the promise ring you gave them.`,participants:[p.id],priority:2,expiresDays:3,choices:[{id:'ask',label:'Ask for it back'},{id:'keep',label:'Let them keep it'}]})}
// ---------- R59/60. NPC families & NPC couples ----------
function npcFamilyLine(p){const n=npcById(p.npcId);if(!n)return '';const hh=(S.households||[]).find(h=>h.id===n.householdId);if(!hh)return '';const sibs=hh.members.filter(id=>id!==n.id).map(npcById).filter(Boolean);return `Lives with ${(hh.parents||[]).join(' and ')||'their family'}${sibs.length?` • sibling${sibs.length>1?'s':''}: ${sibs.map(x=>`${x.firstName} (${npcAge(x)})`).join(', ')}`:''}${hh.pet?` • a ${hh.pet} named ${hh.petName}`:''}`}
function coupleAgeOK(a,b){const x=npcAge(a),y=npcAge(b);if(x<13||y<13)return false;if(x<18||y<18)return x<18&&y<18&&Math.abs(x-y)<=2;return true}
function npcCouples(){return (S.npcCouples=S.npcCouples||[])}
function coupleOf(npcId){return npcCouples().find(c=>c.status==='dating'&&(c.a===npcId||c.b===npcId))}
function partnerNpcOf(npcId){const c=coupleOf(npcId);return c?npcById(c.a===npcId?c.b:c.a):null}
function makeNpcCouple(a,b,why='started dating'){if(!a||!b||a.id===b.id||coupleOf(a.id)||coupleOf(b.id)||!coupleAgeOK(a,b)||!npcsCompatible(a,b))return null;const c={id:uid('cpl'),a:a.id,b:b.id,since:currentDate(),strength:45+Math.floor(Math.random()*20),status:'dating',why};npcCouples().push(c);syncCoupleNames(c);return c}
function syncCoupleNames(c){const a=npcById(c.a),b=npcById(c.b);for(const p of S.people){if(p.npcId===c.a)p.datingNpc=c.status==='dating'?b?.fullName:null;if(p.npcId===c.b)p.datingNpc=c.status==='dating'?a?.fullName:null}if(a)a.datingId=c.status==='dating'?c.b:null;if(b)b.datingId=c.status==='dating'?c.a:null}
const BREAKUP_REASONS=['they kept fighting about small things','they drifted apart over the summer','one of them liked someone else','their parents did not approve','they wanted different things','one of them is moving away'];
function breakNpcCouple(c,reason=rand(BREAKUP_REASONS)){c.status='broken';c.endedDate=currentDate();c.reason=reason;syncCoupleNames(c);const pa=S.people.find(p=>p.npcId===c.a||p.npcId===c.b);if(pa&&!SIM.skipping&&tierRank(pa)>=1){const o=npcById(pa.npcId===c.a?c.b:c.a);log(`${firstName(pa)} and ${o?.firstName||'their partner'} broke up`,`From what you hear, ${reason}.`);if(tierRank(pa)>=2&&chance(60))queueEvent({type:'helpRequest',title:`${firstName(pa)} is heartbroken`,text:`${firstName(pa)} and ${o?.firstName} broke up — ${reason}.`,participants:[pa.id],priority:3,expiresDays:1,choices:[{id:'help',label:'Be there for them'},{id:'later',label:'Text them later'}]})}}
function migrateNpcDating(){for(const p of S.people){if(!p.datingNpc||!p.npcId)continue;if(coupleOf(p.npcId))continue;const o=(S.npcs||[]).find(n=>n.fullName===p.datingNpc);const me=npcById(p.npcId);if(o&&me&&coupleAgeOK(me,o))makeNpcCouple(me,o,'already dating');else p.datingNpc=null}}
function npcCoupleTick(){
 migrateNpcDating();
 for(const c of npcCouples().filter(c=>c.status==='dating')){c.strength=clamp(c.strength+(Math.random()*6-3.2));const a=npcById(c.a),b=npcById(c.b);if(!a||!b||!coupleAgeOK(a,b)){breakNpcCouple(c,'life took them in different directions');continue}if(c.strength<15&&chance(30))breakNpcCouple(c)}
 if(chance(10)){const pool=(S.npcs||[]).filter(n=>npcAge(n)>=13&&!coupleOf(n.id)&&!S.people.some(p=>p.npcId===n.id&&p.id===S.romance?.partnerId));const a=rand(pool),b=a&&rand(pool.filter(x=>x.id!==a.id&&coupleAgeOK(a,x)&&npcsCompatible(a,x)));if(a&&b){const c=makeNpcCouple(a,b);const known=S.people.find(p=>p.npcId===a.id||p.npcId===b.id);if(c&&known&&!SIM.skipping&&tierRank(known)>=1){const o=npcById(known.npcId===a.id?b.id:a.id);log('News',`${firstName(known)} is dating ${o.fullName} now.`);loveTriangleCheck(known)}}}
 if(!SIM.skipping&&chance(4)){const c=rand(npcCouples().filter(c=>c.status==='dating'));const p=c&&S.people.find(x=>(x.npcId===c.a||x.npcId===c.b)&&tierRank(x)>=2);if(p){const o=partnerNpcOf(p.npcId);queueEvent({type:'loveAdvice',title:`${firstName(p)} needs relationship advice`,text:`"${o.firstName} and I keep ${rand(['arguing about nothing','missing each other\'s messages','disagreeing about how much time to spend together'])}. What should I do?"`,participants:[p.id],payload:{coupleId:c.id},priority:2,expiresDays:2,choices:[{id:'talk',label:'Tell them to talk honestly'},{id:'space',label:'Suggest a little space'},{id:'breakup',label:'Tell them to break up'},{id:'neutral',label:'Just listen'}]})}}
}
function loveTriangleCheck(known){if(SIM.skipping)return;const L=known.love;if(!L||!['crushOne','crushMutual','noticing'].includes(L.stage)||!eligibleRomance(known))return;if(L.stage==='noticing'&&(known.attraction||0)<50)return;queueEvent({type:'triangle',title:`Your crush is dating someone`,text:`${firstName(known)} is going out with ${known.datingNpc}. You find out between classes.`,participants:[known.id],priority:3,expiresDays:2,choices:[{id:'happy',label:'Be happy for them'},{id:'sad',label:'Feel it, quietly'},{id:'confess',label:'Tell them how you feel anyway'}]})}
function matchmakeModal(personId){const p=personById(personId);if(!p||p.id===S.romance?.partnerId)return;const n=npcById(p.npcId);if(!n||npcAge(n)<13){toast('Matchmaking is for teens and adults.');return}if(coupleOf(n.id)){toast(`${firstName(p)} is already seeing someone.`);return}
 const cands=S.people.filter(x=>x.id!==p.id&&x.npcId&&!isFamilyPerson(x)&&x.id!==S.romance?.partnerId&&!coupleOf(x.npcId)&&coupleAgeOK(n,npcById(x.npcId)));if(!cands.length){toast('Nobody you know fits — they need to be single and close in age.');return}
 openModal(`Set ${displayName(p)} up with…`,`<p class="muted-text">Both must be single, close in age, and it has to be their choice.</p><div class="modal-action-grid">${cands.slice(0,8).map(x=>`<button data-matchmake="${p.id}" data-with="${x.id}">${esc(displayName(x))}</button>`).join('')}</div>`)}
function matchmake(aId,bId){const a=personById(aId),b=personById(bId);closeChoiceModal();if(!a||!b)return;const na=npcById(a.npcId),nb=npcById(b.npcId);if(!coupleAgeOK(na,nb))return;const shared=(a.traits||[]).filter(t=>(b.traits||[]).includes(t)).length;const ok=chance(25+shared*15+((a.rel+b.rel)/2-50)*.3);advanceTime(30,{silent:true});
 if(ok){const c=makeNpcCouple(na,nb,'you set them up');if(c){c.strength=60;a.rel=clamp(a.rel+4);b.rel=clamp(b.rel+4);rememberPerson(a,`You set them up with ${b.name}.`,2);rememberPerson(b,`You set them up with ${a.name}.`,2);log('💘 Matchmaker',`You introduce ${firstName(a)} and ${firstName(b)}. A week later they are inseparable — and both thank you.`,true);return}}
 a.rel=clamp(a.rel-1);b.rel=clamp(b.rel-1);log('Awkward setup',`You introduce ${firstName(a)} and ${firstName(b)}. Polite small talk, zero sparks. Everyone agrees not to mention it again.`)}
// ---------- S. Person window: history (left) + shared memories (right) ----------
const GENERIC_MEMO=/Something changed in their life|drifted slightly|exchanged messages|^Hang out on /i;
function personHistoryHtml(p){const h=p.history||[];const left=h.slice(0,40).map(x=>`<div class="ph-row"><small>${formatDate(x.dateISO||currentDate())} • age ${x.age??S.age}</small><span>${esc(x.text)}</span></div>`).join('')||'<p class="muted-text">Nothing yet.</p>';
 const mem=h.filter(x=>(x.importance||1)>=2&&!GENERIC_MEMO.test(x.text)).slice(0,12).map(x=>`<div class="pm-row"><small>${formatDate(x.dateISO||currentDate())}</small><span>${esc(x.text)}</span></div>`).join('')||'<p class="muted-text">Big moments — milestones and things that changed your relationship — appear here.</p>';
 const L=eligibleRomance(p)&&p.love&&LOVE_IDX[p.love.stage]>=1?`<div class="love-line"><b>💗 ${esc(loveStage(p).label)}</b><div class="progress"><i style="width:${Math.round(p.love.progress)}%"></i></div></div>`:'';
 const fam=parentsKnown(p)?npcFamilyLine(p):'',cp=p.npcId&&relStatusKnown(p)&&partnerNpcOf(p.npcId);
 return `<p class="id-line">${esc(identityLine(p))}${loveInterestVisible(p)&&!loveInterestKnown(p)?` <button class="small ghost" data-ask-love="${p.id}">Ask about their love life</button>`:''}</p>${narrativeHtml(p)}${L}${fam||cp?`<p class="muted-text person-family">${esc(fam)}${cp?`${fam?' • ':''}Dating ${esc(cp.fullName)}`:''}</p>`:''}<div class="person-cols"><div><h4>Relationship log</h4><div class="ph-list">${left}</div></div><div><h4>Milestones</h4><div class="pm-list">${milestonesHtml(p)}</div></div></div>`}
// ---------- R. Romance menu with love stages ----------
function romanceMenu(personId){
 const p=personById(personId);if(!p)return;if(!eligibleRomance(p)){toast(S.age<13?'Romance is not part of this stage of life.':'That would not be appropriate.');return}ensureRomanceProfile(p);const L=ensureLove(p),st=loveStage(p),i=LOVE_IDX[L.stage],minor=S.age<18,opts=[],nx=nextLoveStep(p);
 if(i<=LOVE_IDX.crushMutual){opts.push(['admire',minor&&S.age<16?'Admit you like them':'Flirt a little']);opts.push(['askOut',minor?'Ask them to hang out, just you two':'Ask them on a date'])}
 if(i>=LOVE_IDX.goingOut){opts.push(['date',minor?'Plan a date (hang out together)':'Plan a date']);opts.push(['talkRel','Talk about the relationship'])}
 if(i>=LOVE_IDX.goingOut&&adultRomance(p))opts.push(['intimate','Suggest an intimate evening together']);
 if(i>=LOVE_IDX.goingOut)opts.push(['breakUp','Break up']);
 const ladder=LOVE.filter(s=>(!s.adult||adultRomance(p))&&(!s.minAge||S.age>=s.minAge)).map(s=>`<span class="ladder-step ${s.id===L.stage?'on':LOVE_IDX[s.id]<i?'done':''}">${esc(s.label)}</span>`).join('');
 openModal(`${displayName(p)} • ${st.label}`,`<div class="love-ladder">${ladder}</div>${i>=LOVE_IDX.goingOut||L.stage==='crushMutual'?`<div class="love-line"><small>Progress in this stage</small><div class="progress"><i style="width:${Math.round(L.progress)}%"></i></div></div>`:''}<p class="muted-text">${minor?'Teen relationships stay age-appropriate. Every step needs both of you to want it.':'Every step needs both of you to want it. A "no" is never punished.'}</p><div class="modal-action-grid">${nx?`<button class="primary" data-love="${nx.id}" data-person-id="${p.id}">${esc(nx.label)}</button>`:''}${opts.map(([id,l])=>`<button data-romance="${id}" data-person-id="${p.id}">${esc(l)}</button>`).join('')}<button class="ghost" data-close-modal="1">Not now</button></div>`)
}
function syncLoveAfterRomance(p,kind,before){if(!p||!eligibleRomance(p))return;const L=ensureLove(p);
 if(kind==='admire'){const mutual=p.romanceStage==='crush'&&(p.attraction||0)>=60;if(mutual&&LOVE_IDX[L.stage]<LOVE_IDX.crushMutual)setLoveStage(p,'crushMutual');else if(LOVE_IDX[L.stage]<LOVE_IDX.crushOne)setLoveStage(p,'crushOne')}
 if(kind==='askOut'&&S.romance.partnerId===p.id&&LOVE_IDX[L.stage]<LOVE_IDX.goingOut)setLoveStage(p,'goingOut','started going out');
 if(kind==='official'&&p.romanceStage==='partner'&&LOVE_IDX[L.stage]<LOVE_IDX.official)setLoveStage(p,'official');
 if(kind==='breakUp'){L.stage='noticing';L.progress=0;ringOnBreakup(p)}
 if(kind==='talkRel')addLove(p,6);if(kind==='intimate')addLove(p,5)}
// ---------- T. Independence section (replaces the Growing Up tab) ----------
function independenceHtml(){if(!S.development)return '';const sk=S.development.skills||{},rows=Object.entries(sk);const done=rows.every(([,v])=>v>=100);if(S.age>12&&done)return '';
 return `<section class="card wide"><h3>Independence</h3><p class="muted-text">Everyday self-care skills grow through real routines. As they grow, you can do more on your own.</p>${rows.map(([k,v])=>`<div class="skill-line"><span>${esc(k.replace(/([A-Z])/g,' $1').replace(/^./,c=>c.toUpperCase()))}</span><div class="progress"><i style="width:${clamp(v)}%"></i></div><b>${Math.round(v)}%</b></div>`).join('')}</section>${S.age<=6&&S.development.kindergarten?`<section class="card"><h3>Early education</h3>${statRow('Kindergarten',esc(S.development.kindergarten.enrolled?'Enrolled':S.development.kindergarten.status||'Not enrolled'))}${(S.education?.graduations||[]).length?`<h4>Milestones</h4>${S.education.graduations.map(g=>`<p>🎓 ${esc(g.stage)} — ${esc(g.school)}, ${g.year}</p>`).join('')}`:''}</section>`:''}`}
// ---------- wiring ----------
function rstEventChoice(e,id){
 if(e.type==='loveAdvice'){const p=personById(e.participants?.[0]),c=npcCouples().find(x=>x.id===e.payload?.coupleId);if(!p)return true;p.trust=clamp(p.trust+(id==='neutral'||id==='talk'?3:0));p.rel=clamp(p.rel+(id==='breakup'?-1:2));if(c&&c.status==='dating'){c.strength=clamp(c.strength+({talk:12,space:4,breakup:-25,neutral:2}[id]||0));if(id==='breakup'&&c.strength<25)breakNpcCouple(c,'they took your advice to end it')}log('Relationship advice',{talk:`"Just talk to them honestly." ${firstName(p)} nods. Later they text: "We talked. Better now."`,space:'You suggest a bit of space. They think about it.',breakup:`You tell ${firstName(p)} to end it. They go quiet.`,neutral:'You mostly listen. Sometimes that is the advice.'}[id]);return true}
 if(e.type==='triangle'){const p=personById(e.participants?.[0]);if(!p)return true;if(id==='happy'){S.happiness=clamp(S.happiness-1);p.rel=clamp(p.rel+1);log('Happy for them','It stings a little, but you mean it.')}else if(id==='sad'){S.happiness=clamp(S.happiness-5);setEmotion('Heartbroken','Your crush is with someone else.',55);log('Quietly sad','You put on a playlist and let yourself feel it.')}else{const ok=chance(15);if(ok){const c=coupleOf(p.npcId);if(c)breakNpcCouple(c,'one of them liked someone else');p.attraction=clamp((p.attraction||50)+10);log('Unexpected',`${firstName(p)} goes very quiet. A few days later, they are single — and they keep looking at you.`,true)}else{p.rel=clamp(p.rel-2);log('Bad timing',`"I'm with ${p.datingNpc||'someone'} now," ${firstName(p)} says gently. It is awkward for a while.`)}}return true}
 if(e.type==='ringBack'){const p=personById(e.participants?.[0]);if(id==='ask'){S.romance.spareRing=true;if(p)p.rel=clamp(p.rel-2);log('The ring','They hand it back without a word. It feels final.')}else log('Let them keep it','You tell them to keep it. Some things are not meant to be returned.');return true}
 return false}
function rstFollowUp(f){if(f.type==='wedding'){weddingDay(f);return true}if(f.type==='babyArrives'){babyArrives(f);return true}return false}
function rstClick(b){const d=b.dataset;if(d.love){loveStep(d.personId,d.love);save();render();return true}if(d.matchmake){matchmake(d.matchmake,d.with);save();render();return true}if(d.matchmakeOpen){matchmakeModal(d.matchmakeOpen);return true}return false}
function rstDaily(){npcCoupleTick();const pp=partnerPerson();if(pp&&eligibleRomance(pp)){const L=ensureLove(pp),last=(pp.history||[])[0]?.dateISO;if(last&&daysBetween(last,currentDate())>=7&&LOVE_IDX[L.stage]>=LOVE_IDX.official){L.progress=clamp(L.progress-2);pp.rel=clamp(pp.rel-.5)}}}

function loveLifeHtml(){const pp=partnerPerson();return S.age>=13?`<section class="card"><h3>Love life</h3>${S.romance.optOut?'<p class="muted-text">Romance content is off.</p>':pp&&eligibleRomance(pp)?`<p><b>${esc(displayName(pp))}</b> • ${esc(loveStage(pp).label)}</p><div class="progress"><i style="width:${Math.round(ensureLove(pp).progress)}%"></i></div><div class="inline-actions"><button class="small" data-romance-open="${pp.id}">Relationship steps</button></div>`:'<p class="muted-text">Single. Romance is optional — nothing here is forced.</p>'}${S.romance.married?`<p class="muted-text">Married since ${formatDate(S.romance.married.dateISO)}.</p>`:''}<div class="inline-actions"><button class="small ghost" data-romance-toggle="1">${S.romance.optOut?'Turn romance content on':'Turn romance content off'}</button></div></section>`:''}
function familyTripHtml(){return S.trip?`<section class="card"><h3>Family trip</h3><p>${S.trip.going?'🧳 Going':'🏠 Staying home'} • ${esc(S.trip.dest)} • ${formatDate(S.trip.start)}–${formatDate(S.trip.end)}</p></section>`:''}
function familyExtrasHtml(){return `${familyTreeHtml()}${loveLifeHtml()}${housingHtml()}${familyTripHtml()}`}
