
// =====================================================================
// v7.3 V3 — Scholarships: senior-year competitive awards (100/75/50/25%, all years), class-rank merit with ties,
// university semesters with semester GPA and per-semester scholarships, stacking rules
// =====================================================================
const RANK_AWARD={1:15000,2:12000,3:10000},TOP10_AWARD=5000,SCH_TIERS=[100,75,50,25],STIPEND_CAP=3000;
const UNI_AWARDS={dean:{label:"Dean's List award",amount:1000},department:{label:'Department scholarship',amount:2500},leadership:{label:'Leadership & activities scholarship',amount:1500},need:{label:'Financial-need grant',amount:3000}};
// ---------- Ranks with ties (competition ranking: 1,1,3) ----------
function classRank(){const yr=parseISO(currentDate()).getUTCFullYear(),mine=Math.round(schoolAverage()*10)/10,peers=(S.npcs||[]).filter(n=>Math.abs((yr-n.birthYear)-S.age)<=1).map(n=>Math.round(peerGpa(n)*10)/10);
 const above=peers.filter(g=>g>mine).length,tied=peers.filter(g=>g===mine).length>0;return {rank:1+above,tied,size:peers.length+1,school:1+Math.round(above*3.2),avg:mine}}
function rankLabel(cr){return `${cr.rank}${cr.tied?' (tied)':''}`}
function rankAward(cr=classRank()){if(RANK_AWARD[cr.rank])return {amount:RANK_AWARD[cr.rank],why:`#${rankLabel(cr)} in your class`};if(cr.school<=10)return {amount:TOP10_AWARD,why:'top 10 in the school'};return {amount:0,why:''}}
function honorsTitle(cr=classRank()){return cr.rank===1?(cr.tied?'Co-Valedictorian':'Valedictorian'):cr.rank===2?(cr.tied?'Co-Salutatorian':'Salutatorian'):null}
// ---------- Senior-year competitive scholarship (applied for mid-semester 2) ----------
function writeScholarshipEssay(){const u=uniState();if(!inSenior()){toast('Scholarship essays are for senior year.');return}if(atSchool()){toast('After school.');return}const g=practiceSkill('writing',1);if(g===0&&S.lastFarmNote){toast(S.lastFarmNote);S.lastFarmNote=null;return}u.schEssay=clamp((u.schEssay||0)+8+(S.skills?.writing||0)*.12);advanceTime(90,{silent:true});log('Scholarship essay',u.schEssay>=80?'Your story, told well. This one could win something.':u.schEssay>=50?'A solid draft. A little more polish.':'A first draft. It needs work.')}
function scholarshipProfile(){const r=ensureRep(),cr=classRank(),u=uniState(),awards=(S.awards||[]).length,lead=(S.school?.clubs||[]).filter(c=>c.status==='Active'&&ladderFor(c).slice(-2).includes(c.position)).length,progs=(S.programs||[]).filter(p=>p.status==='Done'&&!PROGRAMS.find(x=>x.id===p.progId)?.job).length,contests=(S.school?.contests||[]).filter(c=>/Winner|Place/.test(c.result||'')).length,title=honorsTitle(cr);
 const parts={grades:(cr.avg-70)*1.6,essay:(u.schEssay||0)*.25,achievements:Math.min(18,awards*3+lead*4+contests*3+progs*2+(r.leadership||0)*.05),recommendation:(avgTeacherRel()-50)*.2,honors:title?(title.includes('Valedictorian')?15:10):0};return {parts,total:Object.values(parts).reduce((a,b)=>a+b,0),title,cr}}
function applyScholarship(){const u=uniState(),tl=seniorTimeline(),t=currentDate();if(!inSenior()){toast('This scholarship is for seniors.');return}if(t<tl.loanFrom||t>tl.loanTo){toast(`Scholarship applications are open ${formatDate(tl.loanFrom)}–${formatDate(tl.loanTo)} (middle of semester 2).`);return}if(u.schApplied){toast('You already applied.');return}u.schApplied={dateISO:t,essay:u.schEssay||0};advanceTime(40,{silent:true});log('Scholarship application sent',`Essay ${Math.round(u.schEssay||0)}%. Results come with your university decisions.`)}
function scholarshipDecision(){const u=uniState();if(!u.schApplied||u.scholarship)return;const p=scholarshipProfile(),score=p.total+(Math.random()*8-4);const pct=score>=62?100:score>=50?75:score>=40?50:score>=30?25:0;
 const weak=Object.entries(p.parts).sort((a,b)=>a[1]-b[1])[0][0],why=pct?(pct===100?`${p.title?p.title+', ':''}an outstanding record and essay`:`a strong application; the weakest part was your ${weak}`):`not selected — the weakest part was your ${weak}`;
 u.scholarship={pct,why,dateISO:currentDate()};recordOutcome('Scholarship','Senior-year scholarship',pct?`${pct}% of tuition, all years`:'Not awarded',why);if(!SIM.skipping)log(pct?`🏅 Scholarship: ${pct}% for all years`:'Scholarship: not this time',pct?`${pct===100?'A full scholarship! ':''}It covers ${pct}% of tuition every year at any university you attend (keep a GPA of 3.0+). Reason: ${why}.`:`Reason: ${why}.`,pct>0)}
// ---------- Graduation honors ----------
function graduationHonors(){if(!needsFormalSchool())return;const cr=classRank(),title=honorsTitle(cr);S.education.rankAwardAtGrad=rankAward(cr).amount;S.education.tierAidEligible=schoolAverage()>=95;if(!title)return;S.education.honors={title,rank:cr.rank,tied:cr.tied,dateISO:currentDate()};S.milestones.unshift({dateISO:currentDate(),age:S.age,title:`🎓 ${title}`,text:`#${rankLabel(cr)} of ${cr.size} in your graduating class.`});if(!SIM.skipping)queueEvent({type:'gradSpeech',title:`${title} speech`,text:`As ${title.toLowerCase()}, you speak at graduation. Hundreds of faces look up at you.`,priority:4,expiresDays:1,choices:[{id:'heartfelt',label:'Heartfelt and personal'},{id:'funny',label:'Funny'},{id:'short',label:'Short and sweet'}]})}
// ---------- Funding & stacking (scholarships → parents → loan → you) ----------
function aidFor(x){const sch=S.uniApps?.scholarship,pct=sch?.pct||0,ra=S.uni?.rankAward??rankAward().amount,tierAid=(x.tier==='elite'||x.tier==='top')&&(S.uni?.tierAid??(needsFormalSchool()&&schoolAverage()>=95))?8000:0,semAid=(S.uni?.nextSemAid||0)*2;
 const competitive=Math.round(x.tuition*pct/100),others=ra+tierAid+semAid,covered=Math.min(x.tuition,competitive+others);return {competitive,others,covered,stipend:pct===100?Math.min(STIPEND_CAP,competitive+others-covered):0}}
function funding(x){const share={Struggling:0,Modest:.25,'Middle class':.5,Comfortable:.75,Wealthy:1,'Extremely wealthy':1}[S.wealth]??.5,aid=aidFor(x),rest=x.tuition-aid.covered,parents=Math.round(rest*share),loanCap=uniState().loan?.amount||0,loan=Math.min(loanCap,rest-parents),gap=Math.max(0,rest-parents-loan);
 return {tuition:x.tuition,scholarship:aid.covered,competitive:aid.competitive,stipend:aid.stipend,parents,loan,gap,merit:rankAward().amount,rank:classRank()}}
// ---------- University: semesters, GPA per semester, tuition per semester ----------
const CLASS_YEAR=['Freshman','Sophomore','Junior','Senior'];
function uniSemesterInfo(){const a=academicInfo();return {a,key:`${a.key}-${a.semester||0}`}}
function chargeSemester(){const x=UNIS.find(y=>y.name===S.uni.school)||{tuition:S.uni.tuition,tier:S.uni.tier};const f=funding(x),half=v=>Math.round(v/2),own=Math.min(half(f.gap),S.money);S.money-=own;S.finance.uniDebt=(S.finance.uniDebt||0)+half(f.loan)+(half(f.gap)-own);if(f.stipend){S.money+=half(f.stipend)}S.uni.nextSemAid=0;
 if(!SIM.skipping)log('Tuition',`${CLASS_YEAR[S.uni.year-1]||'Year '+S.uni.year} semester: ${money(half(f.tuition))} — scholarships ${money(half(f.scholarship))}, parents ${money(half(f.parents))}, loan ${money(half(f.loan))}${own?`, you ${money(own)}`:''}${f.stipend?` • living stipend ${money(half(f.stipend))}`:''}.`)}
function closeUniSemester(){const u=S.uni;const g=Math.max(0,Math.min(4,Math.round((2.2+(u.semStudy||0)*.09+(Math.random()*.4-.2))*100)/100));u.semGpas=[...(u.semGpas||[]),{sem:u.semKey,gpa:g,year:u.year}];u.gpa=Math.round(u.semGpas.reduce((a,x)=>a+x.gpa,0)/u.semGpas.length*100)/100;u.semStudy=0;u.lastSemGpa=g;u.awardWindow={from:currentDate(),to:addDays(currentDate(),14),applied:{}};
 if(!SIM.skipping){log('Semester grades',`Semester GPA ${g.toFixed(2)} • cumulative ${u.gpa.toFixed(2)}.`);notify('Scholarship applications open',`University scholarships: apply within 2 weeks.`,{sourceType:'uniAward',sourceId:'aw-'+u.semKey,tab:'school'})}else autoUniAwards()}
function autoUniAwards(){for(const k of Object.keys(UNI_AWARDS))applyUniAward(k,true)}
function uniAwardOdds(k){const u=S.uni,g=u.lastSemGpa||0;return k==='dean'?(g>=3.7?95:0):k==='department'?(g>=3.5?clamp(35+(u.essayDept||0)*.5,0,90):g>=3.2?15:0):k==='leadership'?(u.club?clamp(30+(ensureRep().leadership||0)*.5,0,85):0):k==='need'?({Struggling:85,Modest:60,'Middle class':20}[S.wealth]||5):0}
function applyUniAward(k,quiet=false){const u=S.uni;if(!u?.enrolled||!u.awardWindow||currentDate()>u.awardWindow.to){if(!quiet)toast('No scholarship window is open right now (it opens after each semester).');return}if(u.awardWindow.applied[k]){if(!quiet)toast('Already applied.');return}u.awardWindow.applied[k]=true;scheduleFollowUp('uniAward',{k,sem:u.semKey,odds:uniAwardOdds(k)},{days:14,minute:600});if(!quiet){advanceTime(30,{silent:true});log(`Applied: ${UNI_AWARDS[k].label}`,'Results in about two weeks.')}}
function uniYearTick(){
 const u=S.uniApps;
 if(S.uni?.enrolled){const {a,key}=uniSemesterInfo();if(!a.semester)return;if(S.uni.semKey!==key){if(S.uni.semKey)closeUniSemester();const newYear=S.uni.yearKey!==a.key;if(newYear){S.uni.yearKey=a.key;S.uni.year++;if(S.uni.year>4){finishUniversity();return}renewScholarship()}S.uni.semKey=key;chargeSemester()}return}
 if(u?.choice&&S.education?.highSchoolDone&&!S.uni){const x=UNIS.find(y=>y.id===u.choice),{a,key}=uniSemesterInfo();if(a.semester&&currentDate()>=a.start){S.uni={enrolled:true,school:x.name,tier:x.tier,tuition:x.tuition,year:1,yearKey:a.key,semKey:key,gpa:0,semGpas:[],semStudy:0,started:currentDate(),rankAward:rankAwardAtGrad(),tierAid:!!S.education?.tierAidEligible};chargeSemester();if(!SIM.skipping){log(`🎒 First day at ${x.name}`,'Lecture halls, a campus map you cannot read, and a thousand new faces. Declare your major in Education → University.',true);notify('Declare your major','Education → University',{sourceType:'major',sourceId:'major-'+S.uni.started,tab:'school'})}else declareMajor(Object.keys(MAJORS).find(k=>majorBonus(k).talent)||'business')}}
}
function rankAwardAtGrad(){return S.education?.rankAwardAtGrad??0}
function renewScholarship(){const s=S.uniApps?.scholarship;if(!s?.pct||!S.uni.semGpas?.length)return;if(S.uni.gpa<3){const i=SCH_TIERS.indexOf(s.pct),old=s.pct;s.pct=SCH_TIERS[i+1]||0;if(!SIM.skipping)log('Scholarship reduced',`Your GPA (${S.uni.gpa.toFixed(2)}) fell below 3.0, so your scholarship drops from ${old}% to ${s.pct}%. Bring it back up to keep the rest.`)}}
function finishUniversity(){const u=S.uni;u.enrolled=false;u.graduated=currentDate();S.education.degree={school:u.school,gpa:u.gpa||3,dateISO:currentDate(),major:u.major||null};S.milestones.unshift({dateISO:currentDate(),age:S.age,title:'🎓 University graduation',text:`Bachelor's degree from ${u.school} (GPA ${(u.gpa||3).toFixed(2)}).`});if(!SIM.skipping)log('🎓 Graduated from university',`Four years at ${u.school}. Caps in the air.`,true);if(housing().type==='dorm')S.housing={type:'parents',since:currentDate(),missed:0}}
function uniStudy(){if(!S.uni?.enrolled)return;const mb=majorBonus(),g=practiceSkill(mb.skill,mb.mult);if(g===0&&S.lastFarmNote){toast(S.lastFarmNote);S.lastFarmNote=null;return}S.uni.semStudy=(S.uni.semStudy||0)+concentration()*mb.mult;advanceTime(120,{silent:true});log('Studying',`Library, coffee, notes${S.uni.major?` for ${majorInfo(S.uni.major).label}`:''}. (${S.uni.semStudy.toFixed(1)} study points this semester${bonusText(mb)?` • ${bonusText(mb)}`:''}.)`)}
function joinCampusClub(){if(!S.uni?.enrolled)return;if(S.uni.club){toast(`You are already in ${S.uni.club}.`);return}S.uni.club=rand(mySchool()?.clubs||['Debate Society','Student Union','Coding Society','Theatre Society','Volunteer Corps']);addRep('leadership',2);advanceTime(60,{silent:true});log('Campus club',`You join the ${S.uni.club}.`)}
function universityHtml(){
 if(S.uni?.enrolled){const u=S.uni,w=u.awardWindow&&currentDate()<=u.awardWindow.to?u.awardWindow:null,sch=S.uniApps?.scholarship;
  return `<section class="card wide"><h3>University</h3>${statRow('School',esc(u.school))}${statRow('Year',`${CLASS_YEAR[u.year-1]||u.year} (${u.year} of 4)`)}${majorHtml()}${statRow('Cumulative GPA',u.semGpas?.length?u.gpa.toFixed(2):'—')}${u.semGpas?.length?`<small class="muted-text">Semesters: ${u.semGpas.map(x=>x.gpa.toFixed(2)).join(' • ')}</small>`:''}${sch?.pct?statRow('Senior-year scholarship',`${sch.pct}% (keep GPA ≥ 3.0)`):''}${u.rankAward?statRow('Class-rank award',money(u.rankAward)+'/year'):''}${statRow('Student loan balance',money(S.finance.uniDebt||0))}
  <div class="inline-actions"><button class="small" data-uni-study="1">Study (2 h)</button>${u.club?'':'<button class="small ghost" data-uni-club="1">Join a campus club</button>'}</div>${campusActionsHtml()}
  ${w?`<h4>Scholarships this semester (apply by ${formatDate(w.to)}; results in 2 weeks)</h4><div class="inline-actions">${Object.entries(UNI_AWARDS).map(([k,v])=>`<button class="small ${w.applied[k]?'ghost':''}" data-uni-award="${k}" ${w.applied[k]?'disabled':''}>${esc(v.label)} • ${money(v.amount)}${w.applied[k]?' ✓':''}</button>`).join('')}</div>`:'<p class="muted-text">University scholarships open for 2 weeks after each semester (Dean\'s List, department, leadership, financial need).</p>'}</section>`}
 if(S.education?.degree)return `<section class="card wide"><h3>University</h3><p>🎓 ${esc(S.education.degree.school)}${S.education.degree.major?` • ${esc(majorInfo(S.education.degree.major)?.label||'')}`:''} • GPA ${S.education.degree.gpa.toFixed(2)}</p></section>`;
 if(!(needsFormalSchool()&&gradeNumber()>=11)&&!S.uniApps?.choice)return '';
 const u=uniState(),tl=inSenior()?seniorTimeline():null,t=currentDate(),cr=needsFormalSchool()?classRank():null,open=tl&&t>=tl.windowOpen&&t<=tl.windowClose,midOpen=tl&&t>=tl.loanFrom&&t<=tl.loanTo,ra=cr?rankAward(cr):null,title=cr?honorsTitle(cr):null;
 return `<section class="card wide"><h3>University applications</h3>${inSenior()?`<p class="muted-text">Senior year: counselor in semester 1 • applications ${formatDate(tl.windowOpen)}–${formatDate(tl.windowClose)} • scholarship & student loan ${formatDate(tl.loanFrom)}–${formatDate(tl.loanTo)} • decisions around ${formatDate(tl.decisions)}.</p>`:'<p class="muted-text">Applications happen in senior year (Grade 12). Grades, clubs, awards and your essays all count.</p>'}
 ${cr?`<p>Average ${cr.avg.toFixed(1)} • class rank #${rankLabel(cr)} of ${cr.size}${title?` • <b>${title}</b>`:''}${ra.amount?` • class-rank award ${money(ra.amount)}/year (${ra.why})`:''} • application essay ${Math.round(u.essay)}% • scholarship essay ${Math.round(u.schEssay||0)}%</p>`:''}
 ${u.scholarship?`<p><b>Senior-year scholarship: ${u.scholarship.pct?u.scholarship.pct+'% of tuition, all years':'not awarded'}</b> <small class="muted-text">(${esc(u.scholarship.why)})</small></p>`:u.schApplied?'<p class="muted-text">Scholarship application sent — results come with your university decisions.</p>':''}
 <div class="uni-list">${UNIS.map(x=>{const d=u.decisions[x.id],ap=u.applied[x.id],inl=u.list.includes(x.id);return `<div class="uni-row"><span><b>${esc(x.name)}</b><small>${x.label} • fee ${x.fee?money(x.fee):'free'} • tuition ${money(x.tuition)}/yr</small></span><span><button class="small ghost" data-uni-brochure="${x.id}">Learn more</button>${d?`<b class="tag ${d==='Accepted'?'ok':''}">${d}</b>${d==='Accepted'&&!u.choice?` <button class="small primary" data-uni-enroll="${x.id}">Enroll</button>`:''}${u.choice===x.id?' ✅ Enrolled':''}`:ap?'<span class="tag">Applied</span>':`${inSenior()?`<button class="small ghost" data-uni-list="${x.id}">${inl?'Remove':'Add to list'}</button>`:''}${open&&inl?` <button class="small" data-uni-apply="${x.id}">Apply</button>`:''}`}</span></div>`}).join('')}</div>
 ${inSenior()?`<div class="inline-actions"><button class="small" data-uni-essay="1">Application essay (1.5 h)</button><button class="small" data-sch-essay="1">Scholarship essay (1.5 h)</button>${midOpen&&!u.schApplied?'<button class="small primary" data-sch-apply="1">Apply for the senior scholarship</button>':''}${midOpen&&!u.loan?'<button class="small" data-uni-loan="1">Apply for the interest-free student loan</button>':''}</div>`:''}${u.loan?`<p class="muted-text">Student loan: up to ${money(u.loan.amount)}/year, interest-free.</p>`:''}</section>`}
function uniFollowUp(f){if(healthFollowUp(f))return true;if(familyFollowUp(f))return true;
 if(f.type==='waitlist'){const u=uniState();if(u.decisions[f.payload.id]!=='Waitlisted')return true;u.decisions[f.payload.id]=chance(45)?'Accepted':'Rejected';if(!SIM.skipping)log('Waitlist update',`${UNIS.find(y=>y.id===f.payload.id).name}: ${u.decisions[f.payload.id]}.`,u.decisions[f.payload.id]==='Accepted');return true}
 if(f.type==='uniAward'){const k=f.payload.k,v=UNI_AWARDS[k];if(!S.uni?.enrolled)return true;const ok=chance(f.payload.odds);S.uni.awards=[...(S.uni.awards||[]),{k,sem:f.payload.sem,ok}];if(ok)S.uni.nextSemAid=(S.uni.nextSemAid||0)+v.amount;recordOutcome('University scholarship',v.label,ok?`Awarded ${money(v.amount)}`:'Not awarded',ok?'Applied to next semester':'');if(!SIM.skipping)log(ok?`🏅 ${v.label}`:`${v.label}: not this time`,ok?`${money(v.amount)} off next semester.`:'Maybe next semester.',ok);return true}
 return false}
function uniClick(b){const d=b.dataset;if(d.uniList){addToList(d.uniList);save();render();return true}if(d.uniApply){applyTo(d.uniApply);save();render();return true}if(d.uniEssay){writeEssay();save();render();return true}if(d.schEssay){writeScholarshipEssay();save();render();return true}if(d.schApply){applyScholarship();save();render();return true}if(d.uniLoan){applyLoan();save();render();return true}if(d.uniEnroll){enroll(d.uniEnroll);save();render();return true}if(d.uniStudy){uniStudy();save();render();return true}if(d.uniClub){joinCampusClub();save();render();return true}if(d.uniAward){applyUniAward(d.uniAward);save();render();return true}if(d.move){moveTo(d.move);save();render();return true}return false}
function gradSpeech(e,id){addRep('social',3);S.happiness=clamp(S.happiness+6);log('Graduation speech',{heartfelt:'You talk about the people who got you here. Half the audience is crying, including you.',funny:'The jokes land. The principal laughs despite himself.',short:'Three sentences, a thank-you, and a standing ovation for brevity.'}[id]);return true}
