// =====================================================================
// PHASE 4B.2 — CLASS REPRESENTATIVE + STUDENT COUNCIL ELECTIONS
// Extends the canonical 4B.1 organization/role model. S.elections remains
// the persistent election ledger; no parallel election system is created.
// =====================================================================
const SCHOOL_ELECTION_SCHEMA_4B2=2;
const CAMPAIGN_LIMITS_4B2={message:3,talk:3,friends:2,posters:2,speech:2,online:2,promise:1};
function electionRoleId4B2(position){const s=roleId4B1(position);return s==='class_representative'?'class_representative':s}
function electionTerm4B2(){return currentAcademicTerm4B1()}
function electionKey4B2(orgId,roleId,termKey){return `${orgId}|${roleId4B1(roleId)}|${String(termKey)}`}
function electionForKey4B2(key){return (S.elections||[]).find(e=>e.electionKey===key)||null}
function schoolElectionKind4B2(scope,position){if(scope==='class'||/class representative/i.test(position||''))return 'class_representative';if(scope==='student_council'||scope==='council')return 'student_council';return null}
function classOrganization4B2(schoolId,grade,classId){return ensureOrganization4B1({schoolId,name:`${grade} ${classId}`,type:'class',grade,classId,memberIds:currentClassMemberIds4B1(schoolId,grade,classId),roles:standardRoleDefinitions4B1('class','Class')})}
function councilOrganization4B2(schoolId){return ensureOrganization4B1({schoolId,name:'Student Council',type:'student_council',memberIds:[],roles:standardRoleDefinitions4B1('student_council','Student Council')})}
function electionOrganization4B2({kind,schoolId,grade=null,classId=null}={}){return kind==='class_representative'?classOrganization4B2(schoolId,grade,classId):kind==='student_council'?councilOrganization4B2(schoolId):null}
function candidateSchoolEligible4B2(n,org,kind){if(!n||!org)return false;syncNpcSchool4A3(n);if(n.currentSchoolId!==org.schoolId)return false;if(kind==='class_representative')return n.schoolGrade===org.grade&&n.schoolClass===org.classId;const g=gradeNumberFromLabel4A3(n.schoolGrade);return Number.isFinite(g)&&g>=8&&g<=12}
function otherClassName4B2(grade,current){const g=gradeNumberFromLabel4A3(grade)||gradeNumber()||10,letter=/-(\w)$/.exec(String(current||''))?.[1]||'A';const i=Math.max(0,'ABCD'.indexOf(letter));return `${g}-${'ABCD'[(i+1)%4]}`}
function ensureCandidatePool4B2(org,kind,min=5){
 if(!org)return [];
 let pool=(S.npcs||[]).filter(n=>candidateSchoolEligible4B2(n,org,kind));let guard=0;
 while(pool.length<min&&guard++<16){
  const sameClass=kind==='class_representative'||pool.length%2===0,grade=kind==='class_representative'?org.grade:(S.school?.currentSchoolId===org.schoolId?S.school.grade:`Grade ${Math.max(8,Math.min(12,gradeNumber()||10))}`),cls=kind==='class_representative'?org.classId:(sameClass?(S.school?.currentSchoolId===org.schoolId?S.school.className:`${gradeNumberFromLabel4A3(grade)||10}-A`):otherClassName4B2(grade,S.school?.className));
  generateHousehold({kids:1,childAge:S.age,schoolId:org.schoolId,schoolGrade:grade,schoolClass:cls});pool=(S.npcs||[]).filter(n=>candidateSchoolEligible4B2(n,org,kind));
 }
 if(kind==='student_council'&&playerCurrentSchoolId4A2()===org.schoolId&&S.school?.className&&!pool.some(n=>n.schoolClass!==S.school.className)){const grade=S.school.grade,cls=otherClassName4B2(grade,S.school.className);generateHousehold({kids:1,childAge:S.age,schoolId:org.schoolId,schoolGrade:grade,schoolClass:cls});pool=(S.npcs||[]).filter(n=>candidateSchoolEligible4B2(n,org,kind))}
 if(kind==='class_representative')org.memberIds=[...new Set([...(org.memberIds||[]),...pool.map(n=>n.id),...(playerCurrentSchoolId4A2()===org.schoolId&&S.school?.grade===org.grade&&S.school?.className===org.classId?['player']:[])])];
 return pool
}
function candidateBaseStrength4B2(n,kind){
 const tr=n.traits||[],go=n.goals||[];let x=32+(n.reputation||30)*.42;
 if(tr.includes('Ambitious'))x+=8;if(tr.includes('Outgoing'))x+=5;if(tr.includes('Studious'))x+=kind==='student_council'?6:3;if(tr.includes('Kind'))x+=2;if(tr.includes('Competitive'))x+=3;if(go.includes('classPresident'))x+=10;
 x+=(hashOf(`${n.id}|${kind}|candidate`)%1200)/100-6;return Math.round(clamp(x,18,92)*10)/10
}
function playerEligibility4B2(org,roleId){
 if(!S.school||!org||playerCurrentSchoolId4A2()!==org.schoolId)return {ok:false,reason:'You are not enrolled in this school.'};
 if(org.type==='class'&&(S.school.grade!==org.grade||S.school.className!==org.classId))return {ok:false,reason:'This election belongs to another class.'};
 const g=gradeNumber();if(g<8||g>12)return {ok:false,reason:'School leadership elections are available from Grade 8 through Grade 12.'};
 if((S.school.attendance??100)<60)return {ok:false,reason:'Your attendance is currently too low to stand for election.'};
 if((S.school.behavior??100)<45)return {ok:false,reason:'Your current discipline record makes you ineligible this term.'};
 const r=ensureRep();if((r.troublemaker||0)>=75)return {ok:false,reason:'Your current discipline standing makes you ineligible this term.'};
 if(roleId!=='class_representative'&&org.type==='student_council'&&g<9)return {ok:false,reason:'School-wide Student Council offices open from Grade 9.'};
 return {ok:true,reason:'Eligible'}
}
function npcCandidateRecord4B2(n,kind){return {id:n.id,personId:n.id,name:n.fullName,strength:candidateBaseStrength4B2(n,kind),schoolId:n.currentSchoolId,grade:n.schoolGrade,classId:n.schoolClass}}
function chooseCandidates4B2(org,kind,count=3){
 const pool=ensureCandidatePool4B2(org,kind,Math.max(5,count+1)),sorted=[...pool].sort((a,b)=>{const sa=candidateBaseStrength4B2(a,kind),sb=candidateBaseStrength4B2(b,kind);if(sb!==sa)return sb-sa;return String(a.id).localeCompare(String(b.id))});let picks=sorted.slice(0,count);
 if(kind==='student_council'&&playerCurrentSchoolId4A2()===org.schoolId&&S.school?.className&&!picks.some(n=>n.schoolClass!==S.school.className)){const other=sorted.find(n=>n.schoolClass!==S.school.className);if(other&&picks.length)picks[picks.length-1]=other}
 return picks.map(n=>npcCandidateRecord4B2(n,kind))
}
function electionDate4B2(){let d=nextSchoolDay(addDays(currentDate(),7));for(let i=0;i<12;i++){const hit=(S.calendar||[]).some(e=>e.dateISO===d&&!isTerminal(e.status)&&(e.startMinute??0)<900&&(e.endMinute??1440)>870);if(!hit)return d;d=nextSchoolDay(addDays(d,1))}return d}
function electionCandidateName4B2(id){if(id==='player')return S.name||'You';return npcById(id)?.fullName||String(id)}
function electionPublicStanding4B2(id){if(id==='player')return 'You';const n=npcById(id),p=(S.people||[]).find(x=>x.npcId===id);if(!n)return 'Student';const rel=p?(p.rel>=75?'Close to you':p.rel>=55?'Friendly with you':p.rel<=25?'Tense history with you':'You know them'):'Not personally known';const rep=(n.reputation||30)>=55?'well known around school':(n.reputation||30)>=35?'known in their year':'low-key around school';return `${rel} • ${rep}`}
function beginSchoolElection4B2({kind='class_representative',schoolId=null,grade=null,classId=null,roleId=null,playerMode='running'}={}){
 migrateSchoolOrganizations4B1();schoolId=schoolId||playerCurrentSchoolId4A2();if(!schoolId||!schoolById(schoolId))return {ok:false,reason:'missing-school'};kind=kind==='student_council'?'student_council':'class_representative';grade=grade||(schoolId===playerCurrentSchoolId4A2()?S.school?.grade:null);classId=classId||(schoolId===playerCurrentSchoolId4A2()?S.school?.className:null);if(kind==='class_representative'&&(!grade||!classId))return {ok:false,reason:'missing-class'};
 roleId=roleId4B1(roleId||(kind==='class_representative'?'class_representative':'president'));const org=electionOrganization4B2({kind,schoolId,grade,classId});if(!org)return {ok:false,reason:'missing-organization'};let role=roleDefinition4B1(org,roleId);if(!role){role=addRoleDefinition4B1(org,{roleId,unique:true,selectionMethod:'election'})}if(role.holders?.length)return {ok:false,reason:'occupied',holderId:role.holders[0].holderId};
 const term=electionTerm4B2(),key=electionKey4B2(org.organizationId,roleId,term.termKey),existing=electionForKey4B2(key);if(existing)return {ok:true,existing:true,electionId:existing.id,status:existing.status};
 const isPlayerContext=schoolId===playerCurrentSchoolId4A2()&&(kind!=='class_representative'||(grade===S.school?.grade&&classId===S.school?.className));if(playerMode==='running'&&isPlayerContext){const elig=playerEligibility4B2(org,roleId);if(!elig.ok)return {ok:false,reason:'ineligible',detail:elig.reason}}
 const npcs=chooseCandidates4B2(org,kind,kind==='student_council'?3:3),candidates=npcs.map(x=>({...x}));if(playerMode==='running'&&isPlayerContext)candidates.push({id:'player',personId:'player',name:S.name,strength:null,schoolId,grade:S.school?.grade,classId:S.school?.className});
 const date=electionDate4B2(),el={id:uid('elec'),schemaVersion:SCHOOL_ELECTION_SCHEMA_4B2,electionKey:key,kind,scope:kind,organizationId:org.organizationId,schoolId,grade:kind==='class_representative'?grade:null,classId:kind==='class_representative'?classId:null,roleId,position:role.displayName,name:kind==='class_representative'?`Class Representative — ${grade} ${classId}`:'Student Council',termKey:String(term.termKey),termStart:term.startDate,termEnd:term.expectedEndDate,startDate:currentDate(),date,status:'Campaign',playerCandidacy:playerMode==='running'&&isPlayerContext?'Running':'Declined',supportedCandidateId:null,points:0,done:{},campaignLog:[],promise:null,candidates,opponents:candidates.filter(x=>x.id!=='player'),tiePolicy:'teacher_tiebreak',resultLocked:false};
 S.elections=S.elections||[];S.elections.unshift(el);createCalendarEvent({id:`elec-${el.id}`,type:'election',title:`${el.position} election`,dateISO:date,startMinute:870,endMinute:900,graceMinute:900,payload:{electionId:el.id},required:false,location:'School',source:'school'});scheduleFollowUp('electionResult',{electionId:el.id},{dateISO:date,minute:900});const th=thread('election',el.id,`${el.position} election`);threadStep(th,'Election opened',`Candidates: ${candidates.map(c=>c.name).join(', ')}`);if(playerMode==='running'&&isPlayerContext)log(`Running for ${el.position}`,`Election day is ${formatDate(date)}. Your opponents are ${el.opponents.map(o=>o.name).join(', ')}.`,true);else log(`${el.position} election opened`,`Election day is ${formatDate(date)}. Candidates: ${candidates.map(o=>o.name).join(', ')}.`);return {ok:true,electionId:el.id,status:el.status}
}
function startElection({scope,name,position,clubId=null}={}){
 const kind=schoolElectionKind4B2(scope,position);if(kind){const role=kind==='class_representative'?'class_representative':electionRoleId4B2(position||'President');const r=beginSchoolElection4B2({kind,roleId:role,playerMode:'running'});if(!r.ok)toast(r.detail||r.reason||'You cannot run in this election.');return r}
 if(scope==='club'&&typeof openLeadershipSelection4B3==='function'){const c=clubId?clubById(clubId):(S.school?.clubs||[]).find(x=>x.name===name&&x.status==='Active'),role=roleFromLegacyPosition4B1(position)||null,r=openLeadershipSelection4B3({clubId:c?.id||clubId,roleId:role,playerApplies:true,reason:'legacy club-election redirect'});if(!r.ok)toast(r.detail||r.reason||'This leadership role is not available.');return r}
 // 4B.3 owns club/team leadership selection. The fallback below remains only for older builds where 4B.3 is absent.
 if(!electionGradeOK()){toast('School elections are open to Grade 8 and Grades 10–12.');return null}
 S.elections=S.elections||[];if(S.elections.some(e=>e.status==='Campaign'&&e.name===name))return null;
 const date=electionDate4B2(),el={id:uid('elec'),scope,name,clubId,position,startDate:currentDate(),date,status:'Campaign',points:0,done:{},opponents:electionCandidates(scope,name),promise:null};
 S.elections.unshift(el);createCalendarEvent({id:`elec-${el.id}`,type:'election',title:`${name} election`,dateISO:date,startMinute:870,endMinute:900,graceMinute:900,payload:{electionId:el.id},required:false,location:'School',source:'school'});
 const th=thread('election',el.id,`Running for ${position}${scope==='club'?` of ${name}`:''}`);threadStep(th,'Campaign started',`Against ${el.opponents.map(o=>o.name).join(' and ')}`);scheduleFollowUp('electionResult',{electionId:el.id},{dateISO:date,minute:900});log(`Running for ${position}`,`You put your name forward. Election day is ${formatDate(date)}. You are up against ${el.opponents.map(o=>o.name).join(' and ')}.`,true);return {ok:true,electionId:el.id}
}
function campaignCount4B2(el,kind){return (el.campaignLog||[]).filter(x=>x.kind===kind).length}
function campaignAction(elId,kind,arg){
 const el=S.elections?.find(x=>x.id===elId),c=CAMPAIGN[kind];if(!el||el.status!=='Campaign'||!c)return;if(el.schemaVersion!==SCHOOL_ELECTION_SCHEMA_4B2){return campaignActionLegacy4B2(el,kind,arg)}if(el.playerCandidacy!=='Running'){toast('You are not a candidate in this election.');return}if(atSchool()&&kind!=='talk'){toast('Not during class.');return}
 const k=`${kind}-${currentDate()}`;if(el.done[k]){toast('You already did that today.');return}if((el.campaignLog||[]).length>=10){toast('Your campaign schedule is full.');return}if(campaignCount4B2(el,kind)>=(CAMPAIGN_LIMITS_4B2[kind]||2)){toast('You have already used that campaign tactic enough this election.');return}if(c.phone&&!canUsePhone()){toast('You need your phone.');return}if(c.cost&&S.age>=12&&!spendOwn(c.cost)){toast(`Posters cost ${money(c.cost)}.`);return}
 const r=ensureRep();let pts=0,story;if(kind==='message'){const g=skillValue('writing');pts=4+g*.08;story='You refine a short, specific campaign message.'}else if(kind==='talk'){recordTraitEvidence('Social',{source:'talked to new people',system:'school social',context:'campaign'});pts=3+r.social*.06;addRep('social',.8);story='You talk with classmates about what they actually want changed.'}else if(kind==='friends'){const fs=S.people.filter(p=>!isFamilyPerson(p)&&p.rel>=55);pts=Math.min(12,fs.length*2);fs.forEach(f=>rememberPerson(f,'Promised to support your school campaign.'));story=fs.length?'Friends agree to spread the word.':'You do not have many close supporters to ask yet.'}else if(kind==='posters'){pts=3+skillValue('art')*.06;practiceSkill('art',1);story='You put up a clean set of campaign posters.'}else if(kind==='speech'){const q=skillValue('writing')*.35+r.leadership*.28+(S.smart??50)*.12+(S.happiness-S.stress)*.15+(hashOf(`${el.id}|speech|${campaignCount4B2(el,'speech')}`)%2200)/100;el.speech=Math.round(clamp(q));pts=el.speech*.14;story=el.speech>=60?'Your speech lands well and sounds prepared.':el.speech>=40?'The speech is solid, if a little stiff.':'You lose your place midway but finish it.'}else if(kind==='online'){pts=4+r.social*.05;story='Your campaign post gets passed around student chats.';drainActivePhone()}else if(kind==='promise'){el.promise=arg||rand(['a better school trip','more club funding','a student feedback meeting','more study-space access']);pts=5;story=`You promise to work on ${el.promise}.`}
 el.points=Math.round((el.points+pts)*10)/10;el.done[k]=true;el.campaignLog=el.campaignLog||[];el.campaignLog.push({dateISO:currentDate(),kind,points:Math.round(pts*10)/10});addRep('leadership',1);advanceTime(c.minutes);const th=thread('election',el.id,el.name);threadStep(th,'Campaigning',c.label);log(`Campaign • ${c.label}`,`${story} (campaign +${Math.round(pts)})`)
}
function campaignActionLegacy4B2(el,kind,arg){
 const c=CAMPAIGN[kind];if(!c)return;const k=`${kind}-${currentDate()}`;if(el.done?.[k]){toast('You already did that today.');return}el.done=el.done||{};let pts=kind==='speech'?6:4;el.points=Math.round(((el.points||0)+pts)*10)/10;el.done[k]=true;advanceTime(c.minutes);log(`Campaign • ${c.label}`,`Campaign +${pts}.`)
}
function supportCandidate4B2(elId,candidateId){const el=S.elections?.find(x=>x.id===elId);if(!el||el.schemaVersion!==SCHOOL_ELECTION_SCHEMA_4B2||el.status!=='Campaign')return {ok:false,reason:'not-open'};if(el.playerCandidacy==='Running')return {ok:false,reason:'player-running'};if(!el.candidates.some(c=>c.id===candidateId&&candidateId!=='player'))return {ok:false,reason:'invalid-candidate'};el.playerCandidacy='Supporting';el.supportedCandidateId=candidateId;const p=(S.people||[]).find(x=>x.npcId===candidateId);if(p){p.rel=clamp(p.rel+3);rememberPerson(p,'You publicly supported their school election campaign.',2)}log('Endorsement',`You publicly support ${electionCandidateName4B2(candidateId)} for ${el.position}.`);return {ok:true,candidateId}}
function playerElectionScore4B2(el){const r=ensureRep(),friends=S.people.filter(p=>!isFamilyPerson(p)&&p.rel>=60&&(!el.schoolId||schoolRelationNow4A4(p)!=='differentSchool')).length,teacher=(S.school?.subjects||[]).length?(S.school.subjects.reduce((a,s)=>a+(ensureTeacher(s).rel||50),0)/S.school.subjects.length):50,avg=schoolAverage();return clamp(26+r.leadership*.22+r.social*.14+r.kindness*.08-r.troublemaker*.14+(S.smart??50)*.08+(S.school?.attendance??80)*.06+(S.school?.behavior??70)*.07+avg*.05+teacher*.05+(el.points||0)+friends*1.2+(el.speech||0)*.1)}
function npcElectionScore4B2(el,c){let x=Number(c.strength)||40;const n=npcById(c.id);if(n?.traits?.includes('Ambitious'))x+=2;if(n?.traits?.includes('Studious')&&el.kind==='student_council')x+=2;if(el.supportedCandidateId===c.id)x+=4;return clamp(x)}
function allocateVotes4B2(rows,totalVotes){const sum=rows.reduce((a,x)=>a+Math.max(1,x.score),0),raw=rows.map(x=>Math.max(1,x.score)/sum*totalVotes),votes=raw.map(Math.floor);let left=totalVotes-votes.reduce((a,b)=>a+b,0);const order=raw.map((v,i)=>({i,rem:v-Math.floor(v),id:rows[i].id})).sort((a,b)=>b.rem-a.rem||String(a.id).localeCompare(String(b.id)));for(let i=0;i<left;i++)votes[order[i%order.length].i]++;return votes}
function resultShares4B2(rows,totalVotes){let shares=rows.map(x=>Math.round(x.votes*1000/totalVotes)/10),diff=Math.round((100-shares.reduce((a,b)=>a+b,0))*10)/10;if(diff){const i=rows.reduce((best,x,j,a)=>x.votes>a[best].votes?j:best,0);shares[i]=Math.round((shares[i]+diff)*10)/10}return shares}
function assignElectionWinner4B2(el,winnerId){const org=schoolOrganizationById4B1(el.organizationId);if(!org)return {ok:false,reason:'missing-organization'};if(!(org.memberIds||[]).includes(winnerId))org.memberIds.push(winnerId);const a=assignSchoolRole4B1(org.organizationId,el.roleId,winnerId,{source:`election:${el.id}`,startDate:el.date,expectedEndDate:el.termEnd,termKey:el.termKey});if(!a.ok)return a;if(winnerId==='player'){
  if(el.kind==='class_representative'){S.school.councilRole='Class Representative';S.school.councilRoleSchoolId4B1=el.schoolId}
  else{S.school.councilRole=roleDefinition4B1(org,el.roleId)?.displayName||el.position;S.school.councilRoleSchoolId4B1=el.schoolId;let sc=(S.school.clubs||[]).find(c=>c.name==='Student Council');if(!sc){sc={id:uid('club'),name:'Student Council',status:'Active',joinedDate:currentDate(),position:S.school.councilRole,attended:0,missed:0,excused:0,skill:50,leader:'Advisor',leaderRel:55,schoolId4B1:el.schoolId};S.school.clubs.push(sc)}else{sc.status='Active';sc.position=S.school.councilRole;sc.schoolId4B1=el.schoolId}}
 }return a}
function decideElection(el){
 if(!el)return null;if(el.schemaVersion!==SCHOOL_ELECTION_SCHEMA_4B2)return decideElectionLegacy4B2(el);if(el.status==='Decided'&&el.resultLocked)return el.results;if(el.status!=='Campaign')return el.results||null;
 const rows=el.candidates.map(c=>({id:c.id,name:electionCandidateName4B2(c.id),score:c.id==='player'?playerElectionScore4B2(el):npcElectionScore4B2(el,c)}));const totalVotes=el.kind==='class_representative'?Math.max(24,(schoolOrganizationById4B1(el.organizationId)?.memberIds||[]).length):Math.max(120,Math.min(600,(S.npcs||[]).filter(n=>n.currentSchoolId===el.schoolId).length*8));const votes=allocateVotes4B2(rows,totalVotes);rows.forEach((x,i)=>x.votes=votes[i]);const shares=resultShares4B2(rows,totalVotes);rows.forEach((x,i)=>x.share=shares[i]);rows.sort((a,b)=>b.votes-a.votes||b.score-a.score||String(a.id).localeCompare(String(b.id)));
 const topVotes=rows[0]?.votes||0,tied=rows.filter(x=>x.votes===topVotes);let winner=rows[0],tieResolved=false;if(tied.length>1){tieResolved=true;winner=[...tied].sort((a,b)=>{const ta=a.score+(hashOf(`${el.electionKey}|${a.id}|teacher`)%1000)/1000,tb=b.score+(hashOf(`${el.electionKey}|${b.id}|teacher`)%1000)/1000;return tb-ta||String(a.id).localeCompare(String(b.id))})[0]}
 el.status='Decided';el.resultLocked=true;el.decidedDate=currentDate();el.voterCount=totalVotes;el.results=rows;el.winnerId=winner.id;el.winner=winner.name;el.tieResolved=tieResolved;el.tieCandidates=tieResolved?tied.map(x=>x.id):[];assignElectionWinner4B2(el,winner.id);const th=thread('election',el.id,el.name),ev=(S.calendar||[]).find(e=>e.id===`elec-${el.id}`);if(ev)setCalendarStatus(ev,'Completed',tieResolved?'Votes counted • teacher tie-break':'Votes counted');const me=rows.find(x=>x.id==='player'),win=winner.id==='player';recordOutcome('Election',`${el.position} • ${schoolDisplayName(el.schoolId)}`,win?'Won':el.playerCandidacy==='Running'?`Lost to ${winner.name}`:`${winner.name} elected`,`Votes: ${rows.map(x=>`${x.id==='player'?'You':x.name} ${x.votes} (${x.share}%)`).join(', ')}.${tieResolved?' Tie resolved by the school teacher tie-break rule.':''}`);
 if(el.playerCandidacy==='Running'){if(win){addRep('leadership',15);addRep('social',4);threadStep(th,'Won',`${winner.votes} votes (${winner.share}%)`,{resolve:true});if(!SIM.skipping){setEmotion('Proud','You won an election.',75);log(`🗳️ You won: ${el.position}`,`You finish first with ${winner.votes} votes (${winner.share}%).${tieResolved?' The school tie-break rule decided the tie.':''}`,true)}}else{addRep('leadership',3);threadStep(th,'Lost',`${winner.name} won with ${winner.votes} votes`,{resolve:true});if(!SIM.skipping)queueEvent({type:'electionLost',title:`${winner.name} won the election`,text:`You received ${me?.votes||0} votes (${me?.share||0}%). What now?`,payload:{electionId:el.id,winnerId:winner.id},priority:3,expiresDays:3,choices:[{id:'support',label:`Congratulate ${winner.name} and offer help`},{id:'elsewhere',label:'Look for leadership elsewhere'},{id:'nextYear',label:'Plan to run again next year'},{id:'sulk',label:'Keep your distance'}]})}}
 else{threadStep(th,'Result',`${winner.name} won with ${winner.votes} votes`,{resolve:true});if(el.supportedCandidateId===winner.id){addRep('leadership',2);const p=(S.people||[]).find(x=>x.npcId===winner.id);if(p)p.rel=clamp(p.rel+4)}}return el.results
}
function decideElectionLegacy4B2(el){if(!el||el.status!=='Campaign')return el?.results||null;el.status='Decided';const me=clamp(35+(ensureRep().leadership||0)*.25+(el.points||0)),all=[{id:'player',name:S.name,score:me},...(el.opponents||[]).map(o=>({id:o.id,name:o.name,score:o.strength||40}))].sort((a,b)=>b.score-a.score);const votes=allocateVotes4B2(all,100);all.forEach((x,i)=>{x.votes=votes[i];x.share=votes[i]});el.results=all;el.winnerId=all[0].id;el.winner=all[0].name;el.resultLocked=true;return all}
function migrateSchoolElections4B2(){
 S.elections=Array.isArray(S.elections)?S.elections:[];migrateSchoolOrganizations4B1();for(const el of S.elections){if(!el||el.schemaVersion===SCHOOL_ELECTION_SCHEMA_4B2)continue;const kind=schoolElectionKind4B2(el.scope,el.position);if(!kind||el.clubId)continue;const sid=el.schoolId||playerCurrentSchoolId4A2();if(!sid||!S.school||sid!==playerCurrentSchoolId4A2())continue;const grade=el.grade||S.school.grade,classId=el.classId||S.school.className,roleId=kind==='class_representative'?'class_representative':electionRoleId4B2(el.position||'President'),org=electionOrganization4B2({kind,schoolId:sid,grade,classId});if(!org)continue;el.schemaVersion=SCHOOL_ELECTION_SCHEMA_4B2;el.kind=kind;el.scope=kind;el.organizationId=org.organizationId;el.schoolId=sid;el.grade=kind==='class_representative'?grade:null;el.classId=kind==='class_representative'?classId:null;el.roleId=roleId;el.termKey=String(el.termKey||electionTerm4B2().termKey);el.electionKey=el.electionKey||electionKey4B2(org.organizationId,roleId,el.termKey);el.position=roleDefinition4B1(org,roleId)?.displayName||el.position;el.playerCandidacy=el.playerCandidacy||'Running';el.campaignLog=Array.isArray(el.campaignLog)?el.campaignLog:[];el.candidates=Array.isArray(el.candidates)?el.candidates:[...(el.opponents||[]).map(o=>({id:o.id,personId:o.id,name:o.name||electionCandidateName4B2(o.id),strength:o.strength||candidateBaseStrength4B2(npcById(o.id)||{},kind)})),{id:'player',personId:'player',name:S.name,strength:null,schoolId:sid,grade:S.school.grade,classId:S.school.className}];el.opponents=el.candidates.filter(c=>c.id!=='player');el.tiePolicy=el.tiePolicy||'teacher_tiebreak';el.resultLocked=!!(el.resultLocked||el.status==='Decided');if(el.winner&&!el.winnerId){const found=el.candidates.find(c=>c.name===el.winner);if(found)el.winnerId=found.id}}
 const seen=new Set();for(const el of S.elections){if(!el?.electionKey)continue;if(seen.has(el.electionKey)&&el.status==='Campaign')el.status='Superseded';else seen.add(el.electionKey)}return {schemaVersion:SCHOOL_ELECTION_SCHEMA_4B2,count:S.elections.length,canonical:S.elections.filter(e=>e.schemaVersion===SCHOOL_ELECTION_SCHEMA_4B2).length}
}
function activeCanonicalElection4B2(orgId,roleId){return (S.elections||[]).find(e=>e.schemaVersion===SCHOOL_ELECTION_SCHEMA_4B2&&e.organizationId===orgId&&e.roleId===roleId4B1(roleId)&&e.status==='Campaign')||null}
function roleHolderName4B2(org,roleId){const id=roleDefinition4B1(org,roleId)?.holders?.[0]?.holderId;return id?electionCandidateName4B2(id):'Vacant'}
function schoolElectionEntryHtml4B2(){
 if(!S.school||!playerCurrentSchoolId4A2())return '';migrateSchoolOrganizations4B1();migrateSchoolElections4B2();const sid=playerCurrentSchoolId4A2(),cls=classOrganization4B2(sid,S.school.grade,S.school.className),council=councilOrganization4B2(sid),classEl=activeCanonicalElection4B2(cls.organizationId,'class_representative'),presEl=activeCanonicalElection4B2(council.organizationId,'president'),classHeld=roleHolderName4B2(cls,'class_representative'),presHeld=roleHolderName4B2(council,'president'),g=gradeNumber(),canClass=g>=8&&g<=12,canCouncil=g>=9&&g<=12;
 const row=(title,holder,el,kind,role,can)=>`<div class="commitment-card"><div><b>${esc(title)}</b><small>Current holder: ${esc(holder)}${el?` • election ${formatDate(el.date)}`:''}</small></div><div class="inline-actions">${el?'':holder==='Vacant'&&can?`<button class="small primary" data-school-election-run="${kind}" data-school-election-role="${role}">Run</button><button class="small ghost" data-school-election-follow="${kind}" data-school-election-role="${role}">Follow / support another candidate</button>`:''}</div></div>`;return `<h4>School leadership</h4>${row(`Class Representative • ${S.school.grade} ${S.school.className}`,classHeld,classEl,'class_representative','class_representative',canClass)}${row('Student Council President',presHeld,presEl,'student_council','president',canCouncil)}`
}
function electionHtml(){const live=(S.elections||[]).filter(e=>e.status==='Campaign');const cards=live.map(el=>{if(el.schemaVersion!==SCHOOL_ELECTION_SCHEMA_4B2)return `<div class="session-card is-live"><div class="session-head"><div><b>🗳️ ${esc(el.position||el.name||'Election')}</b><small>Election ${formatDate(el.date)}</small></div></div></div>`;const d=daysBetween(currentDate(),el.date),cand=el.candidates.map(c=>`<div><b>${esc(c.name)}</b><small>${esc(electionPublicStanding4B2(c.id))}</small>${el.playerCandidacy!=='Running'&&c.id!=='player'?`<button class="small ghost" data-school-election-support="${el.id}" data-candidate-id="${c.id}">${el.supportedCandidateId===c.id?'Supporting':'Support'}</button>`:''}</div>`).join('');return `<div class="session-card is-live"><div class="session-head"><div><b>🗳️ ${esc(el.position)} • ${esc(schoolDisplayName(el.schoolId))}${el.classId?` • ${esc(el.grade)} ${esc(el.classId)}`:''}</b><small>Election ${d<=0?'today':`in ${d} day${d===1?'':'s'}`} • ${esc(el.playerCandidacy)}</small></div></div><div class="candidate-grid">${cand}</div>${el.playerCandidacy==='Running'?`<div class="session-actions">${Object.entries(CAMPAIGN).filter(([,c])=>S.age>=(c.minAge||0)).map(([k,c])=>`<button class="small ${el.done?.[`${k}-${currentDate()}`]?'ghost':''}" data-campaign="${el.id}" data-kind="${k}" ${el.done?.[`${k}-${currentDate()}`]?'disabled':''}>${esc(c.label)}</button>`).join('')}</div><small class="muted-text">Campaign actions: ${(el.campaignLog||[]).length}/10${el.promise?` • Promise: ${esc(el.promise)}`:''}</small>`:''}</div>`}).join('');const recent=(S.elections||[]).filter(e=>e.schemaVersion===SCHOOL_ELECTION_SCHEMA_4B2&&e.status==='Decided').slice(0,3).map(el=>`<div class="timeline-entry"><span>${esc(el.position)} • ${formatDate(el.date)}</span><b>${esc(el.winner||'Winner')} elected</b><p>${(el.results||[]).map(x=>`${esc(x.name)} ${x.votes} (${x.share}%)`).join(' • ')}${el.tieResolved?' • Tie resolved by teacher tie-break.':''}</p></div>`).join('');return schoolElectionEntryHtml4B2()+cards+(recent?`<h4>Recent election results</h4>${recent}`:'')}
function schoolElectionClick4B2(b){const d=b.dataset;if(d.schoolElectionRun){const r=beginSchoolElection4B2({kind:d.schoolElectionRun,roleId:d.schoolElectionRole,playerMode:'running'});if(!r.ok)toast(r.detail||r.reason);save();render();return true}if(d.schoolElectionFollow){const r=beginSchoolElection4B2({kind:d.schoolElectionFollow,roleId:d.schoolElectionRole,playerMode:'declined'});if(!r.ok)toast(r.detail||r.reason);save();render();return true}if(d.schoolElectionSupport){const r=supportCandidate4B2(d.schoolElectionSupport,d.candidateId);if(!r.ok)toast(r.reason);save();render();return true}return false}
