// =====================================================================
// PHASE 4B.4 — SCHOOL REPUTATION / AMBASSADOR / FUTURE ROLE HOOKS
// Contextual Looks/Smart integration, teacher/coach opinion, school-level
// representative foundation, Valedictorian eligibility foundation, Prom
// organization permission hooks, role visibility, and lightweight duties.
// =====================================================================
const SCHOOL_RECOGNITION_SCHEMA_4B4=1;
const MEANINGFUL_SCHOOL_ROLES_4B4=new Set(['class_representative','president','vice_president','secretary','treasurer','captain','vice_captain','editor_in_chief','production_lead','stage_manager','concertmaster','ambassador','committee_head','event_coordinator']);
function recognitionState4B4(){const st=schoolOrganizationState4B1();st.recognitionSchemaVersion=SCHOOL_RECOGNITION_SCHEMA_4B4;st.recognition=st.recognition&&typeof st.recognition==='object'?st.recognition:{};const r=st.recognition;r.ambassadorConsiderations=Array.isArray(r.ambassadorConsiderations)?r.ambassadorConsiderations:[];r.valedictorianSnapshots=Array.isArray(r.valedictorianSnapshots)?r.valedictorianSnapshots:[];r.roleMemories=Array.isArray(r.roleMemories)?r.roleMemories:[];r.dutyLog=Array.isArray(r.dutyLog)?r.dutyLog:[];return r}
function teacherOpinion4B4(){const subs=S.school?.subjects||[];if(!subs.length)return 50;const vals=subs.map(s=>ensureTeacher(s)?.rel??50);return clamp(vals.reduce((a,b)=>a+b,0)/vals.length)}
function opinionLabel4B4(v){v=Number(v)||0;return v>=80?'Excellent':v>=65?'Strong':v>=50?'Positive':v>=35?'Mixed':'Poor'}
function teacherCoachOpinion4B4(organizationId=null){if(organizationId&&typeof clubForOrganization4B3==='function'){const c=clubForOrganization4B3(organizationId);if(c)return clamp(c.leaderRel??50)}return teacherOpinion4B4()}
function currentSchoolRoles4B4(holderId='player'){const sid=holderId==='player'?playerCurrentSchoolId4A2():actorSchoolId4B1(holderId);return activeRolesForHolder4B1(holderId).filter(x=>x.schoolId===sid&&MEANINGFUL_SCHOOL_ROLES_4B4.has(x.roleId))}
function leadershipExperience4B4(holderId='player'){const sid=holderId==='player'?playerCurrentSchoolId4A2():actorSchoolId4B1(holderId),active=currentSchoolRoles4B4(holderId).length,hist=schoolOrganizationState4B1().roleHistory.filter(x=>x.holderId===holderId&&(!sid||x.schoolId===sid)).length;return Math.min(100,active*18+hist*10)}
function schoolRepresentativeOrganization4B4(schoolId=playerCurrentSchoolId4A2()){
 if(!schoolId||!schoolById(schoolId)||!S.school||schoolId!==playerCurrentSchoolId4A2())return null;const g=gradeNumber(),stage=canonicalSchoolStage4A1(S.school.stage||schoolStage(schoolId));if(!['middle','high'].includes(stage)||g<8)return null;
 const org=ensureOrganization4B1({schoolId,name:'School Representatives',type:'school_committee',memberIds:[],roles:[{roleId:'ambassador',displayName:'School Ambassador',unique:true,selectionMethod:'advisor_appointment',eligibility:{membershipRequired:false,schoolId}}]});const role=roleDefinition4B1(org,'ambassador');if(role){role.displayName='School Ambassador';role.unique=true;role.selectionMethod='advisor_appointment';role.eligibility=Object.assign({},role.eligibility||{},{membershipRequired:false,schoolId})}return org
}
function playerCommunicationStanding4B4(){const p=S.personality||[];let v=50;if(p.includes('Social'))v+=14;if(p.includes('Bold'))v+=10;if(p.includes('Kind'))v+=6;if(p.includes('Responsible'))v+=5;if(p.includes('Shy'))v-=8;return clamp(v)}
function ambassadorAssessment4B4(){
 const org=schoolRepresentativeOrganization4B4(),r=ensureRep(),g=gradeNumber(),teacher=teacherOpinion4B4(),attendance=clamp(S.school?.attendance??0),behavior=clamp(S.school?.behavior??0),academic=clamp(schoolAverage()),looks=clamp(S.looks??50),smart=clamp(S.smart??50),communication=playerCommunicationStanding4B4(),experience=leadershipExperience4B4('player');
 if(!org)return {eligible:false,score:0,reason:'School Ambassador is only available in an appropriate middle/high-school context.',components:{}};
 const components={leadership:r.leadership||0,social:r.social||0,kindness:r.kindness||0,troublemaker:r.troublemaker||0,attendance,behavior,academic,teacher,communication,looks,smart,experience};
 // Looks is intentionally a small public-facing factor; conduct, attendance,
 // reputation, communication and teacher standing carry much more weight.
 const score=clamp((r.leadership||0)*.16+(r.social||0)*.13+(r.kindness||0)*.08+(100-(r.troublemaker||0))*.09+attendance*.10+behavior*.10+academic*.06+teacher*.10+communication*.08+looks*.05+smart*.02+experience*.03);
 const reasons=[];if(g<8)reasons.push('grade');if(attendance<75)reasons.push('attendance');if(behavior<60)reasons.push('behavior');if((r.troublemaker||0)>55)reasons.push('discipline');if(teacher<45)reasons.push('teacher standing');if(score<55)reasons.push('overall school standing');
 return {eligible:reasons.length===0,score:Math.round(score*10)/10,reason:reasons.length?`Needs improvement: ${reasons.join(', ')}.`:'Eligible for school ambassador consideration.',components,organizationId:org.organizationId,schoolId:org.schoolId}
}
function npcAmbassadorScore4B4(id){const n=ensureNpcTraits(npcById(id));if(!n)return 0;const tr=n.traits||[],go=n.goals||[];let communication=48+(tr.includes('Outgoing')?14:0)+(tr.includes('Social')?12:0)+(tr.includes('Kind')?7:0)+(tr.includes('Responsible')?7:0)+(tr.includes('Shy')?-8:0),leadership=35+(n.reputation||30)*.45+(tr.includes('Ambitious')?10:0)+(go.includes('classPresident')?8:0);return clamp(leadership*.28+(n.reputation||35)*.20+communication*.18+(n.smart??50)*.12+(n.looks??50)*.06+(tr.includes('Responsible')?8:0)+(hashOf(`${id}|ambassador`)%900)/100-4.5)}
function ensureAmbassadorCandidates4B4(schoolId,min=3){let ids=studentsAtSchool4A3(schoolId).filter(id=>id!=='player'&&npcById(id));let guard=0;while(ids.length<min&&guard++<10){const n=generateHousehold({kids:1,childAge:S.age,schoolId,schoolGrade:S.school?.grade,schoolClass:S.school?.className})[0];if(n)ids=studentsAtSchool4A3(schoolId).filter(id=>id!=='player'&&npcById(id))}return [...new Set(ids)].sort((a,b)=>npcAmbassadorScore4B4(b)-npcAmbassadorScore4B4(a)||String(a).localeCompare(String(b))).slice(0,3)}
function ambassadorSelectionKey4B4(org){const term=currentAcademicTerm4B1(),hist=schoolOrganizationState4B1().roleHistory.filter(x=>x.organizationId===org.organizationId&&x.roleId==='ambassador').sort((a,b)=>String(b.endDate||'').localeCompare(String(a.endDate||'')))[0];return `${org.organizationId}|ambassador|${term.termKey}|${hist?.endDate||'initial'}`}
function requestAmbassadorConsideration4B4(){
 migrateSchoolRecognition4B4();const a=ambassadorAssessment4B4(),org=a.organizationId&&schoolOrganizationById4B1(a.organizationId),role=roleDefinition4B1(org,'ambassador');if(!a.eligible)return {ok:false,reason:'ineligible',detail:a.reason};if(!org||!role)return {ok:false,reason:'missing-context'};if(role.holders?.length)return {ok:false,reason:'occupied',holderId:role.holders[0].holderId};
 const state=recognitionState4B4(),key=ambassadorSelectionKey4B4(org),old=state.ambassadorConsiderations.find(x=>x.selectionKey===key);if(old)return {ok:true,existing:true,winnerId:old.winnerId,considerationId:old.id};const npcIds=ensureAmbassadorCandidates4B4(org.schoolId,3),rows=[{id:'player',name:S.name,score:a.score},...npcIds.map(id=>({id,name:npcById(id)?.fullName||'Student',score:Math.round(npcAmbassadorScore4B4(id)*10)/10}))].sort((x,y)=>y.score-x.score||((hashOf(`${key}|${x.id}|advisor`)%10000)-(hashOf(`${key}|${y.id}|advisor`)%10000))||String(x.id).localeCompare(String(y.id)));const winner=rows[0];if(!(org.memberIds||[]).includes(winner.id))org.memberIds.push(winner.id);const asn=assignSchoolRole4B1(org.organizationId,'ambassador',winner.id,{source:'4B.4 ambassador appointment'});if(!asn.ok)return {ok:false,reason:asn.reason};const rec={id:uid('amb'),schemaVersion:SCHOOL_RECOGNITION_SCHEMA_4B4,selectionKey:key,schoolId:org.schoolId,organizationId:org.organizationId,roleId:'ambassador',dateISO:currentDate(),method:'advisor_appointment',candidateIds:rows.map(x=>x.id),winnerId:winner.id,winner:winner.name,resultLocked:true,results:rows.map(x=>({id:x.id,name:x.name,outcome:x.id===winner.id?'Selected':'Not selected'}))};state.ambassadorConsiderations.unshift(rec);
 recordOutcome('School recognition','School Ambassador',winner.id==='player'?'Selected':`Selected: ${winner.name}`,'Advisor appointment considered school reputation, conduct, attendance, communication, academics and leadership.');if(winner.id==='player'){addRep('leadership',8);addRep('social',4);if(!SIM.skipping)log('🏫 School Ambassador',`You are selected to represent ${schoolDisplayName(org.schoolId)} at public-facing school activities.`,true)}else if(!SIM.skipping)log('School Ambassador selection',`${winner.name} is selected. You can keep building your school reputation and leadership record.`);syncRoleNarrativeMemory4B4();return {ok:true,winnerId:winner.id,considerationId:rec.id,results:rec.results}
}
function valedictorianConsistency4B4(){const reps=Object.values(S.school?.reports||{}).filter(x=>x&&Number.isFinite(Number(x.avg))).map(x=>Number(x.avg));if(!reps.length)return clamp(schoolAverage());const avg=schoolAverage(),mean=reps.reduce((a,b)=>a+b,0)/reps.length,spread=reps.reduce((a,b)=>a+Math.abs(b-mean),0)/reps.length;return clamp(Math.min(avg,mean)-spread*.7)}
function valedictorianEligibility4B4(){
 if(!S.school||canonicalSchoolStage4A1(S.school.stage||schoolStage(playerCurrentSchoolId4A2()))!=='high')return {tracked:false,eligible:false,status:'Not in high school',score:0};const avg=clamp(schoolAverage()),smart=clamp(S.smart??50),attendance=clamp(S.school.attendance??0),behavior=clamp(S.school.behavior??0),consistency=valedictorianConsistency4B4(),cr=typeof classRank==='function'?classRank():{rank:null,size:null},standing=cr?.rank?clamp(100-Math.max(0,cr.rank-1)*12):avg;
 // Academic performance, class standing and consistency dominate this score.
 // Popularity, Looks and social reputation are deliberately absent.
 const score=clamp(avg*.55+standing*.20+consistency*.07+smart*.08+attendance*.06+behavior*.04),senior=gradeNumber()===12,eligible=senior&&avg>=85&&attendance>=80&&behavior>=60&&cr?.rank<=3;let status;if(!senior)status='Foundation tracking — final eligibility is decided in Grade 12';else status=eligible?'Eligible for graduation-time Valedictorian consideration':'Not currently eligible for graduation-time Valedictorian consideration';return {tracked:true,eligible,status,score:Math.round(score*10)/10,schoolId:playerCurrentSchoolId4A2(),grade:S.school.grade,academicAverage:Math.round(avg*10)/10,classRank:cr?.rank??null,classSize:cr?.size??null,consistency:Math.round(consistency*10)/10,attendance:Math.round(attendance*10)/10,behavior:Math.round(behavior*10)/10,smart:Math.round(smart*10)/10}
}
function syncValedictorianSnapshot4B4(){const v=valedictorianEligibility4B4();if(!v.tracked)return v;const r=recognitionState4B4(),term=currentAcademicTerm4B1(),key=`${v.schoolId}|${term.termKey}|${v.grade}`;let x=r.valedictorianSnapshots.find(s=>s.key===key);const payload={key,schoolId:v.schoolId,termKey:String(term.termKey),grade:v.grade,status:v.status,eligible:v.eligible,score:v.score,academicAverage:v.academicAverage,classRank:v.classRank,updatedDate:currentDate()};if(x)Object.assign(x,payload);else r.valedictorianSnapshots.unshift(payload);return v}
function promOrganizationEligibility4B4(){const sid=playerCurrentSchoolId4A2();if(!sid||!S.school)return {ok:false,reason:'No current school context.'};const active=currentSchoolRoles4B4('player'),council=active.find(x=>schoolOrganizationById4B1(x.organizationId)?.type==='student_council'),committee=active.find(x=>{const o=schoolOrganizationById4B1(x.organizationId);return o&&(/event committee/i.test(o.name)||['committee_head','event_coordinator'].includes(x.roleId))});const registered=(S.school.registeredEventRoles||[]).find(x=>x&&x.event==='prom'&&x.schoolId===sid&&(!x.expiresDate||x.expiresDate>=currentDate()));if(council)return {ok:true,source:'student_council',role:council};if(committee)return {ok:true,source:'event_committee',role:committee};if(registered)return {ok:true,source:'registered_event_role',role:registered};return {ok:false,reason:'Prom organization requires a current Student Council role, school event-committee role, or a registered Prom event role.'}}
function schoolRolePermissions4B4(){const roles=currentSchoolRoles4B4('player'),sid=playerCurrentSchoolId4A2(),has=(pred)=>roles.find(x=>pred(x,schoolOrganizationById4B1(x.organizationId))),classRep=has(x=>x.roleId==='class_representative'),council=has((x,o)=>o?.type==='student_council'),captain=has((x,o)=>o?.type==='sports_team'&&['captain','vice_captain'].includes(x.roleId)),ambassador=has(x=>x.roleId==='ambassador'),prom=promOrganizationEligibility4B4();return {schoolId:sid,roles,classRepresentative:classRep||null,council:council||null,captain:captain||null,ambassador:ambassador||null,canOrganizeProm:!!prom.ok,promSource:prom.source||null}}
function roleDutyAvailable4B4(kind){const p=schoolRolePermissions4B4(),map={class_checkin:p.classRepresentative,council_meeting:p.council,team_lead:p.captain,ambassador_welcome:p.ambassador},role=map[kind];if(!role)return {ok:false,reason:'This action requires a current school role.'};const log=recognitionState4B4().dutyLog,last=[...log].reverse().find(x=>x.kind===kind&&x.schoolId===p.schoolId);if(last&&daysBetween(last.dateISO,currentDate())<7)return {ok:false,reason:'You already handled this responsibility recently.'};return {ok:true,role}}
function performSchoolRoleDuty4B4(kind){const g=roleDutyAvailable4B4(kind);if(!g.ok){toast(g.reason);return {ok:false,reason:g.reason}}const cfg={class_checkin:{mins:30,title:'Class Representative check-in',text:'You collect classmates’ concerns and summarize what needs attention.',rep:['leadership',2,'kindness',1]},council_meeting:{mins:45,title:'Student Council meeting',text:'You help turn student concerns into an agenda and follow-up tasks.',rep:['leadership',2,'social',1]},team_lead:{mins:45,title:'Team leadership',text:'You lead a short team check-in and help keep practice focused.',rep:['leadership',2,'athletic',1]},ambassador_welcome:{mins:60,title:'School Ambassador duty',text:'You help welcome visitors and represent the school in a public-facing activity.',rep:['leadership',2,'social',2]}}[kind];advanceTime(cfg.mins,{silent:true});addRep(cfg.rep[0],cfg.rep[1]);addRep(cfg.rep[2],cfg.rep[3]);recognitionState4B4().dutyLog.push({kind,schoolId:playerCurrentSchoolId4A2(),dateISO:currentDate(),roleId:g.role.roleId,organizationId:g.role.organizationId});recordOutcome('School role',cfg.title,'Completed',cfg.text);if(!SIM.skipping)log(cfg.title,cfg.text);return {ok:true,minutes:cfg.mins}}
function syncRoleNarrativeMemory4B4(){const r=recognitionState4B4(),seen=new Set(r.roleMemories.map(x=>x.key));for(const x of currentSchoolRoles4B4('player')){const org=schoolOrganizationById4B1(x.organizationId),role=roleDefinition4B1(org,x.roleId),h=role?.holders?.find(z=>z.holderId==='player');if(!h||/legacy|migration/i.test(h.source||''))continue;const key=`active|${x.organizationId}|${x.roleId}|${h.startDate}`;if(seen.has(key))continue;seen.add(key);r.roleMemories.unshift({key,dateISO:h.startDate||currentDate(),schoolId:x.schoolId,organizationId:x.organizationId,organizationName:x.organizationName,roleId:x.roleId,roleName:x.roleName,kind:'role_started'});if(!S.milestones?.some(m=>m.phase4b4Key===key)){S.milestones=S.milestones||[];S.milestones.unshift({dateISO:h.startDate||currentDate(),age:S.age,title:`🏫 ${x.roleName}`,text:`Became ${x.roleName} in ${x.organizationName}.`,phase4b4Key:key})}}
 r.roleMemories=r.roleMemories.slice(0,30);return r.roleMemories}
function publicSchoolLeadershipForPerson4B4(p){if(!p?.npcId||!schoolKnownToPlayer4A4(p))return null;const info=personCurrentSchoolInfo4A4(p);if(!info.known||!info.schoolId)return null;const priority={president:100,ambassador:95,captain:90,editor_in_chief:85,class_representative:80,vice_president:70,vice_captain:65,secretary:60,treasurer:60,production_lead:55,stage_manager:50,concertmaster:50},roles=activeRolesForHolder4B1(p.npcId).filter(x=>x.schoolId===info.schoolId&&MEANINGFUL_SCHOOL_ROLES_4B4.has(x.roleId)).sort((a,b)=>(priority[b.roleId]||0)-(priority[a.roleId]||0)||a.organizationName.localeCompare(b.organizationName));return roles[0]||null}
function schoolLeadershipProfileTile4B4(p,tile){const x=publicSchoolLeadershipForPerson4B4(p);return x?tile('star','School role',esc(`${x.roleName} · ${x.organizationName}`)):''}
function schoolRecognitionHtml4B4(){if(!S.school||S.school.grade==='Kindergarten')return '';migrateSchoolRecognition4B4();const roles=currentSchoolRoles4B4('player'),former=schoolOrganizationState4B1().roleHistory.filter(x=>x.holderId==='player').slice().sort((a,b)=>String(b.endDate||'').localeCompare(String(a.endDate||''))).slice(0,3),amb=ambassadorAssessment4B4(),aorg=amb.organizationId&&schoolOrganizationById4B1(amb.organizationId),ah=roleDefinition4B1(aorg,'ambassador')?.holders?.[0]?.holderId,val=valedictorianEligibility4B4(),perm=schoolRolePermissions4B4(),btns=[];
 if(perm.classRepresentative&&roleDutyAvailable4B4('class_checkin').ok)btns.push('<button class="small ghost" data-school-role-duty="class_checkin">Class Representative check-in</button>');if(perm.council&&roleDutyAvailable4B4('council_meeting').ok)btns.push('<button class="small ghost" data-school-role-duty="council_meeting">Plan council meeting</button>');if(perm.captain&&roleDutyAvailable4B4('team_lead').ok)btns.push('<button class="small ghost" data-school-role-duty="team_lead">Lead team check-in</button>');if(perm.ambassador&&roleDutyAvailable4B4('ambassador_welcome').ok)btns.push('<button class="small ghost" data-school-role-duty="ambassador_welcome">Represent the school</button>');
 const ambAction=aorg&&!ah&&amb.eligible?'<button class="small primary" data-ambassador-consider="1">Request ambassador consideration</button>':'',ambText=!aorg?'Not offered at this school stage.':ah?`Current holder: ${ah==='player'?'You':npcById(ah)?.fullName||'another student'}`:amb.eligible?'Eligible for advisor consideration.':amb.reason;
 return `<section class="card wide"><div class="section-heading"><div><h3>School leadership & recognition</h3><p class="muted-text">Current offices, responsibilities and future recognition hooks use your real school context.</p></div></div>${roles.length?`<div class="fx-row">${roles.map(x=>`<span class="tag ok">${esc(x.roleName)} · ${esc(x.organizationName)}</span>`).join('')}</div>`:'<p class="muted-text">You do not currently hold a school leadership office.</p>'}${btns.length?`<div class="inline-actions">${btns.join('')}</div>`:''}<div class="timeline-entry"><span>Teacher standing</span><b>${esc(opinionLabel4B4(teacherOpinion4B4()))}</b><p>Teacher/coach opinions can influence nominations and appointments, but they do not override the rest of your record.</p></div><div class="timeline-entry"><span>School Ambassador</span><b>${esc(ambText)}</b><p>Public-facing selection weighs reputation, conduct, attendance, communication, academics and leadership; Looks is only a small factor.</p>${ambAction}</div>${val.tracked?`<div class="timeline-entry"><span>Valedictorian foundation</span><b>${esc(val.status)}</b><p>Academic average ${val.academicAverage}%${val.classRank?` • current class rank #${val.classRank}`:''}. Popularity and Looks are not part of this eligibility hook.</p></div>`:''}${former.length?`<div class="timeline-entry"><span>Former roles</span><b>${esc(former.map(x=>`${x.roleName} · ${x.organizationName}`).join(' • '))}</b><p>Former offices stay in history but do not grant current permissions.</p></div>`:''}</section>`}
function schoolRecognitionClick4B4(b){const d=b.dataset;if(d.ambassadorConsider){const r=requestAmbassadorConsideration4B4();if(!r.ok)toast(r.detail||r.reason);save();render();return true}if(d.schoolRoleDuty){performSchoolRoleDuty4B4(d.schoolRoleDuty);save();render();return true}return false}
function migrateSchoolRecognition4B4(){migrateSchoolOrganizations4B1();const r=recognitionState4B4();schoolRepresentativeOrganization4B4();r.ambassadorConsiderations=r.ambassadorConsiderations.filter(x=>x&&x.selectionKey&&x.schoolId&&x.organizationId).map(x=>({...x,schemaVersion:SCHOOL_RECOGNITION_SCHEMA_4B4,resultLocked:x.resultLocked!==false}));const seen=new Set();r.ambassadorConsiderations=r.ambassadorConsiderations.filter(x=>!seen.has(x.selectionKey)&&(seen.add(x.selectionKey),true));r.roleMemories=r.roleMemories.filter(x=>x&&x.key);const mseen=new Set();r.roleMemories=r.roleMemories.filter(x=>!mseen.has(x.key)&&(mseen.add(x.key),true));r.dutyLog=r.dutyLog.filter(x=>x&&x.kind&&x.schoolId&&x.dateISO);syncValedictorianSnapshot4B4();syncRoleNarrativeMemory4B4();schoolOrganizationState4B1().recognitionSchemaVersion=SCHOOL_RECOGNITION_SCHEMA_4B4;return {schemaVersion:SCHOOL_RECOGNITION_SCHEMA_4B4,ambassadorConsiderations:r.ambassadorConsiderations.length,valedictorianSnapshots:r.valedictorianSnapshots.length,roleMemories:r.roleMemories.length}}
function reconcileSchoolRecognition4B4(reason='School recognition reconciliation'){reconcileSchoolRoles4B1(reason);const r=migrateSchoolRecognition4B4();const sid=playerCurrentSchoolId4A2();for(const x of recognitionState4B4().ambassadorConsiderations)if(x.schoolId!==sid&&x.winnerId==='player')x.historical=true;return r}
