// =====================================================================
// PHASE 4D.2 — DISCOVERY / REGISTRATION / DECLINE / WITHDRAWAL
// Extends canonical S.school.contests records from 4D.1.  Preparation,
// participation/results and full notification cleanup remain 4D.3/4D.4.
// =====================================================================
const SCHOOL_EVENT_SCHEMA_4D2=1;
function eventMomentCmp4D2(a,b){const ad=String(a?.dateISO||''),bd=String(b?.dateISO||'');if(ad!==bd)return ad<bd?-1:1;return Number(a?.minute||0)-Number(b?.minute||0)}
function registrationWindow4D2(c){
 if(!c)return {state:'closed',reason:'Event missing'};normalizeSchoolEvent4D1(c);const now={dateISO:currentDate(),minute:currentMinute()},open=c.registrationOpenAt||{dateISO:c.openDate||c.createdDate||currentDate(),minute:0},deadline=c.registrationDeadline||{dateISO:c.decisionDate||c.eventDate,minute:1439},eventAt=c.eventDateTime||{dateISO:c.eventDate,minute:0};
 if(eventMomentCmp4D2(now,eventAt)>0)return {state:'event_passed',open,deadline,eventAt};if(eventMomentCmp4D2(now,open)<0)return {state:'upcoming',open,deadline,eventAt};if(eventMomentCmp4D2(now,deadline)>0)return {state:'closed',open,deadline,eventAt};return {state:'open',open,deadline,eventAt}
}
function eventRequirement4D2(c){const raw=c?.eligibility||c?.requirements||{};return Object.assign({minGrade:null,maxGrade:null,minAge:null,maxAge:null,organizationId:null,roleId:null,minAcademic:null,minAttendance:null,minBehavior:null},raw)}
function eventOrganization4D2(c,req=eventRequirement4D2(c)){
 if(req.organizationId&&typeof schoolOrganizationById4B1==='function')return schoolOrganizationById4B1(req.organizationId);const name=req.clubName||req.teamName||c?.organizationName||c?.teamName||c?.clubName;if(!name||typeof schoolOrganizationsFor4B1!=='function')return null;return schoolOrganizationsFor4B1(c.schoolId).find(o=>String(o.name).toLowerCase()===String(name).toLowerCase())||null
}
function eventEligibility4D2(idOrEvent){
 const c=typeof idOrEvent==='object'?idOrEvent:schoolEventById4D1(idOrEvent);if(!c)return {eligible:false,reasons:['event-missing'],labels:['Event unavailable']};normalizeSchoolEvent4D1(c);const reasons=[],labels=[],sid=playerCurrentSchoolId4A2?.()||S.school?.currentSchoolId||null,req=eventRequirement4D2(c),g=Number(gradeNumber?.()||0),age=Number(S.age)||0;
 if(c.scope==='school'&&c.schoolId&&sid!==c.schoolId){reasons.push('wrong-school');labels.push('For another school')}
 if(req.minGrade!=null&&g<Number(req.minGrade)){reasons.push('grade-too-low');labels.push(`Grade ${req.minGrade}+ required`)}if(req.maxGrade!=null&&g>Number(req.maxGrade)){reasons.push('grade-too-high');labels.push(`Up to grade ${req.maxGrade}`)}if(req.minAge!=null&&age<Number(req.minAge)){reasons.push('age-too-low');labels.push(`Age ${req.minAge}+ required`)}if(req.maxAge!=null&&age>Number(req.maxAge)){reasons.push('age-too-high');labels.push(`Age ${req.maxAge} or younger`)}
 const org=eventOrganization4D2(c,req);const membershipRequired=!!(req.organizationId||req.clubName||req.teamName||req.membershipRequired||c.membershipRequired);if(membershipRequired){if(!org){reasons.push('organization-missing');labels.push('Required team/club is unavailable')}else if(!(org.memberIds||[]).includes('player')){reasons.push('membership-required');labels.push(`${org.name} membership required`)}}
 if(req.roleId){const ok=typeof activeRolesForHolder4B1==='function'&&activeRolesForHolder4B1('player').some(r=>(!org||r.organizationId===org.organizationId)&&r.roleId===req.roleId);if(!ok){reasons.push('role-required');labels.push(`${roleDisplay4B1?.(req.roleId)||req.roleId} role required`)}}
 if(req.minAcademic!=null&&schoolAverage()<Number(req.minAcademic)){reasons.push('academic-standing');labels.push(`Academic average ${req.minAcademic}%+ required`)}if(req.minAttendance!=null&&Number(S.school?.attendance||0)<Number(req.minAttendance)){reasons.push('attendance');labels.push(`Attendance ${req.minAttendance}%+ required`)}if(req.minBehavior!=null&&Number(S.school?.behavior||0)<Number(req.minBehavior)){reasons.push('discipline');labels.push(`Behavior ${req.minBehavior}%+ required`)}
 return {eligible:reasons.length===0,reasons,labels,organizationId:org?.organizationId||null}
}
function normalizeSchoolEventDiscovery4D2(c,{legacyKnown=true}={}){
 if(!c)return null;normalizeSchoolEvent4D1(c);c.schemaVersion4D2=SCHOOL_EVENT_SCHEMA_4D2;const req=eventRequirement4D2(c);c.eligibility=req;const known=c.discovery&&typeof c.discovery==='object'?c.discovery:null;
 c.discovery=Object.assign({discovered:legacyKnown,source:legacyKnown?'legacy_school_event':'unknown',discoveredAt:legacyKnown?{dateISO:c.createdDate||currentDate(),minute:0}:null,announcementSent:false},known||{});
 c.registration=Object.assign({openAt:c.registrationOpenAt,deadline:c.registrationDeadline,registeredAt:null,declinedAt:null,withdrawnAt:null,missedAt:null},c.registration||{});c.registration.openAt=c.registrationOpenAt;c.registration.deadline=c.registrationDeadline;
 if(['registered','preparing','participating','completed','withdrawn','missed','eliminated','disqualified'].includes(c.lifecycleState))c.registration.registeredAt=c.registration.registeredAt||{dateISO:c.registeredDate||c.createdDate||currentDate(),minute:0};
 if(c.lifecycleState==='declined')c.registration.declinedAt=c.registration.declinedAt||{dateISO:c.declinedDate||c.closedDate||currentDate(),minute:0};if(c.lifecycleState==='withdrawn')c.registration.withdrawnAt=c.registration.withdrawnAt||{dateISO:c.withdrawnDate||currentDate(),minute:0};if(c.lifecycleState==='registration_missed')c.registration.missedAt=c.registration.missedAt||{dateISO:c.closedDate||currentDate(),minute:0};return c
}
function resolveRegistrationNotifications4D2(c){if(!c)return;for(const key of ['reg-'+c.id,'event-reg-'+c.eventId,'closed-'+c.id])try{resolveNotificationsFor(key)}catch(_e){}}
function announceSchoolEvent4D2(idOrEvent,{source='school_announcement',silent=false}={}){
 const c=typeof idOrEvent==='object'?idOrEvent:schoolEventById4D1(idOrEvent);if(!c)return {ok:false,reason:'event-missing'};normalizeSchoolEventDiscovery4D2(c,{legacyKnown:false});if(c.scope==='school'&&c.schoolId!==playerCurrentSchoolId4A2())return {ok:false,reason:'wrong-school'};const elig=eventEligibility4D2(c);if(!elig.eligible)return {ok:false,reason:'ineligible',eligibility:elig};
 if(!c.discovery.discovered){c.discovery.discovered=true;c.discovery.source=source;c.discovery.discoveredAt={dateISO:currentDate(),minute:currentMinute()}}
 if(!c.discovery.announcementSent){c.discovery.announcementSent=true;if(!silent&&!SIM.skipping){const w=registrationWindow4D2(c),txt=w.state==='open'?`Register by ${formatDate(c.registrationDeadline.dateISO)} • event ${formatDate(c.eventDate)}.`:`${c.name} • event ${formatDate(c.eventDate)}.`;notify(`School announcement: ${c.name}`,txt,{sourceType:'contest',sourceId:'event-reg-'+c.eventId,tab:'school'})}}
 return {ok:true,event:c,eligibility:elig}
}
function registerSchoolEvent4D2(idOrEvent,{approved=false}={}){
 const c=typeof idOrEvent==='object'?idOrEvent:schoolEventById4D1(idOrEvent);if(!c)return {ok:false,reason:'event-missing'};normalizeSchoolEventDiscovery4D2(c);const w=registrationWindow4D2(c),elig=eventEligibility4D2(c);if(!elig.eligible)return {ok:false,reason:'ineligible',eligibility:elig};if(w.state!=='open'){if(w.state==='closed'||w.state==='event_passed')markRegistrationMissed4D2(c,'Registration deadline passed');return {ok:false,reason:w.state}}
 if(c.lifecycleState==='announced')transitionSchoolEvent4D1(c,'registration_open',{reason:'Registration window open'});if(!['registration_open','registration_pending'].includes(c.lifecycleState))return {ok:false,reason:'state-'+c.lifecycleState};
 if(S.age<13&&!approved){const existing=(S.pendingDecisions||[]).find(p=>!p.resolved&&p.type==='contestApproval'&&p.payload?.contestId===c.id);if(!existing){transitionSchoolEvent4D1(c,'registration_pending',{reason:'Caregiver approval requested'});createPending({type:'contestApproval',title:`Enter ${c.name}`,resolveDate:addDays(currentDate(),1),payload:{contestId:c.id,schoolEventId:c.eventId},status:'Waiting for caregiver',detail:'Decision tomorrow.'});log('Asked to enter',`You ask to enter ${c.name}.`);return {ok:true,pending:true,event:c}}return {ok:true,pending:true,existing:true,event:c}}
 if(c.lifecycleState==='registration_pending'&&!approved)return {ok:false,reason:'approval-pending'};const tr=transitionSchoolEvent4D1(c,'registered',{reason:approved?'Caregiver approved registration':'Player registered'});if(!tr.ok)return tr;c.registeredDate=currentDate();c.registration.registeredAt={dateISO:currentDate(),minute:currentMinute()};registerContest(c);resolveRegistrationNotifications4D2(c);return {ok:true,event:c}
}
function declineSchoolEvent4D2(idOrEvent,{reason='Player declined'}={}){
 const c=typeof idOrEvent==='object'?idOrEvent:schoolEventById4D1(idOrEvent);if(!c)return {ok:false,reason:'event-missing'};normalizeSchoolEventDiscovery4D2(c);if(c.lifecycleState==='announced'){const w=registrationWindow4D2(c);if(w.state==='open')transitionSchoolEvent4D1(c,'registration_open',{reason:'Registration window open'})}if(!['registration_open','registration_pending'].includes(c.lifecycleState))return {ok:false,reason:'state-'+c.lifecycleState};const tr=transitionSchoolEvent4D1(c,'declined',{reason});if(!tr.ok)return tr;c.declinedDate=currentDate();c.registration.declinedAt={dateISO:currentDate(),minute:currentMinute()};resolveRegistrationNotifications4D2(c);for(const p of S.pendingDecisions||[])if(!p.resolved&&p.type==='contestApproval'&&p.payload?.contestId===c.id){p.resolved=true;p.status='Declined';p.resolvedDate=currentDate();p.resolutionReason='Player declined'}log('Event declined',`You decide not to enter ${c.name}.`);return {ok:true,event:c}
}
function markRegistrationMissed4D2(idOrEvent,reason='Registration deadline passed'){
 const c=typeof idOrEvent==='object'?idOrEvent:schoolEventById4D1(idOrEvent);if(!c)return {ok:false,reason:'event-missing'};normalizeSchoolEventDiscovery4D2(c);if(['declined','registered','preparing','participating','completed','withdrawn','missed','eliminated','disqualified','archived'].includes(c.lifecycleState))return {ok:true,unchanged:true,event:c};if(c.lifecycleState==='announced')transitionSchoolEvent4D1(c,'registration_open',{reason:'Registration window elapsed'});const tr=transitionSchoolEvent4D1(c,'registration_missed',{reason});if(!tr.ok)return tr;c.closedDate=c.closedDate||currentDate();c.registration.missedAt={dateISO:currentDate(),minute:currentMinute()};resolveRegistrationNotifications4D2(c);return {ok:true,event:c}
}
function withdrawSchoolEvent4D2(idOrEvent){
 const c=typeof idOrEvent==='object'?idOrEvent:schoolEventById4D1(idOrEvent);if(!c)return {ok:false,reason:'event-missing'};normalizeSchoolEventDiscovery4D2(c);if(!['registered','preparing'].includes(c.lifecycleState))return {ok:false,reason:'state-'+c.lifecycleState};const late=daysBetween(currentDate(),c.eventDate)<=3,tr=transitionSchoolEvent4D1(c,'withdrawn',{reason:late?'Late withdrawal':'Player withdrew'});if(!tr.ok)return tr;c.withdrawnDate=currentDate();c.registration.withdrawnAt={dateISO:currentDate(),minute:currentMinute()};const ev=eventCalendarFor4D1(c);if(ev&&!isTerminal(ev.status))setCalendarStatus(ev,'Cancelled','Withdrew');resolveRegistrationNotifications4D2(c);if(late){const sub=S.school.subjects?.[0];if(sub)ensureTeacher(sub).rel=clamp(sub.teacher.rel-3);log(`Withdrew from ${c.name}`,`So close to the event, your teacher is disappointed: "I had you on the list already."`)}else log(`Withdrew from ${c.name}`,'You let the organizer know in good time. No hard feelings.');return {ok:true,event:c,late}
}
function markSchoolEventOut4D2(idOrEvent,kind='eliminated',reason='Out of event'){
 const c=typeof idOrEvent==='object'?idOrEvent:schoolEventById4D1(idOrEvent);if(!c)return {ok:false,reason:'event-missing'};if(!['eliminated','disqualified','withdrawn'].includes(kind))return {ok:false,reason:'invalid-out-kind'};normalizeSchoolEventDiscovery4D2(c);const tr=transitionSchoolEvent4D1(c,kind,{reason});return tr.ok?{ok:true,event:c,state:kind}:tr
}
function findSchoolEvent4D2(){
 if(!S.school||S.age<6){toast('Formal school events are not part of this life stage.');return null}reconcileSchoolEventDiscovery4D2('find-event');const sid=playerCurrentSchoolId4A2(),existing=(S.school.contests||[]).filter(c=>c.schoolId===sid&&!SCHOOL_EVENT_TERMINAL_4D1.has(c.lifecycleState)&&eventEligibility4D2(c).eligible);
 const undiscovered=existing.find(c=>!c.discovery?.discovered);if(undiscovered){announceSchoolEvent4D2(undiscovered,{source:'notice_board'});log('School event opportunity',`${undiscovered.name}: ${registrationWindow4D2(undiscovered).state==='open'?'registration is open':'coming up'} • event ${formatDate(undiscovered.eventDate)}.`);return undiscovered}
 const known=existing.find(c=>c.discovery?.discovered&&['announced','registration_open','registration_pending'].includes(c.lifecycleState));if(known){toast(`${known.name} is already on your event list.`);return known}
 const activeNames=new Set((S.school.contests||[]).filter(c=>c.schoolId===sid&&!SCHOOL_EVENT_TERMINAL_4D1.has(c.lifecycleState)).map(c=>c.name)),choices=minorEventOptions().filter(n=>!activeNames.has(n));if(!choices.length){toast('No new school events are available.');return null}const name=rand(choices),c={id:uid('contest'),name,annual:false,status:'Open',createdDate:currentDate(),openDate:currentDate(),decisionDate:addDays(currentDate(),2),eventDate:addDays(currentDate(),12+Math.floor(Math.random()*10)),prep:0,result:null,schoolId:sid,discovery:{discovered:true,source:'notice_board',discoveredAt:{dateISO:currentDate(),minute:currentMinute()},announcementSent:true}};normalizeSchoolEventDiscovery4D2(c);S.school.contests.unshift(c);reconcileSchoolEvents4D1('find-event-created');log('School event opportunity',`${name}: register by ${formatDate(c.decisionDate)} • event ${formatDate(c.eventDate)}.`);return c
}
function exploreSchoolEvent(){if(!requireAction('exploreSchoolEvent'))return null;return findSchoolEvent4D2()}
function reconcileSchoolEventDiscovery4D2(reason='tick'){
 if(!S.school)return {count:0};reconcileSchoolEvents4D1(reason);const sid=playerCurrentSchoolId4A2(),now=currentDate();let announced=0,missed=0;for(const c of S.school.contests||[]){const had4d2=!!c.schemaVersion4D2;normalizeSchoolEventDiscovery4D2(c,{legacyKnown:had4d2?!!c.discovery?.discovered:true});const w=registrationWindow4D2(c);if(c.lifecycleState==='announced'&&w.state==='open')transitionSchoolEvent4D1(c,'registration_open',{reason:'Registration opened'});if(['registration_open','registration_pending'].includes(c.lifecycleState)&&(w.state==='closed'||w.state==='event_passed')){markRegistrationMissed4D2(c,'Registration deadline passed');missed++}if(reason!=='render'&&c.schoolId===sid&&c.scope==='school'&&c.annual&&['registration_open'].includes(c.lifecycleState)&&!c.discovery.announcementSent&&eventEligibility4D2(c).eligible){announceSchoolEvent4D2(c,{source:'school_announcement'});announced++}}
 return {count:S.school.contests.length,announced,registrationMissed:missed}
}
function migrateSchoolEventDiscovery4D2(){if(!S.school)return {count:0};reconcileSchoolEvents4D1('4d2-migrate');for(const c of S.school.contests||[])normalizeSchoolEventDiscovery4D2(c,{legacyKnown:true});return reconcileSchoolEventDiscovery4D2('4d2-migrate')}
function resolveContestApproval(p){
 const c=schoolEventById4D1(p?.payload?.schoolEventId||p?.payload?.contestId);if(!c){p.resolved=true;p.status='Cancelled';return}if(registrationWindow4D2(c).state!=='open'){markRegistrationMissed4D2(c,'Approval arrived after registration deadline');p.resolved=true;p.status='Expired';p.resolvedDate=currentDate();return}if(caregiverApproval(5)){registerSchoolEvent4D2(c,{approved:true});p.status='Approved'}else{declineSchoolEvent4D2(c,{reason:'Caregiver denied permission'});p.status='Denied';log('Event permission denied',`Your caregiver says no to ${c.name}.`)}p.resolved=true;p.resolvedDate=currentDate()
}
function schoolEventStatusLabel4D2(c){return ({announced:'Upcoming',registration_open:'Available',registration_pending:'Waiting',registered:'Registered',preparing:'Preparing',participating:'Participating',completed:'Completed',declined:'Declined',registration_missed:'Registration missed',withdrawn:'Withdrawn',missed:'Missed',eliminated:'Out',disqualified:'Disqualified',cancelled:'Cancelled',archived:'Archived'})[c.lifecycleState]||c.status||'Upcoming'}
function schoolEventsHtml4D2(){
 if(typeof schoolEventsHtml4D4==='function')return schoolEventsHtml4D4();
 if(!S.school)return '<p class="muted-text">No current event opportunities.</p>';reconcileSchoolEventDiscovery4D2('render');const sid=playerCurrentSchoolId4A2(),events=(S.school.contests||[]).filter(c=>c.schoolId===sid&&c.discovery?.discovered).sort((a,b)=>String(a.eventDate).localeCompare(String(b.eventDate))).slice(0,10);if(!events.length)return '<p class="muted-text">No current event opportunities.</p>';
 return events.map(c=>{const st=c.lifecycleState,w=registrationWindow4D2(c),elig=eventEligibility4D2(c),d=daysBetween(currentDate(),c.eventDate),label=schoolEventStatusLabel4D2(c),why=!elig.eligible?elig.labels.join(' • '):'';if(st==='registration_open'){return `<div class="opportunity-row"><div><b>${esc(c.name)}</b><small>${why||`Register by ${formatDate(c.registrationDeadline.dateISO)} • event ${formatDate(c.eventDate)}`}</small></div><div class="inline-actions"><button class="small" data-contest-enter="${c.id}" ${!elig.eligible?'disabled':''}>${S.age<13?'Ask to enter':'Register'}</button><button class="small ghost" data-contest-decline="${c.id}">Not participating</button></div></div>`}if(st==='registration_pending')return `<div class="opportunity-row"><div><b>${esc(c.name)}</b><small>Waiting for caregiver approval • deadline ${formatDate(c.registrationDeadline.dateISO)}</small></div>${statusTag('Waiting')}</div>`;if(['registered','preparing'].includes(st)){if(typeof schoolEventActiveCard4D3==='function')return schoolEventActiveCard4D3(c);const ev=contestEvent(c),live=ev&&ev.dateISO===currentDate()&&currentMinute()<=ev.graceMinute;return `<div class="commitment-card"><div><b>${esc(c.name)}</b><small>${d<=0?`Today • check-in ${timeLabel(ev?.startMinute??600)}–${timeLabel(ev?.graceMinute??690)}`:`Event in ${d} day${d===1?'':'s'} • ${formatDate(c.eventDate)}`} • preparation ${Math.round(c.prep||0)}%</small><div class="progress"><i style="width:${clamp(c.prep||0)}%"></i></div></div><div class="inline-actions">${live?`<button class="small primary" data-contest-attend="${c.id}">Go to the event</button>`:''}<button class="small ghost" data-contest-practice="${c.id}" ${contestPrepSessionsToday(c)>=3||(c.prep||0)>=100?'disabled':''}>Prepare 75m • ${contestPrepSessionsToday(c)}/3 today</button><button class="small ghost" data-contest-withdraw="${c.id}">Withdraw</button></div></div>`}const detail=c.result||(st==='announced'&&w.state==='upcoming'?`Registration opens ${formatDate(c.registrationOpenAt.dateISO)} • event ${formatDate(c.eventDate)}`:label);return `<div class="opportunity-row"><div><b>${esc(c.name)}</b><small>${esc(detail)}</small></div>${statusTag(label)}</div>`}).join('')
}
function schoolEventDiscoveryClick4D2(b){if(typeof schoolEventParticipationClick4D3==='function'&&schoolEventParticipationClick4D3(b))return true;if(b.dataset.contestWithdraw){withdrawSchoolEvent4D2(b.dataset.contestWithdraw);save();render();return true}return false}
