// =====================================================================
// PHASE 4D.1 — CANONICAL SCHOOL EVENT / COMPETITION LIFECYCLE
// Extends the existing S.school.contests + Calendar schoolEvent model.
// This checkpoint intentionally does NOT implement discovery/registration
// UI, preparation changes, results overhaul, or notification cleanup.
// =====================================================================
const SCHOOL_EVENT_SCHEMA_4D1=1;
const SCHOOL_EVENT_LIFECYCLE_4D1=Object.freeze([
 'announced','registration_open','registration_pending','registered','preparing',
 'participating','completed','declined','registration_missed','withdrawn','missed',
 'eliminated','disqualified','cancelled','archived'
]);
const SCHOOL_EVENT_TERMINAL_4D1=new Set(['completed','declined','registration_missed','withdrawn','missed','eliminated','disqualified','cancelled','archived']);
const SCHOOL_EVENT_TRANSITIONS_4D1=Object.freeze({
 announced:['registration_open','cancelled'],
 registration_open:['registration_pending','registered','declined','registration_missed','cancelled'],
 registration_pending:['registered','declined','registration_missed','cancelled'],
 registered:['preparing','participating','withdrawn','missed','cancelled'],
 preparing:['participating','withdrawn','missed','cancelled'],
 participating:['completed','eliminated','disqualified','withdrawn','cancelled'],
 completed:['archived'],declined:['archived'],registration_missed:['archived'],withdrawn:['archived'],
 missed:['archived'],eliminated:['archived'],disqualified:['archived'],cancelled:['archived'],archived:[]
});
function eventSlug4D1(v){return String(v||'school_event').trim().toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_+|_+$/g,'')||'school_event'}
function eventSchoolYearKey4D1(dateISO){try{const a=academicInfo(dateISO||currentDate());if(a&&Number.isFinite(Number(a.key)))return String(a.key)}catch(_e){}return String(parseISO(dateISO||currentDate()).getUTCFullYear())}
function eventSeason4D1(dateISO){const m=parseISO(dateISO||currentDate()).getUTCMonth()+1;return m<=2||m===12?'winter':m<=5?'spring':m<=8?'summer':'autumn'}
function eventCategory4D1(name,type=null){const n=String(name||'').toLowerCase(),t=String(type||'').toLowerCase();if(/sport|basketball|football|soccer|track|race|athletic|swim/.test(n+t))return 'sports_event';if(/art|music|drama|talent|performance|theater|theatre|showcase/.test(n+t))return 'arts_performance';if(/math|science|coding|robot|debate|reading|spelling|olympiad|challenge|fair/.test(n+t))return 'academic_competition';if(/council|leadership|committee/.test(n+t))return 'leadership_activity';if(/club/.test(n+t))return 'club_event';if(/ceremony|graduation|assembly/.test(n+t))return 'school_ceremony';return 'school_social_event'}
function eventType4D1(c){const n=String(c?.name||'').toLowerCase();if(c?.eventType)return c.eventType;if(/olympiad|challenge|tournament|meet|fair|showcase|talent show|competition|contest/.test(n))return 'competition';return 'school_event'}
function eventScope4D1(c){return c?.scope||c?.eventScope||'school'}
function eventRepeat4D1(c,dateISO,schoolId){const existing=c?.repeat||c?.repeatMeta||null;if(existing&&typeof existing==='object')return Object.assign({},existing,{schoolYearKey:String(existing.schoolYearKey??eventSchoolYearKey4D1(dateISO)),season:existing.season||eventSeason4D1(dateISO)});const annual=c?.annual!==false;return {frequency:annual?'annual':'once',schoolYearKey:eventSchoolYearKey4D1(dateISO),season:eventSeason4D1(dateISO),templateKey:eventSlug4D1(c?.templateKey||c?.name),schoolId:schoolId||null}}
function stableSchoolEventId4D1(c,schoolId=null){if(c?.eventId)return String(c.eventId);const sid=schoolId||c?.schoolId||playerCurrentSchoolId4A2?.()||S.school?.currentSchoolId||'school',date=c?.eventDate||c?.eventDateTime?.dateISO||c?.dateISO||currentDate(),repeat=eventRepeat4D1(c,date,sid),base=eventSlug4D1(c?.templateKey||c?.name||c?.title);return repeat.frequency==='annual'?`${base}_${repeat.schoolYearKey}_${eventSlug4D1(sid)}`:`${base}_${date}_${eventSlug4D1(sid)}`}
function lifecycleFromLegacy4D1(status,c=null){const s=String(status||'').toLowerCase();if(!s&&c?.lifecycleState&&SCHOOL_EVENT_LIFECYCLE_4D1.includes(c.lifecycleState))return c.lifecycleState;if(['open','considering'].includes(s))return 'registration_open';if(s==='waiting')return 'registration_pending';if(s==='registered'){if(['registered','preparing','participating'].includes(c?.lifecycleState))return c.lifecycleState;return (Number(c?.prep)||0)>0?'preparing':'registered'};if(s==='attending')return 'participating';if(s==='completed')return 'completed';if(['declined','denied','not participating'].includes(s))return 'declined';if(['registration closed','expired'].includes(s))return 'registration_missed';if(['withdrew','withdrawn'].includes(s))return 'withdrawn';if(['no-show','missed'].includes(s))return 'missed';if(s==='out'||s==='eliminated')return 'eliminated';if(s==='disqualified')return 'disqualified';if(s==='cancelled')return 'cancelled';if(s==='archived'||s==='resolved')return 'archived';if(s==='upcoming')return 'announced';return 'announced'}
function legacyStatusFromLifecycle4D1(state,prior='Open'){return {announced:'Upcoming',registration_open:'Open',registration_pending:'Waiting',registered:'Registered',preparing:'Registered',participating:'Registered',completed:'Completed',declined:'Declined',registration_missed:'Registration Closed',withdrawn:'Withdrew',missed:'No-show',eliminated:'Out',disqualified:'Disqualified',cancelled:'Cancelled',archived:'Resolved'}[state]||prior}
function playerStatusFromLifecycle4D1(state){return {announced:'upcoming',registration_open:'available',registration_pending:'pending_approval',registered:'registered',preparing:'preparing',participating:'participating',completed:'completed',declined:'declined',registration_missed:'not_registered',withdrawn:'withdrawn',missed:'missed',eliminated:'out',disqualified:'out',cancelled:'cancelled',archived:'archived'}[state]||'upcoming'}
function eventLifecycleRank4D1(state){return ({announced:0,registration_open:1,registration_pending:2,registered:3,preparing:4,participating:5,registration_missed:6,declined:6,withdrawn:7,missed:7,eliminated:8,disqualified:8,completed:9,cancelled:9,archived:10})[state]??0}
function canTransitionSchoolEvent4D1(from,to){if(!SCHOOL_EVENT_LIFECYCLE_4D1.includes(from)||!SCHOOL_EVENT_LIFECYCLE_4D1.includes(to))return false;if(from===to)return true;return (SCHOOL_EVENT_TRANSITIONS_4D1[from]||[]).includes(to)}
function schoolEventById4D1(id){if(!S.school||!id)return null;return (S.school.contests||[]).find(c=>c.eventId===id||c.id===id)||null}
function schoolEventsForSchool4D1(schoolId=null){const sid=schoolId||playerCurrentSchoolId4A2?.()||S.school?.currentSchoolId||null;return (S.school?.contests||[]).filter(c=>!sid||c.schoolId===sid)}
function eventCalendarFor4D1(c){if(!c)return null;const list=(S.calendar||[]).filter(e=>e.type==='schoolEvent'&&(e.payload?.schoolEventId===c.eventId||e.payload?.contestId===c.id));return list.sort((a,b)=>String(a.dateISO||'').localeCompare(String(b.dateISO||''))||String(a.id||'').localeCompare(String(b.id||'')))[0]||null}
function normalizeSchoolEvent4D1(c,{schoolId=null}={}){
 if(!c||typeof c!=='object')return null;const sid=c.schoolId||schoolId||playerCurrentSchoolId4A2?.()||S.school?.currentSchoolId||null,date=c.eventDate||c.eventDateTime?.dateISO||c.dateISO||addDays(currentDate(),14),repeat=eventRepeat4D1(c,date,sid),state=lifecycleFromLegacy4D1(c.status,c),slot=typeof contestSlot==='function'?contestSlot(date):{startMinute:600,endMinute:780,location:'School hall'};
 c.schemaVersion4D1=SCHOOL_EVENT_SCHEMA_4D1;c.schoolId=sid;c.scope=eventScope4D1(c);c.eventType=eventType4D1(c);c.category=c.category||eventCategory4D1(c.name,c.eventType);c.host=c.host||{type:c.scope==='school'?'school':'external',schoolId:sid};c.repeat=repeat;c.eventId=stableSchoolEventId4D1(c,sid);c.annualKey=repeat.frequency==='annual'?`${repeat.templateKey}:${repeat.schoolYearKey}:${sid||c.scope}`:null;c.lifecycleState=state;c.playerStatus=playerStatusFromLifecycle4D1(state);c.lifecycleHistory=Array.isArray(c.lifecycleHistory)?c.lifecycleHistory:[];
 c.registrationOpenAt=c.registrationOpenAt||{dateISO:c.createdDate||currentDate(),minute:480};c.registrationDeadline=c.registrationDeadline||{dateISO:c.decisionDate||c.registrationDeadlineDate||date,minute:1439};c.eventDate=date;c.eventDateTime=c.eventDateTime||{dateISO:date,minute:Number(c.eventMinute??slot.startMinute??600)};c.durationMinutes=Number.isFinite(Number(c.durationMinutes))?Number(c.durationMinutes):Math.max(30,Number(slot.endMinute??780)-Number(slot.startMinute??600));c.location=c.location||slot.location||'School';c.participantIds=Array.isArray(c.participantIds)?[...new Set(c.participantIds.map(String))]:[];c.preparationState=Object.assign({progress:clamp(Number(c.prep)||0),sessionsByDate:{}},c.preparationState||{});c.preparationState.progress=clamp(Math.max(Number(c.prep)||0,Number(c.preparationState.progress)||0));c.prep=c.preparationState.progress;c.result=c.result??null;c.resolvedAt=c.resolvedAt??null;c.calendarRef=c.calendarRef||null;
 const cal=eventCalendarFor4D1(c);if(cal){cal.payload=cal.payload||{};cal.payload.contestId=c.id;cal.payload.schoolEventId=c.eventId;cal.schoolId=cal.schoolId||c.schoolId;cal.category=cal.category||'Competition';c.calendarRef=cal.id}
 return c
}
function mergeDuplicateSchoolEvent4D1(keep,drop){const keepId=keep.id,dropId=drop.id,stableId=keep.eventId||drop.eventId,ka=lifecycleFromLegacy4D1(keep.status,keep),da=lifecycleFromLegacy4D1(drop.status,drop),prefer=eventLifecycleRank4D1(da)>eventLifecycleRank4D1(ka)?drop:keep,other=prefer===keep?drop:keep;Object.assign(keep,prefer);keep.id=keepId;keep.eventId=stableId;keep.schoolId=prefer.schoolId||other.schoolId||keep.schoolId;keep.prep=Math.max(Number(prefer.prep)||0,Number(other.prep)||0);keep.preparationState=Object.assign({},other.preparationState||{},prefer.preparationState||{},{progress:Math.max(Number(prefer.preparationState?.progress)||0,Number(other.preparationState?.progress)||0,keep.prep)});if(!keep.result&&other.result)keep.result=other.result;if(!keep.resolvedAt&&other.resolvedAt)keep.resolvedAt=other.resolvedAt;keep.lifecycleHistory=[...(other.lifecycleHistory||[]),...(prefer.lifecycleHistory||[])].filter((x,i,a)=>a.findIndex(y=>JSON.stringify(y)===JSON.stringify(x))===i);for(const ev of S.calendar||[]){if(ev.type==='schoolEvent'&&ev.payload?.contestId===dropId){ev.payload.contestId=keepId;ev.payload.schoolEventId=keep.eventId}}for(const p of S.pendingDecisions||[])if(p.payload?.contestId===dropId)p.payload.contestId=keepId;return normalizeSchoolEvent4D1(keep,{schoolId:keep.schoolId})}
function transitionSchoolEvent4D1(idOrEvent,to,{reason='',syncLegacy=true}={}){const c=typeof idOrEvent==='object'?idOrEvent:schoolEventById4D1(idOrEvent);if(!c||!SCHOOL_EVENT_LIFECYCLE_4D1.includes(to))return {ok:false,reason:'event-or-state-invalid'};normalizeSchoolEvent4D1(c);const from=c.lifecycleState;if(from===to)return {ok:true,event:c,unchanged:true};if(!canTransitionSchoolEvent4D1(from,to))return {ok:false,reason:'invalid-transition',from,to};c.lifecycleHistory.push({from,to,dateISO:currentDate(),minute:currentMinute(),reason});if(c.lifecycleHistory.length>30)c.lifecycleHistory.splice(0,c.lifecycleHistory.length-30);c.lifecycleState=to;c.playerStatus=playerStatusFromLifecycle4D1(to);if(syncLegacy)c.status=legacyStatusFromLifecycle4D1(to,c.status);if(SCHOOL_EVENT_TERMINAL_4D1.has(to)&&!c.resolvedAt)c.resolvedAt={dateISO:currentDate(),minute:currentMinute()};return {ok:true,event:c}}
function reconcileSchoolEvents4D1(reason='tick'){
 if(!S.school)return null;S.school.contests=Array.isArray(S.school.contests)?S.school.contests:[];const sid=playerCurrentSchoolId4A2?.()||S.school.currentSchoolId||null,byEvent=new Map(),out=[];
 for(const raw of S.school.contests){const c=normalizeSchoolEvent4D1(raw,{schoolId:sid});if(!c)continue;const prior=byEvent.get(c.eventId);if(prior){mergeDuplicateSchoolEvent4D1(prior,c);continue}byEvent.set(c.eventId,c);out.push(c)}
 S.school.contests=out;
 for(const c of out){const legacy=lifecycleFromLegacy4D1(c.status,c);if(c.lifecycleState!==legacy&&!(c.lifecycleState==='preparing'&&legacy==='registered')){c.lifecycleState=legacy;c.playerStatus=playerStatusFromLifecycle4D1(legacy)}const cal=eventCalendarFor4D1(c);if(cal){cal.payload=cal.payload||{};cal.payload.contestId=c.id;cal.payload.schoolEventId=c.eventId;cal.schoolId=c.schoolId;cal.eventCategory=c.category;c.calendarRef=cal.id}else if(c.calendarRef&&!S.calendar.some(e=>e.id===c.calendarRef))c.calendarRef=null}
 return {count:out.length,schoolId:sid,eventIds:out.map(c=>c.eventId)}
}
function migrateSchoolEvents4D1(){if(!S.school)return {count:0,schoolId:null,eventIds:[]};return reconcileSchoolEvents4D1('migrate')}
