
// =====================================================================
// v7.2 PHASE 5a — PEOPLE WITH NAMES, LIVES, GOALS & REPUTATION
// =====================================================================
const NAME_POOLS={
 EN:{order:'given',first:['Olivia','Liam','Emma','Noah','Ava','Oliver','Sophia','Elijah','Isabella','James','Mia','Lucas','Amelia','Mason','Harper','Ethan','Evelyn','Aiden','Abigail','Logan','Ella','Jackson','Chloe','Sebastian','Grace','Mateo','Zoe','Henry','Lily','Owen','Nora','Daniel','Hannah','Samuel','Aria','Caleb','Layla','Isaac','Maya','Julian','Riley','Gabriel','Stella','Leo','Aurora','Ezra','Naomi','Miles','Ruby','Jordan','Priya','Arjun','Fatima','Omar','Sofia','Diego','Aisha','Kenji','Andre','Alexandra','Benjamin','Nathaniel','Katherine','Theodore','Elizabeth','Christopher','Margaret','Jonathan'],last:['Smith','Johnson','Williams','Brown','Jones','Garcia','Miller','Davis','Rodriguez','Martinez','Hernandez','Lopez','Wilson','Anderson','Thomas','Taylor','Moore','Jackson','Martin','Lee','Thompson','White','Harris','Clark','Lewis','Robinson','Walker','Young','Allen','King','Wright','Scott','Torres','Nguyen','Hill','Flores','Green','Adams','Nelson','Baker','Hall','Rivera','Campbell','Mitchell','Carter','Roberts','Patel','Kim','Chen','Okafor','Singh','Murphy','Kowalski','Cohen','Ali','Rossi','Brooks','Reyes','Foster','Hughes']},
 VN:{order:'family',first:['An','Bảo','Châu','Dũng','Đức','Giang','Hà','Hải','Hạnh','Hiếu','Hoa','Hoàng','Hùng','Hương','Khang','Khánh','Khoa','Lan','Linh','Long','Mai','Minh','My','Nam','Ngọc','Nhi','Phong','Phương','Quân','Quang','Quỳnh','Sơn','Tâm','Thảo','Thành','Thu','Trang','Trí','Trung','Tuấn','Tú','Uyên','Việt','Vy','Yến','Anh','Thiện','Kiệt','Nhung','Tiến'],last:['Nguyễn','Trần','Lê','Phạm','Hoàng','Huỳnh','Phan','Vũ','Võ','Đặng','Bùi','Đỗ','Hồ','Ngô','Dương','Lý','Trương','Đinh','Lâm','Mai','Cao','Lưu','Hà','Trịnh','Đoàn','Thái','Châu','Tạ','Quách','Kiều']},
 KR:{order:'family',first:['Minjun','Seoyeon','Jiwoo','Haeun','Doyun','Seojun','Jiho','Yuna','Hayoon','Eunwoo','Siwoo','Jiyu','Chaewon','Minseo','Junho','Yejin','Dahyun','Hyunwoo','Sumin','Taeyang','Jisoo','Yerin','Donghyun','Soojin','Hana','Jaemin','Nayeon','Sungmin'],last:['Kim','Lee','Park','Choi','Jung','Kang','Cho','Yoon','Jang','Lim','Han','Oh','Seo','Shin','Kwon','Hwang','Ahn','Song','Yoo','Hong']},
 JP:{order:'family',first:['Haruto','Yui','Sota','Hina','Ren','Yuna','Minato','Aoi','Riku','Sakura','Yuto','Mei','Kaito','Rin','Hinata','Akari','Sora','Mio','Takumi','Koharu','Daiki','Nanami','Kenta','Emi'],last:['Sato','Suzuki','Takahashi','Tanaka','Watanabe','Ito','Yamamoto','Nakamura','Kobayashi','Kato','Yoshida','Yamada','Sasaki','Yamaguchi','Matsumoto','Inoue','Kimura','Hayashi','Shimizu','Mori']},
 CN:{order:'family',first:['Wei','Jing','Yu','Hao','Xin','Jun','Lei','Mei','Yan','Ming','Ling','Chen','Hui','Jie','Ting','Kai','Yi','Ning','Rui','Xuan','Zhen','Qing','Bo','Lan'],last:['Wang','Li','Zhang','Liu','Chen','Yang','Huang','Zhao','Wu','Zhou','Xu','Sun','Ma','Zhu','Hu','Guo','He','Lin','Luo','Gao','Tan','Lim','Ong','Goh']},
 FR:{order:'given',first:['Louis','Emma','Gabriel','Jade','Raphaël','Louise','Arthur','Alice','Jules','Chloé','Adam','Léa','Hugo','Manon','Lucas','Inès','Nathan','Camille','Léo','Lina','Paul','Zoé','Théo','Juliette','Malik','Yasmine'],last:['Martin','Bernard','Dubois','Thomas','Robert','Richard','Petit','Durand','Leroy','Moreau','Simon','Laurent','Lefebvre','Michel','Garcia','David','Bertrand','Roux','Vincent','Fournier','Morel','Girard','André','Mercier','Blanc','Benali']},
 TH:{order:'given',first:['Somchai','Malee','Niran','Ploy','Anan','Kanya','Chai','Ratana','Kiet','Nong','Arun','Pim','Krit','Fon','Tawan','Mali','Nattapong','Siriporn','Win','Bee'],last:['Saetang','Srisuk','Wongsa','Chaiyaporn','Rattanakorn','Somboon','Thongchai','Kittisak','Phromsri','Boonmee','Jaidee','Suwannarat','Inthavong','Kaewmanee','Prasert','Sukprasert']}
};
const FAMILY_NAMES={EN:{f:['Sarah','Jennifer','Laura','Michelle','Anna','Rachel','Helen','Grace','Maria','Linda'],m:['David','Michael','Robert','Mark','Thomas','Paul','Richard','Peter','Steven','George']},VN:{f:['Lan','Hoa','Mai','Hương','Thu','Hạnh','Ngọc','Phương','Trang','Yến'],m:['Hùng','Dũng','Minh','Tuấn','Quang','Sơn','Hải','Long','Nam','Đức']},KR:{f:['Jiyoung','Sunhee','Mikyung','Eunjung','Hyejin'],m:['Sungho','Jinwoo','Youngsoo','Minho','Dongwook']},JP:{f:['Yuko','Keiko','Naoko','Akiko','Tomoko'],m:['Hiroshi','Takeshi','Kenji','Satoshi','Makoto']},CN:{f:['Mei','Ling','Hui','Yan','Jing'],m:['Wei','Jun','Ming','Hao','Lei']},FR:{f:['Sophie','Nathalie','Isabelle','Claire','Céline'],m:['Nicolas','Julien','Olivier','Laurent','Pierre']},TH:{f:['Malee','Kanya','Ratana','Siriporn','Pim'],m:['Somchai','Anan','Niran','Krit','Arun']}};
function minutesUntil(dateISO,minute){return daysBetween(currentDate(),dateISO)*1440+(minute-currentMinute())}
const NICKNAMES={Alexandra:'Alex',Benjamin:'Ben',Nathaniel:'Nate',Katherine:'Kate',Theodore:'Theo',Elizabeth:'Liz',Christopher:'Chris',Margaret:'Maggie',Jonathan:'Jon',Isabella:'Bella',Abigail:'Abby',Samuel:'Sam',Gabriel:'Gabe',Daniel:'Danny',Sebastian:'Seb',Nattapong:'Nat',Siriporn:'Porn'};
const NPC_TRAITS=['Kind','Funny','Quiet','Competitive','Curious','Ambitious','Shy','Outgoing','Studious','Sporty','Artsy','Generous','Busy','Loyal'];
function poolKey(){const r=calendarProfile().region;return ['VN','KR','JP','CN','FR','TH'].includes(r)?r:r==='SG'?'CN':'EN'}
function nameRegistry(){const set=new Set();for(const p of S.people||[])if(p.fullName)set.add(p.fullName.toLowerCase());for(const n of S.npcs||[])set.add(n.fullName.toLowerCase());if(S.name)set.add(String(S.name).toLowerCase());return set}
function composeName(first,last,key=poolKey()){return NAME_POOLS[key]?.order==='family'?`${last} ${first}`:`${first} ${last}`}
function generateName({surname=null,key=poolKey(),avoid=null}={}){
 const pool=NAME_POOLS[key]||NAME_POOLS.EN,used=avoid||nameRegistry();
 for(let i=0;i<80;i++){const first=rand(pool.first),last=surname||rand(pool.last),full=composeName(first,last,key);if(!used.has(full.toLowerCase())){used.add(full.toLowerCase());return {firstName:first,surname:last,fullName:full,nickname:NICKNAMES[first]||null}}}
 const first=rand(pool.first),last=surname||rand(pool.last),mid=String.fromCharCode(65+Math.floor(Math.random()*26)),full=NAME_POOLS[key]?.order==='family'?`${last} ${mid}. ${first}`:`${first} ${mid}. ${last}`;used.add(full.toLowerCase());return {firstName:first,surname:last,fullName:full,nickname:NICKNAMES[first]||null}
}
function npcGoals(traits,age){const g=[];if(traits.includes('Sporty')||chance(25))g.push('makeTeam');if(traits.includes('Studious')||chance(25))g.push('goodGrades');if(traits.includes('Ambitious')&&age>=10)g.push('classPresident');if(traits.includes('Artsy'))g.push(chance(50)?'musician':'artist');if(traits.includes('Outgoing')||traits.includes('Shy'))g.push('moreFriends');if(age>=15&&chance(35))g.push('university');if(age>=13&&chance(25))g.push('saveMoney');return [...new Set(g)].slice(0,3)}
const GOAL_LABEL={makeTeam:'make a sports team',goodGrades:'get good grades',classPresident:'become class president',musician:'become a musician',artist:'get into art seriously',moreFriends:'make more friends',university:'get into university',saveMoney:'save up for something',partner:'find a partner'};
function generateHousehold({kids=1,childAge=S.age,key=poolKey()}={}){
 const used=nameRegistry(),pool=NAME_POOLS[key]||NAME_POOLS.EN,famSurname=rand(pool.last);
 const style=['VN','KR','CN'].includes(key)?'parentsKeepOwn':chance(70)?'shared':chance(50)?'hyphenated':'separate';
 const motherSurname=style==='shared'?famSurname:rand(pool.last.filter(x=>x!==famSurname));
 const kidSurname=style==='hyphenated'?`${famSurname}-${motherSurname}`:famSurname;
 const hh={id:uid('hh'),surname:famSurname,style,members:[]};S.households=S.households||[];S.households.push(hh);
 const year=parseISO(currentDate()).getUTCFullYear(),out=[];
 for(let i=0;i<kids;i++){const age=Math.max(1,childAge+(i===0?0:rand([-2,-1,1,2,3]))),traits=[rand(NPC_TRAITS),rand(NPC_TRAITS)].filter((v,j,a)=>a.indexOf(v)===j),nm=generateName({surname:kidSurname,key,avoid:used});
  const npc=Object.assign({id:uid('npc'),householdId:hh.id,birthYear:year-age,traits,goals:npcGoals(traits,age),clubDay:1+Math.floor(Math.random()*5),interest:rand(['Football','Basketball','Art Club','Drama','Music','Science Club','Debate','Coding Club','Student Council','Chess Club','Swimming']),reputation:20+Math.floor(Math.random()*40)},nm);S.npcs.push(npc);hh.members.push(npc.id);out.push(npc)}
 hh.parents=[generateName({surname:famSurname,key,avoid:used}),generateName({surname:motherSurname,key,avoid:used})].map(n=>n.fullName);
 return out
}
function npcAge(n){return parseISO(currentDate()).getUTCFullYear()-n.birthYear}
function ensureRoster(){
 S.npcs=Array.isArray(S.npcs)?S.npcs:[];S.households=Array.isArray(S.households)?S.households:[];
 if(S.age<3)return;const peers=S.npcs.filter(n=>Math.abs(npcAge(n)-S.age)<=1);
 let guard=0;while(peers.length<28&&guard++<40){const made=generateHousehold({kids:chance(30)?2:1});peers.push(...made.filter(n=>Math.abs(npcAge(n)-S.age)<=1))}
}
function npcById(id){return (S.npcs||[]).find(n=>n.id===id)||null}
function personFromNpc(npc,role,roleLabel){const p=makePerson(npc.fullName,role,npcAge(npc),S.age);Object.assign(p,{metDate:currentDate(),metVia:roleLabel,metAt:/^met /.test(roleLabel||'')?roleLabel.replace(/^met /,''):undefined,respect:50,npcId:npc.id,firstName:npc.firstName,surname:npc.surname,fullName:npc.fullName,nickname:npc.nickname,name:npc.fullName,roleLabel,traits:npc.traits,goals:npc.goals});return p}
function firstName(p){if(!p)return '';if(p.role==='parent'||p.role==='grandparent')return p.name;return p.nickname||p.firstName||String(p.name||'').split(' • ')[0].split(' ')[0]}
function displayName(p,ctx='casual'){if(!p)return '';if(['parent','grandparent'].includes(p.role))return p.name;if(ctx==='formal')return p.fullName||p.name;return p.rel>=60?(p.nickname||p.firstName||p.name):(p.fullName||p.name)}
function familySurname(){S.familyName=S.familyName||(String(S.name||'').trim().split(/\s+/).length>1?String(S.name).trim().split(/\s+/).pop():rand((NAME_POOLS[poolKey()]||NAME_POOLS.EN).last));return S.familyName}
function migratePeopleNames(){
 const key=poolKey(),used=nameRegistry(),fam=familySurname();
 for(const p of S.people){
  if(p.fullName)continue;
  if(['parent','grandparent','older sibling','younger sibling','sibling','aunt','uncle','relative'].includes(p.role)){const sur=['VN','KR','CN'].includes(key)&&(p.relation||migrateRelations(),['mother','grandmother'].includes(p.relation))?rand((NAME_POOLS[key]||NAME_POOLS.EN).last.filter(x=>x!==fam)):fam;const fem=(p.relation||migrateRelations(),p.gender?p.gender==='Female':['mother','grandmother','aunt'].includes(p.relation)),fn=FAMILY_NAMES[key]||FAMILY_NAMES.EN;let first,full;for(let i=0;i<30;i++){first=rand(fem?fn.f:fn.m);full=composeName(first,sur,key);if(!used.has(full.toLowerCase()))break}used.add(full.toLowerCase());Object.assign(p,{firstName:first,surname:sur,fullName:full,nickname:p.name});continue}
  const parts=String(p.name).split(' • '),given=parts[0].trim(),label=parts[1]||p.role,first=given;let nm,full;for(let i=0;i<40;i++){nm=generateName({key,avoid:new Set()});full=composeName(first,nm.surname,key);if(!used.has(full.toLowerCase()))break}
  used.add(full.toLowerCase());Object.assign(p,{firstName:first,surname:nm.surname,fullName:full,nickname:NICKNAMES[first]||null,roleLabel:label,name:full});
  if(!p.goals)p.goals=npcGoals(p.traits||[],p.age||S.age);
  const npc={id:uid('npc'),firstName:first,surname:nm.surname,fullName:full,nickname:p.nickname,birthYear:parseISO(currentDate()).getUTCFullYear()-(p.age||S.age),traits:p.traits||[],goals:p.goals,clubDay:1+Math.floor(Math.random()*5),interest:rand(['Football','Art Club','Drama','Music','Science Club']),reputation:30};S.npcs.push(npc);p.npcId=npc.id;
  S.flags[`stage-${label.replace(/\s+/g,'')}`]=true
 }
}
function addStagePeople(){
 normalizePeople();S.npcs=Array.isArray(S.npcs)?S.npcs:[];S.households=Array.isArray(S.households)?S.households:[];migratePeopleNames();if(S.people.filter(p=>p.roleLabel==='classmate').length>=2)S.flags['stage-classmate2']=true;ensureRoster();
 const slots=[[3,'neighbor','neighbor'],[6,'classmate','classmate'],[10,'classmate2','classmate'],[13,'schoolfriend','school friend'],[18,'acquaintance','acquaintance']];
 for(const [age,key,label] of slots){if(S.age<age||S.flags[`stage-${key}`])continue;if(key==='classmate2'&&S.flags['stage-classmate']&&S.people.filter(p=>p.roleLabel==='classmate').length>=2){S.flags[`stage-${key}`]=true;continue}
  const taken=new Set(S.people.map(p=>p.npcId).filter(Boolean)),npc=S.npcs.find(n=>!taken.has(n.id)&&Math.abs(npcAge(n)-S.age)<=1)||generateHousehold({kids:1})[0];
  S.people.push(Object.assign(personFromNpc(npc,'friend',label),{metDate:undefined}));S.flags[`stage-${key}`]=true}
}
// ---------- Availability: NPCs have their own day ----------
function dayHash(s){let h=0;for(const c of s)h=(h*31+c.charCodeAt(0))>>>0;return h%100}
function npcStatusAt(p,dateISO=currentDate(),m=currentMinute()){
 if(!p||['parent','grandparent'].includes(p.role))return {free:true};
 const npc=npcById(p.npcId),age=p.age||S.age,wd=weekdayIndex(dateISO),bed=age<10?1260:age<13?1290:age<18?1350:1410;
 if(npc?.vacationUntil&&npc.vacationUntil>=dateISO)return {free:false,why:`${firstName(p)} is away on a family trip until ${formatDate(npc.vacationUntil)}.`};
 if(m>=bed||m<420)return {free:false,why:`It is ${timeLabel(m)} — ${firstName(p)} is asleep or not allowed out this late.`};
 if(age>=6&&age<=18&&isSchoolDay(dateISO)&&m>=SCHOOL_DAY.start&&m<SCHOOL_DAY.end)return {free:false,why:`${firstName(p)} is at school until ${timeLabel(SCHOOL_DAY.end)}.`,atSchool:true};
 if(age>=19&&age<65&&wd<5&&m>=540&&m<1020)return {free:false,why:`${firstName(p)} is at work until 5:00 PM.`};
 if(npc&&age>=6&&age<=18&&isSchoolDay(dateISO)&&wd===npc.clubDay-1&&m>=900&&m<1020){const mins=930-m;return {free:false,why:mins>0?`${firstName(p)} can't hang out right now because ${npc.interest.toLowerCase()} practice starts in ${mins} minutes.`:`${firstName(p)} is at ${npc.interest} until 5:00 PM.`}}
 if(m>=1080&&m<1140&&dayHash(p.id+dateISO)<40)return {free:false,why:`${firstName(p)} is having dinner with family right now.`};
 const goalsTest=(p.goals||npc?.goals||[]).includes('goodGrades');if(goalsTest&&m>=1140&&dayHash(p.id+dateISO+'s')<35)return {free:false,why:`${firstName(p)} is studying tonight — they really want good grades this term.`};
 return {free:true}
}
function availabilityGate(p){const a=npcStatusAt(p);if(a.free)return true;openModal(`${displayName(p)} is busy`,`<p>${esc(a.why)}</p><div class="modal-action-grid"><button data-close-modal="1">Ask later</button><button class="primary" data-plan-open="${p.id}">Schedule something</button>${canUsePhone()?`<button data-person-action="message" data-person-id="${p.id}">Message instead</button>`:''}</div>`);return false}
// ---------- School reputation & identity ----------
const REP_DIMS={academic:'Academic',athletic:'Athletic',creative:'Creative',leadership:'Leadership',social:'Social',kindness:'Kindness',troublemaker:'Troublemaker',club:'Clubs'};
function ensureRep(){if(!S.schoolRep){const avg=S.school?schoolAverage():60;S.schoolRep={academic:clamp(avg-45),athletic:12,creative:12,leadership:8,social:clamp((S.social?.reputation||40)-20),kindness:20,troublemaker:4,club:6}}return S.schoolRep}
function schoolIdentities(){const r=ensureRep(),out=[],has=n=>(S.school?.clubs||[]).some(c=>c.status==='Active'&&c.name===n);
 if(r.athletic>=55)out.push('Star Athlete');if(r.academic>=65)out.push('Academic Competitor');if(r.leadership>=50)out.push('Student Leader');if(r.creative>=50&&has('Drama'))out.push('Theatre Kid');else if(r.creative>=50)out.push('Art Student');if(has('Debate')&&r.leadership+r.academic>=80)out.push('Debate Kid');if(has('Music')&&r.creative>=40)out.push('Musician');if(r.troublemaker>=50)out.push('Known Troublemaker');if(r.kindness>=60)out.push('Kind Classmate');if(r.social>=65)out.push('Popular');return out.slice(0,3)}
function repDailyTick(){const r=ensureRep();for(const k of Object.keys(r)){const base=k==='troublemaker'?4:k==='academic'&&S.school?clamp(schoolAverage()-45):10;r[k]=clamp(r[k]+(base-r[k])*.004)}
 if(!SIM.skipping&&needsFormalSchool()&&chance(6)&&(!S.flags.lastFame||daysBetween(S.flags.lastFame,currentDate())>=14)){const top=Object.entries(r).filter(([k])=>k!=='troublemaker').sort((a,b)=>b[1]-a[1])[0];if(top&&top[1]>=55){S.flags.lastFame=currentDate();const lines={athletic:'A younger student recognizes you from the last game and asks for a high five.',academic:'A classmate asks if you would explain last week\'s lesson — apparently you are "the smart one".',creative:'Your work is displayed near the library. Someone you do not know says it is their favorite.',leadership:'A teacher asks for your opinion on a school decision, like it matters. It does.',social:'People you barely know say hi to you in the hallway now.',kindness:'A younger student thanks you for helping them on their first week. You had forgotten.',club:'Someone asks how to join your club. You are apparently the person to ask.'};log('Recognized at school',lines[top[0]]);S.happiness=clamp(S.happiness+3)}}
}
// ---------- Story threads & outcome history ----------
function thread(kind,key,title,participants=[]){S.threads=S.threads||[];let t=S.threads.find(x=>x.key===key&&!x.resolved);if(!t){t={id:uid('thread'),key,kind,title,participants,startedDate:currentDate(),updatedDate:currentDate(),stage:'Started',resolved:false,log:[]};S.threads.unshift(t);if(S.threads.length>40)S.threads.length=40}return t}
function threadStep(t,stage,note,{resolve=false}={}){if(!t)return;t.stage=stage;t.updatedDate=currentDate();t.log.push({dateISO:currentDate(),stage,note});if(t.log.length>12)t.log.shift();if(resolve){t.resolved=true;t.resolvedDate=currentDate()}}
function recordOutcome(category,title,result,reason,detail=''){S.outcomes=S.outcomes||[];S.outcomes.unshift({id:uid('out'),dateISO:currentDate(),age:S.age,category,title,result,reason,detail});if(S.outcomes.length>80)S.outcomes.length=80}
function threadsHtml(){const t=(S.threads||[]).slice(0,10);return t.length?t.map(x=>`<div class="timeline-entry"><span>${formatDate(x.startedDate)} • ${x.resolved?'Resolved':'Ongoing'}</span><b>${esc(x.title)}</b><p>${esc(x.stage)}${x.log.length?` — ${esc(x.log[x.log.length-1].note)}`:''}</p></div>`).join(''):'<p class="muted-text">Story threads appear when something unfolds over time — a tryout, an election, a plan with a friend.</p>'}
function outcomesHtml(){const o=(S.outcomes||[]).slice(0,12);return o.length?o.map(x=>`<div class="timeline-entry"><span>${formatDate(x.dateISO)} • ${esc(x.category)}</span><b>${esc(x.title)} — ${esc(x.result)}</b><p>${esc(x.reason)}${x.detail?` ${esc(x.detail)}`:''}</p></div>`).join(''):'<p class="muted-text">Important outcomes (tryouts, elections, plans) are recorded here with the reason behind them.</p>'}
function personForMessage(m){if(!m)return null;if(m.fromId)return personById(m.fromId);const f=String(m.from||''),[g,role]=f.split(' • ');const exact=S.people.find(x=>x.name===f||x.fullName===f);if(exact)return exact;const cand=S.people.filter(x=>!isFamilyPerson(x)&&x.firstName===g);return cand.find(x=>role&&x.roleLabel===role)||cand[0]||null}
function replyMessage(id){const m=S.messages.find(x=>x.id===id);if(!m)return;m.read=true;const p=personForMessage(m);if(p){m.fromId=p.id;p.rel=clamp(p.rel+2);p.trust=clamp(p.trust+1);rememberPerson(p,'You replied to a message.')}advanceTime(8);closeChoiceModal();feedback('Replied',`You replied to ${p?displayName(p):m.from}.`,8)}
function socialReconcile(){ensureBirthdays();if(S.dob)S.zodiac=zodiacFromDate(S.dob);for(const m of S.messages||[])if(!m.fromId&&m.from!==S.name){const p=personForMessage(m);if(p){m.fromId=p.id;m.from=displayName(p,'formal')}}if(!S.chatsMigrated){S.chatsMigrated=true;for(const m of (S.messages||[]).slice().reverse())if(m.fromId&&m.from!==S.name){const c=chatOf(m.fromId);c.msgs.push({id:m.id,from:'them',text:m.text,kind:'chitchat',dateISO:m.dateISO||currentDate(),minute:m.minute||600,read:!!m.read,replied:!!m.read})}}S.npcs=Array.isArray(S.npcs)?S.npcs:[];S.households=Array.isArray(S.households)?S.households:[];S.plans=Array.isArray(S.plans)?S.plans:[];S.threads=S.threads||[];S.outcomes=S.outcomes||[];S.family.trust=S.family.trust??60;ensureRep();if(S.people?.length)migratePeopleNames();if(S.age>=3){ensureRoster();ensureNeighborhood()}migrateIdentity();migrateRomance3B1()}
