// =====================================================================
// PHASE 5B.4 — Summer Jobs / Shifts / Pay / Work-School Compatibility
// Upgrades legacy teen summer work in the existing S.programs + Calendar
// architecture. Adult S.career employment remains separate and unchanged.
// =====================================================================
const SUMMER_JOB_SCHEMA_5B4=1;
const SUMMER_JOB_PREFIX_5B4='summer5b4:';
const SUMMER_JOBS_5B4=Object.freeze([
 {id:'summer5b4:cafe',name:'Café Crew',role:'Café Assistant',employer:'Corner Café',location:'Corner Café',category:'Food Service',skill:'business',minAge:16,maxAge:17,pay:52,weeks:8,days:[1,3,5],start:600,end:840,tips:true},
 {id:'summer5b4:retail',name:'Retail Crew',role:'Retail Assistant',employer:'Town Center Shop',location:'Town Center Shop',category:'Retail',skill:'business',minAge:16,maxAge:17,pay:50,weeks:8,days:[2,4,6],start:720,end:960,tips:false},
 {id:'summer5b4:recreation',name:'Recreation Center Crew',role:'Recreation Assistant',employer:'Community Recreation Center',location:'Community Recreation Center',category:'Recreation',skill:'fitness',minAge:16,maxAge:17,pay:58,weeks:8,days:[1,3,5],start:780,end:1020,tips:false},
 {id:'summer5b4:library',name:'Library Summer Crew',role:'Library Assistant',employer:'Community Library',location:'Community Library',category:'Community',skill:'knowledge',minAge:16,maxAge:17,pay:48,weeks:8,days:[2,4],start:600,end:840,tips:false}
]);
function summerJobDefinition5B4(id){const j=SUMMER_JOBS_5B4.find(x=>x.id===id);if(!j)return null;return Object.assign({},j,{templateId:j.id,progId:j.id,job:true,formal:false,kind:'summer_job',scope:'summer',provider:j.employer,format:'shift',cost:0,safety:'low',rep:'work'})}
function summerJobSeason5B4(dateISO=currentDate()){const a=academicInfo(dateISO);return `${a.region}-${a.key}`}
function summerJobProgramId5B4(def,dateISO=currentDate()){return `summer-job:${def.id}:${summerJobSeason5B4(dateISO)}`}
function summerJobOffer5B4(defOrId,{dateISO=currentDate()}={}){
 const def=typeof defOrId==='string'?summerJobDefinition5B4(defOrId):summerJobDefinition5B4(defOrId?.id);if(!def||S.age<def.minAge||S.age>def.maxAge)return null;const w=summerWindow();if(!w.open)return null;const from=addDays(w.from<dateISO?dateISO:w.from,2),dates=datesForWeekdays5B1(def,from,w.to);if(!dates.length)return null;return {programId:summerJobProgramId5B4(def,w.from),jobId:def.id,templateId:def.id,progId:def.id,name:def.name,role:def.role,employer:def.employer,provider:def.employer,location:def.location,category:def.category,skill:def.skill,kind:'summer_job',summerJob5B4:true,job:true,formal:false,scope:'summer',minAge:def.minAge,maxAge:def.maxAge,pay:def.pay,tips:!!def.tips,startDate:dates[0],endDate:dates[dates.length-1],summerEndDate:w.to,startMinute:def.start,endMinute:def.end,days:[...def.days],dates,durationShifts:dates.length}
}
function discoverSummerJobs5B4(){if(S.age<16||S.age>17)return [];return SUMMER_JOBS_5B4.map(d=>summerJobOffer5B4(d)).filter(Boolean)}
function activeSummerJob5B4(){return (S.programs||[]).find(r=>r.summerJob5B4&&['Employed','Active'].includes(r.status))||null}
function summerJobRecord5B4(id){return (S.programs||[]).find(r=>r.summerJob5B4&&(r.id===id||r.programId===id||r.jobId===id||r.progId===id))||null}
function stableWorkplacePerson5B4(rec,kind,index=0){const seed=`${rec.programId}|${kind}|${index}`,firsts=kind==='manager'?['Morgan','Jordan','Taylor','Casey','Avery','Riley']:['Jamie','Alex','Sam','Parker','Quinn','Robin','Drew','Cameron'],name=firsts[hashOf(seed)%firsts.length];return {id:`summer-work:${kind}:${hashOf(seed).toString(36)}`,name,role:kind==='manager'?'Manager':'Coworker',opinion:50}}
function ensureSummerWorkplacePeople5B4(rec){if(!rec)return null;rec.workplacePeople5B4=rec.workplacePeople5B4||{};rec.workplacePeople5B4.manager=Object.assign(stableWorkplacePerson5B4(rec,'manager'),rec.workplacePeople5B4.manager||{});rec.workplacePeople5B4.coworkers=Array.isArray(rec.workplacePeople5B4.coworkers)&&rec.workplacePeople5B4.coworkers.length?rec.workplacePeople5B4.coworkers:[stableWorkplacePerson5B4(rec,'coworker',0),stableWorkplacePerson5B4(rec,'coworker',1)];return rec.workplacePeople5B4}
function normalizeSummerJob5B4(rec){if(!rec)return null;const def=summerJobDefinition5B4(rec.jobId||rec.progId||rec.templateId);if(!def)return rec;rec.schema5B4=SUMMER_JOB_SCHEMA_5B4;rec.summerJob5B4=true;rec.kind='summer_job';rec.formal=false;rec.job=true;rec.jobId=rec.jobId||def.id;rec.progId=rec.progId||def.id;rec.templateId=rec.templateId||def.id;rec.name=rec.name||def.name;rec.role=rec.role||def.role;rec.employer=rec.employer||def.employer;rec.provider=rec.provider||def.employer;rec.location=rec.location||def.location;rec.category=rec.category||def.category;rec.skill=rec.skill||def.skill;rec.pay=Number(rec.pay||def.pay);rec.status=rec.status||'Applied';rec.lifecycle=rec.lifecycle||String(rec.status).toLowerCase();rec.attended=Number(rec.attended||0);rec.missed=Number(rec.missed||0);rec.late=Number(rec.late||0);rec.performance=Number.isFinite(Number(rec.performance))?Number(rec.performance):55;rec.paidShiftIds=Array.isArray(rec.paidShiftIds)?rec.paidShiftIds:[];rec.shiftAttendance5B4=rec.shiftAttendance5B4&&typeof rec.shiftAttendance5B4==='object'?rec.shiftAttendance5B4:{};rec.calendarIds=Array.isArray(rec.calendarIds)?rec.calendarIds:[];ensureSummerWorkplacePeople5B4(rec);return rec}
function summerJobApplicationScore5B4(offer){const skill=Number(S.skills?.[offer.skill]||0),resp=Number(S.family?.responsibility||50),school=S.school?schoolAverage():70,att=Number(S.school?.attendance??95),variance=(hashOf(`${offer.programId}|${S.name}|application`)%1700)/100-8;return Math.round(clamp(44+skill*.12+(resp-50)*.12+(school-65)*.08+(att-85)*.08+variance,0,100)*10)/10}
function summerJobApplicationGate5B4(offer){if(!offer)return {ok:false,reason:'That summer job is unavailable.'};if(S.age<16)return {ok:false,reason:'Standard summer jobs unlock at age 16.',underage:true};if(S.age>17)return {ok:false,reason:'This teen summer-job program is for ages 16–17.'};const active=activeSummerJob5B4();if(active&&active.programId!==offer.programId)return {ok:false,reason:`You already have a summer job at ${active.employer}.`,existing:active};const old=summerJobRecord5B4(offer.programId);if(old&&['Employed','Active','Completed','Ended','Fired','Rejected'].includes(old.status))return {ok:false,reason:`This application is already ${old.status.toLowerCase()}.`,existing:old};const conflicts=programScheduleConflicts5B1({dates:offer.dates,startMinute:offer.startMinute,endMinute:offer.endMinute});if(conflicts.length)return {ok:false,reason:`Schedule conflict with ${conflicts[0].title} on ${formatDate(conflicts[0].dateISO)}.`,conflicts};return {ok:true}}
function scheduleSummerJobShifts5B4(rec,offer){rec.calendarIds=[];offer.dates.forEach((dateISO,i)=>{const id=`job:${offer.programId}:shift:${String(i+1).padStart(2,'0')}`,ev=createCalendarEvent({id,type:'program',title:`Shift • ${offer.role}`,dateISO,startMinute:offer.startMinute,endMinute:offer.endMinute,graceMinute:Math.min(1439,offer.startMinute+20),location:offer.location,payload:{recId:rec.id,programId:rec.programId,summerJob5B4:true,jobId:rec.jobId,shiftIndex:i,last:i===offer.dates.length-1},required:true,source:'summerWork5B4'});rec.calendarIds.push(ev.id)});return rec.calendarIds}
function applySummerJob5B4(offer,{forceOutcome=null}={}){
 const gate=summerJobApplicationGate5B4(offer);if(!gate.ok){toast(gate.reason);return gate.existing||null}const score=summerJobApplicationScore5B4(offer),accepted=forceOutcome==='accept'?true:forceOutcome==='reject'?false:score>=45,rec={id:`employment:${offer.programId}`,programId:offer.programId,jobId:offer.jobId,progId:offer.jobId,templateId:offer.jobId,name:offer.name,role:offer.role,employer:offer.employer,provider:offer.employer,location:offer.location,category:offer.category,skill:offer.skill,pay:offer.pay,status:accepted?'Employed':'Rejected',lifecycle:accepted?'employed':'rejected',summerJob5B4:true,kind:'summer_job',formal:false,job:true,scope:'summer',applicationDate:currentDate(),applicationScore:score,startDate:offer.startDate,endDate:offer.endDate,summerEndDate:offer.summerEndDate,start:offer.startDate,end:offer.endDate,total:offer.dates.length,attended:0,missed:0,late:0,performance:55,paidShiftIds:[],shiftAttendance5B4:{},calendarIds:[],schedule:{days:[...offer.days],startMinute:offer.startMinute,endMinute:offer.endMinute,startDate:offer.startDate,endDate:offer.endDate}};S.programs=S.programs||[];S.programs.unshift(rec);normalizeSummerJob5B4(rec);if(accepted){scheduleSummerJobShifts5B4(rec,offer);log(`Hired: ${offer.role}`,`${offer.employer} • ${money(offer.pay)} per completed shift • ${offer.dates.length} scheduled shifts.`,true)}else log(`Application: ${offer.role}`,`${offer.employer} chose another applicant this time.`);return rec
}
function summerJobShiftRecord5B4(rec,ev){rec.shiftAttendance5B4=rec.shiftAttendance5B4||{};return rec.shiftAttendance5B4[ev.id]||(rec.shiftAttendance5B4[ev.id]={eventId:ev.id,dateISO:ev.dateISO,status:'scheduled',pay:0,tip:0})}
function summerJobTip5B4(rec,ev){const def=summerJobDefinition5B4(rec.jobId);if(!def?.tips)return 0;const n=hashOf(`${rec.programId}|${ev.id}|tip`)%4;if(n!==0)return 0;return 2+(hashOf(`${ev.id}|tip-amount`)%5)}
function paySummerJobShift5B4(rec,ev,{late=false}={}){if(rec.paidShiftIds.includes(ev.id))return 0;const base=Math.round(rec.pay*(late?.9:1)),tip=late?0:summerJobTip5B4(rec,ev),total=base+tip;S.money+=total;S.finance.earned=(S.finance.earned||0)+total;rec.paidShiftIds.push(ev.id);const sr=summerJobShiftRecord5B4(rec,ev);sr.pay=base;sr.tip=tip;sr.totalPay=total;return total}
function attendSummerJobShift5B4(evId,{simulated=false}={}){
 const ev=(S.calendar||[]).find(e=>e.id===evId);if(!ev||isTerminal(ev.status))return null;const rec=programRec(ev);if(!rec?.summerJob5B4)return null;normalizeSummerJob5B4(rec);if(!['Employed','Active'].includes(rec.status))return null;if(!simulated){if(ev.dateISO!==currentDate()){toast(`That shift is on ${formatDate(ev.dateISO)}.`);return null}if(currentMinute()>ev.graceMinute){missSummerJobShift5B4(ev,'Arrived after the shift grace period');return null}if(currentMinute()<ev.startMinute)advanceTime(ev.startMinute-currentMinute(),{silent:true})}
 const late=!simulated&&currentMinute()>ev.startMinute,sr=summerJobShiftRecord5B4(rec,ev);sr.status=late?'late':'attended';sr.recordedDate=currentDate();sr.recordedMinute=currentMinute();rec.status='Active';rec.lifecycle='active';rec.attended++;if(late)rec.late++;rec.performance=clamp(rec.performance+(late?-1:2));const ppl=ensureSummerWorkplacePeople5B4(rec);ppl.manager.opinion=clamp(ppl.manager.opinion+(late?-2:2));for(const c of ppl.coworkers)c.opinion=clamp(c.opinion+1);setCalendarStatus(ev,'Attended',late?'Late but completed shift':'Completed shift');ev.attendanceStatus=late?'Late':'Present';const paid=paySummerJobShift5B4(rec,ev,{late});practiceSkill(rec.skill,late?.65:.9);recordTraitEvidence('Responsible',{source:'summer job shift',system:'summer work',eventId:ev.id,context:rec.role,quality:late?1:2});if(!simulated){const remain=Math.max(0,ev.endMinute-currentMinute());if(remain)advanceTime(remain,{silent:true});S.energy=clamp(S.energy-(late?14:18));S.stress=clamp(S.stress+(late?5:3));log(late?`Late shift • ${rec.role}`:`Shift • ${rec.role}`,`${paid?`Earned ${money(paid)}. `:''}${late?'Your manager notes the late arrival.':'A completed shift and another little bit of work experience.'}`)}if(ev.payload?.last)completeSummerJob5B4(rec,'Summer schedule completed');return rec
}
function missSummerJobShift5B4(ev,reason='Missed shift'){const rec=programRec(ev);if(!rec?.summerJob5B4)return null;normalizeSummerJob5B4(rec);const sr=summerJobShiftRecord5B4(rec,ev);if(sr.status!=='scheduled')return rec;sr.status='missed';sr.reason=reason;sr.recordedDate=currentDate();rec.missed++;rec.performance=clamp(rec.performance-8);const ppl=ensureSummerWorkplacePeople5B4(rec);ppl.manager.opinion=clamp(ppl.manager.opinion-6);setCalendarStatus(ev,'Missed',reason);if(rec.missed>=3||rec.performance<15){rec.status='Fired';rec.lifecycle='fired';rec.endedDate=currentDate();rec.endReason=rec.missed>=3?'Repeated missed shifts':'Performance fell too low';for(const e of programCalendarEvents5B1(rec))if(!isTerminal(e.status))setCalendarStatus(e,'Cancelled','Employment ended');recordOutcome('Summer job',`${rec.role} at ${rec.employer}`,'Fired',rec.endReason);if(!SIM.skipping)log(`Job ended: ${rec.role}`,rec.endReason,true)}return rec}
function completeSummerJob5B4(rec,reason='Summer ended'){rec=summerJobRecord5B4(rec?.id||rec?.programId||rec);if(!rec||['Completed','Ended','Fired'].includes(rec.status))return rec;rec.status='Completed';rec.lifecycle='completed';rec.endedDate=currentDate();rec.endReason=reason;for(const e of programCalendarEvents5B1(rec))if(!isTerminal(e.status))setCalendarStatus(e,'Cancelled',reason);recordOutcome('Summer job',`${rec.role} at ${rec.employer}`,'Completed',`${rec.attended} shifts completed • ${rec.missed} missed.`);return rec}
function summerJobsDaily5B4(){for(const rec of (S.programs||[]).filter(r=>r.summerJob5B4&&['Employed','Active'].includes(r.status))){normalizeSummerJob5B4(rec);if(rec.summerEndDate&&currentDate()>rec.summerEndDate)completeSummerJob5B4(rec,'School return ended the summer schedule');else if(needsFormalSchool()&&isSchoolDay(currentDate())&&schoolBreakState5B1().kind!=='summer'&&rec.endDate&&currentDate()>rec.endDate)completeSummerJob5B4(rec,'School term resumed')}}
function summerJobSummary5B4(rec){normalizeSummerJob5B4(rec);const ppl=ensureSummerWorkplacePeople5B4(rec),earned=(Object.values(rec.shiftAttendance5B4||{}).reduce((n,x)=>n+Number(x.totalPay||0),0));return {status:rec.status,role:rec.role,employer:rec.employer,manager:ppl.manager.name,coworkers:ppl.coworkers.map(x=>x.name),attended:rec.attended,late:rec.late,missed:rec.missed,performance:Math.round(rec.performance),earned}}
function summerJobsHtml5B4(){const offers=discoverSummerJobs5B4(),active=(S.programs||[]).filter(r=>r.summerJob5B4&&!['Rejected'].includes(r.status));if(S.age<16)return `<h4>Summer jobs</h4><p class="muted-text">Standard paid summer employment starts at age 16. Younger side hustles remain separate.</p>`;return `<h4>Summer jobs</h4>${active.map(r=>{const q=summerJobSummary5B4(r);return `<div class="calendar-row"><div><b>${esc(q.role)} • ${esc(q.employer)}</b><small>${esc(q.status)} • ${money(r.pay)}/shift • Manager ${esc(q.manager)}<br>Shifts ${q.attended} attended • ${q.late} late • ${q.missed} missed • earned ${money(q.earned)} • performance ${q.performance}%</small></div>${statusTag(q.status)}</div>`}).join('')}${offers.length?offers.map(o=>{const g=summerJobApplicationGate5B4(o),old=summerJobRecord5B4(o.programId),state=old?.status||'Available';return `<div class="calendar-row"><div><b>${esc(o.role)}</b><small>${esc(o.employer)} • ${esc(o.category)} • ${money(o.pay)}/completed shift<br>${formatDate(o.startDate)}–${formatDate(o.endDate)} • ${timeLabel(o.startMinute)}–${timeLabel(o.endMinute)} • ${o.durationShifts} shifts</small></div><div class="inline-actions">${statusTag(!g.ok?g.reason:state)}<button class="small primary" data-summer-job5b4="${esc(o.jobId)}" ${g.ok?'':'disabled'}>Apply</button></div></div>`}).join(''):'<p class="muted-text">No summer job currently fits your age, summer dates and schedule.</p>'}`}
function summerJobClick5B4(b){const id=b?.dataset?.summerJob5b4;if(!id)return false;const offer=summerJobOffer5B4(id);if(offer)applySummerJob5B4(offer);save();render();return true}
function migratePrograms5B4(){for(const rec of S.programs||[]){if(rec.summerJob5B4||String(rec.progId||rec.templateId||'').startsWith(SUMMER_JOB_PREFIX_5B4))normalizeSummerJob5B4(rec);else if(['babysit','lawn','cafe','lifeguard'].includes(rec.progId||rec.templateId)){rec.legacySummerJob5B4=true;rec.schema5B4=SUMMER_JOB_SCHEMA_5B4}}return S.programs}
