
// ---------- v7.2 UI: hero, upcoming, panels ----------
function upcomingEvents(limit=7,{includeRoutine=false}={}){
 const today=currentDate(),now=nowStamp(),arr=[];
 arr.push({id:'birthday',title:`${S.name}'s birthday`,dateISO:nextBirthday(),type:'birthday',icon:'🎂'});
 for(const p of (S.people||[]).filter(p=>p.bday&&careAboutBirthday(p)&&!p.movedAway)){let d=`${today.slice(0,4)}-${p.bday}`;if(d<today)d=`${Number(today.slice(0,4))+1}-${p.bday}`;if(daysBetween(today,d)<=21)arr.push({id:'pbday-'+p.id,title:`${displayName(p)}'s birthday`,dateISO:d,type:'birthday',icon:'🎂'})}
 for(const x of upcomingHolidays(4))arr.push({id:'hol-'+x.h.id,title:x.h.name,dateISO:x.dateISO,type:'holiday',icon:x.h.icon});
 for(const mk of academicMarkers().filter(x=>x.dateISO>=today).slice(0,40).sort((a,b)=>a.dateISO.localeCompare(b.dateISO)).slice(0,4))arr.push(mk);
 for(const e of S.calendar){if(isTerminal(e.status))continue;if(!includeRoutine&&e.type==='schoolDay')continue;if(e.dateISO<today)continue;if(e.dateISO===today&&stamp(e.dateISO,e.graceMinute??e.minute??0)<now)continue;arr.push(e)}
 if(needsFormalSchool())for(const s of S.school.subjects){const hw=s.homework;if(hw&&HW_OPEN.includes(hw.status)&&hw.dueDate>=today)arr.push({id:hw.id,title:`${s.name} homework`,dateISO:hw.dueDate,minute:480,type:'homework',status:homeworkLabel(hw)})}
 for(const p of S.pendingDecisions.filter(x=>!x.resolved&&x.resolveDate&&x.resolveDate>=today))arr.push({id:p.id,title:p.title,dateISO:p.resolveDate,type:'decision'});
 return arr.sort((a,b)=>a.dateISO.localeCompare(b.dateISO)||(a.minute||0)-(b.minute||0)).slice(0,limit)
}
function typeIcon(t){return ({workDay:'💼',wedding:'💒',program:'☀️',trip:'🧳',conference:'👪',prom:'💃',tryout:'🏅',plan:'🤝',election:'🗳️',decision:'⏳',birthday:'🎂',exam:'📝',homework:'📒',holiday:'🎉',schoolDay:'🏫',clubSession:'🎨',schoolEvent:'🏆',party:'🎉'})[t]||'🗓️'}
function renderUpcomingCompact(){const host=$('upcoming-strip');if(!host)return;const list=upcomingEvents(6);host.innerHTML=list.length?list.map(e=>{const d=daysBetween(currentDate(),e.dateISO),now=e.status==='Due';return `<div class="upcoming-chip ${now?'is-now':d===0?'is-today':''}"><span>${e.icon||typeIcon(e.type)}</span><b>${esc(e.title)}</b><small>${now?'Now':d===0?(e.minute!=null&&e.type!=='homework'?timeLabel(e.minute):'Today'):d===1?'Tomorrow':d+'d'}</small></div>`}).join(''):'<span class="muted-text">No upcoming deadlines.</span>'}
function meter(label,value,inverse=false){const v=Math.round(clamp(value)),good=inverse?v<=35:v>=65,bad=inverse?v>=65:v<=35;return `<div class="hero-stat ${good?'good':bad?'bad':''}"><span>${esc(label)}</span><b>${v}%</b><i><em style="width:${v}%"></em></i></div>`}
function heroParts(c){
 const agenda=()=>{const a=todayAgenda().filter(x=>x.type!=='birthday').slice(0,4);return a.length?`<div class="hero-agenda">${a.map(x=>`<div class="${x.done?'done':''}"><span>${x.icon}</span><b>${esc(x.title)}</b><small>${x.done?esc(x.status):x.type==='homework'?esc(x.status):timeLabel(x.minute)}</small></div>`).join('')}</div>`:''};
 if(c.sourceType==='exam'){const e=S.exams.find(x=>x.id===c.sourceId),sub=examSubject(e);if(!e)return {detail:'',actions:''};
  const phase=currentMinute()<e.minute?`Today • ${timeLabel(e.minute)}`:currentMinute()<=e.endMinute?'In progress now':`Late sitting until ${timeLabel(e.graceMinute)}`;
  return {detail:`<div class="hero-when urgent">${phase}</div><div class="hero-stats">${meter('Preparation',sub?.prep||0)}${meter('Skill',sub?.skill||0)}${meter('Sleep',S.needs.sleep)}${meter('Stress',S.stress,true)}</div>`,actions:`<button class="primary" data-exam-take="${e.id}">Take Assessment</button>${e.minute<SCHOOL_DAY.end&&schoolDayEvent()&&!isTerminal(schoolDayEvent().status)?'<small class="muted-text">Includes going to school for the day.</small>':''}`}}
 if(c.sourceType==='event'){const e=S.events.find(x=>x.id===c.sourceId);if(!e)return {detail:'',actions:''};const by=e.expiresAt?`Respond by ${e.expiresAt.dateISO===currentDate()?'':formatDate(e.expiresAt.dateISO)+' '}${timeLabel(e.expiresAt.minute)}`:'';return {detail:inviteMeta(e)?inviteMetaHtml(e):by?`<div class="hero-when">${by}</div>`:'',actions:e.choices.map(ch=>`<button data-event-id="${e.id}" data-event-choice="${esc(ch.id)}">${esc(ch.label)}</button>`).join('')}}
 if(c.sourceType==='calendar'){const ev=S.calendar.find(x=>x.id===c.sourceId);if(!ev)return {detail:'',actions:''};
  if(ev.type==='clubSession'){const cl=clubById(ev.payload?.clubId);return {detail:`<div class="hero-when">${currentMinute()<ev.startMinute?`Starts ${timeLabel(ev.startMinute)}`:`Started ${timeLabel(ev.startMinute)} • arrive by ${timeLabel(ev.graceMinute)}`}</div><div class="hero-stats">${meter('Attendance',clubAttendanceRate(cl||{}))}${meter('Club skill',cl?.skill||0)}${meter('Energy',S.energy)}</div>`,actions:`<button class="primary" data-club-attend="${cl?.id}">Attend session</button><button class="ghost" data-club-skip="${cl?.id}">Skip</button>${currentMinute()<ev.startMinute?`<button class="ghost" data-club-excuse="${cl?.id}">Tell ${esc(cl?.leader||'the leader')} you can't come</button>`:''}`}}
  if(ev.type==='tryout'){const t=S.school?.tryouts?.find(x=>x.id===ev.payload?.tryoutId);return {detail:`<div class="hero-when urgent">Check in by ${timeLabel(ev.graceMinute)}</div><div class="hero-stats">${meter('Preparation',t?.prep||0)}${meter('Energy',S.energy)}${meter('Stress',S.stress,true)}</div>`,actions:`<button class="primary" data-tryout-go="${t?.id}">Go to ${esc(clubInfo(t?.club).entry||'tryout')}</button>`}}
  if(ev.type==='workDay')return {detail:`<div class="hero-when">9:00–5:00 • ${esc(ev.location||'')}</div>`,actions:`<button class="primary" data-work="normal">Go to work</button><button class="ghost" data-work="sick">Call in sick</button><button class="ghost" data-work="leave">Take today off</button>`};
  if(ev.type==='program')return {detail:`<div class="hero-when">${timeLabel(ev.startMinute)}–${timeLabel(ev.endMinute)} • ${esc(ev.location||'')}</div>`,actions:`<button class="primary" data-program-go="${ev.id}">Go</button>`};
  if(ev.type==='prom')return {detail:`<div class="hero-when urgent">Doors 7:00 PM • ${esc(ev.location||'')}</div>`,actions:`<button class="primary" data-prom-go="1">Go to prom</button>`};
  if(ev.type==='plan'){const pl=S.plans?.find(x=>x.id===ev.payload?.planId);return {detail:`<div class="hero-when">${timeLabel(ev.startMinute)} • ${esc(ev.location||'')}</div>`,actions:`<button class="primary" data-plan-go="${pl?.id}">Go</button><button class="ghost" data-plan-cancel="${pl?.id}">Cancel (last minute)</button>`}}
  const ct=contestById(ev.payload?.contestId);return {detail:`<div class="hero-when urgent">Check-in ${timeLabel(ev.startMinute)}–${timeLabel(ev.graceMinute)}</div><div class="hero-stats">${meter('Preparation',ct?.prep||0)}${meter('Energy',S.energy)}${meter('Stress',S.stress,true)}</div>`,actions:`<button class="primary" data-contest-attend="${ct?.id}">Go to the event</button>`}}
 if(c.sourceType==='scene')return {detail:'',actions:'<button class="primary" data-scene-resume="1">Continue</button>'};
 if(c.sourceType==='schoolSession'){const p=periodAt(),sd=sessionEvent(),sub=bestPrepSubject()?.name||'';if(p?.kind==='lunch')return {detail:'',actions:`${sd&&!sd.ateLunch?'<button class="primary" data-lunch="eat">Eat in the cafeteria</button>':''}<button data-lunch="friend">Sit with friends</button><button class="ghost" data-lunch="library" data-arg="${esc(sub)}">Library</button><button class="ghost" data-tab-jump="school">More school options</button>`};return {detail:`<div class="hero-stats">${meter('Energy',S.energy)}${meter('Sleep',S.needs.sleep)}${meter('Social',S.needs.social)}</div>`,actions:'<button class="primary" data-class="attend">Pay attention</button><button data-class="participate">Participate</button><button class="ghost" data-class="chat">Chat</button><button class="ghost" data-school-skip="1">Skip to dismissal</button>'}}
 if(c.sourceType==='schoolDay')return {detail:`<div class="hero-when">${timeLabel(SCHOOL_DAY.start)}–${timeLabel(SCHOOL_DAY.end)} • attendance cutoff ${timeLabel(SCHOOL_DAY.cutoff)}</div>${agenda()}`,actions:`<button class="primary" data-act="school">Go to school</button>`};
 if(c.sourceType==='holiday'){const x=holidayWindow().find(w=>w.h.id===c.sourceId),acts=x?availableActivities(x).slice(0,4):[];return {detail:agenda(),actions:acts.map((a,i)=>`<button class="${i?'':'primary'}" data-holiday-act="${x.h.id}:${a.id}">${esc(a.label)}</button>`).join('')+(x?'<button class="ghost" data-tab-jump="home">All holiday options</button>':'')}}
 const evening=currentMinute()>=Math.min(1200,bedtimeMinute()-60)||currentMinute()<300;
 return {detail:agenda(),actions:evening?`<button data-act="sleep">Go to sleep</button>`:''}
}
function renderHero(){clearCurrentContextIfSourceResolved();const c=S.current,{detail,actions}=heroParts(c);$('event-title').textContent=c.title;$('event-text').textContent=c.text||'';const d=$('event-detail');if(d)d.innerHTML=detail;$('event-actions').innerHTML=actions;document.querySelector('.hud-story')?.setAttribute('data-kind',c.sourceType||'daily')}

function statusTag(status){const cls=['Completed','Attended','Submitted','Enrolled','Approved'].includes(status)?'ok':['Missed','No-show','Missing','Absent','Late','Denied','Removed'].includes(status)?'bad':['Due','Due today','Attending','In progress','Make-up scheduled','Submitted late','Excused','Superseded','Expired'].includes(status)?'warn':'';return `<span class="tag ${cls}">${esc(status)}</span>`}
function pendingHtml(){const p=pendingOpen();if(!p.length)return '<p class="muted-text">Nothing is waiting on a future decision.</p>';return p.slice(0,7).map(x=>`<div class="pending-row"><div><b>${esc(x.title)}</b><small>${esc(x.detail||x.status)}${x.resolveDate?` • decision ${formatDate(x.resolveDate)}`:x.autoDecideDate?` • family decides by ${formatDate(x.autoDecideDate)}`:x.expiresDate?` • expires ${formatDate(x.expiresDate)}`:''}</small></div><div class="inline-actions">${statusTag(x.status)}${['purchaseConsideration','conditionalPurchase'].includes(x.type)?`<button class="small ghost" data-pending-again="${x.id}">Ask again</button>`:''}${x.type==='kindergarten'&&x.status==='Waiting for your preference'?'<button class="small" data-act="kindergartenYes">I want to go</button><button class="small ghost" data-act="kindergartenNo">I don\'t want to</button>':''}</div></div>`).join('')}
function eventHtml(){const shown=S.current?.sourceType==='event'?S.current.sourceId:null,list=S.events.filter(x=>x.status==='Open'&&x.id!==shown&&!eventExpired(x));if(!list.length)return `<p class="muted-text">${shown?'The current moment is shown at the top of the page.':'No major interruption right now. Ordinary life is still moving.'}</p>`;return list.slice(0,3).map(e=>`<div class="event-card"><div class="event-kicker">WAITING FOR YOU${e.expiresAt?` • RESPOND BY ${esc(timeLabel(e.expiresAt.minute))}${e.expiresAt.dateISO!==currentDate()?' '+esc(formatDate(e.expiresAt.dateISO)):''}`:''}</div><h3>${esc(e.title)}</h3>${inviteMetaHtml(e)}<p>${esc(e.text)}</p><div class="event-actions">${e.choices.map(c=>`<button data-event-id="${e.id}" data-event-choice="${esc(c.id)}">${esc(c.label)}</button>`).join('')}</div></div>`).join('')}
function notificationsHtml(){const n=activeNotifications().slice(0,6);if(!n.length)return '<p class="muted-text">No active notifications.</p>';return n.map(x=>`<button class="note-row ${x.status==='Unread'?'unread':''}" data-note-open="${x.id}"><b>${esc(x.title)}</b><small>${esc(x.text)} • ${formatDate(x.dateISO)}</small></button>`).join('')+`<div class="inline-actions"><button class="small ghost" data-notes-read="1">Mark all read</button></div>`}
function agendaHtml(){const a=todayAgenda();if(!a.length)return '<p class="muted-text">Nothing scheduled today.</p>';return a.map(x=>`<div class="agenda-row ${x.done?'done':''}"><span>${x.icon}</span><b>${esc(x.title)}</b><small>${x.type==='homework'||x.type==='birthday'?esc(x.status||''):timeLabel(x.minute)}</small>${x.type!=='homework'&&x.type!=='birthday'&&x.status?statusTag(x.status):''}</div>`).join('')}
function homePanel(){const q=quickContextActions(),gift=S.giftHistory.find(x=>!x.reaction);return `<div class="dashboard home-dashboard"><section class="card wide"><div class="section-heading"><div><h3>What needs your attention?</h3><p class="muted-text">The game surfaces context instead of making you hunt through menus.</p></div><span class="tag">${esc(S.emotion.current)}</span></div><div class="context-grid">${q.map(x=>`<button class="context-action" data-tab-jump="${x[0]}"><b>${x[1]}</b><small>${x[2]}</small></button>`).join('')}</div></section><section class="card"><h3>Today • ${esc(weekday())}</h3>${agendaHtml()}${isGrounded()?`<p class="urgent-text">Grounded until ${formatDate(S.family.restrictions.groundedUntil)}.</p>`:''}</section><section class="card"><h3>Mood</h3>${moodHtml()}</section><section class="card"><h3>Notifications</h3>${notificationsHtml()}</section>${promHtml()?`<section class="card wide"><h3>Prom</h3>${promHtml()}</section>`:''}${holidayWindow().length?`<section class="card wide"><h3>Holidays</h3>${holidayHtml()}</section>`:''}<section class="card wide"><h3>What's happening?</h3>${eventHtml()}</section><section class="card"><h3>Right now</h3>${statRow('Location',esc(S.location))}${statRow('Weather',`${weatherIcon(S.weather.type)} ${esc(S.weather.type)} • ${S.weather.temp}°C`)}${statRow('Emotion',esc(S.emotion.current))}<p class="muted-text">${esc(S.emotion.reason||weatherAdvice())}</p></section><section class="card"><h3>Pending decisions</h3>${pendingHtml()}</section>${gift?`<section class="card wide"><h3>🎁 A gift reaction is still yours to choose</h3><p>You received <b>${esc(gift.item)}</b> for ${esc(gift.occasion)}. Your private feeling and outward behavior do not have to match.</p><div class="inline-actions"><button data-act="giftThank">Say thank you</button><button data-act="giftExcited">Act excited</button><button data-act="giftHide">Hide disappointment</button><button data-act="giftHug">Hug giver</button><button class="ghost" data-act="giftComplain">Complain</button></div></section>`:''}</div>`}
function quickContextActions(){const a=[];const exam=nextExam();if(exam){const d=daysBetween(currentDate(),exam.dateISO);if(d<=3)a.push(['school','📝 '+exam.subject,d<=0?`Assessment today • ${timeLabel(exam.minute)}`:`Assessment in ${d} day${d===1?'':'s'} • prep ${Math.round(examSubject(exam)?.prep||0)}%`])}const sd=schoolDayEvent();if(sd&&!isTerminal(sd.status)&&currentMinute()<=SCHOOL_DAY.cutoff)a.push(['school','🏫 School today',schoolDayStatus()]);if(needsFormalSchool()){const hw=S.school.subjects.find(s=>s.homework?.status==='Late'||(s.homework?.status==='Assigned'&&daysBetween(currentDate(),s.homework.dueDate)<=1));if(hw)a.push(['school','📒 '+hw.name+' homework',homeworkLabel(hw.homework)])}if(S.needs.hunger>=60)a.push(['places','🍽️ Eat',S.age<=1?'Signal caregiver / be fed':'Take care of hunger']);if(S.needs.toilet>=65)a.push(['places','🚽 Bathroom',S.age<=4?'Age-appropriate toileting help':'Relieve yourself']);if(S.needs.sleep<=35||S.energy<=30)a.push(['places','😴 Sleep','You are running low on rest']);if(unreadMessages())a.push(['phone','💬 Messages',`${unreadMessages()} unread`]);if(pendingOpen().length)a.push(['calendar','⏳ Pending decision',`${pendingOpen().length} unresolved`]);if(!a.length)a.push(['places','🧭 Choose an activity','Your immediate needs are stable'],['people','👥 See someone','Relationships keep moving']);return a.slice(0,6)}
function developmentPanel(){const k=S.development.kindergarten,p=S.pendingDecisions.find(x=>!x.resolved&&x.type==='kindergarten');return `<div class="dashboard"><section class="card"><h3>Development & autonomy</h3><p class="stage-note"><b>${lifeStage()}</b> • skills grow through actual care routines.</p>${Object.entries(S.development.skills).map(([key,v])=>`<div class="skill-line"><span>${esc(key.replace(/([A-Z])/g,' $1'))}</span><div class="progress"><i style="width:${clamp(v)}%"></i></div><b>${Math.round(v)}%</b></div>`).join('')}</section><section class="card"><h3>Early education</h3>${statRow('Kindergarten',esc(k.decision||(p?p.status:'Not decided')))}${p&&p.status==='Waiting for your preference'?`<p>Your family is discussing kindergarten. Your preference matters, but caregivers still make the final decision${p.autoDecideDate?` — by ${formatDate(p.autoDecideDate)} at the latest`:''}.</p><div class="inline-actions"><button data-act="kindergartenYes">I want to go</button><button class="ghost" data-act="kindergartenNo">I don't want to go</button></div>`:p?`<p class="muted-text">${esc(p.detail)}</p>`:''}<h4>Milestones</h4>${S.development.milestones.slice(0,6).map(x=>`<p>${esc(x)}</p>`).join('')||'<p class="muted-text">Milestones appear as skills develop.</p>'}</section></div>`}
function examStatusLabel(e){const d=daysBetween(currentDate(),e.dateISO);if(e.status==='Completed')return `${e.score}%`;if(e.status==='Replaced by make-up')return 'Replaced';if(e.status==='Make-up scheduled'){const mk=S.exams.find(x=>x.id===e.makeupId);return mk?`Make-up ${formatDate(mk.dateISO)}`:'Make-up'}if(!examIsOpen(e))return e.status;return d===0?`TODAY ${timeLabel(e.minute)}`:`${d} day${d===1?'':'s'}`}
function schoolPanel(){
 if(!S.school)return `<div class="dashboard"><section class="card wide"><h3>No school right now</h3><p class="muted-text">Education appears when it is part of your current stage or family decision.</p></section></div>`;normalizeSchool();
 if(S.school.grade==='Kindergarten')return `<div class="dashboard"><section class="card"><h3>${esc(S.school.name)}</h3>${typeof playerSchoolIdentityRows4A2==='function'?playerSchoolIdentityRows4A2():''}${statRow('Group',esc(S.school.className))}${statRow('Attendance',Math.round(S.school.attendance)+'%')}${statRow('Today',esc(schoolDayStatus()))}${actionButton('school','🎒 Go to kindergarten','Weekdays 8:00 AM–3:00 PM')}<p class="muted-text">Kindergarten is play-based. No GPA, rank, formal exams or competitive club system.</p></section><section class="card wide"><h3>Learning through play</h3><div class="action-grid">${S.school.subjects.map(s=>`<button class="action" data-early-learn="${esc(s.name)}"><strong>${esc(s.name)}</strong><small>Development ${Math.round(s.score)}% • stories, games and guided activity</small></button>`).join('')}</div></section></div>`;
 const primary=S.age<=11,rec=ensureSchoolRecord(),offers=(S.school.activityOffers||[]).filter(o=>['Offered','Waiting','Denied','Waitlisted'].includes(o.status)).slice(0,6),clubs=(S.school.clubs||[]).filter(c=>c.status==='Active'),removed=(S.school.clubs||[]).filter(c=>c.status==='Removed'),events=(S.school.contests||[]).filter(c=>!['Declined'].includes(c.status)).slice(0,8);
 const sd=schoolDayEvent(),sdOpen=sd&&!isTerminal(sd.status)&&currentMinute()<=SCHOOL_DAY.cutoff;
 const subjectHtml=S.school.subjects.map(s=>{const t=ensureTeacher(s),exam=S.exams.filter(e=>e.subject===s.name&&examIsOpen(e)).sort((a,b)=>a.dateISO.localeCompare(b.dateISO))[0],due=exam?daysBetween(currentDate(),exam.dateISO):null,live=exam&&due===0&&currentMinute()<=exam.graceMinute,hw=s.homework||{},hwOpen=HW_OPEN.includes(hw.status);
  return `<div class="subject-card ${live?'is-due':''}"><div class="subject-head"><div class="subject-title"><b class="subject-name">${boostedKeys().has('subject:'+s.name)?'<em class="star" title="Boosted by your talent or personality">★</em> ':''}${esc(s.name)}</b><span class="subject-teacher">${esc(t.name)} · Relationship ${Math.round(t.rel)}%</span></div><div class="subject-grade"><small>Grade</small><strong>${(Math.round(s.score*10)/10).toFixed(1)}</strong></div></div><div class="progress"><i style="width:${clamp(s.score)}%"></i></div><div class="mini-meta"><span>Skill ${Math.round(s.skill)}%</span><span>Prep ${Math.round(s.prep)}%</span>${hw.status&&hw.status!=='None'?`<span class="${['Late','Missing'].includes(hw.status)||homeworkLabel(hw)==='Due today'?'urgent-text':''}">Homework: ${esc(homeworkLabel(hw))}${hwOpen?` ${hw.progress||0}%`:''}</span>`:''}${exam&&!live?`<span class="${due<=3?'urgent-text':''}">${esc(exam.type)} ${due===0?'today':`in ${due}d`}</span>`:''}</div>${live?`<div class="assessment-callout"><div><b>ASSESSMENT TODAY • ${timeLabel(exam.minute)}</b><small>${currentMinute()>exam.endMinute?`Late sitting until ${timeLabel(exam.graceMinute)}`:esc(exam.type)}</small></div><button class="primary small" data-exam-take="${exam.id}">Take Assessment</button></div>`:''}<div class="subject-actions"><details class="study-menu"><summary class="${live?'ghost':''}">Study ▾ <small>${farmLeft('study:'+s.name)}/3 left</small></summary><div><button class="small" data-study="${esc(s.name)}" data-minutes="30">30 min</button><button class="small" data-study="${esc(s.name)}" data-minutes="60">1 hour</button><button class="small" data-study="${esc(s.name)}" data-minutes="180">3 hours</button></div></details><button class="small ghost" data-study-friend="${esc(s.name)}">Study with friend</button><button class="small ghost" data-study-teacher="${esc(s.name)}">Ask teacher</button><button class="small ghost" data-extra-ex="${esc(s.name)}" ${dayCounts()['extra:'+s.name]?'disabled':''}>Advanced exercises</button>${hwOpen?`<button class="small" data-homework="${esc(s.name)}">Do homework</button>`:''}</div></div>`}).join('');
 const examList=[...S.exams].sort((a,b)=>a.dateISO.localeCompare(b.dateISO)||a.minute-b.minute);
 const examHtml=examList.map(e=>{const d=daysBetween(currentDate(),e.dateISO),can=examIsOpen(e)&&d===0&&currentMinute()<=e.graceMinute;return `<div class="exam-row ${examIsOpen(e)?'':'is-done'}"><div><b>${esc(e.subject)}</b><small>${esc(e.type)} • ${formatDate(e.dateISO)} ${timeLabel(e.minute)}${e.reason&&!examIsOpen(e)?` • ${esc(e.reason)}`:''}</small></div><div class="inline-actions">${examIsOpen(e)?`<span class="countdown">${esc(examStatusLabel(e))}</span>`:statusTag(e.status==='Completed'?`Completed ${e.score}%`:examStatusLabel(e))}${can?`<button class="small primary" data-exam-take="${e.id}">Take assessment</button><button class="small ghost" data-exam-cheat="${e.id}">Attempt cheat</button>`:''}</div></div>`}).join('')||'<p class="muted-text">No assessments scheduled.</p>';
 const offerHtml=offers.length?offers.map(o=>`<div class="opportunity-row"><div><b>${esc(o.name)}</b><small>${o.status==='Offered'?`Decide by ${formatDate(o.decisionDate)}${S.age<13?' • caregiver approval required':''}`:o.status==='Waiting'?'Waiting for caregiver decision':o.status==='Denied'?'Caregiver said no this time':esc(o.status)}</small></div>${offerButtons(o)}</div>`).join(''):'<p class="muted-text">No activity offers waiting.</p>';
 const clubHtml=clubs.length?clubs.map(c=>{ensureClub(c);const def=D.clubDefs[c.name]||{actions:[['practice','Practice',60],['special','Special activity',90],['social','Talk with members',45]]},ev=clubSessionEvent(c),today=ev&&ev.dateISO===currentDate(),open=today&&currentMinute()<=ev.graceMinute,before=ev&&(ev.dateISO>currentDate()||(today&&currentMinute()<ev.startMinute));
  return `<div class="commitment-card club-card"><div><b>${esc(c.name)} <span class="tag">${esc(c.position)}</span>${(()=>{const L=ladderFor(c),i=L.indexOf(c.position);return i>=0&&i<L.length-1?` <small class="muted-text">next: ${esc(L[i+1])}</small>`:''})()}${c.leaderNpc?` <small class="muted-text">• led by ${esc(c.leaderNpc)}</small>`:''}${c.warnings?' <span class="tag bad">Warning</span>':''}</b><small>Led by ${esc(c.leader)} · relationship ${Math.round(c.leaderRel)}% • attendance ${clubAttendanceRate(c)}% (${c.attended} attended, ${c.missedSessions} missed${c.excusedSessions?`, ${c.excusedSessions} excused`:''}) • skill ${Math.round(c.skill||0)}%</small><small>${ev?`Next session ${today?'<b>today</b>':formatDate(ev.dateISO)} ${timeLabel(ev.startMinute)}–${timeLabel(ev.endMinute)}${ev.status==='Due'?' • happening now':''}`:'No session scheduled'}</small><div class="progress"><i style="width:${clamp(c.skill||0)}%"></i></div></div><div class="inline-actions">${open?`<button class="small primary" data-club-attend="${c.id}">Attend session</button><button class="small ghost" data-club-skip="${c.id}">Skip</button>`:''}${before?`<button class="small ghost" data-club-excuse="${c.id}">Tell leader you can't come</button>`:''}${def.actions.map(a=>`<button class="small ghost" data-club-action="${c.id}" data-kind="${a[0]}">${esc(a[1])}</button>`).join('')}<button class="small ghost" data-club-action="${c.id}" data-kind="leave">Leave</button></div></div>`}).join(''):'<p class="muted-text">You have not joined a club yet.</p>';
 const eventHtml=events.length?events.map(c=>{const d=daysBetween(currentDate(),c.eventDate);if(c.status==='Open')return `<div class="opportunity-row"><div><b>${esc(c.name)}</b><small>Register by ${formatDate(c.decisionDate)} • event ${formatDate(c.eventDate)}</small></div><div class="inline-actions"><button class="small" data-contest-enter="${c.id}">${S.age<13?'Ask to enter':'Register'}</button><button class="small ghost" data-contest-decline="${c.id}">Not participating</button></div></div>`;if(c.status==='Waiting')return `<div class="opportunity-row"><div><b>${esc(c.name)}</b><small>Waiting for caregiver approval</small></div>${statusTag('Waiting')}</div>`;if(c.status==='Registered'){const ev=contestEvent(c),live=ev&&ev.dateISO===currentDate()&&currentMinute()<=ev.graceMinute;return `<div class="commitment-card"><div><b>${esc(c.name)}</b><small>${d<=0?`Today • check-in ${timeLabel(ev?.startMinute??600)}–${timeLabel(ev?.graceMinute??690)}`:`Event in ${d} day${d===1?'':'s'} • ${formatDate(c.eventDate)}`} • preparation ${Math.round(c.prep||0)}%</small><div class="progress"><i style="width:${clamp(c.prep||0)}%"></i></div></div><div class="inline-actions">${live?`<button class="small primary" data-contest-attend="${c.id}">Go to the event</button>`:''}<button class="small ghost" data-contest-practice="${c.id}" ${contestPrepSessionsToday(c)>=3||(c.prep||0)>=100?'disabled':''}>Prepare 75m • ${contestPrepSessionsToday(c)}/3 today</button><button class="small ghost" data-contest-withdraw="${c.id}">Withdraw</button></div></div>`}return `<div class="opportunity-row"><div><b>${esc(c.name)}</b><small>${esc(c.result||(c.status==='Upcoming'?`Registration opens ${formatDate(c.openDate)} • event ${formatDate(c.eventDate)}`:c.status==='Declined'?'Not participating':c.status))}</small></div>${statusTag(c.status)}</div>`}).join(''):'<p class="muted-text">No current event opportunities.</p>';
 return `<div class="dashboard"><section class="card wide"><h3>Today at school</h3>${schoolSessionHtml()}${stayHomeHtml()}<p class="muted-text">On time by ${timeLabel(SCHOOL_DAY.tardyAfter)}, absent after ${timeLabel(SCHOOL_DAY.cutoff)}. This year: ${rec.daysAttended} days • ${rec.absences} absent • ${rec.tardies} late${rec.classesSkipped?` • ${rec.classesSkipped} classes skipped`:''}.</p></section><section class="card"><h3>${esc(S.school.name)}</h3>${typeof playerSchoolIdentityRows4A2==='function'?playerSchoolIdentityRows4A2():''}${statRow('Grade',esc(S.school.grade))}${statRow('Semester',esc(semesterLabel()))}${statRow('Class',esc(S.school.className))}${statRow('Academic average',Math.round(schoolAverage())+'%')}${statRow('Attendance',Math.round(S.school.attendance)+'%')}${statRow('Behavior',Math.round(S.school.behavior)+'%')}${!primary&&S.school.gpa!=null?statRow('GPA',Number(S.school.gpa).toFixed(2)):''}</section><section class="card"><h3>School reputation</h3>${repHtml()}</section><section class="card"><h3>Education history</h3>${educationHistoryHtml()}</section><section class="card wide"><h3>Subjects, teachers & homework</h3><div class="subject-grid">${subjectHtml}</div></section><section class="card wide"><h3>Assessments</h3>${examHtml}</section>${attendanceHtml()}<section class="card wide"><div class="section-heading"><div><h3>Clubs & activities</h3><p class="muted-text">Sessions are weekly commitments. Missing them has consequences; telling the leader beforehand is understood.</p></div><button class="small" data-act="exploreClub">Explore activities</button></div>${electionHtml()}${tryoutsHtml()?`<h4>Tryouts & auditions</h4>${tryoutsHtml()}`:''}<h4>Offers</h4>${offerHtml}${electionGradeOK()&&!(S.school.clubs||[]).some(c=>c.name==='Student Council'&&c.status==='Active')&&!(S.elections||[]).some(e=>e.status==='Campaign'&&e.scope==='council')?'<div class="inline-actions"><button class="small ghost" data-run-council="1">Run for class representative</button></div>':''}<h4>Your commitments</h4>${clubHtml}${removed.length?`<p class="muted-text">Removed: ${removed.map(c=>esc(c.name)).join(', ')}</p>`:''}</section><section class="card wide"><div class="section-heading"><div><h3>Competitions & school events</h3><p class="muted-text">Registering is not enough — you have to show up on the day.</p></div><button class="small" data-act="exploreContest">Find event</button></div>${eventHtml}</section></div>`
}
function handleLifecycleClick(b){
 if(typeof communication3C4Click==='function'&&communication3C4Click(b))return true;if(typeof communication3C3Click==='function'&&communication3C3Click(b))return true;if(typeof communication3C2Click==='function'&&communication3C2Click(b))return true;if(typeof communication3C1Click==='function'&&communication3C1Click(b))return true;if(typeof romance3B2Click==='function'&&romance3B2Click(b))return true;if(handleInventoryClick(b))return true;if(promClick(b))return true;if(worldClick(b))return true;if(peopleHubClick(b))return true;if(people3a5Click(b))return true;if(narrativeClick(b))return true;if(friends3aClick(b))return true;if(people3aClick(b))return true;if(nurseClick(b))return true;if(healthClick(b))return true;if(ffClick(b))return true;if(eventsClick(b))return true;if(identClick(b))return true;if(majorClick(b))return true;if(campusClick(b))return true;if(oClick(b))return true;if(workClick(b))return true;if(uniClick(b))return true;if(bizClick(b))return true;if(rstClick(b))return true;if(lmpqClick(b))return true;if(knxClick(b))return true;if(handleSchoolClick(b))return true;if(hijClick(b))return true;if(handlePlanClick(b))return true;if(handleClubClick(b))return true;if(handleUIClick(b))return true;
 const d=b.dataset;
 if(d.nextDayConfirm){performNextDay();return true}
 if(d.closeModal){closeChoiceModal();render();return true}
 if(d.clubAttend){attendClubSession(d.clubAttend);save();render();return true}
 if(d.clubSkip){skipClubSession(d.clubSkip);save();render();return true}
 if(d.clubExcuse){excuseClubSession(d.clubExcuse);save();render();return true}
 if(d.contestAttend){attendContest(d.contestAttend);save();render();return true}
 if(d.noteOpen){const n=S.notifications.find(x=>x.id===d.noteOpen);if(n){n.read=true;if(n.status==='Unread')n.status='Read';if(n.tab)active=n.tab}save();render();return true}
 if(d.notesRead){for(const n of activeNotifications()){n.read=true;n.status='Read'}save();render();return true}
 return false
}

function attendanceHtml(){if(!needsFormalSchool())return '';const r=ensureSchoolRecord(),past=(S.schoolHistory||[]).filter(h=>h.record&&h.grade!=='Kindergarten').slice(0,4);const row=(l,v,warn)=>statRow(l,warn?`<span class="urgent-text">${v}</span>`:v);
 return `<section class="card"><h3>Attendance this year</h3>${row('Days attended',r.daysAttended)}${row('Unexcused absences',r.absences,r.absences>=5)}${row('Excused absences',r.excused)}${row('Late arrivals',r.tardies,r.tardies>=8)}${row('Classes skipped',r.classesSkipped||0,(r.classesSkipped||0)>=3)}${row('Left early',r.leftEarly||0)}${row('Missed assessments',r.examsMissed,r.examsMissed>0)}${row('Missing homework',r.missingHomework,r.missingHomework>=3)}${row('Attendance rate',Math.round(S.school.attendance)+'%')}<p class="muted-text">On time by ${timeLabel(SCHOOL_DAY.tardyAfter)}, absent after ${timeLabel(SCHOOL_DAY.cutoff)}.</p></section><section class="card"><h3>Attendance history</h3>${past.length?past.map(h=>`<div class="timeline-entry"><span>${esc(h.grade)} • ${esc(h.school)}</span><b>${h.attendance}% attendance • average ${h.average}%</b><p>${h.record.absences} unexcused • ${h.record.excused} excused • ${h.record.tardies} late${h.record.classesSkipped?` • ${h.record.classesSkipped} classes skipped`:''}</p></div>`).join(''):'<p class="muted-text">Past school years appear here.</p>'}</section>`}
