
// =====================================================================
// v7.3 V1 — Living arrangements (18+), university applications in senior year, funding, university years
// =====================================================================
const UNI_TIERS={elite:{label:'Elite',fee:90,need:93,tuition:55000},top:{label:'Top',fee:75,need:88,tuition:40000},strong:{label:'Strong',fee:60,need:82,tuition:28000},state:{label:'State',fee:45,need:74,tuition:12000},community:{label:'Community college',fee:0,need:0,tuition:4000}};
const UNIS=[['Northbridge University','elite'],['Halden College','elite'],['Westfield Institute of Technology','top'],['Marlow University','top'],['Ashford University','top'],['Lakeview University','strong'],['Brighton Arts University','strong'],['Kingsley University','strong'],['Riverside State University','state'],['Pinecrest State University','state'],['Eastgate State College','state'],['Cedar Valley Community College','community']].map(([name,tier],i)=>({id:'uni'+i,name,tier,...UNI_TIERS[tier]}));
const HOUSING={parents:{label:'Live with your parents',rent:0,bills:0},apartment:{label:'Rent an apartment',rent:900,bills:120},condo:{label:'Rent a condo',rent:1600,bills:180},dorm:{label:'University dorm',rent:650,bills:0,needsUni:true}};
// ---------- Living arrangements ----------
function housing(){S.housing=S.housing||{type:'parents',since:currentDate(),missed:0};return S.housing}
function moveTo(type){
 const h=HOUSING[type];if(!h)return;if(S.age<18){toast('Moving out starts at 18.');return}if(h.needsUni&&!S.uni?.enrolled){toast('Dorms are for enrolled university students.');return}if(type==='dorm'){syncDormRent();if(!mySchool()?.dorm){toast('Your school has no dorms.');return}}
 const cur=housing();if(cur.type===type){toast('You already live there.');return}if(cur.type==='withPartner'&&type!=='withPartner'&&partnerPerson()){toast('You live with your partner — talk to them first.');return}
 const deposit=h.rent;if(deposit&&S.money<deposit){toast(`You need ${money(deposit)} for the deposit (one month's rent).`);return}
 S.money-=deposit;S.housing={type,since:currentDate(),missed:0,deposit};if(type!=='parents'){S.family.closeness=clamp(S.family.closeness-2);S.location='Home'}
 log(type==='parents'?'Back home':'Moving out',type==='parents'?'You move back in with your parents. Your old room still has the same posters.':type==='dorm'?'A tiny room, a roommate you just met, and a shared bathroom down the hall. It is yours.':`Your own ${type==='condo'?'condo':'apartment'}. Echoing rooms, a borrowed mattress, total freedom. Rent: ${money(h.rent)}/month.`,true);
 if(type!=='parents')S.milestones.unshift({dateISO:currentDate(),age:S.age,title:'🏠 Moved out',text:`${h.label.replace('Rent an ','').replace('Rent a ','')} from ${formatDate(currentDate())}.`})
}
function housingMonthly(){const h=housing();if(currentDate().slice(8)!=='01')return;const def=HOUSING[h.type];if(!def||!def.rent&&!def.bills)return;const due=def.rent+def.bills;
 if(S.money>=due){S.money-=due;h.missed=0;if(!SIM.skipping)log('Rent & bills paid',`${money(due)} for ${h.type==='dorm'?'the dorm':'rent and bills'} this month.`);return}
 h.missed=(h.missed||0)+1;if(h.missed>=2){S.housing={type:'parents',since:currentDate(),missed:0};S.family.tension=clamp(S.family.tension+4);if(!SIM.skipping)log('Evicted',`Two months without rent. You move back in with your parents — awkwardly.`,true)}else if(!SIM.skipping)log('Rent is late',`You are ${money(due-S.money)} short this month. Miss another and you lose the place.`)}
// ---------- Class rank (for merit money) ----------
function peerGpa(n){let h=0;for(const ch of n.id)h=(h*31+ch.charCodeAt(0))>>>0;return 60+(h%3900)/100}
function uniState(){if(!S.uniApps)S.uniApps={list:[],applied:{},decisions:{},essay:0,counselor:false,loan:null,choice:null,year:inSenior()?academicInfo().key:null};if(S.uniApps.year==null&&inSenior())S.uniApps.year=academicInfo().key;return S.uniApps}
function seniorTimeline(){const a=academicInfo();const sem2=a.sem2Start,end=a.end,mid=addDays(sem2,Math.round(daysBetween(sem2,end)/2));return {a,windowOpen:sem2,windowClose:addDays(sem2,60),loanFrom:addDays(mid,-15),loanTo:addDays(mid,15),decisions:addDays(end,-21),end}}
function inSenior(){return needsFormalSchool()&&gradeNumber()===12}
function uniTick(){
 if(inSenior()){const u=uniState(),tl=seniorTimeline(),t=currentDate();if(u.year!=null&&u.year!==tl.a.key){Object.assign(u,{list:[],applied:{},decisions:{},essay:0,counselor:false,loan:null,choice:null,year:tl.a.key,lettersSent:false})}
  if(!u.counselor&&tl.a.semester===1&&daysBetween(tl.a.start,t)>=14&&!SIM.skipping){u.counselor=true;queueEvent({type:'counselor',title:'Meeting with the school counselor',text:`"Senior year — time to think about what comes next." Your average is ${schoolAverage().toFixed(1)}. The counselor suggests a balanced list: a few reach schools, several matches, and a safe option. Applications open on ${formatDate(tl.windowOpen)} and close ${formatDate(tl.windowClose)}.`,priority:3,expiresDays:5,choices:[{id:'ok',label:'Make a plan'},{id:'later',label:'Not now'}]})}
  if(t===tl.windowOpen&&!SIM.skipping)notify('University applications are open',`Apply until ${formatDate(tl.windowClose)} (max 10).`,{sourceType:'uni',sourceId:'uniopen-'+tl.a.key,tab:'school'});
  if(t===tl.loanFrom&&!SIM.skipping)notify('Student loan applications open',`Interest-free university loan: apply until ${formatDate(tl.loanTo)}.`,{sourceType:'uni',sourceId:'loan-'+tl.a.key,tab:'school'});
  if(t>=tl.decisions&&!u.lettersSent&&Object.keys(u.applied).length)sendDecisions();
  if(t>=tl.decisions&&u.schApplied&&!u.scholarship)scholarshipDecision();
  if(SIM.skipping&&!Object.keys(u.applied).length&&t>=tl.windowClose&&t<tl.decisions)autoApply();
 }
 uniYearTick();
}
function autoApply(){const u=uniState(),avg=schoolAverage();if(!u.schApplied)u.schApplied={dateISO:currentDate(),essay:35};u.schEssay=u.schEssay||35;const pick=UNIS.filter(x=>x.need<=avg+4).slice(-4);for(const x of pick)u.applied[x.id]={dateISO:currentDate(),essay:40};if(!pick.length)u.applied.uni11={dateISO:currentDate(),essay:30}}
function addToList(id){const u=uniState();if(u.list.includes(id)){u.list=u.list.filter(x=>x!==id);return}if(u.list.length>=10){toast('Your list is full (10 schools).');return}u.list.push(id)}
function writeEssay(){const u=uniState();if(!inSenior()){toast('Essays are for senior year.');return}if(atSchool()){toast('After school.');return}const g=practiceSkill('writing',1);if(g===0&&S.lastFarmNote){toast(S.lastFarmNote);S.lastFarmNote=null;return}u.essay=clamp(u.essay+8+(S.skills?.writing||0)*.12);advanceTime(90,{silent:true});log('Application essay',u.essay>=80?'The essay finally sounds like you. Your counselor calls it "memorable."':u.essay>=50?'Another draft. Getting there.':'A rough first draft. It is a start.')}
function applyTo(id){const u=uniState(),x=UNIS.find(y=>y.id===id),tl=seniorTimeline(),t=currentDate();if(!inSenior()||!x)return;if(t<tl.windowOpen||t>tl.windowClose){toast(`Applications are open ${formatDate(tl.windowOpen)}–${formatDate(tl.windowClose)}.`);return}if(u.applied[id]){toast('Already applied.');return}if(Object.keys(u.applied).length>=10){toast('You can apply to at most 10 schools.');return}
 if(x.fee){const parents=caregiverYes(S.wealth==='Struggling'?-25:0);if(!parents&&!spendOwn(x.fee)){toast(`The application fee is ${money(x.fee)}.`);return}if(parents)log('Fee covered',`${primaryCaregiver()} pays the ${money(x.fee)} application fee.`)}
 u.applied[id]={dateISO:t,essay:u.essay};advanceTime(45,{silent:true});log(`Applied: ${x.name}`,`${x.label} • fee ${x.fee?money(x.fee):'none'}. Now you wait.`)}
function strength(){const r=ensureRep(),clubs=(S.school?.clubs||[]).filter(c=>c.status==='Active').length,awards=(S.awards||[]).length,teacher=avgTeacherRel();return {avg:schoolAverage(),extra:Math.min(10,clubs*2+awards*1.5+(r.leadership||0)*.05),teacher}}
function avgTeacherRel(){const s=S.school?.subjects||[];return s.length?s.reduce((a,x)=>a+(x.teacherRel||50),0)/s.length:50}
function sendDecisions(){const u=uniState();u.lettersSent=true;scholarshipDecision();const st=strength(),how=S.inventoryItems.some(i=>i.key==='laptop')?'email':S.phone?.owned?'phone':'mail';
 for(const id of Object.keys(u.applied)){const x=UNIS.find(y=>y.id===id),essay=u.applied[id].essay||0,score=st.avg+st.extra+(essay-50)*.08+(st.teacher-50)*.05+(Math.random()*8-4)-x.need;u.decisions[id]=x.tier==='community'?'Accepted':score>=1?'Accepted':score>=-2.5?'Waitlisted':'Rejected'}
 const acc=Object.entries(u.decisions).filter(([,v])=>v==='Accepted').map(([k])=>UNIS.find(y=>y.id===k));
 if(SIM.skipping){u.choice=acc.sort((a,b)=>b.need-a.need)[0]?.id||null;return}
 const via={email:'Your laptop pings: new emails from admissions offices.',phone:'Your phone lights up with admissions notifications.',mail:'A stack of envelopes in the mailbox — some thick, some thin.'}[how];
 log('📬 University decisions',`${via} ${Object.entries(u.decisions).map(([k,v])=>`${UNIS.find(y=>y.id===k).name}: ${v}`).join(' • ')}`,true);
 const best=acc.sort((a,b)=>b.need-a.need)[0],r=familyRules(),cg=caregiverPerson(),cn=cg?firstName(cg):'Your parents';
 if(best){S.family.closeness=clamp(S.family.closeness+4);S.happiness=clamp(S.happiness+10);log('🎉 Family celebration',`${cn} reads the ${best.name} letter twice, then hugs you so hard it hurts. There is cake that night.`,true);S.milestones.unshift({dateISO:currentDate(),age:S.age,title:'🎓 Accepted',text:`Accepted to ${acc.map(x=>x.name).join(', ')}.`})}
 else{const tone=S.family.closeness>=55?'comfort':r.strictness>70?'anger':'silence';S.happiness=clamp(S.happiness-10);if(tone==='anger')S.family.tension=clamp(S.family.tension+6);log('No acceptances',{comfort:`${cn} sits with you for a long time. "This does not decide who you are. We'll figure out the next step together."`,anger:`${cn} is furious — about the grades, the effort, all of it. It is a long, bad evening.`,silence:`${cn} reads the letters and says nothing. The silence is worse than shouting.`}[tone],true)}
 for(const [k,v] of Object.entries(u.decisions))if(v==='Waitlisted')scheduleFollowUp('waitlist',{id:k},{days:14,minute:600})}
function applyLoan(){const u=uniState(),tl=seniorTimeline(),t=currentDate();if(!inSenior()){toast('Student loans are for seniors.');return}if(t<tl.loanFrom||t>tl.loanTo){toast(`Loan applications are open ${formatDate(tl.loanFrom)}–${formatDate(tl.loanTo)} (middle of semester 2).`);return}if(u.loan){toast('You already applied.');return}const amount=Math.min(30000,Math.max(...UNIS.filter(x=>u.applied[x.id]||u.list.includes(x.id)).map(x=>x.tuition),12000));u.loan={amount,dateISO:t,interest:0};log('Student loan approved',`An interest-free loan of up to ${money(amount)} per year. You repay it after you finish.`,true)}
function enroll(id){const u=uniState(),x=UNIS.find(y=>y.id===id);if(!x||u.decisions[id]!=='Accepted'){toast('You can only enroll where you were accepted.');return}const f=funding(x);if(f.gap>S.money+S.finance.savings){toast(`You are ${money(f.gap-S.money-S.finance.savings)} short for year one. Apply for a loan or choose a cheaper school.`);return}u.choice=id;log(`Enrolled: ${x.name}`,`Tuition ${money(x.tuition)}/year: parents ${money(f.parents)}, scholarship ${money(f.scholarship)}${f.loan?`, loan ${money(Math.min(f.loan,x.tuition-f.parents-f.scholarship))}`:''}${f.gap?`, you ${money(f.gap)}`:''}.`,true)}
// ---------- University years ----------
function housingHtml(){if(S.age<18)return '';const h=housing();return `<section class="card"><h3>Where you live</h3><p><b>${esc((HOUSING[h.type]||{label:h.type==='withPartner'?'With your partner':h.type}).label)}</b> since ${formatDate(h.since)}${HOUSING[h.type]?.rent?` • ${money(HOUSING[h.type].rent+HOUSING[h.type].bills)}/month`:''}</p><div class="inline-actions">${Object.entries(HOUSING).filter(([k,v])=>k!==h.type&&(!v.needsUni||S.uni?.enrolled)).map(([k,v])=>`<button class="small ghost" data-move="${k}">${esc(v.label)}${v.rent?` • ${money(v.rent+v.bills)}/mo`:''}</button>`).join('')}</div></section>`}
function uniEventChoice(e,id){if(respondTalentNotice(e,id))return true;if(threadFollowUpChoice(e,id))return true;if(siblingRequestChoice(e,id))return true;if(healthEventChoice(e,id))return true;if(campusEventChoice(e,id))return true;if(e.type==='gradSpeech')return gradSpeech(e,id);if(e.type==='counselor'){log('Counselor meeting',id==='ok'?'You leave with a list of schools to research and a plan for your essay. (Education → University)':'You promise to come back later.');return true}return false}
function uniDaily(){uniTick();campusDaily();housingMonthly()}
