
// =====================================================================
// v7.3 V2 — Adult careers: workdays, boss & coworkers, levels Intern → CEO, promotions, raises, monthly salary
// =====================================================================
const CAREER_LEVELS=['Intern','Junior','Associate','Senior','Lead','Manager','Senior Manager','Director','VP','CEO'];
const LEVEL_PAY=[.55,.8,1,1.25,1.5,1.8,2.2,2.8,3.6,5];
const TRACKS={office:{base:3400,company:'Brightline Group',field:'Operations'},developer:{base:4800,company:'Nimbus Software',field:'Engineering'},designer:{base:4000,company:'Studio Halcyon',field:'Design'},general:{base:3200,company:'Meridian Partners',field:'Business'}};
function isCareer(){return !!S.career?.job?.career}
function careerJob(){return S.career?.job}
function startCareer(base){
 const track=TRACKS[base.id]?base.id:'general',t=TRACKS[track],deg=S.education?.degree,uniTier=(UNIS.find(u=>u.name===deg?.school)||{}).tier,level=deg?(['elite','top'].includes(uniTier)?2:1):0;
 const mk=(label)=>{const nm=generateName({});const p=makePerson(nm.firstName,'friend',30+Math.floor(Math.random()*20),S.age);Object.assign(p,{name:nm.fullName,fullName:nm.fullName,firstName:nm.firstName,surname:nm.surname,roleLabel:label,rel:45,trust:50,work:true});S.people.push(p);return p};
 const boss=mk(`your manager at ${t.company}`),cw=[mk(`coworker at ${t.company}`),mk(`coworker at ${t.company}`)];cw.forEach(p=>{p.age=Math.max(S.age-2,22)+Math.floor(Math.random()*8)});
 S.career.job={career:true,id:base.id,title:`${CAREER_LEVELS[level]} ${base.title.replace(/^Junior /,'')}`,baseTitle:base.title.replace(/^Junior /,''),track,company:t.company,level,points:0,salary:Math.round(t.base*LEVEL_PAY[level]),bossId:boss.id,coworkerIds:cw.map(p=>p.id),start:currentDate(),sickLeft:5,leaveLeft:12,noShows:[],lastRaise:currentDate(),lastPromoAsk:null,monthLog:{worked:0,paidOff:0,unpaid:0}};
 if(majorFitsJob(base.id)&&S.career.job.level<3){S.career.job.level++;S.career.job.title=`${CAREER_LEVELS[S.career.job.level]} ${S.career.job.baseTitle}`;S.career.job.salary=Math.round(t.base*LEVEL_PAY[S.career.job.level]);log('Your degree fits the role',`Your ${majorInfo(S.education.degree.major).label} degree gets you hired one level higher.`)}
 S.career.performance=55;log(`💼 New job: ${S.career.job.title}`,`${t.company} • ${money(S.career.job.salary)}/month • Monday–Friday, 9:00–5:00. Your manager is ${boss.name}.`,true);S.milestones.unshift({dateISO:currentDate(),age:S.age,title:'💼 First day at work',text:`${S.career.job.title} at ${t.company}.`})
}
function upgradeJobIfAdult(){const j=careerJob();if(j&&!j.career&&S.age>=18&&D.jobs.adult.some(a=>a.id===j.id))startCareer(D.jobs.adult.find(a=>a.id===j.id))}
function workdayEvent(d=currentDate()){return S.calendar.find(e=>e.type==='workDay'&&e.dateISO===d)}
function ensureWorkday(d=currentDate()){if(!isCareer()||isWeekend(d)||dayOffHoliday(d,calendarProfile().region))return null;let ev=workdayEvent(d);if(!ev)ev=createCalendarEvent({id:`work-${d}`,type:'workDay',title:`Work • ${careerJob().company}`,dateISO:d,startMinute:540,endMinute:1020,graceMinute:555,required:true,location:careerJob().company,payload:{},source:'work'});return ev}
const bossP=()=>personById(careerJob()?.bossId),coworkers=()=>(careerJob()?.coworkerIds||[]).map(personById).filter(Boolean);
function goToWork(style='normal'){
 const j=careerJob(),ev=ensureWorkday();if(!ev){toast('No work today.');return}if(isTerminal(ev.status)){toast('Today is already settled.');return}const m=currentMinute();if(m>660){processCalendar();return}
 if(m<540)advanceTime(540-m,{silent:true});const late=currentMinute()>555,boss=bossP();
 const pts={focus:4,normal:3,social:2}[style]*(0.6+S.career.performance/125)*concentration();j.points=clamp(j.points+pts);
 S.career.performance=clamp(S.career.performance+(late?-3:style==='focus'?1.5:.8)+(S.energy<30?-1:0));if(boss){boss.rel=clamp(boss.rel+(late?-3:style==='focus'?1.2:.6))}
 if(style==='social')coworkers().forEach(p=>{p.rel=clamp(p.rel+1.5)});else coworkers().forEach(p=>{p.rel=clamp(p.rel+.4)});
 setCalendarStatus(ev,'Attended',late?'Late':'On time');ev.attendanceStatus=late?'Tardy':'Present';j.monthLog.worked++;
 advanceTime(1020-currentMinute(),{silent:true});S.energy=clamp(S.energy-(style==='focus'?28:22));S.stress=clamp(S.stress+(style==='focus'?7:4));S.location='Home';
 log(late?'Work (late)':'Workday',`${late?`${boss?firstName(boss):'Your manager'} glances at the clock when you walk in. `:''}${{focus:'Heads-down all day. You get through a lot.',normal:'A normal day: meetings, emails, one actual win.',social:'You spend a lot of the day with coworkers. Less done, better vibes.'}[style]} (job points ${Math.round(j.points)}/100)`)
}
function callInSick(){const j=careerJob(),ev=ensureWorkday();if(!ev||isTerminal(ev.status)){toast('Nothing to call in sick for.');return}const really=S.health<70||!!S.healthState?.illness||S.needs.sleep<20,boss=bossP();
 if(j.sickLeft>0){j.sickLeft--;j.monthLog.paidOff++}else j.monthLog.unpaid++;setCalendarStatus(ev,'Excused','Sick day');ev.attendanceStatus='Sick';
 if(!really&&chance(25)&&boss){boss.trust=clamp(boss.trust-6);S.career.performance=clamp(S.career.performance-3);log('Called in sick',`${firstName(boss)} does not sound convinced. "Feel better… I guess."`)}else{S.stress=clamp(S.stress-6);log('Called in sick',`You email ${boss?firstName(boss):'your manager'} and go back to bed.${j.sickLeft<0?'':` Sick days left: ${j.sickLeft}.`}`)}}
function takeLeave(when='today'){const j=careerJob(),d=when==='today'?currentDate():addDays(currentDate(),1),ev=ensureWorkday(d);if(!ev||isTerminal(ev.status)){toast('Nothing to take off.');return}if(j.leaveLeft<=0){toast('No paid leave left this year.');return}j.leaveLeft--;j.monthLog.paidOff++;setCalendarStatus(ev,'Excused','Paid leave');ev.attendanceStatus='Leave';const boss=bossP();if(when==='today'&&boss)boss.rel=clamp(boss.rel-2);S.stress=clamp(S.stress-10);log('Day off',`${when==='today'?'Short notice, but approved.':'Approved in advance.'} Leave days left: ${j.leaveLeft}.`)}
function workNoShow(ev){const j=careerJob();if(!j)return;setCalendarStatus(ev,'Missed','No-show');ev.attendanceStatus='No-show';j.monthLog.unpaid++;j.noShows=[...(j.noShows||[]).filter(d=>daysBetween(d,currentDate())<=30),ev.dateISO];S.career.performance=clamp(S.career.performance-10);const boss=bossP();if(boss){boss.rel=clamp(boss.rel-8);boss.trust=clamp(boss.trust-8)}
 if(j.noShows.length>=3||S.career.performance<15){fireJob(j.noShows.length>=3?'three no-shows in a month':'performance kept slipping');return}
 if(!SIM.skipping){log('Missed work',`You did not show up and did not call. ${boss?`${firstName(boss)} sends a short, cold email.`:''}`);if(boss)incomingCall(boss,'chat')}}
function fireJob(reason){const j=careerJob();if(!j)return;recordOutcome('Work',`${j.title} at ${j.company}`,'Fired',reason);S.career.job=null;S.career.performance=50;for(const e of S.calendar)if(e.type==='workDay'&&!isTerminal(e.status))setCalendarStatus(e,'Cancelled','Job ended');S.happiness=clamp(S.happiness-12);S.stress=clamp(S.stress+15);if(!SIM.skipping)log('Fired',`HR calls you in: ${reason}. You leave with a cardboard box.`,true)}
function requestPromotion(){const j=careerJob();if(!j)return;if(j.level>=CAREER_LEVELS.length-1){toast('You are already the CEO.');return}if(j.lastPromoAsk&&daysBetween(j.lastPromoAsk,currentDate())<60){toast(`Wait until ${formatDate(addDays(j.lastPromoAsk,60))} to ask again.`);return}if(j.points<100){toast(`You need a full job-points bar first (${Math.round(j.points)}/100).`);return}
 j.lastPromoAsk=currentDate();const boss=bossP(),score=S.career.performance*.5+(boss?boss.rel:50)*.35+(boss?boss.trust:50)*.15+Math.min(10,daysBetween(j.start,currentDate())/60)-j.level*2+(Math.random()*16-8);
 if(score>=55){j.level++;j.points=0;const old=j.salary;j.salary=Math.round(j.salary*(LEVEL_PAY[j.level]/LEVEL_PAY[j.level-1]));j.title=`${CAREER_LEVELS[j.level]==='CEO'?'CEO':CAREER_LEVELS[j.level]+' '+j.baseTitle}`;j.lastRaise=currentDate();S.milestones.unshift({dateISO:currentDate(),age:S.age,title:'📈 Promoted',text:`${j.title} at ${j.company} (${money(old)} → ${money(j.salary)}/month).`});S.happiness=clamp(S.happiness+8);log('📈 Promotion',`${boss?firstName(boss):'Your manager'} shakes your hand: you are now ${j.title}. Salary ${money(old)} → ${money(j.salary)}/month.`,true)}
 else{j.points=clamp(j.points-25);const why=S.career.performance<55?'your performance needs to be more consistent':(boss?.rel||50)<50?'your manager is not fully convinced yet':'the timing is not right';log('Promotion: not yet',`"Not this time — ${why}." You can ask again in 60 days.`)}advanceTime(30,{silent:true})}
function requestRaise(){const j=careerJob();if(!j)return;const months=daysBetween(j.lastRaise,currentDate())/30;if(months<6){toast(`Raises can be discussed every 6 months (next: ${formatDate(addDays(j.lastRaise,180))}).`);return}const boss=bossP(),score=S.career.performance*.6+(boss?boss.rel:50)*.4+(Math.random()*16-8);j.lastRaise=currentDate();
 if(score>=58){const pct=3+Math.round(Math.random()*5),old=j.salary;j.salary=Math.round(j.salary*(1+pct/100));log('💰 Raise',`${pct}% raise: ${money(old)} → ${money(j.salary)}/month.`,true)}else{if(boss)boss.rel=clamp(boss.rel-1);log('No raise this time',`"Let's revisit in six months."`)}advanceTime(20,{silent:true})}
function payday(){const j=careerJob();if(!isCareer()||currentDate().slice(8)!=='01')return;const ml=j.monthLog,sched=ml.worked+ml.paidOff+ml.unpaid;if(!sched){j.monthLog={worked:0,paidOff:0,unpaid:0};return}const gross=Math.round(j.salary*(ml.worked+ml.paidOff)/Math.max(sched,ml.worked+ml.paidOff+ml.unpaid));
 const loan=Math.min(S.finance.uniDebt||0,Math.round(gross*.05));S.money+=gross-loan;S.finance.earned=(S.finance.earned||0)+gross;if(loan)S.finance.uniDebt-=loan;j.monthLog={worked:0,paidOff:0,unpaid:0};
 if(!SIM.skipping)log('💵 Payday',`${money(gross)} for last month (${ml.worked} days worked, ${ml.paidOff} paid days off${ml.unpaid?`, ${ml.unpaid} unpaid`:''})${loan?` • student loan repayment ${money(loan)} (interest-free, ${money(S.finance.uniDebt)} left)`:''}.`)}
function workDaily(){upgradeJobIfAdult();if(!isCareer())return;payday();ensureWorkday();const j=careerJob();if(currentDate().slice(5)==='01-01'){j.sickLeft=5;j.leaveLeft=12}if(!SIM.skipping&&chance(5)){const c=rand(coworkers());if(c)log('At work',rand([`${firstName(c)} brings donuts for the team.`,`${firstName(c)} asks for your help on a deadline.`,`Office gossip: someone is leaving. ${firstName(c)} knows who.`]))}}
function careerJobPanel(){const j=careerJob(),boss=bossP(),ev=workdayEvent(),cw=coworkers(),bar=(p,l)=>p?`<div class="skill-line"><span>${esc(l)}: ${esc(p.name)}</span><div class="progress"><i style="width:${clamp(p.rel)}%"></i></div><b>${Math.round(p.rel)}</b></div>`:'';
 return `<div class="dashboard"><section class="card wide"><h3>Work • ${esc(j.company)}</h3>${statRow('Role',esc(j.title))}${statRow('Level',`${j.level+1} / 10 (${CAREER_LEVELS[j.level]})`)}${statRow('Salary',money(j.salary)+'/month (paid on the 1st)')}${statRow('Performance',Math.round(S.career.performance)+'%')}<div class="skill-line"><span>Job points</span><div class="progress"><i style="width:${clamp(j.points)}%"></i></div><b>${Math.round(j.points)}/100</b></div>${statRow('Sick days / leave left',`${j.sickLeft} / ${j.leaveLeft}`)}${S.finance.uniDebt?statRow('Student loan left',money(S.finance.uniDebt)):''}
 ${ev&&!isTerminal(ev.status)?`<h4>Today • 9:00–5:00</h4><div class="inline-actions"><button class="small primary" data-work="focus">Go to work: focus</button><button class="small" data-work="normal">Go to work</button><button class="small" data-work="social">Go to work: socialize</button><button class="small ghost" data-work="sick">Call in sick</button><button class="small ghost" data-work="leave">Take today off</button></div>`:ev?`<p class="muted-text">Today: ${esc(ev.attendanceStatus||ev.status)}.</p>`:'<p class="muted-text">No work today.</p>'}
 <div class="inline-actions"><button class="small ghost" data-work="leaveTomorrow">Request tomorrow off</button><button class="small" data-work="promo" ${j.points>=100?'':'disabled'}>Request a promotion</button><button class="small ghost" data-work="raise">Ask for a raise</button><button class="small ghost" data-act="quitJob">Quit</button></div></section>
 <section class="card"><h3>People at work</h3>${bar(boss,'Manager')}${cw.map(p=>bar(p,'Coworker')).join('')}</section></div>`}
function workClick(b){const w=b.dataset.work;if(!w)return false;if(w==='sick')callInSick();else if(w==='leave')takeLeave('today');else if(w==='leaveTomorrow')takeLeave('tomorrow');else if(w==='promo')requestPromotion();else if(w==='raise')requestRaise();else goToWork(w);save();render();return true}
