
// ---------- v7.2 PHASE 5b: neighborhood, groups, rivals, awards, gifts, sneaking, NPC agency ----------
// ===== Neighborhood (§91–93) =====
function ensureNeighborhood(){
 if(!S.neighborhood)S.neighborhood={households:[],rep:{helpful:15,friendly:20,quiet:50,social:15,troublemaker:4,business:3,known:8},cooldown:null};
 const nb=S.neighborhood;if(S.age>=3&&nb.households.length<4){for(let i=nb.households.length;i<4;i++){const kids=generateHousehold({kids:chance(60)?1:2,childAge:3+Math.floor(Math.random()*14)});const hh=S.households.find(h=>h.id===kids[0].householdId);hh.neighbor=true;hh.pet=rand(['dog','cat',null,null]);hh.petName=hh.pet?rand(['Biscuit','Luna','Max','Mochi','Pepper','Coco','Rocky','Bella']):null;nb.households.push(hh.id)}}
 return nb
}
function nbRep(k,v){const r=ensureNeighborhood().rep;if(k in r)r[k]=clamp(r[k]+v)}
function nbHousehold(){const nb=ensureNeighborhood();return S.households.find(h=>h.id===rand(nb.households))}
function hhKids(hh){return (hh?.members||[]).map(npcById).filter(Boolean)}
function addNeighborPerson(npc,label='neighbor'){if(!npc)return null;let p=S.people.find(x=>x.npcId===npc.id);if(!p){p=personFromNpc(npc,'friend',label);p.rel=48;S.people.push(p)}return p}
const NB_EVENTS={
 newFamily:{title:'A new family moved in',choices:[['introduce','Introduce yourself'],['food','Bring food or a small gift'],['kids','Meet their kids'],['pet','Meet their pet'],['ignore','Leave them be']]},
 movingAway:{title:'Neighbors are moving away',choices:[['goodbye','Say a proper goodbye'],['keepInTouch','Promise to keep in touch'],['avoid','Avoid it']]},
 blockParty:{title:'Block party this afternoon',choices:[['go','Go and mingle'],['bring','Bring something to share'],['skip','Skip it']]},
 garageSale:{title:'Garage sale down the street',choices:[['browse','Browse for bargains'],['help','Help them sell'],['skip','Walk past']]},
 cleanup:{title:'Community cleanup day',choices:[['join','Join in'],['skip','Not today']]},
 lostPet:{title:'A lost pet',choices:[['search','Help search'],['poster','Share the poster'],['skip','Hope they find it']]},
 wrongPackage:{title:'A package delivered to your door — not yours',choices:[['return','Return it next door'],['leave','Leave it for the courier'],['keep','Keep it']]},
 powerOutage:{title:'Power outage',choices:[['candles','Candlelight family time'],['outside','See what the neighbors are doing'],['sleep','Go to bed early']]},
 waterOutage:{title:'Water is off until evening',choices:[['help','Help carry water'],['wait','Wait it out']]},
 streetRepairs:{title:'Street repairs (very loud)',choices:[['earplugs','Find somewhere quieter'],['complain','Complain to the city'],['watch','Watch the machines']]},
 festival:{title:'Local festival this weekend',choices:[['go','Go'],['volunteer','Volunteer at a stall'],['skip','Skip it']]},
 fundraiser:{title:'School fundraiser — neighbors are selling raffle tickets',choices:[['buy','Buy a ticket ($5)'],['sell','Help sell tickets'],['no','Say no']]},
 lemonade:{title:'A neighbor kid has a lemonade stand',choices:[['buy','Buy a cup ($2)'],['tip','Buy two and tip'],['walk','Walk by']]},
 noiseComplaint:{title:'A noise complaint about your house',choices:[['apologize','Apologize'],['argue','Argue']]},
 argument:{title:'Two neighbors are arguing loudly',choices:[['mediate','Try to calm things down'],['stay','Stay out of it'],['gossip','Tell everyone about it']]},
 kidsPlaying:{title:'Kids are playing outside',choices:[['join','Join in'],['watch','Watch for a bit'],['skip','Stay inside']]},
 snow:{title:'It snowed overnight',choices:[['snowman','Build a snowman'],['shovel','Shovel a neighbor\'s path'],['inside','Stay warm inside']]},
 garden:{title:'The community garden needs help',choices:[['help','Help plant'],['skip','Not today']]},
 market:{title:'Weekend market in the square',choices:[['shop','Wander and snack ($6)'],['skip','Skip it']]},
 watch:{title:'Neighborhood watch meeting',choices:[['attend','Attend'],['skip','Skip it']]}
};
function neighborhoodTick(){
 if(SIM.skipping||S.age<4)return;const nb=ensureNeighborhood();if(nb.cooldown&&nb.cooldown>currentDate())return;if(!chance(9))return;
 const month=Number(currentDate().slice(5,7)),cold=['KR','JP','CN','US','CA','UK','FR'].includes(calendarProfile().region)&&(month===12||month<=2);
 const pool=Object.keys(NB_EVENTS).filter(k=>(k!=='snow'||cold)&&(k!=='watch'||S.age>=18)&&(k!=='noiseComplaint'||S.flags.loudParty)&&(k!=='movingAway'||nb.households.length>3)&&(k!=='fundraiser'||S.school));
 const kind=rand(pool),hh=kind==='newFamily'?null:nbHousehold();let payload={kind,hhId:hh?.id};
 if(kind==='newFamily'){const kids=generateHousehold({kids:chance(50)?1:2,childAge:Math.max(3,S.age+rand([-2,-1,0,1,2]))});const h=S.households.find(x=>x.id===kids[0].householdId);h.neighbor=true;h.pet=rand(['dog','cat',null]);h.petName=h.pet?rand(['Biscuit','Luna','Max','Mochi','Pepper']):null;nb.households.push(h.id);payload.hhId=h.id}
 const h=S.households.find(x=>x.id===payload.hhId),fam=h?`the ${h.surname} family`:'a neighbor';
 const text={newFamily:`A moving truck all morning: ${fam} moved in next door${hhKids(h).length?`, with ${hhKids(h).map(n=>n.firstName).join(' and ')}`:''}${h?.pet?` and a ${h.pet} named ${h.petName}`:''}.`,movingAway:`${fam[0].toUpperCase()+fam.slice(1)} is packing up — they are moving to another city.`,blockParty:'Folding tables, music and grills — the whole street is out.',garageSale:`${fam[0].toUpperCase()+fam.slice(1)} is selling everything from lamps to old toys.`,cleanup:'Gloves and bags are being handed out at the corner.',lostPet:`${fam[0].toUpperCase()+fam.slice(1)}'s ${h?.pet||'cat'}${h?.petName?` ${h.petName}`:''} is missing.`,wrongPackage:`The label says ${h?.parents?.[0]||'someone else'}.`,powerOutage:'Everything goes dark and quiet at once.',waterOutage:'A water main is being repaired.',streetRepairs:'Jackhammers from 8 AM.',festival:'Lanterns, food stalls and music in the square.',fundraiser:`${fam[0].toUpperCase()+fam.slice(1)} is selling raffle tickets for the school.`,lemonade:`${hhKids(h)[0]?.firstName||'A kid'} has a hand-painted sign and very serious prices.`,noiseComplaint:'Someone complained about the noise from your last get-together.',argument:`${fam[0].toUpperCase()+fam.slice(1)} and the people across the street are shouting about a fence.`,kidsPlaying:'A game of tag is happening in the street.',snow:'Everything is white and quiet.',garden:'Seedlings need planting before the weekend.',market:'Fresh bread, street food, handmade things.',watch:'A meeting about safety and streetlights.'}[kind];
 nb.cooldown=addDays(currentDate(),3);queueEvent({type:'nbh',title:NB_EVENTS[kind].title,text,payload,priority:2,expiresDays:1,choices:NB_EVENTS[kind].choices.map(([id,label])=>({id,label}))})
}
function handleNeighborhood(e,id){
 const {kind,hhId}=e.payload||{},h=S.households.find(x=>x.id===hhId),kid=hhKids(h).sort((a,b)=>Math.abs(npcAge(a)-S.age)-Math.abs(npcAge(b)-S.age))[0],fam=h?`the ${h.surname}s`:'the neighbors';let s='',mins=30;
 const met=()=>{const p=addNeighborPerson(kid);return p?firstName(p):null};
 switch(kind){
  case 'newFamily':if(id==='introduce'){nbRep('friendly',4);const n=met();s=`You say hello to ${fam}.${n?` ${n} seems nice — about your age.`:''}`}else if(id==='food'){if(S.age>=13)spendOwn(5);nbRep('friendly',6);nbRep('helpful',2);const n=met();const p=n&&S.people.find(x=>x.npcId===kid.id);if(p)p.rel=clamp(p.rel+6);s=`You bring over something homemade. ${fam[0].toUpperCase()+fam.slice(1)} are touched — a great first impression.`}else if(id==='kids'){const n=met();s=n?`You meet ${n}. You end up talking for an hour.`:'They have no kids your age, but they are friendly.';mins=60}else if(id==='pet'){S.needs.fun=clamp(S.needs.fun+8);nbRep('friendly',2);s=h?.pet?`${h.petName} the ${h.pet} immediately decides you are a friend.`:'No pet after all — but a nice chat.'}else s='You leave them to settle in.';break;
  case 'movingAway':{const p=S.people.find(x=>kid&&x.npcId===kid.id);if(id==='goodbye'){nbRep('friendly',3);if(p){p.rel=clamp(p.rel+4);rememberPerson(p,'You said a real goodbye before they moved away.',3)}s=p?`You and ${firstName(p)} say goodbye properly. It is harder than you expected.`:`You help ${fam} load the last boxes and wave them off.`}else if(id==='keepInTouch'){if(p){p.trust=clamp(p.trust+4);rememberPerson(p,'You promised to keep in touch.',2)}s='You swap contacts and promise to keep in touch.'}else{if(p)p.rel=clamp(p.rel-3);s='You stay inside. Later you wish you had gone out.'}if(p)p.movedAway=true;const nb=ensureNeighborhood();nb.households=nb.households.filter(x=>x!==hhId);break}
  case 'blockParty':if(id==='skip'){s='You hear the party all afternoon.';break}nbRep('social',4);nbRep('friendly',3);S.needs.social=clamp(S.needs.social+15);S.needs.fun=clamp(S.needs.fun+10);if(id==='bring'){nbRep('helpful',3);s='Your dish is gone in ten minutes. People ask who made it.'}else s=rand(['You end up in a long conversation with neighbors you had only ever waved at.','Someone brings a speaker; the street becomes a dance floor for an hour.']);mins=150;if(kid&&chance(50))met();break;
  case 'garageSale':if(id==='browse'){const k=rand(['book','toy','boardGame','puzzle','headphones','backpack'].filter(x=>D.catalog[x]&&S.age>=D.catalog[x].minAge));const price=Math.max(1,Math.round(D.catalog[k].price*.25));if(spendOwn(price)){addItem(k,`garage sale (${fam})`,55);s=`You find a used ${D.catalog[k].name.toLowerCase()} for ${money(price)}. A bargain.`}else s='Nothing you can afford today.'}else if(id==='help'){nbRep('helpful',4);nbRep('business',3);S.money+=5;s=`You help ${fam} haggle with customers. They slip you ${money(5)}.`;mins=90}else s='You walk past.';break;
  case 'cleanup':if(id==='join'){nbRep('helpful',6);addRep('kindness',1);S.needs.social=clamp(S.needs.social+8);s='Two hours, eight bags of trash, and a street that looks noticeably better.';mins=120}else s='You skip it this time.';break;
  case 'lostPet':if(id==='search'){mins=90;if(chance(45)){nbRep('helpful',8);nbRep('known',4);const p=kid&&met();s=`You find ${h?.petName||'the pet'} hiding under a car two streets over. ${fam[0].toUpperCase()+fam.slice(1)} are overjoyed.`;if(p){const pp=S.people.find(x=>x.npcId===kid.id);pp.rel=clamp(pp.rel+8)}}else{nbRep('helpful',3);s=`You search for an hour with no luck. Later you hear ${h?.petName||'the pet'} came home on its own.`}}else if(id==='poster'){nbRep('helpful',2);s='You share the poster around. Every bit helps.'}else s='You hope they find it.';break;
  case 'wrongPackage':if(id==='return'){nbRep('helpful',3);nbRep('friendly',2);s=`You return it. ${fam[0].toUpperCase()+fam.slice(1)} had been looking everywhere for it.`}else if(id==='leave')s='You leave it for the courier to sort out.';else{nbRep('troublemaker',8);S.family.tension=clamp(S.family.tension+(S.age<18?3:0));if(chance(40)){nbRep('friendly',-6);s='You keep it. Two days later the neighbors ask about a missing package. It is very awkward.'}else s='You keep it. Nobody asks. It does not feel great.'}break;
  case 'powerOutage':if(id==='candles'){S.family.closeness=clamp(S.family.closeness+3);s='Candles, a card game and stories you have never heard before. Better than TV.'}else if(id==='outside'){nbRep('social',3);s='Half the street is outside comparing flashlights. Strangely fun.'}else{S.needs.sleep=clamp(S.needs.sleep+5);s='You give up and go to bed early.'}mins=120;break;
  case 'waterOutage':s=id==='help'?'You carry water jugs for an older neighbor. They insist on giving you cookies.':'You wait it out. Showers are a luxury tonight.';if(id==='help')nbRep('helpful',4);break;
  case 'streetRepairs':s={earplugs:'You find a quiet café and get a surprising amount done.',complain:'You file a complaint. The jackhammers continue, but you feel heard.',watch:'Honestly, the excavator is kind of mesmerizing.'}[id];break;
  case 'festival':if(id==='skip'){s='You skip the festival.';break}S.needs.fun=clamp(S.needs.fun+15);nbRep('social',3);if(id==='volunteer'){nbRep('helpful',5);nbRep('known',3);s='You work a food stall for three hours. Everyone in the neighborhood now knows your face.';mins=180}else{if(S.age>=13)spendOwn(5);s='Street food, lanterns and music late into the evening.';mins=150}break;
  case 'fundraiser':if(id==='buy'){if(spendOwn(5)){nbRep('friendly',2);s=chance(10)?'You buy a ticket — and win a gift card. Wild.':'You buy a raffle ticket. You do not win, but it was for a good cause.'}else s='You do not have $5 on you.'}else if(id==='sell'){nbRep('helpful',3);nbRep('business',3);addRep('kindness',1);s='You sell raffle tickets door to door. Most neighbors buy one.';mins=90}else s='You say no politely.';break;
  case 'lemonade':if(id==='walk'){s='You walk by. The kid looks crushed.';nbRep('friendly',-1);break}if(spendOwn(id==='tip'?5:2)){nbRep('friendly',id==='tip'?4:2);s=id==='tip'?'You buy two cups and tip. The kid announces you are their best customer ever.':'The lemonade is extremely sweet. You say it is great.'}else s='You do not have change.';break;
  case 'noiseComplaint':S.flags.loudParty=false;if(id==='apologize'){nbRep('friendly',2);nbRep('quiet',5);s='You apologize. They appreciate it, and you keep things quieter.'}else{nbRep('troublemaker',6);nbRep('friendly',-5);s='The argument does not help. Now you have a reputation.'}break;
  case 'argument':if(id==='mediate'){const ok=chance(50);nbRep(ok?'helpful':'social',ok?5:1);s=ok?'You calm things down. Both sides grudgingly agree to talk tomorrow.':'They both turn on you briefly. Lesson learned.'}else if(id==='gossip'){nbRep('troublemaker',3);nbRep('social',2);s='The story spreads. It gets back to them.'}else s='You stay out of it.';break;
  case 'kidsPlaying':if(id==='join'){S.needs.fun=clamp(S.needs.fun+15);S.energy=clamp(S.energy-8);nbRep('friendly',2);if(kid)met();s='You join the game and end up running around until the streetlights come on.';mins=90}else s=id==='watch'?'You watch from the steps for a while.':'You stay in.';break;
  case 'snow':if(id==='snowman'){S.needs.fun=clamp(S.needs.fun+15);s='Your snowman is lopsided and magnificent.';mins=60}else if(id==='shovel'){nbRep('helpful',6);s='You shovel an elderly neighbor\'s path. They wave from the window, beaming.';mins=60}else s='Hot drink, blanket, window view.';break;
  case 'garden':if(id==='help'){nbRep('helpful',5);addRep('kindness',1);practiceSkill('knowledge',.5);s='Dirt under your nails and rows of seedlings. You will come back to see them grow.';mins=90}else s='Maybe next time.';break;
  case 'market':if(id==='shop'){if(spendOwn(6))s='You eat your way through the stalls.';else s='You just wander and smell everything.';S.needs.fun=clamp(S.needs.fun+8);mins=90}else s='You skip it.';break;
  case 'watch':if(id==='attend'){nbRep('known',4);nbRep('helpful',2);s='A long meeting about streetlights. You volunteer for one thing, and people remember your name.';mins=90}else s='You skip the meeting.';break;
 }
 advanceTime(mins,{silent:true});log(e.title,s);return true
}
function neighborhoodHtml(){const nb=ensureNeighborhood(),r=nb.rep,labels={helpful:'Helpful',friendly:'Friendly',quiet:'Quiet',social:'Social',troublemaker:'Troublemaker',business:'Local business',known:'Well-known'};const fams=nb.households.map(id=>S.households.find(h=>h.id===id)).filter(Boolean);return `${Object.entries(labels).map(([k,l])=>`<div class="skill-line"><span>${l}</span><div class="progress ${k==='troublemaker'?'dangerbar':''}"><i style="width:${clamp(r[k])}%"></i></div><b>${Math.round(r[k])}</b></div>`).join('')}<h4>Neighbors</h4>${fams.map(h=>`<div class="pl-row"><span>🏠</span><b>The ${esc(h.surname)} family</b><small>${hhKids(h).map(n=>esc(n.firstName)).join(', ')}${h.pet?` • ${h.pet} ${esc(h.petName)}`:''}</small></div>`).join('')||'<p class="muted-text">You do not know the neighbors yet.</p>'}`}
// ===== Friend groups (§106) =====
function groupTick(){
 if(SIM.skipping||S.age<8)return;const friends=S.people.filter(p=>!isFamilyPerson(p)&&p.rel>=55&&!p.movedAway);S.groups=S.groups||[];
 formGroups();if(!S.groups.length)return;
 const g=rand(S.groups);if(!g||!chance(5))return;g.members=g.members.filter(id=>personById(id));if(g.members.length<2)return;
 const a=personById(rand(g.members)),b=personById(rand(g.members.filter(x=>x!==a.id)));const kind=rand(['joke','excluded','argument','chat','newMember','outing']);
 if(kind==='joke'){const j=rand(['the incident with the vending machine','"the potato thing"','that one teacher\'s catchphrase','the fake band name']);g.jokes.unshift(j);if(g.jokes.length>5)g.jokes.length=5;g.members.forEach(id=>{const p=personById(id);if(p)p.rel=clamp(p.rel+1)});log('Inside joke',`${g.name[0].toUpperCase()+g.name.slice(1)} now has an inside joke about ${j}. Nobody else gets it. That is the point.`);return}
 if(kind==='chat'&&canUsePhone()){S.needs.social=clamp(S.needs.social+6);log('Group chat',`The group chat goes off for an hour: ${firstName(a)} sent a blurry photo and ${firstName(b)} roasted it mercilessly.`);return}
 if(kind==='excluded'){queueEvent({type:'groupExcluded',title:`${firstName(a)} seems left out`,text:`Lately ${firstName(a)} has been quiet in the group — like they are on the outside of every conversation.`,participants:[a.id],priority:2,expiresDays:2,choices:[{id:'include',label:'Make an effort to include them'},{id:'ask',label:'Ask them privately if they are okay'},{id:'ignore',label:'It is probably nothing'}]});return}
 if(kind==='argument'&&b){queueEvent({type:'groupArgument',title:`${firstName(a)} and ${firstName(b)} are fighting`,text:'The group splits into sides over something that started small.',participants:[a.id,b.id],priority:3,expiresDays:2,choices:[{id:'mediate',label:'Try to mediate'},{id:'sideA',label:`Side with ${firstName(a)}`},{id:'sideB',label:`Side with ${firstName(b)}`},{id:'out',label:'Stay out of it'}]});return}
 if(kind==='newMember'){const n=(S.npcs||[]).find(x=>Math.abs(npcAge(x)-S.age)<=1&&!S.people.some(p=>p.npcId===x.id));if(!n)return;const p=personFromNpc(n,'friend','friend of friends');p.rel=52;S.people.push(p);g.members.push(p.id);log('New in the group',`${firstName(a)} brings ${p.name} along. They fit in surprisingly fast.`);return}
 if(kind==='outing'){npcInvitesPlayer(a);const inv=S.events.find(e=>e.type==='invitation'&&e.participants?.[0]===a.id&&e.status==='Open');if(inv){inv.title=`Group outing: ${inv.title.split(': ')[1]||'hang out'}`;inv.text=`${firstName(a)} is organizing something for the whole group. `+inv.text;const pl=S.plans.find(x=>x.id===inv.payload?.planId);if(pl){pl.groupId=g.id;pl.title=`Group outing (${g.name})`}}}
}
function handleGroupEvent(e,id){const [a,b]=(e.participants||[]).map(personById);let s;
 if(e.type==='groupExcluded'){if(id==='include'){a.rel=clamp(a.rel+5);addRep('kindness',2);s=`You make a point of including ${firstName(a)}. By the end of the week they are laughing again.`}else if(id==='ask'){a.trust=clamp(a.trust+6);a.rel=clamp(a.rel+3);s=`${firstName(a)} admits they have felt invisible. Talking helps.`}else{a.rel=clamp(a.rel-3);s=`It was not nothing. ${firstName(a)} drifts a little further away.`}}
 else{if(id==='mediate'){const ok=chance(55);[a,b].forEach(p=>p&&(p.rel=clamp(p.rel+(ok?3:-1))));addRep('leadership',ok?2:0);s=ok?'You get them talking instead of shouting. The group exhales.':'They both get annoyed with you for interfering. It blows over eventually.'}else if(id==='sideA'){a.rel=clamp(a.rel+4);b.rel=clamp(b.rel-6);b.conflict=clamp((b.conflict||0)+8);s=`You back ${firstName(a)}. ${firstName(b)} notices.`}else if(id==='sideB'){b.rel=clamp(b.rel+4);a.rel=clamp(a.rel-6);a.conflict=clamp((a.conflict||0)+8);s=`You back ${firstName(b)}. ${firstName(a)} notices.`}else s='You stay out of it. It burns out in a few days.'}
 log(e.title,s);return true}
function groupHtml(){const gs=S.groups||[];if(!gs.length)return '<p class="muted-text">A friend group forms naturally once you have a few close friends (up to 3 groups).</p>';return gs.map(g=>`<div class="group-block"><p><b>${esc(g.name)}</b> • since ${formatDate(g.formed)}</p><p class="muted-text">${g.members.map(id=>personById(id)).filter(Boolean).map(p=>esc(displayName(p))).join(', ')}</p>${g.jokes.length?`<small class="muted-text">Inside jokes: ${g.jokes.map(esc).join(' • ')}</small>`:''}<div class="inline-actions"><button class="small" data-group-plan="${g.id}">Plan a group outing (this weekend)</button></div></div>`).join('')}
// ===== Rivalries (§114) =====
function maybeRival(npcId,domain){if(!npcId||S.age<8)return;const n=npcById(npcId);if(!n)return;S.rivals=S.rivals||[];if(S.rivals.length>=3&&!S.rivals.some(r=>r.npcId===npcId))return;let r=S.rivals.find(x=>x.npcId===npcId);if(!r){r={npcId,domain,type:'friendly competition',score:1,since:currentDate()};S.rivals.push(r);let p=S.people.find(x=>x.npcId===npcId);if(!p){p=personFromNpc(n,'friend','rival');p.rel=40;S.people.push(p)}else if(!p.roleLabel||p.roleLabel==='classmate')p.roleLabel='rival'}else r.score++;
 if(SIM.skipping)return;const p=S.people.find(x=>x.npcId===npcId);queueEvent({type:'rivalMoment',title:`${p.name} again`,text:`${p.name} was right there competing with you in ${domain} — again. They catch your eye afterward.`,participants:[p.id],payload:{npcId},priority:2,expiresDays:1,choices:[{id:'shake',label:'Shake hands, good game'},{id:'trash',label:'Trash talk'},{id:'ignore',label:'Ignore them'}]})}
function handleRival(e,id){const p=personById(e.participants?.[0]),r=(S.rivals||[]).find(x=>x.npcId===e.payload?.npcId);if(!p||!r)return true;let s;
 if(id==='shake'){p.rel=clamp(p.rel+5);p.trust=clamp(p.trust+3);r.type=p.rel>=60?'respect':'friendly competition';s=`${firstName(p)} grins. "Next time, I'm winning." It feels like respect.`}else if(id==='trash'){p.rel=clamp(p.rel-6);p.conflict=clamp((p.conflict||0)+8);r.type=r.score>=3?'resentment':'jealous rivalry';addRep('troublemaker',1);s=`You say something cutting. ${firstName(p)} fires back. This is personal now.`}else{s='You ignore them. They notice that too.'}
 if(p.rel>=68&&r.type!=='resentment'){p.roleLabel='friend (former rival)';r.type='friendship';s+=' Somewhere along the way, the rivalry turned into a friendship.'}
 rememberPerson(p,`Rivalry in ${r.domain}: ${r.type}.`);log(e.title,s);return true}
// ===== Awards (§115) =====
function awardsCeremony(old){if(!old||old.grade==='Kindergarten'||!old.record)return;const rec=old.record,avg=old.subjects?.reduce((a,s)=>a+s.score,0)/Math.max(1,old.subjects?.length||1),r=ensureRep(),a=[];
 if(avg>=85)a.push(['Honor Roll','academic']);if(rec.absences===0&&rec.tardies<=2&&rec.daysAttended>=60)a.push(['Perfect Attendance','club']);if((old.contests||[]).some(c=>/Winner/.test(c.result||'')))a.push(['Competition Winner','academic']);if((old.clubs||[]).some(c=>c.status==='Active'&&ladderFor(c).slice(-2).includes(c.position)))a.push(['Club Leadership Award','leadership']);if(r.creative>=60)a.push(['Art & Creativity Award','creative']);if(r.athletic>=60)a.push(['Athlete of the Year','athletic']);if(old.councilRole)a.push(['Student Government Service','leadership']);if(r.kindness>=60)a.push(['Kindness Award','kindness']);
 if(!a.length)return;S.awards=S.awards||[];for(const [name,dim] of a){S.awards.unshift({name,grade:old.grade,year:parseISO(currentDate()).getUTCFullYear(),dateISO:currentDate()});addRep(dim,4);recordOutcome('Award',name,old.grade,'Recognized at the end-of-year ceremony.')}
 const parent=S.people.find(p=>p.role==='parent');if(parent){parent.rel=clamp(parent.rel+3);rememberPerson(parent,`Watched you receive ${a.map(x=>x[0]).join(', ')}.`,2)}const f=bestNonFamily();if(f)f.rel=clamp(f.rel+1);S.happiness=clamp(S.happiness+5);
 if(SIM.summary)SIM.summary.notable.push(`Awards: ${a.map(x=>x[0]).join(', ')}`);
 S.milestones.unshift({dateISO:currentDate(),age:S.age,title:'🏅 End-of-year awards',text:`${a.map(x=>x[0]).join(', ')} (${old.grade}).`});
 if(!SIM.skipping)log('🏅 Awards ceremony',`Your name is called for ${a.map(x=>x[0]).join(', ')}. ${parent?`${parent.name} takes about forty photos.`:''} ${f?`${firstName(f)} cheers louder than anyone.`:''}`,true)}
// ===== Gift reactions (§108) =====
const TRAIT_LIKES={Sporty:['Sports'],Artsy:['Arts & crafts','Books'],Studious:['Books','School supplies'],Curious:['Books','Electronics','Toys & games'],Outgoing:['Beauty & care','Clothes','Gifts'],Funny:['Toys & games'],Kind:['Gifts','Food & drinks'],Competitive:['Sports','Toys & games'],Quiet:['Books'],Generous:['Gifts']};
const INTEREST_LIKES={Football:'Sports',Basketball:'Sports',Swimming:'Sports','Art Club':'Arts & crafts',Drama:'Clothes',Music:'Electronics','Science Club':'Books','Coding Club':'Electronics',Debate:'Books','Chess Club':'Toys & games','Student Council':'School supplies'};
function npcGiftReaction(p,gift,d){
 const likes=new Set([...(p.traits||[]).flatMap(t=>TRAIT_LIKES[t]||[]),INTEREST_LIKES[npcById(p.npcId)?.interest]].filter(Boolean)),cat=d.category||gift.category,price=d.price||0,handmade=/Handmade|homemade/i.test([gift.source,gift.origin,gift.name].filter(Boolean).join(' ')),occasion=holidayWindow().some(x=>x.days<=0&&['christmas','valentines','lunarNewYear','mothersDay','fathersDay','teachersDay'].includes(x.h.id));
 p.giftsReceived=p.giftsReceived||[];const owns=p.giftsReceived.includes(gift.key);
 if(isSpoiled(gift))return {tier:'dislike',rel:-2,trust:0,why:`${firstName(p)} notices it has gone bad. Awkward.`};
 if(price>=60&&(p.boundaries?.includes('noExpensiveGifts')||p.rel<50))return {tier:'awkward',rel:0,trust:-1,why:`"This is too much — I can't accept something this expensive." ${p.boundaries?.includes('noExpensiveGifts')?`${firstName(p)} really is uncomfortable with big gifts.`:'You do not know each other that well yet.'}`};
 if(owns)return {tier:'alreadyOwn',rel:2,trust:1,why:`"Oh — I actually already have one from you! But thank you."`};
 if(handmade&&p.rel>=55)return {tier:'love',rel:9,trust:4,why:`${firstName(p)} goes quiet, then hugs you. A handmade gift from someone close means more than anything from a store.`};
 if(d.personal)return {tier:p.rel>=55?'love':'effort',rel:p.rel>=55?7:4,trust:4,why:`${firstName(p)} reads what you wrote twice. "You actually mean this."`};
 if(hasCondition(gift.lifecycleType)&&gift.condition<45)return {tier:'effort',rel:1,trust:0,why:`${firstName(p)} thanks you, though the ${gift.name.toLowerCase()} has clearly seen better days.`};
 if(likes.has(cat))return {tier:'love',rel:6+Math.min(3,price/40)+(occasion?2:0),trust:2,why:`${firstName(p)} lights up — it is exactly their kind of thing.${occasion?' Perfect timing, too.':''}`};
 if(p.rel<45&&likes.size&&!likes.has(cat))return {tier:'dislike',rel:0,trust:0,why:`${firstName(p)} says thank you, but it is clearly not their thing.`};
 return {tier:'like',rel:3+Math.min(4,price/40)+(occasion?2:0),trust:1,why:rand([`${firstName(p)} smiles. "That's really thoughtful."`,`"For me? Thanks!"`])}
}
function giveInventoryItem(itemId,personId){
 const it=S.inventoryItems.find(x=>x.id===itemId),p=personById(personId);if(!it||!p)return;const d=catalogItem(it.key)||{};
 if(S.age<13&&d.price>=100&&!caregiverApproval(0)){closeChoiceModal();log('Not allowed',`Your caregiver says the ${it.name.toLowerCase()} is too valuable to give away.`);return}
 const gift=removeItem(it.id,true)||it,r=npcGiftReaction(p,gift,d);let extra='';
 if(gift.wrapped&&r.tier!=='dislike'){r.rel+=gift.wrapped.paper==='heart'?2:1.5;extra=` ${firstName(p)} tears open the ${gift.wrapped.paper==='heart'?'heart-covered':'bright'} paper first.`;if(gift.wrapped.paper==='heart'&&eligibleRomance(p)){ensureRomanceProfile(p);p.attraction=clamp((p.attraction||40)+3)}}
 if(r.tier==='love')addLove(p,8);p.rel=clamp(p.rel+r.rel);p.trust=clamp(p.trust+r.trust);p.giftsReceived=[...(p.giftsReceived||[]),gift.key].slice(-12);rememberPerson(p,`You gave them ${gift.name.toLowerCase()} — ${r.tier}.`,r.tier==='love'?2:1);
 if(gift.sentimental>=35&&gift.origin)S.happiness=clamp(S.happiness+(r.rel>0?1:-2));
 advanceTime(10);closeChoiceModal();recordOutcome('Gift',`${gift.name} → ${displayName(p,'formal')}`,{love:'Loved it',like:'Liked it',effort:'Appreciated the effort',awkward:'Awkward',alreadyOwn:'Already had one',dislike:'Not their thing'}[r.tier],r.why);
 log(`Gave ${gift.name.toLowerCase()} to ${firstName(p)}`,`${r.why}${extra}`);toast(`Gift • ${firstName(p)}`)
}
// ===== Sneaking out / in (§82). Minors: friends & parties only — never romantic. =====
function canSneak(p){if(S.age<12||S.age>=18||!p||isFamilyPerson(p))return false;const m=currentMinute(),late=m>=Math.min(curfewMinute()||1439,bedtimeMinute())||m<300;return late}
function sneakOut(personId,mode){
 const p=personById(personId);if(!canSneak(p)){toast('That is not something to sneak around for right now.');return}closeChoiceModal();
 if(p.id===S.romance?.partnerId&&S.age<18&&mode==='over'){toast('Not that — keep time with them to daytime plans.');return}
 if(mode==='over'||mode==='meet'){const st=npcStatusAt(p,currentDate(),1000);const refuse=(p.traits||[]).includes('Studious')&&chance(50)||chance(25);if(refuse){log('They say no',`${firstName(p)} texts back: "${rand(["My parents will be home soon — no way.","I'd get in so much trouble. Not tonight.","It's too late, I have school tomorrow."])}"`);return}}
 const r=familyRules(),brk=S.family.ruleBreaks||0,sib=S.people.find(x=>/sibling/.test(x.role));let pCaught=clamp(18+r.strictness*.35+(currentMinute()<300?10:0)+brk*5+Math.random()*15-(S.luck-50)*.1,5,85);
 S.family.ruleBreaks=brk+1;advanceTime(mode==='over'?150:120,{silent:true});S.needs.fun=clamp(S.needs.fun+12);p.rel=clamp(p.rel+3);rememberPerson(p,mode==='over'?'You snuck them over late at night.':'You snuck out to meet them.',2);
 let story=mode==='over'?`You let ${firstName(p)} in through the back. You whisper-laugh through a movie with the volume at 2.`:`You slip out and meet ${firstName(p)}. The empty streets at night feel like another world.`;
 if(sib&&chance(30)){queueEvent({type:'sneakSibling',title:`${firstName(sib)} caught you`,text:`${firstName(sib)} is standing in the hallway. "Where were you?"`,participants:[sib.id],priority:3,expiresDays:1,choices:[{id:'ask',label:'Ask them to keep it secret'},{id:'bribe',label:'Bribe them ($10)'},{id:'let',label:'Let them tell'}]});log('Sneaking',story);return}
 if(chance(pCaught*.5)){S.family.trust=clamp(S.family.trust-12);S.family.tension=clamp(S.family.tension+7);ground(5,'Sneaking out');log('Caught sneaking',`${story} Then the hallway light snaps on. ${primaryCaregiver()} is standing there. Grounded for five days, and trust takes a hit.`);return}
 if(chance(pCaught*.4)){scheduleFollowUp('sneakFound',{how:chance(50)?'neighbor':'parent'},{days:1,minute:1080});log('Sneaking',story+' You make it back in. Probably nobody noticed.');return}
 setEmotion('Excited','You got away with sneaking out.',55);log('Sneaking',story+' You make it back without a sound.')
}
function handleSneakSibling(e,id){const sib=personById(e.participants?.[0]);if(!sib)return true;let s;if(id==='ask'){if(sib.rel>=55&&chance(70)){sib.trust=clamp(sib.trust+2);s=`${firstName(sib)} rolls their eyes. "Fine. You owe me."`}else{scheduleFollowUp('sneakFound',{how:'sibling'},{minute:Math.min(1439,currentMinute()+120)});s=`${firstName(sib)} does not promise anything.`}}else if(id==='bribe'){if(spendOwn(10)){s=`${firstName(sib)} pockets the money. Silence bought.`}else{scheduleFollowUp('sneakFound',{how:'sibling'},{minute:Math.min(1439,currentMinute()+120)});s='You do not have $10. That goes badly.'}}else{scheduleFollowUp('sneakFound',{how:'sibling'},{minute:Math.min(1439,currentMinute()+60)});s='You shrug. Whatever happens, happens.'}log(e.title,s);return true}
// ===== NPC agency (§62): NPCs date, break up, need help, send gifts =====
function npcAgencyTick(){
 if(S.age<10)return;
 for(const p of S.people){if(isFamilyPerson(p)||p.movedAway)continue;const a=personAge(p);
  /* NPC dating now handled by real couples (npcCoupleTick) */
 }
 const partner=partnerPerson();if(partner&&partner.rel<35&&chance(15)){const why=partner.conflict>25?'too many fights':'they felt you had drifted apart';endRelationship(partner,why,{byNpc:true});if(!SIM.skipping)log('Breakup',`${firstName(partner)} ends things. "${why==='too many fights'?'We just keep fighting. I can\'t do this anymore.':'It feels like we\'re not really together anymore.'}"`,true)}
 if(!SIM.skipping&&chance(2)){const p=rand(S.people.filter(x=>!isFamilyPerson(x)&&x.rel>=50&&!x.movedAway));if(p)queueEvent({type:'helpRequest',title:`${firstName(p)} needs a favor`,text:rand([`${firstName(p)} is stuck on an assignment and asks for help.`,`${firstName(p)} is moving furniture and asks for an extra pair of hands.`,`${firstName(p)} needs someone to talk to.`]),participants:[p.id],priority:2,expiresDays:1,choices:[{id:'help',label:'Help'},{id:'later',label:'Not right now'}]})}
 if(!SIM.skipping&&chance(.6)){const p=rand(S.people.filter(x=>!isFamilyPerson(x)&&x.rel>=70));if(p){const k=rand(['book','snackPack','greetingCard','comicBook'].filter(x=>D.catalog[x]&&S.age>=D.catalog[x].minAge));if(k){addItem(k,`from ${displayName(p,'formal')}`);log('A surprise gift',`${firstName(p)} gives you a ${D.catalog[k].name.toLowerCase()} — "Saw this and thought of you."`)}}}
}
function handleHelpRequest(e,id){const p=personById(e.participants?.[0]);if(!p)return true;if(id==='help'){recordTraitEvidence('Empathetic',{source:'helped someone',system:'social',eventId:'help-'+e.id,context:'helping a friend'});advanceTime(60,{silent:true});p.rel=clamp(p.rel+5);p.trust=clamp(p.trust+4);addRep('kindness',1);log(e.title,`You show up. ${firstName(p)} will not forget it.`);rememberPerson(p,'You helped them when they needed it.',2)}else{p.rel=clamp(p.rel-1);log(e.title,`You say you can't right now. ${firstName(p)} understands, mostly.`)}return true}
// ===== Relationship action stories (§60, §123) =====
function relationshipTitle(p,action){return `${firstName(p)} • ${{talk:'talked',hangout:'spent time together',play:'played together',confide:'confided',gossip:'gossiped',argue:'argued',apologize:'apologized',message:'messaged',call:'called'}[action]||action}`}
function relationshipStory(p,action){const tr=p.traits||[],fn=firstName(p),j=groupsOf(p.id)[0]?.jokes?.[0],mem=(p.history||[])[1]?.text;
 const pools={talk:[`You and ${fn} talk about ${rand(['school','a show you both like','something weird that happened today','what you want to do next summer'])}.${tr.includes('Funny')?` ${fn} has you laughing within minutes.`:''}`,`${fn} tells you about ${rand(['a problem at home','a new hobby','someone they cannot stand'])}. You mostly listen.`,mem?`${fn} brings up the time "${mem.slice(0,60)}" — they remember more than you thought.`:`A normal conversation that runs longer than either of you planned.`],
  hangout:[`You and ${fn} ${rand(['wander around town','end up at the park','try a new snack place','do absolutely nothing productive'])}.${j?` Someone mentions ${j} and you both lose it.`:''}`,`${tr.includes('Sporty')?`${fn} talks you into shooting hoops.`:tr.includes('Artsy')?`${fn} drags you to a tiny gallery.`:`You and ${fn} spend the afternoon together.`} It is easy, the way it is with good friends.`],
  play:[`You and ${fn} invent a game with complicated rules that change every five minutes.`,`${fn} wants to play pretend; you are assigned the role of dragon.`],
  confide:[`You tell ${fn} something you have not told anyone. ${p.trust>=65?'They handle it with care.':'They listen, a little unsure what to say.'}`],
  gossip:[`You and ${fn} trade gossip. ${tr.includes('Kind')?`${fn} looks a bit uncomfortable.`:'It is fun, if not exactly kind.'}`],
  argue:[`It starts over something small and gets bigger. ${fn} says something that stings; so do you.`],
  apologize:[`You apologize to ${fn} without excuses. ${p.conflict>20?'They are not ready to let it go completely.':'They soften. "Thanks for saying that."'}`],
  message:[`You send ${fn} a message. ${rand(['They reply with seven emojis.','They answer an hour later with a meme.','A short reply, but warm.'])}`],
  call:[`A long call with ${fn}. You talk until someone's battery complains.`]};
 return rand(pools[action]||[`You spend some time with ${fn}.`])}
// ===== Click & event routing =====
function worldEventChoice(e,id){
 if(e.type==='nbh')return handleNeighborhood(e,id);if(e.type==='meetPeople')return handleMeetPeople(e,id);if(e.type==='promInvite')return handlePromInvite(e,id);if(e.type==='promSkipNight')return handlePromSkip(id);
 if(e.type==='groupExcluded'||e.type==='groupArgument')return handleGroupEvent(e,id);if(e.type==='rivalMoment')return handleRival(e,id);if(e.type==='sneakSibling')return handleSneakSibling(e,id);if(e.type==='helpRequest')return handleHelpRequest(e,id);
 if(e.type==='sneakTalk'){const s={apologize:'You admit it and apologize. Grounded for three days, but some trust is saved.',lie:'You deny it. They do not believe you. That makes it worse.',argue:'You argue that you are old enough. It goes badly.'}[id];if(id==='apologize'){ground(3,'Sneaking out');S.family.trust=clamp(S.family.trust-4)}else{ground(6,'Sneaking out');S.family.trust=clamp(S.family.trust-12);S.family.tension=clamp(S.family.tension+6)}log(e.title,s);return true}
 return false}
function worldFollowUp(f){
 if(f.type==='promTimeout'){const pr=S.school?.prom,p=personById(f.payload.personId),rec=pr?.received?.find(r=>r.personId===p?.id&&r.status==='Waiting');if(!rec)return true;rec.status='Expired';const o2=freePromNpc([p.npcId],personAge(p));if(o2)pairPersonWithNpc(p,o2);else setPromWithPerson(p,'someone else');p.rel=clamp(p.rel-2);if(!SIM.skipping)log('Too slow',`${firstName(p)} got tired of waiting and asked ${personPromWith(p)} instead.`);return true}
 if(f.type==='promAnswer'){const pr=S.school?.prom,p=personById(f.payload.personId),a=pr?.asked?.find(x=>x.personId===p?.id&&x.result==='Pending');if(!a)return true;if(!pr.partnerId&&chance(55)){a.result='Accepted';pr.partnerId=p.id;pr.plan='date';p.promWith=S.name;if(!SIM.skipping)log(`${firstName(p)} said yes!`,`"Okay. Yes. I'd like to go with you." Worth the wait.`,true)}else{a.result='Rejected';a.reason='Decided not to';if(!SIM.skipping)log(`${firstName(p)} decided`,`"I thought about it… I don't think so. Sorry."`)}return true}
 if(f.type==='sneakFound'){if(SIM.skipping){S.family.trust=clamp(S.family.trust-6);return true}const how={neighbor:'A neighbor mentioned seeing you out late',sibling:'Your sibling told',parent:'Something gave you away'}[f.payload.how]||'Someone noticed';queueEvent({type:'sneakTalk',title:'They know you snuck out',text:`${how}. ${primaryCaregiver()} wants to talk — now.`,priority:4,expiresDays:1,choices:[{id:'apologize',label:'Admit it and apologize'},{id:'lie',label:'Deny it'},{id:'argue',label:'Argue'}]});if(f.payload.how==='neighbor')nbRep('troublemaker',2);return true}
 return false}
function worldClick(b){const d=b.dataset;if(d.sneak){sneakOut(d.personId,d.sneak);save();render();return true}return false}
